dmlc/dgl

- python/dgl/graph.py
- tests/pytorch/test_basics.py
Fix conversion from networkx when there is no `id` in edge feature. (Issue #283)
> [Bugfix] Fix conversion from networkx

- docs/source/index.rst
- docs/source/install/index.rst
Fixed the link to the repo after migrating to dmlc. 
> [DOC] Fix repo link 

- Jenkinsfile
- docs/Makefile
- docs/README.md
- python/dgl/contrib/sampling/sampler.py
- tutorials/models/1_gnn/8_sse_mx.py
- tutorials/models/4_old_wines/7_transformer.py
Current document build fails and has to be fixed manually because different tutorials use different tensor backend (pytorch, mxnet) but sphinx builds using only one process and loads DGL only once.
Instead of tweaking tutorial code to dynamically switch backend, this PR builds documents in two rounds to bypass the issue:
- First round builds all documents which uses MXNet
- Second round builds all documents which uses PyTorch
Step 1 and 2 build documents twice, so there are redundant work. But I am not sure how to minimize each step.
> [Doc] Fix document building for multiple tensor backends

- python/dgl/contrib/sampling/sampler.py
- tests/mxnet/test_sampler.py
Added a prefetch option to the existing neighbor sampler. If enabled, an extra python thread is spawned for prefetching. This is a simplified version of the one from gluon-nlp.
@zheng-da @aksnzhy 
- added prefetch option, and corresponding test
> [Feature] Add threaded prefetcher for neighbor sampler

- Jenkinsfile
- tests/pytorch/test_graph.py
- tests/scripts/build_dgl.bat
- tests/scripts/build_dgl.sh
- tests/scripts/task_example_test.bat
- tests/scripts/task_unit_test.bat
- tests/scripts/task_unit_test.sh
Added Windows build & unit/example tests on PyTorch/CPU.  The backend is built with MSBuild and MinGW is no longer required.
> [CI] Jenkins on Windows builds

- python/dgl/backend/backend.py
- python/dgl/backend/mxnet/tensor.py
- python/dgl/backend/pytorch/tensor.py
- python/dgl/frame.py
- python/dgl/graph.py
- python/dgl/runtime/ir/executor.py
- python/dgl/runtime/scheduler.py
- python/dgl/utils.py
- tests/pytorch/test_basics.py
- tests/pytorch/test_multi_send_recv.py
This PR fixes #75 and other small bugs (see below) and supports multiple recv after send.
Previously, each recv call clears message graph so following recv won't see any message. This PR fix the bug by removing message graph and put message in edge space (but still in a separate message frame). Now message frame has the same size as edge frame and whether there is a message on an edge is indicated by a special "boolean" index in DGLGraph (graph._msg_index).
Now users can:
- call multiple send (on the edges or not), each using a different message function (with different message fields)
- call multiple recv
> [Bugfix] Fix multiple send recv

- docs/Makefile
- docs/source/conf.py
- readthedocs.yml
Same as https://github.com/dmlc/dgl/pull/352. Need to modify conf.py add config file to build.
Move file_pattern option from Makefile to conf.py and add doc build config file. This is for further doc autobuild and versioning settings.
> [Docs] [0.1.x] Move file_pattern option from Makefile to conf.py

- python/dgl/graph.py
Fixed a typo in the documentation of DglGraph.out_edges method.
> [Doc] Fix a typo

- docs/source/api/python/data.rst
- python/dgl/data/__init__.py
- python/dgl/data/minigc.py
- tests/compute/test_data.py
A synthetic dataset for graph classification task. The dataset will also be used in our tutorial #360 .
> [Data] Synthetic dataset for graph classificaiton

- docs/source/api/python/data.rst
- docs/source/index.rst
- python/dgl/data/minigc.py
- tutorials/basics/4_batch.py
Motivated by the [forum discussion](https://discuss.dgl.ai/t/how-to-classify-entire-graphs-in-batches/45), we decide to add a tutorial on batched graph classification.
- Added the tutorial as the last one in the `basics` section.
- Modified `docs/index.rst` accordingly
> [Tutorial] Batched Graph Classification

- include/dgl/graph.h
I think `edge_id` is not the predecessor vertex list. It is the out edge list.
> [Doc] fix the comment error of edge_id in graph.h

- python/dgl/graph_index.py
graph_index.py `from_scipy_sparse_matrix` function requires input to be either coo or csr sparse matrix. But it's not necessary because code that calls this function guarantees that input is sparse matrix and this function immediately calls `adj.tocoo()`.
Remove this assertion allows user to create DGLGraph from other sparse matrix format.
> [Bugfix] Remove unnecessary assert in from_scipy_sparse_matrix

- CMakeLists.txt
- src/graph/sampler.cc
Organically find OpenMP in CMake instead of hard-coding.
Also changes `omp.h` to `dmlc/omp.h`.
> [Build] Find OpenMP in CMake

- tutorials/models/1_gnn/9_gat.py
As mentioned during our meeting, I've observed different behavior for the attention entropy distribution in the final layer of GAT on the PPI dataset with the authors' code. I've re-performed experiments on the dgl implementation and confirmed that observation. It is most likely that some mistakes were made before.
@jermainewang I'll PR a fix for the blog as well. Could you please help fix the Zhihu column article?
> [Tutorial] Hotfix for GAT Tutorial

- examples/mxnet/sampling/gcn_cv_sc.py
- examples/mxnet/sampling/gcn_ns_sc.py
- examples/mxnet/sampling/graphsage_cv.py
- examples/mxnet/sse/sse_batch.py
- python/dgl/contrib/sampling/sampler.py
- python/dgl/node_flow.py
- tests/compute/test_sampler.py
- tutorials/models/1_gnn/8_sse_mx.py
Previously, the sampled result from neighbor sampler is a tuple of NodeFlow and a dictionary of aux info. The aux info may contain the seed ids for the minibatch. The reason we used aux_info to contain extra information is that we used DGLSubgraph for the sampled graph. After using NodeFlow, it's not necessary to keep extra info in aux_info. All information in the sampled graph is contained in NodeFlow.
> [Sampler] fix the API of neighbor sampler.

- python/dgl/backend/pytorch/tensor.py
Spmm with uncoalesced sparse matrix in PyTorch has bad performance because the coalesce step is costly. Although coalesce sparse matrix ahead of time could make the forward pass much faster, the backward phase is still slow. Given expression y=spmat * x, in order to calculate gradient of x, we need to do spmat^T * grad_y. But transpose sparse matrix and then coalesce is again very costly. See profiling results [here](https://docs.google.com/document/d/1VaOksLx4yc76gdGpv2BpozJV4G96-7y07E6f9qwUqWM/edit#heading=h.49fpnq8w33hh).
This PR replaces PyTorch spmm with index_select and scatter_add. This solution is motivated by [pytorch_geometric](https://github.com/rusty1s/pytorch_geometric). See profiling results after improvement [here](https://docs.google.com/document/d/1VaOksLx4yc76gdGpv2BpozJV …
> [Feature] Reduce messages with scatter_add in PyTorch

- examples/pytorch/rgcn/layers.py
- examples/pytorch/rgcn/link_predict.py
- python/dgl/contrib/data/knowledge_graph.py
RGCN entity dataset processing code generates relation type id wrongly. And index_select is much faster than tensor's __getitem__ operator.
> [BugFix] Fix bug in RGCN data processing and use index_select to improve speed

- src/graph/sampler.cc
Currently random walk will crash with floating point exception if the current visited vertex has no successors (hence unable to continue random walking). This PR fails random walk gracefully in this case.
It seems that OpenMP does not work well with existing C++ exception handling (i.e. `LOG(FATAL)`). So I removed OpenMP in that routine as well.
> [BUG] Graceful handling of random walking with no successors

- python/dgl/nodeflow.py
- tests/scripts/build_dgl.sh
* Cython cannot distinguish numpy.int and int. So `int()` is recommended when calling CAPI. @zheng-da 
* Update Jenkins to allow cython test.
> [Hotfix] fix cython bug

- python/dgl/function/reducer.py
> [Doc] added index [0] to torch.max comment

- conda/dgl/bld.bat
- conda/dgl/meta.yaml
0.2.x+ on Windows no longer needs mingw to build.
Note that currently the Windows packages are already built with MSBuild.
> [Build] Switching to msbuild for conda windows

- python/dgl/contrib/sampling/sampler.py
- python/dgl/graph.py
- tutorials/models/1_gnn/8_sse_mx.py
Current neighbor sampler and layerwise sampler code breaks Python code convention: the functions "pretend" to be classes by having CamelCase names.
Also layerwise sampling and neighbor sampling are mangled in the same `SubgraphSampler` class via if-else blocks, which is not very friendly when new samplers are added.
Tested with `examples/mxnet/gcn_ns_sc.py` and it didn't break.
> [Refactor] Sampler code refactor

- python/dgl/nn/pytorch/softmax.py
`EdgeSoftmax` module did not pop the temporary max feature. In GAT model, this bug leads to huge slow down in `get_ndata_name` function because GAT uses one single graph, and after `n` epochs, there are `n` max feature in `g.ndata`, and `get_ndata_name` has to retry `n` times to find a usable feature name. Also, the bug leads to extra memory consumption because the reference to tensor is still kept by DGLGraph.
This explains why when running GAT models, the training time of one epoch keeps increasing.
> [BugFix] Fix performance bug in EdgeSoftmax

- python/dgl/contrib/sampling/sampler.py
The refactor forgots the prefetch toggle for neighbor and layerwise sampler.
> [Bug] Fix unused prefetch switch for NeighborSampler and LayerSampler

- README.md
Add GTC 2019 Tutorial as news in readme
> [News] Add GTC 2019 Tutorial as news in readme

- examples/mxnet/gat/gat_batch.py
- examples/mxnet/gcn/train.py
- examples/pytorch/gat/train.py
- examples/pytorch/gcn/gcn_mp.py
- examples/pytorch/gcn/train.py
I find that  some nodes in citation dataset have self-edge orginally, if we use `g.add_edges(g.nodes(), g.nodes())` directly, some nodes will have more than one self-edge.  This PR fixes that.
> fix self-edge bug in GCN and GAT.

- examples/mxnet/tree_lstm/train.py
- examples/mxnet/tree_lstm/tree_lstm.py
For some reason, the dtype of the inputs is inconsistent. We need to explicitly cast the type.
> [BUGFIX] fix treelstm

- tests/mxnet/test_shared_mem_store.py
It seems RPC calls fail sometimes. It might take a while to investigate the problem. Let's disable the unittest for shared memory for now.
> [Test] Disable unittest for shared memory temporarily

- python/dgl/_ffi/_cython/base.pxi
Fixes #488 
Some time later we need to include CI for Cython builds as well.
> [BUG] Fix crash during Cython build

- examples/pytorch/jtnn/jtnn/jtnn_enc.py
The call in JTNN didn't get updated after changes in traversal interfaces
> Fixing typo in JTNN after interface change

- python/dgl/nodeflow.py
- tests/compute/test_nodeflow.py
When use `NodeFlow.apply_block` with `edges=ALL`(default), it will produce an error. 
More details can be found in #513 
> [BugFix] Fix getting src and dst id of ALL edges in NodeFlow.apply_block

- python/dgl/graph.py
- python/dgl/runtime/scheduler.py
- tests/compute/test_multi_send_recv.py
msg_index in DGLGraph is only used for send and recv, which is very uncommonly used. However, msg_index is created by default, which makes loading a giant graph very slow. We can create the index only when it's actually used. This can significantly reduce memory consumption for giant graphs.
> [Perf] lazily create msg_index.

- python/dgl/contrib/data/knowledge_graph.py
This pull request serves as a fix for #558. It renames edge_src and edge_dst to src and dst in all files related to entity classification task with RGCN.
> [BugFix] Fix error when bfs_level = 0 in Entity Classification with RGCN

- python/dgl/heterograph.py
The Python interface proposal for heterogeneous graphs (heterograph for short - although [the word heterograph means something unrelated](https://study.com/academy/lesson/heterographs-definition-examples-quiz.html)).
* A heterograph in DGL additionally requires that the edges with the same type MUST have the same source node type and destination node type.
* Users can only assign features on one node/edge type at a time.
* Users can induce subgraphs from heterograph with node/edge types.
* Different node/edge types may have different node/edge feature schemes.
* Message functions and edge apply functions can be dictionary of edge types and edge UDFs.
* Reduce functions can be dictionary of edge types and node UDFs.
* Node apply functions can be dictionary of node types and node UDFs. …
> [Feature][RFC] Heterogeneous graph interface

- docker/install/ubuntu_install_mxnet_cpu.sh
- docker/install/ubuntu_install_mxnet_gpu.sh
- python/dgl/backend/mxnet/tensor.py
MXNet 1.4.1 has bugs that have been fixed in MXNet 1.5 nightly build. So switch to MXNet 1.5 20190528 build.
> [Docker]Update MXNet CI Image

- python/dgl/data/minigc.py
As described in #568 , when we create `circular_ladder_graph` with `nx.circular_ladder_graph(num_v)`, we will get a graph with `2 * num_v` nodes.
> [BugFix] Fix minigc dataset

- python/dgl/backend/pytorch/tensor.py
- python/dgl/kernel.py
- src/kernel/binary_reduce.cc
- src/kernel/binary_reduce_impl.h
- src/kernel/binary_reduce_impl_decl.h
- src/kernel/cuda/binary_reduce_sum.cu
- tests/compute/test_nodeflow.py
Fix the bug in using cusparse when the sparse matrix is actually a bipartite graph.
> [Kernel][Bugfix] fix nodeflow bug

- tests/compute/test_sampler.py
Occasionally the NodeFlow sampler test will fail due to isolated nodes (i.e. zero in-degree or out-degree) in the generated graph.
> [BUG][Test] Fix occasional assertion failure in sampler test

- tests/compute/test_traversal.py
Sometimes the BFS traversal will fail due to empty frontier being added in networkx code for nodes with 0 successors.
> [BUG][Test] Fix random BFS traversal test failures

- python/dgl/contrib/sampling/sampler.py
- src/graph/sampler.cc
- tests/compute/test_sampler.py
When our ImmutableGraph is constructed, it may not have one of the CSRs. For example, when we construct ImmutableGraph from a csr input, we only have out-csr. When in-csr is required, it is constructed when required. However, we can't reconstruct the in-csr inside OpenMP. If we do so, multiple threads try to construct the in-csr in parallel and override the one created by another thread. That's why we experience segfault in the sampling test. The right way is to construct the in-csr in advance before we enter OpenMP.
> [BUGFIX] fix sampler.

- include/dgl/immutable_graph.h
- src/c_api_common.h
The == and << operator overloading for DLContext should be defined in the root namespace. Also fix some warning.
> [Bugfix] Fix mac compilation

- python/dgl/nn/pytorch/conv.py
To fix the bug described in #617 .
Input:
```python
import dgl
from dgl.nn.pytorch.conv import GraphConv
import torch.nn as nn
import torch.nn.functional as F
model_0 = GraphConv(2,2,activation=nn.PReLU())
model_1 = GraphConv(2,2, activation=F.relu)
print(model_0)
print(model_1)
```
Output:
```
GraphConv(
in=2, out=2, normalization=True
(_activation): PReLU(num_parameters=1)
)
GraphConv(in=2, out=2, normalization=True, activation=<function relu at 0x119d84bf8>)
```
> [bugfix] fix bug in repr function of GraphConv

- python/dgl/nn/pytorch/softmax.py
The backward phase of edge softmax did not pop out temporary features from the frame, which leads to huge slow down...
> [Bugfix] Fix performance bug in edge softmax operator

- src/graph/sampler.cc
- tests/compute/test_nodeflow.py
When shuffle=False, the seed nodes in a sampled NodeFlow should have the same order as input seed nodes.
> [BUGFIX] fix the order of the seed nodes in NodeFlow

- python/dgl/backend/mxnet/tensor.py
- python/dgl/nn/mxnet/softmax.py
- python/dgl/nn/pytorch/softmax.py
Current DGL operators leak memory, and this happens for both PyTorch (#637 ) and MXNet backend.
For PyTorch, the cause is we used a separate cache instead of PyTorch's `ctx.save_for_backward` API to save tensors from forward pass but forgot to explicitly clear the cache. And the reason for not using `ctx.save_for_backward` API is we need to save non-tensor type data. Similar problem was mentioned in [this thread](https://discuss.pytorch.org/t/when-should-you-save-for-backward-vs-storing-in-ctx/6522).
For MXNet, the interesting thing is, even if we use its standard `save_for_backward` API, there is still memory leak. 
The Solution is simply explicitly clearing the cache.
> [BugFix] Fix memory leak in DGL edge softmax module

- python/dgl/backend/backend.py
- python/dgl/backend/mxnet/tensor.py
- python/dgl/backend/pytorch/tensor.py
- python/dgl/contrib/graph_store.py
MXNet performs operations async. However, the shared-memory graph store needs to run barriers to sync between processes. Before entering barriers, we need to make sure all computation the local processes have complete. Otherwise, there will be race condition.
> [BUGFIX] we need to sync for MXNet.

- python/dgl/backend/mxnet/tensor.py
The old MXNet split doesn't support different section sizes. We now switch to new split in MXNet.
> [Backend] use new split in MXNet

- python/dgl/nodeflow.py
`NodeFlow.prop_flow` should check the `flow_range.step` not `slice.step`.
`slice.step` -> `flow_range.step`.
> [Bugfix] Fix nodeflow.prop_flow range check

- include/dgl/base_heterograph.h
- include/dgl/bipartite.h
- python/dgl/_ffi/_ctypes/types.py
- python/dgl/container.py
- python/dgl/graph_index.py
- src/c_api_common.cc
- src/c_api_common.h
- src/graph/bipartite.cc
- src/graph/bipartite.h
- src/graph/graph_apis.cc
- src/graph/heterograph.cc
- src/graph/heterograph.h
- src/graph/immutable_graph.cc
- tests/graph_index/test_hetero.py
The PR implements bipartite graph and heterograph C++ data structure. As per our discussion, the bipartite graph is implemented similarly to immutable graph which contains on-demand-materialized CSR/COO structure. Heterograph is implemented as a list of bipartite graphs, each for one edge type. On python side, currently only minimal wrapper class is implemented.
Side note:
I feel we should hide the COO/CSR implementation from header file as what is done in [bipartite.h](https://github.com/dmlc/dgl/blob/682a3a9510667a29fbbd3ec35aeca582e8685a5a/src/graph/bipartite.h). It makes the header file much cleaner.
> [Hetero] Heterograph C++ implementation; Bipartite and Python wrapper

- python/dgl/base.py
- python/dgl/graph.py
- python/dgl/graph_index.py
Added a return_edge_id optional argument in DGLGraph.adjacency_matrix_scipy() method which defaults to True. If False, then 1's are returned.
The reason to do this is that if edge IDs are returned, then one of the nonzero entries will be actually 0, which may be confusing.
In the next major release (0.5) it will default to False to keep consistent with `adjacency_matrix` interface.  Since existing code may depend on the current behavior that returns edge IDs, I added a `FutureWarning`.
This PR is separated from #720 
> [Misc] Provide a "return 1s instead of edge IDs" option in scipy adjacency matrix

- docs/source/api/python/graph.rst
- python/dgl/frame.py
- python/dgl/graph.py
- python/dgl/nn/mxnet/conv.py
- python/dgl/nn/mxnet/softmax.py
- python/dgl/nn/pytorch/conv.py
- python/dgl/nn/pytorch/softmax.py
- python/dgl/utils.py
- tests/compute/test_basics.py
- tests/mxnet/test_nn.py
- tests/pytorch/test_nn.py
Using DGLGraph in NN module is quite painful because we always need to avoid (1) accidentally override existing feature data; (2) forget to pop the intermediate tensor. The PR added a `local_scope` function to `DGLGraph` that can solve this issue in one line:
Avoid accidentally overriding existing feature data. This is quite common when implementing a NN module:
```python
>>> def foo(g):
>>>     g = g.local_scope()
>>>     g.ndata['h'] = torch.ones((g.number_of_nodes(), 3))
>>>     return g.ndata['h']
>>>
>>> g = ... # some graph
>>> g.ndata['h'] = torch.zeros((g.number_of_nodes(), 3))
>>> newh = foo(g)  # get tensor of all ones
>>> print(g.ndata['h'])  # still get tensor of all zeros
```
Automatically garbage collect locally-defined tensors. Otherwise, user needs to call ``pop`` …
> [Graph] add local scope function

- src/graph/network.cc
- src/graph/network.h
- src/graph/network/msg_queue.cc
- src/graph/network/msg_queue.h
DGL communicator uses async-send and zero-copy, so we need to hold the NDArray reference over time until the back-end send-thread finish its job. 
This PR fixes this feature.
> [Fix] Hold NDArray reference during send()

- python/setup.py
- python/update_version.py
Some minor changes to setup scripts to optionally include prerelease version numbers & CUDA versions.
Nightly builds will be available on pip with the following commands (Hopefully available from August 16th for Linux; Windows and Mac builds would be available later than that):
```bash
pip install --pre dgl        # CPU
pip install --pre dgl-cu90   # CUDA 9.0
pip install --pre dgl-cu92   # CUDA 9.2
pip install --pre dgl-cu100  # CUDA 10.0
```
> [Build] Setup for prerelease builds

- examples/pytorch/recommendation/README.md
- examples/pytorch/recommendation/main.py
Add noting that the PinSage model example under
example/pytorch/recommendation only work with Python 3.6+
as its dataset loader depends on stanfordnlp package
which work only with Python 3.6+.
This fix for #769 
> [Doc] Update README.md for pytorch PinSage example.

- python/dgl/contrib/graph_store.py
- python/dgl/frame.py
- python/dgl/graph.py
- tests/compute/test_basics.py
**This PR is same as #751 , which has already been approved. I accidentally deleted my original fork before merging the PR and resubmit it here.**
Currently `local_var` and `local_scope` do not use the frame initializers of the original `_node_frame` and `_edge_frame`. This causes warnings about initializers even when we have initializers set, which can be confusing for example when using `nn modules`.
Also as discussed before, warnings about frame initializers are removed.
- Synchronize frame initializers after the copy of frames
- Test cases are added
> [Fix] Synchronize frame initializers for local_var and local_scope & Remove warning

- examples/pytorch/model_zoo/chem/property_prediction/utils.py
Previously we raise an assertion error if an early stop file already exists. This seems to be confusing for some users so we now add a postfix of time to avoid confusion.
Remove assertion error for repeated early stop model and add time dependent postfix.
> [Model Zoo] Fix Early Stop

- src/kernel/binary_reduce.cc
- src/kernel/binary_reduce.h
- src/kernel/binary_reduce_impl.h
- src/kernel/binary_reduce_impl_decl.h
- src/kernel/cpu/backward_binary_reduce_impl.h
- src/kernel/cpu/binary_reduce_impl.cc
- src/kernel/cpu/binary_reduce_impl.h
- src/kernel/csr_interface.h
- src/kernel/cuda/backward_binary_reduce_impl.cuh
- src/kernel/cuda/binary_reduce_impl.cu
- src/kernel/cuda/binary_reduce_impl.cuh
- src/kernel/cuda/binary_reduce_sum.cu
This PR attempts to decouple `ImmutableGraph` from Kernels as much as possible.  This is necessary for running fused message passing on heterogeneous graphs.
Actual kernel routines in C take in `CSRWrapper` references, which can be constructed from either `ImmutableGraph` or `Bipartite` in the future.
> [Refactor] Decoupling ImmutableGraph from Kernels

- examples/mxnet/gat/train.py
- examples/mxnet/gat/utils.py
- examples/pytorch/gat/train.py
- examples/pytorch/gat/utils.py
Get 71.5% accuracy on citeseer (comparing to 70.7% without early stopping)
#743 
> [Model] Early stop GAT

- include/dgl/graph_interface.h
- python/dgl/graph_index.py
- src/graph/graph_apis.cc
- src/graph/immutable_graph.cc
Port the C Subgraph object to FFI, so that we can return Subgraph object directly to Python.
> use FFI for subgraph.

- examples/mxnet/gcn/gcn.py
- examples/pytorch/appnp/appnp.py
- examples/pytorch/gat/gat.py
- examples/pytorch/gcn/gcn.py
- examples/pytorch/gin/gin.py
- examples/pytorch/graphsage/graphsage.py
- examples/pytorch/model_zoo/citation_network/conf.py
- examples/pytorch/model_zoo/citation_network/models.py
- examples/pytorch/sgc/sgc.py
- examples/pytorch/sgc/sgc_reddit.py
- examples/pytorch/tagcn/tagcn.py
- python/dgl/model_zoo/chem/mpnn.py
- python/dgl/nn/mxnet/conv.py
- python/dgl/nn/mxnet/glob.py
- python/dgl/nn/pytorch/conv.py
- python/dgl/nn/pytorch/glob.py
- tests/mxnet/test_nn.py
- tests/pytorch/test_nn.py
As recommended by @jermainewang , it's better to use
```python
def forward(self, graph, node_feat, edge_feat=None, **kwargs)
```
as the unified forward interface for nn modules.
This PR refactors related code.
> [Refactor] Interface of nn modules

- python/dgl/backend/mxnet/tensor.py
- python/dgl/backend/pytorch/tensor.py
- tests/compute/test_kernel.py
- tests/distributed/test_shared_mem_store.py
As mentioned in #755 , `test_shared_memory` occasionally fails CI, as we have not found out the bug yet. We decide to disable this CI currently until we fixed the bug.
This change would not influence the correctness of other components in DGL.
- tests/distributed/test_shared_mem_store.py (disabled).
- tests/compute/kernel.py (improved the doc)
- python/backend/pytorch/tensor.py (fixed a bug in asnumpy)
> [bugfix] Disable shared memory test that may fails CI.

- examples/mxnet/gat/utils.py
- python/dgl/nn/mxnet/softmax.py
- python/dgl/nn/pytorch/softmax.py
- tests/mxnet/test_nn.py
- tests/pytorch/test_nn.py
Our original design of `edge_softmax` applies softmax on all edges of the graph. However, for some scenarios (e.g. beam search) users need to apply edge softmax on a subset of edges in the graph.
This PR changes the api from
```python
def edge_softmax(graph, logits)
```
to
```python
def edge_softmax(graph, logits, eids=ALL)
```
This change is compatible with previous API and allow users to specify the indices of edges to apply edge softmax on.
- dgl.nn.pytorch.softmax
- dgl.nn.mxnet.softmax
> [Feature] Edge softmax on a subset of edges in the graph.

- python/dgl/backend/pytorch/tensor.py
- python/dgl/view.py
- `torch.as_tensor` is recommended in new API, started from 1.0.0. It avoids copy as much as possible.
- This pr will convert np.ndarray to backend tensor when calling `g.ndata['feat'] = np.array(...)`. This simplifies the work in dataset part that don't need to manually convert numpy array to backend tensor. (example https://github.com/dmlc/dgl/blob/189c2c0907cdff54f733299a93360ddfcff4ccb7/python/dgl/data/chem/csv_dataset.py#L99)
> [Feature] Convert np.ndarray to backend tensor at set_n_repr and set_e_repr

- python/dgl/contrib/dis_kvstore.py
This pr improve the kvstore performance by using np.unique() operator, instead of bumpy loop.
> [Fix] use np.unique instead of loop

- python/dgl/convert.py
- tests/compute/test_heterograph.py
If the last few nodes in the last node type have no edges, `to_homo()` will crash.
See the added test case for details.
> [Bugfix] Fix number of nodes mismatch in to_homo() conversion

- include/dgl/runtime/ndarray.h
- python/dgl/data/graph_serialize.py
- src/graph/graph_serialize.cc
Cases:
The indices of a readonly graph without any edges will be a zero shape NDArray. And previously it's not properly handled in serialization.
Related issue:
https://github.com/dmlc/dgl/issues/883
Side notes:
For a zero-shape ndarray, should its ndim be 1 or 0?
> [Fix] Fix serialize NDArray when shape is 0

- src/graph/sampler.cc
When `neg_sample_size` is larger than the number of nodes in a graph, we can negatively sample at most the number of nodes in the graph.
> [BUGFIX] deal with neg_sample_size properly

- python/dgl/subgraph.py
- tests/compute/test_subgraph.py
If the parent doesn't have any node data or edge data, we shouldn't copy anything. Otherwise, the Frame in the subgraph will have 0 rows.
> [BUGFIX] check the number of columns in subgraph.copy_from_parent

- apps/kg/train.py
Current KG train.py script cannot work with only mxnet backend is installed.
There is an error package import.
> [BUG] Fix bug of KG train.py script.

- python/dgl/subgraph.py
- tests/compute/test_subgraph.py
Fixes #717 .
We were only testing on `SubGraphIndex` but not testing on the induced `DGLGraph`, which is why the bug gets away.
> [BUG] Fix #717

- examples/pytorch/appnp/train.py
- examples/pytorch/cluster_gcn/cluster_gcn.py
- examples/pytorch/dgi/train.py
- examples/pytorch/gat/train.py
- examples/pytorch/gcn/gcn_mp.py
- examples/pytorch/gcn/train.py
- examples/pytorch/graphsage/graphsage.py
- examples/pytorch/model_zoo/citation_network/run.py
- examples/pytorch/sampling/dis_sampling/gcn_cv_sc_train.py
- examples/pytorch/sampling/dis_sampling/gcn_ns_sc_train.py
- examples/pytorch/sampling/gcn_cv_sc.py
- examples/pytorch/sampling/gcn_ns_sc.py
- examples/pytorch/sgc/sgc.py
- examples/pytorch/sgc/sgc_reddit.py
- examples/pytorch/tagcn/train.py
Using ByteTensor for indexing has been deprecated in PyTorch, leading to many warnings in the example traning scripts. I've updated these to use BoolTensor.
> [Cleanup] Change Byte to Bool for training masks

- examples/mxnet/monet/README.md
- examples/mxnet/monet/citation.py
- examples/pytorch/appnp/train.py
- examples/pytorch/cluster_gcn/cluster_gcn.py
- examples/pytorch/gat/train.py
- examples/pytorch/gcn/gcn_mp.py
- examples/pytorch/gcn/train.py
- examples/pytorch/graphsage/graphsage.py
- examples/pytorch/model_zoo/citation_network/run.py
- examples/pytorch/monet/README.md
- examples/pytorch/sampling/dis_sampling/gcn_cv_sc_train.py
- examples/pytorch/sampling/dis_sampling/gcn_ns_sc_train.py
- examples/pytorch/sampling/gcn_cv_sc.py
- examples/pytorch/sampling/gcn_ns_sc.py
- examples/pytorch/sgc/sgc.py
- examples/pytorch/sgc/sgc_reddit.py
- examples/pytorch/tagcn/train.py
- python/dgl/nn/mxnet/softmax.py
- python/dgl/nn/pytorch/softmax.py
Docstring of edge softmax has some style problems.
Some pytorch examples are broken because BoolTensor do not support summation on CPU(BoolTensor was brought by #954).
> [Doc] hotfix for docstring and some examples

- examples/mxnet/dis_kvstore/client.py
- examples/mxnet/dis_kvstore/server.py
- examples/pytorch/dis_kvstore/client.py
- examples/pytorch/dis_kvstore/server.py
- python/dgl/contrib/dis_kvstore.py
- tests/compute/test_kvstore.py
Main change:
Add init_data() api on kvserver.
> [KVStore] add init api on kvserver

- python/dgl/convert.py
Fix #1018 . It seems that as of PyTorch 1.3.1, adding a `np.int64` object to a `torch.int64` tensor will give a `torch.float32` tensor. Explicitly converting the `np.int64` object to an `int` object fixes this problem.
> [Bug] Fix dgl.to_homo

- python/dgl/data/graph_serialize.py
Fixed small bugs in example code for documentation of saving/loading a graph. Specifically:
- In setting up graph to save, g1 was used to update the edge data instead of g2
- Save graph used the wrong order of arguments
- Load graph used the wrong import
> [Doc] Fix example code in saving/loading graphs

- python/dgl/graph.py
- python/dgl/heterograph.py
- tests/compute/test_heterograph.py
- tests/compute/test_to_device.py
When using pytorch, users are used to assigning the return value of to () to a new variable:
```
def to(...):
...
return self._apply(convert)
```
DGL's `to` behavior is different from pytorch, i.e. return None, which will cause bugs.
- [Convert BatchedDGL graph to cuda tensor](https://discuss.dgl.ai/t/convert-batcheddgl-graph-to-cuda-tensor/487/2)
> [Graph]To(device) should return updated object

- python/dgl/backend/pytorch/tensor.py
PyTorch documentation recommends saving the tensors required to compute gradients with `ctx.save_for_backward`.  However, DGL currently requires several non-tensor objects, which cannot be saved with `ctx.save_for_backward`, to compute gradients.  We previously worked around this issue by putting everything required in a Python attribute (`ctx.backward_cache`), but without explicitly clearing the cache (i.e. setting `ctx.backward_cache = None`), PyTorch autograd would have trouble deallocating the tensors created in forward() function, hence the memory leakage.  The workaround presumably raises another issue related to backward'ing with `retain_graph=True` according to #1046 .
The following code is copied and modified from `scatter_mul` function in PyTorch-Scatter, which demonstrates the …
> [Backend] Memory leak fix in PyTorch backend

- examples/pytorch/model_zoo/chem/README.md
Fix the outdated README.md about loading a pre-trained model for property prediction.
> [Chem Model Zoo] Hot fix for README

- python/dgl/convert.py
- tests/compute/test_heterograph.py
As #1072, we did not check if node ids are within specified cardinality.
This PR adds a `validate` flag to indicate whether to check validity of node id (defaults to False because it takes some time for large graphs).
- convery.py
- test_heterograph.py
> [hotfix] node id validity check

- python/dgl/backend/pytorch/tensor.py
Fixes deprecation warning by PyTorch
> [Backend] Rename saved_variables to saved_tensors

- apps/kg/dataloader/sampler.py
- apps/kg/eval.py
- apps/kg/models/general_models.py
- apps/kg/train.py
By default, we remove the positive edges from sampled negative edges in evaluation. We should allow disabling the filtering for fair comparison with other frameworks.
> [KG] Disable filter in evaluation

- include/dgl/sample_utils.h
- tests/cpp/test_sampler.cc
Some function names do not follow google C++ style.
As @jermainewang suggests, this PR fix these problems and mvoe sample utils to `dgl::utils` to avoid ambiguity.
- includes/dgl/sample_utils.h
> [Refactor] Renaming class methods of sampler utilities to improve readability

- python/dgl/convert.py
- tests/compute/test_heterograph.py
Heterograph creation crashes with empty list, empty src-dst pair, or empty networkX graph.  However, creating with 0x0 sparse matrix works well.
> [BUG] Fix empty heterograph creation with list & tuple

- apps/kg/dataloader/sampler.py
- tests/compute/test_sampler.py
copy_from_parent() is costy, so remove it:
Test:
python3 train.py —model TransE_l2 —dataset *Freebase* —batch_size 1000 —neg_sample_size 200 —hidden_dim 400 —gamma 10 —lr 0.1 —max_step 400000 —batch_size_eval 1000 -adv —num_proc 32 —gpu 0 1 2 3 4 5 6 7 —mix_cpu_gpu —regularization_coef 1e-9 
with copy_from_parent() 
sample: 14.238, forward: 15.154, backward: 4.530, update: 21.823
sample: 14.256, forward: 15.383, backward: 4.454, update: 21.402
without copy_from_parent() 
sample: 9.380, forward: 15.485, backward: 4.348, update: 21.533
sample: 8.249, forward: 16.283, backward: 4.341, update: 21.670
> [KG][Optimization] Remove copy from parent in minibatch generation

- tutorials/models/1_gnn/1_gcn.py
- tutorials/models/1_gnn/9_gat.py
With the latest version of PyTorch, a lot of warnings have been printed for deprecation messages, which should be fixed.
Replace `ByteTensor` with `BoolTensor` for node mask in loss computation.
> [Tutorial] Fix warnings due to PyTorch deprecation.

- include/dgl/random.h
Setting the same seed in the same run works, but not in different runs.
> [Bug?] Fix non-determinism when setting the same seed across different runs with single thread

- tests/compute/test_kernel.py
- tests/compute/test_sampler.py
The tensor generated for test cases in test_kernel.py is not deterministic for each CI run. This may incur some known failure cases (e.g., for l_op_r_max case, when two value in the max reduce stage are identical and are both the max value, this will fail the pytorch test_kernel test). Set the numpy seed each time it invoke generate_feature will eliminate this problem.
Also fix the print error in _print_error, which will crash every time when the test failed. 
#958
> [Test] Fix the random seed in test_kernel.py and fix the _print_error

- python/dgl/convert.py
- tests/compute/test_heterograph.py
- tests/compute/test_kernel.py
Building graph using dgl.bipartite or dgl.graph with both **data** and **card** set may crash when the node id provied in **data** is larger than the size specified in **card**.
Add boundary check for both dgl.bipartite and dgl.graph creation.
#1190 
> [Bug Fix] Add boundary check for heterograph build with card as input

- examples/pytorch/rgcn-hetero/README.md
- examples/pytorch/rgcn-hetero/entity_classify.py
- examples/pytorch/rgcn-hetero/test_classify.py
- python/dgl/data/rdf.py
RGCN-hetero model should be reloadable for further online and offline inference. But there are several none-deterministic points:
1. For rdf loader, if the graph caching is cleaned, the order of rdf triples loaded changes from run to run
2. For the model nn.Parameters (L160, entity\_classify.py), as g.canonical_etypes is none-deterministic from run to run, we should use torch.nn.ParameterDict() to store the tensors for different nodetype so that they can be loaded in inference step.
3. EntityClassify.rel_names (L222, entity\_classify.py) is not deterministic, which cause a random order of assigning basis_weight tensor for each relation type.
Also we provide an example of how to load the pre-trained model and do the inference (test) separately from traning. 
Updating the Readme.
#1240 …
> [Example] Fix Rgcn hetero nonedetermistic in graph and model initialization

- python/dgl/runtime/scheduler.py
- tests/compute/test_nodeflow.py
Issue #1288 
The bug happens when calling `apply_block` with built-in function. Added a temporary hack to handle the case since `Nodeflow` will be deprecated in the next release. Also added a unit test. Note that the fix is already included in #1143 .
> [Bugfix] Fix no attribute num_edges bug in Nodeflow

- src/runtime/object.cc
This commit fixes a bug where the lock guard (for concurrently accessing
the same scope from different threads) had basically no effect, due to
being bound to a temporary only.
> [Bugfix] Fix missing lock intialization

- include/dgl/runtime/packed_func.h
- src/c_api_common.h
GCC and clang has different symbol lookup implementation.
Standard reference:
https://en.wikipedia.org/wiki/Argument-dependent_name_lookup
> [Fix] Fix build on macos(clang)

- apps/kg/dataloader/sampler.py
https://github.com/dmlc/dgl/issues/1348 reports a bug caused by https://github.com/dmlc/dgl/pull/1343
The way we generate mini-batches in the training cannot deal with the batch whose size is smaller than usual. We need to ignore it.
> [KG][BUGFIX] fix sampler.

- python/dgl/transform.py
metis partition should generate a subgraph from the original graph, instead from a temporary graph.
> [BUGFIX] metis partition should generate a subgraph to the original graph.

- examples/pytorch/graphsage/train_sampling.py
- examples/pytorch/graphsage/train_sampling_multi_gpu.py
- python/dgl/heterograph.py
- tests/compute/test_heterograph.py
`dsttype` is now replaced with `DST/` prefixes.
Also adding two new interfaces `number_of_src_nodes()` and `number_of_dst_nodes()`.
> [Bug] Fix dsttype in GraphSAGE minibatch model

- docs/source/install/backend.rst
- docs/source/install/index.rst
The link to https://docs.dgl.ai/install/backend.html is broken in https://docs.dgl.ai/install/index.html#system-requirements
> [Doc] Fix link to backends docs

- include/dgl/base_heterograph.h
- include/dgl/immutable_graph.h
- python/dgl/backend/mxnet/tensor.py
- python/dgl/transform.py
- src/graph/heterograph.cc
- src/graph/heterograph.h
- src/graph/heterograph_capi.cc
- src/graph/immutable_graph.cc
- src/graph/unit_graph.cc
- src/graph/unit_graph.h
- tests/compute/test_transform.py
Added `as_immutable_graph` and `as_heterograph` that casts between `DGLGraph` and `DGLHeteroGraph` objects efficiently.
Note that this is only a temporary interface for the upcoming 0.4.3 release; in 0.5 we will unify DGLGraph and DGLHeteroGraph and deprecate these interfaces.
> [Feature] Casting between DGLGraph and DGLHeteroGraph

- include/dgl/transform.h
- python/dgl/transform.py
- src/graph/transform/to_bipartite.cc
- tests/compute/test_transform.py
Optionally we can choose not to include the DST nodes in SRC nodes for `to_block`.
This may offer a possibility for alternative implementation of operations such as `push` and `pull`.
> [Feature] Add an optional include_dst_in_src argument for to_block

- conda/dgl/bld.bat
- python/dgl/sampling/neighbor.py
- src/graph/metis_partition.cc
- src/graph/sampling/neighbor/neighbor.cc
- tests/compute/test_sampling.py
Looks like VS2015 has problem compiling something like this:
```c++
std::vector<int64_t> vec = ListValueToVector<int64_t>(list);
```
CI currently uses VS2017.
> [Windows] fix compilation issues on vs2015

- python/dgl/backend/__init__.py
- python/dgl/backend/set_default_backend.py
DGL currently asks for backend selection in standard input, which makes some automation (e.g. pip/docker installation) crash.  This reverts to the previous behavior of assuming PyTorch when backend is not given.  However, it also prints a warning in standard error asking for users to change the backend explicitly in either config file or `DGLBACKEND` environment variable if they wish.
> [Backend][Regression] Rolling back interactive backend selection

- python/dgl/nn/mxnet/conv/graphconv.py
- python/dgl/nn/pytorch/conv/graphconv.py
- python/dgl/nn/tensorflow/conv/graphconv.py
Simple fix to math notation in GraphConv documentation. Without this, math is not formatted correctly: https://docs.dgl.ai/en/0.4.x/api/python/nn.pytorch.html#graphconv
> [Doc] Fix GraphConv math notation

- docs/source/env_var.rst
Simply typo fixes in documentation.
> [Doc] Fix typos in env vars docs

- python/dgl/transform.py
When sampling with multi-processing, the sampler sometimes returns a corrupted original node ID array for destination nodes. The problem seems to be due to:
1. A PyTorch array is converted to a DGL array via DLPack.
1. It is then converted back to PyTorch array via DLPack. There is no data modification in the middle, so the conversion is actually redundant.
1. The array is then transmitted to another process via multi-processing mechanism.
The patch attempts to fix this by removing the redundant steps 1 and 2, though I haven't thoroughly verified whether the problem is completely solved.
> [Bugfix] Fix corrupted memory when using multi-processing

- python/dgl/contrib/dis_kvstore.py
- python/dgl/network.py
- src/graph/network.cc
- src/graph/network.h
- tests/compute/test_kvstore.py
Server side:
```
my_server = KVServer(server_id=0, server_namebook=server_namebook, num_client=1)
my_server.set_global2local(name='data_0', global2local=g2l_0)
my_server.set_global2local(name='data_1', global2local=g2l_1)
my_server.set_partition_book(name='data_0', partition_book=partition_0)
my_server.set_partition_book(name='data_1', partition_book=partition_1)
my_server.init_data(name='data_0', data_tensor=data_0)
my_server.init_data(name='data_1', data_tensor=data_1)
my_server.start()
```
client side:
```
my_client = KVClient(server_namebook=server_namebook)
my_client.connect()
my_client.init_data(name='data_2', shape=my_shape, dtype=F.float32, target_name='data_0')
```
Then the client can access `data_0`, `data_1`, and `data_2` . Note that,` my_client.init_data()` should be invoked …
> [KVStore] add init_data() on client

- python/dgl/data/gindt.py
In order to make the `label2idx` dictionary, tensor values should be used and not the tensor itself.
> [BUG] Fix bug in using degree_as_nlabel for GIN dataset

- python/dgl/convert.py
In `dgl.heterograph()`, inferring number of nodes for each types uses Python's builtin `max()` function which operates very slowly on tensors.  This fix uses `utils.toindex()` instead.
> [Performance] fixing performance on heterogeneous graph creation in specific cases

- python/dgl/graph.py
- python/dgl/graph_index.py
- python/dgl/heterograph.py
- python/dgl/heterograph_index.py
- python/dgl/utils.py
Issue #1494 reported that DGL 0.4.3+ is unable to read pickles dumped in 0.4.2-.  Decided to fix this since it would be quite an obstacle for people reproducing other's works on preprocessed datasets.
> [Bug?] Fixing compatibility of pickles across DGL versions

- examples/pytorch/gat/README.md
- examples/pytorch/gat/train_ppi.py
As reported in [thread 979](https://discuss.dgl.ai/t/bug-reported-the-evaluation-function-of-gat-ppi/979), previously the f1 evaluation for PPI is wrong. Since sigmoid has not been applied to the model output, the output values are logits rather than probabilities and the threshold for binary classification should be 0 rather than 0.5. Recall that sigmoid takes the form 1 / 1 + e^{-z}.
> [Bugfix] Fix GAT on PPI

- include/dgl/runtime/ndarray.h
- include/dgl/runtime/serializer.h
- include/dgl/runtime/shared_mem.h
- include/dgl/zerocopy_serializer.h
- python/dgl/distributed/client.py
- python/dgl/distributed/rpc.py
- python/dgl/distributed/server.py
- python/dgl/distributed/server_state.py
- src/graph/serialize/zerocopy_serializer.cc
- src/rpc/rpc.cc
- src/rpc/rpc.h
- src/runtime/ndarray.cc
- tests/cpp/test_zerocopy_serialize.cc
Currently non-shared-memory NDArray is not supported in same-machine inter-process serialization. (If you serialize a non-shared-memory NDArray, and deserialize it on the same machine, it will raise error.)
> [RPC] Zero copy serializer

- python/dgl/batched_heterograph.py
- tests/compute/test_batched_heterograph.py
Previously we do not allow batching heterogeneous graphs with zero nodes/edges for some type as discussed in #1261 . This PR aims to address it. As a result, we will support something as follows:
```python
import dgl
import torch
g1 = dgl.heterograph({
('user', 'follows', 'user'): [(0, 1), (1, 2)],
('user', 'plays', 'game'): []
})
g1.nodes['user'].data['h1'] = torch.tensor([[0.], [1.], [2.]])
g1.nodes['user'].data['h2'] = torch.tensor([[3.], [4.], [5.]])
g1.edges['follows'].data['h1'] = torch.tensor([[0.], [1.]])
g1.edges['follows'].data['h2'] = torch.tensor([[2.], [3.]])
g2 = dgl.heterograph({
('user', 'follows', 'user'): [(0, 1), (1, 2)],
('user', 'plays', 'game'): [(0, 0), (1, 0)]
})
g2.nodes['user'].data['h1'] = torch.tensor([[0.], [1.], [2.]])
g2.nodes['user'].data['h2'] = …
```
> [Hetero] Allow Batching Graphs with Zero Nodes/Edges

- apps/life_sci/python/dgllife/utils/eval.py
- apps/life_sci/tests/utils/test_eval.py
As requested in #1572 , we need to handle a corner case where the labels for a task have one single class only. In this case we will simply ignore this task and print a warning message.
> [DGL-LifeSci] Handle Same Labels for ROC AUC

- examples/pytorch/pinsage/README.md
remove the duplicate dataset_path from the PinSAGE example
> [Doc] correct PinSAGE knn example syntax

- python/dgl/graph.py
- python/dgl/graph_index.py
Creating `DGLGraph` from edge list will crash if node 0 does not have any edge.
Also fixes a documentation mistake in `DGLGraph.remove_edges`.
> [Bug] Fixing creation of DGLGraph crashing with no edge from node 0

- python/dgl/distributed/kvstore.py
- tests/distributed/test_new_kvstore.py
The current KVStore pull/push handler is global. It's better to make it per tensor. For example, a model contains learnable node embeddings and we want to train the model with control variate methods. We need to support push handler that updates node embeddings with sparse Adagrad as well as push handler that simply writes new data to the corresponding rows.
> [KVStore] make pull/push handler per tensor.

- python/dgl/convert.py
Reorder feature copy and id mapping assignment in `to_homo` function to fix #1682 .
Also apply the same change to `to_hetero`.
- dgl.convert
> [hotfix] Fix #1682

- python/dgl/batched_heterograph.py
- tests/compute/test_batched_heterograph.py
With PR #1660 , `DGLHeteroGraph.to` now returns a new `DGLHeteroGraph` and is no longer an in-place operation, which breaks the behavior of  `BatchedHeteroGraph`.
> [BatchedHeteroGraph] Fix BatchedHeteroGraph.to

- tutorials/basics/2_basics.py
- tutorials/basics/5_hetero.py
This is known to be slow and confuses a lot of new users so we decided to remove it from the tutorial.
The interface itself will probably be deprecated in favor of creation with pair of src-dst arrays.
> [Tutorial] Remove edge list creation

- python/dgl/_ffi/_ctypes/object.py
A debug message `in get attr` will be printed if an attribute is read from an FFI object.
> [Bug?] Remove debug message from __getattr__ of FFI objects

- tests/scripts/build_dgl.bat
According to https://issues.jenkins-ci.org/browse/JENKINS-9104 MSBuild has trouble running parallel builds unless each MSBuild instance is run with a unique MSPDBSRV endpoint.  I observed occasional Windows build failures and I guess this may be one of the reasons.
> [CI] Fix parallel msbuild

- python/dgl/distributed/rpc_client.py
During scanning the list of interfaces,
some of them can be configured invalidly:
lack of ip, link down etc.
This patch handles the error
and inform about problem with concrete interface.
Added handling of invalidly configured network interfaces from the list.
> Fix crashing on SIOCGIFADDR

- tests/cpp/socket_communicator_test.cc
Use random port to test SocketCommunicator avoid port re-binding.
> [TEST] Use random port to test SocketCommunicator

- src/rpc/network/socket_communicator.cc
- src/rpc/network/socket_communicator.h
- src/rpc/network/tcp_socket.cc
- src/rpc/network/tcp_socket.h
Refactor code to use timeval struct
for setting up the SO_RCVTIMEO variable
timeout value for sockets in case of Linux.
Changed SetTimeout API timeout input to seconds.
Fixing error : setsockopt(5, SOL_SOCKET, SO_RCVTIMEO, [600000], 4) = -1 EINVAL (Invalid argument)
SetTimeout API change from millsec to sec is only suggestion.
In case of need for millsec, SetTimeout body can be adjusted.
> Use timeval to set up SO_RCVTIMEO

- tests/distributed/test_dist_graph_store.py
When testing servers and clients, it's possible that clients run before the servers and somehow clients cannot connect to servers correctly sometimes. One option is to create barriers between servers and clients to synchronize servers and clients. However, it somehow prevents clients from running the tests. Making clients sleep seems to work better. However, this is a temporary fix. We need to figure out why sometimes the clients cannot connect the servers.
> [Test] Fix test of distributed graph

- python/dgl/data/heterograph_serialize.py
- tests/compute/test_serialize.py
The heterogenous graph save will crash when some edge type names are identical. (e.g., there are two edge types named 'knows':
```
>>> g_x = dgl.graph(([0, 1, 2], [1, 2, 3]), 'user',
...                   'follows', index_dtype=index_dtype, restrict_format='any')
>>> g_y = dgl.graph(([0, 2], [2, 3]), 'user', 'knows', index_dtype=index_dtype, restrict_format='csr')
>>> g_z = dgl.bipartite(([0, 1, 3], [2, 3, 4]), 'user', 'knows', 'knowledge', index_dtype=index_dtype)
>>> g = dgl.hetero_from_relations([g_x, g_y, g_z])
>>> save_graphs('/tmp/', g)
```
> [Bug Fix] Fix Heterogenous graph save crash when some edge type names are identical.

- examples/pytorch/gcmc/data.py
- examples/pytorch/graphsage/train_cv_multi_gpu.py
- examples/pytorch/graphsage/train_sampling_multi_gpu.py
Also fixes a bug in GCMC where spacy preprocessing crashes with a "cannot find model 'en'" error.
> [Bug] Fix redundant gradient sync code in GraphSAGE Multi-GPU examples

- examples/pytorch/rgcn/entity_classify.py
- python/dgl/heterograph.py
- python/dgl/transform.py
- python/dgl/utils.py
- tests/compute/test_heterograph.py
- tests/compute/test_transform.py
Outplace support for muations.
add_edges
add_nodes
remove_edges
remove_nodes
add_self_loop
remove_self_loop
> [Transfom] Mutable transform

- python/dgl/backend/backend.py
- python/dgl/backend/mxnet/tensor.py
- python/dgl/backend/pytorch/tensor.py
- python/dgl/backend/tensorflow/tensor.py
- python/dgl/distributed/sparse_emb.py
- tests/distributed/test_dist_graph_store.py
When recording data access from embeddings, we need to know whether the operation runs in the training mode or inference mode. We need to check if the system is recording all operators.
> [Distributed] turn off recording on embeddings in the inference.

- docs/source/api/python/ops.rst
- docs/source/index.rst
- python/dgl/backend/backend.py
- python/dgl/backend/mxnet/sparse.py
- python/dgl/backend/pytorch/sparse.py
- python/dgl/backend/tensorflow/sparse.py
- python/dgl/ops/sddmm.py
- python/dgl/ops/spmm.py
- python/dgl/sparse.py
- tests/compute/test_sparse.py
Duplicate of #1864 , the previous PR was closed because `graph_refactor` branch was merged.
------------previous context----------------
As described in #1863 , currently dgl's message passing function do not support 2nd-order derivative. This could be fixed by forcing backward function to call operators with autograd.
For the following code:
```python
import dgl
import torch as th
import dgl.ops as F
from torch.autograd import grad
x = th.rand(3, 4, requires_grad=True)
g = dgl.rand_graph(3, 9)
y = F.u_mul_v(g, x, x)
loss = y.sum()
x_grad = grad(loss, [x], create_graph=True)[0]
x_grad.sum().backward()
print(x.grad)
```
Before:
```
File "***.py", line 11, in <module>
x_grad[0].sum().backward()
File …
```
> [Feature] Support higher order derivative for message passing.

- examples/pytorch/jtnn/README.md
- examples/pytorch/jtnn/jtnn/datautils.py
- examples/pytorch/jtnn/jtnn/jtmpn.py
- examples/pytorch/jtnn/jtnn/jtnn_dec.py
- examples/pytorch/jtnn/jtnn/jtnn_enc.py
- examples/pytorch/jtnn/jtnn/jtnn_vae.py
- examples/pytorch/jtnn/jtnn/mol_tree_nx.py
- examples/pytorch/jtnn/jtnn/mpn.py
- examples/pytorch/jtnn/jtnn/nnutils.py
- examples/pytorch/jtnn/vaetrain_dgl.py
- python/dgl/_ffi/object.py
- python/dgl/heterograph.py
- python/dgl/sampling/pinsage.py
- src/array/cuda/csr_transpose.cc
- tests/compute/test_heterograph.py
- tests/compute/test_pickle.py
- tests/compute/test_shared_mem.py
- tests/test_utils/checks.py
- tutorials/basics/5_hetero.py
Also
* Fixes a problem in transposing an empty CSR matrix with CUSPARSE.
* Use `__dict__` for `__getstate__` and `__copy__` in `DGLHeteroGraph` so that we no longer have to explicitly specify the members to serialize; the serialization of graph storage is delegated to `__getstate__` of graph index in this way.
* Remove cached member `_nx_metagraph` since the property `metagraph` is not used often and `_nx_metagraph` will hinder the speed of serialization once materialized.  `metagraph` is now a method to indicate that the result will be computed every time we call it.
> [Model] Fixes JTNN for 0.5

- python/dgl/_ffi/function.py
Fix excessive warnings like `Warning: invalid API name "_deprecate.runtime.degree_bucketing._CAPI_DGLDegreeBucketing".`
> [Hotfix] fix excessive warnings

- python/dgl/transform.py
- tests/compute/test_graph.py
> [hotfix] Remove usage of deprecated API `adjacency_matrix_scipy'`

- python/dgl/sampling/__init__.py
- python/dgl/sampling/neighbor.py
- python/dgl/sampling/pinsage.py
- python/dgl/sampling/randomwalks.py
- src/random/cpu/choice.cc
Also fixes a bug where `dgl.sampling.sample_neighbors` never picks the first neighbor when sampling uniformly without replacement.
> [Doc] dgl.sampling docstring fixes

- examples/pytorch/rgcn-hetero/model.py
Previously the RGCN example calls `expand_as_pair` function to automatically do feature slicing.  This will be removed and we shall recommend users to do the slicing manually if they were to write their custom NN module to work with blocks, as per the user guide.
> [API] remove the expand_as_pair call

- python/dgl/transform.py
- tests/compute/test_transform.py
add_reverse_edges will crash when some nodes have zero degree.
To reproduce:
```
g = dgl.graph((F.tensor([0, 1, 3, 1]), F.tensor([1, 2, 0, 2])), num_nodes=6)
g.ndata['h'] = F.tensor([[0.], [1.], [2.], [1.], [1.], [1.]])
g.edata['h'] = F.tensor([[3.], [4.], [5.], [6.]])
bg = dgl.add_reverse_edges(g, copy_ndata=True, copy_edata=True)
```
> [HotFix] Fix add_reverse_edges

- examples/pytorch/graphsage/experimental/train_dist.py
Copy feature is now the bottleneck of distributed GraphSage. Let's move it to the sampler to accelerate feature copy. This is a temporary solution. We still need to reduce the overhead of feature copy afterwards.
> [Distributed] move feature copy to samplers in distributed GraphSage.

- python/dgl/distributed/dist_context.py
- python/dgl/utils/internal.py
- src/runtime/utils.cc
- tools/launch.py
When running all processes (trainer, sampler and server) together on the same set of machines, every process is competing for CPU resources. We need to set up the threads correctly to reduce the conflicts on CPU. The sampler processes and the server processes should use fewer threads.
> [Distributed] Set the number of threads correctly to speed up

- examples/pytorch/graphsage/experimental/train_dist.py
- examples/pytorch/graphsage/experimental/train_dist_unsupervised.py
- python/dgl/distributed/__init__.py
- python/dgl/distributed/dist_context.py
- tools/launch.py
If we start the server when importing dgl, the user code doesn't have the opportunity to define the user-defined functions that run on the server process. we should move the server start code to the initialize function. users can define UDF before the initialize function is called.
> [Distributed] Move server start code to initialize.

- python/dgl/backend/pytorch/tensor.py
- python/dgl/ops/spmm.py
- tests/compute/test_sparse.py
Previously DGL has undefined behavior for reduce result on zero-degree nodes. This PR sets them to all zero:
```python
>>> import dgl
Using backend: pytorch
>>> import torch as th
>>> g = dgl.graph(([0, 1, 2, 3], [1, 2, 3, 4]))
>>> x = th.rand(5, 10)
>>> dgl.ops.copy_u_max(g, x)
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
0.0000],
[0.3055, 0.1600, 0.7976, 0.1421, 0.8501, 0.0036, 0.4006, 0.8031, 0.9568,
0.0552],
[0.9056, 0.5081, 0.6965, 0.5684, 0.6408, 0.7829, 0.3059, 0.5300, 0.2697,
0.8028],
[0.0622, 0.6697, 0.1060, 0.4937, 0.7166, 0.7528, 0.2282, 0.4664, 0.4180,
0.6400],
[0.6326, 0.5684, 0.7983, 0.8936, 0.5530, 0.8989, 0.5928, 0.4090, 0.0238,
0.5744]])
>>> 
```
or have been fixed to be …
> [hotfix] Set reduce results to all zero for nodes with zero in-degrees.

- python/dgl/ops/spmm.py
The result tensor in spmm with sum reducer is initialized with all zeros, no need to set them to zeros again.
> [hotfix] Only filling zeros for isolated nodes in min/max reducer

- examples/pytorch/pinsage/README.md
- examples/pytorch/pinsage/data_utils.py
- examples/pytorch/pinsage/process_movielens1m.py
- examples/pytorch/pinsage/process_nowplaying_rs.py
Since `group_apply_edges` is removed the naive train-test split using pandas' `groupby` is unbearably slow.  This PR uses dask to parallelize stuff.
> [Model] Use dask to parallelize preprocessing for PinSAGE

- include/dgl/runtime/container.h
- python/dgl/sampling/neighbor.py
- tests/cpp/test_rowwise.cc
- tests/cpp/test_sampler.cc
Apparently MSVC 2017 (CL 19.10) cannot parse `static_cast<std::string>(value->data)`, which blocks the compilation of CUDA 9.0 binaries.
> [Windows] Work around the bug from CL 19.10

- README.md
- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
Previously compiling from source yields version 0.4.  This PR also bumps the build-from-source version to 0.6.  The 0.5 release is not affected since the version is updated separately.
> [Readme] 0.5.0 release and bump to new prerelease versions

- python/dgl/traversal.py
- tests/compute/test_traversal.py
> [Traversal] Fall back to CPU for Graph Traversal as a Workaround

- docs/source/conf.py
- docs/source/guide/graph-feature.rst
@classicsong brought up an issue on a code cell with manually numbered lines.  I don't like the appearance so I'm replacing it with `:lineno:` tag.
Also @classicsong mentioned that people wants to copy the code without prompts and outputs.  I found a solution using `sphinx-copybutton` extension.  Please check it out.
In the future developer's guide, we should put together another section settling the documentation style as well.
> [Doc] New style of code blocks with prompts; copy button

- src/runtime/ndarray.cc
See #2118 .
When tensor's size on first dimension is 1, the stride on first dimension does not strictly equals the production of sizes on following dimensions:
```python
>>> torch.randn((1, 5, 3))[:, :3, :].contiguous().stride()  # (15, 3, 1), however, we expect (9, 3, 1)
```
> [hotfix] IsContiguous failed when tensor's size on first dimension is 1.

- include/dgl/runtime/c_runtime_api.h
- src/graph/immutable_graph.cc
- src/graph/unit_graph.cc
The implementation of `FindEdges` requires that the COO matrix does *not* have a `data` array.  This is true because currently the only place where COO can have `data` is when it is converted from a CSR/CSC, and we currently do not directly create a CSR/CSC in any place.  Since things may change in the future, I'm preemptively adding this sanity check to prevent it from throwing us off with incorrect results.
> [Feature?] BUG_ON macro and sanity check of FindEdges

- python/dgl/heterograph.py
- src/graph/heterograph.cc
- tests/compute/test_heterograph.py
`FlattenHeteroGraph` does not wrap the C unit graph pointer with a C heterogeneous graph pointer as others do.  This makes it cannot work with other functions such as `apply_edges` as in #2166 .
Also added parameters, returns and examples for the docstring of flatten function.
> [Bugfix] Fix flatten not wrapping unit graph

- python/dgl/data/tu.py
Fixes issue #2165.
The graph labels are processed using the new static method `_idx_reset ` instead of the old static method `_idx_from_zero`. This new method remaps the labels to {0, ..., n-1} where n is the number of labels. Previously some datasets have labels {-1, 1} which were being mapped to {0, 2}, this change maps them to {0, 1}. 
I changed the notes since this class does perform additional process to the labels (before and after this fix).
> [Bugfix] fix TUDataset labelling issue (#2165)

- examples/pytorch/graphsage/experimental/train_dist_unsupervised.py
Fix a bug of using Pytorch’s DataLoader when distributed sampling.
> [Fix] use DistDataLoader instead of Pytorch’s DataLoader

- examples/pytorch/rgcn/experimental/partition_graph.py
to_homogeneous needs to pass edge feature list for saving the features in the generated g.
> [Hotfix] Fix partition of distributed rgcn example for 0.5.1

- python/dgl/dataloading/dataloader.py
This PR fixes a bug where EdgeDataLoader uses np.asarray to create an array of seed nodes instead of `utils.prepare_tensor`, which makes EdgeDataLoader crash on Windows.
> [Bug] Fix dtype mismatch in EdgeDataLoader on Windows

- tools/copy_files.py
Change rsync to scp of copy_files.py because rsync is very slow for big files.
> [Distributed] Change rsync to scp of copy_files.py

- examples/pytorch/graphsage/experimental/train_dist.py
Add `--close_profiler` option that can close the pyinstrument profiler.
> [Distributed Example] Add --close_profiler option to train_dist.py

- python/dgl/ops/segment.py
[segment_reduce()](https://github.com/dmlc/dgl/blob/7e0107c395b24fa55e080dee3903552430008b48/python/dgl/ops/segment.py#L9) supports zeor-length segments. But it fails if the zero-length segments is at the end of `seglen`. 
For example,
```python
import dgl
import torch
val = torch.ones(10, 3)
seg = torch.tensor([1, 0, 5, 4, 0])
x = dgl.ops.segment.segment_reduce(seg, val, "sum")
```
yields a value for `x` as 
```
tensor([[1., 1., 1.],
[0., 0., 0.],
[5., 5., 5.],
[4., 4., 4.]])
```
but it should be
```
tensor([[1., 1., 1.],
[0., 0., 0.],
[5., 5., 5.],
[4., 4., 4.],
[0., 0., 0.]])
```
This PR fixes this.
> Fix segment_reduce() ignoring tailing 0 segments

- python/dgl/nn/pytorch/conv/gatconv.py
- python/dgl/nn/pytorch/conv/nnconv.py
- python/dgl/nn/pytorch/conv/sageconv.py
Fix typo in docstrings of conv layers
> [Doc] Fix typo

- docs/source/install/index.rst
See [discussion #1342](https://discuss.dgl.ai/t/dgl-to-bidirected-throws-unsupported-graph-data-type-class-dgl-heterograph-dglheterograph/1342). Python 3.5 is no longer supported.
> [Doc] Fix Version Requirement

- python/dgl/data/dgl_dataset.py
An unexpected `AttributeError` exception is launched whenever the user defines `save_dir` on `DGLDataset` instantiation and uses `self._save_dir`  within `has_cache` method.
Initializes the attribute `self._save_dir` in all cases.
> [bugfix] Fix crash due to unfound attribute

- python/dgl/frame.py
Currently, when `Column.to(device)` is called, the index is copied to the device immediately, and the storage waits to be copied lazily. However, because the index and the storage need to reside on the same device in order to perform `gather_row()`, the index ends up getting copied again in the reverse direction. Furthermore, while the `kwargs` gets passed to the framework's copy method for the storage, it does not get passed for copying the index.
As seen in the below image of the graphsage example on the reddit dataset, this results in a large number of copy operations, including copying `self.index` to the gpu, only to copy it back to the cpu.
This PR fixes this, by only …
> [Bugfix][Performance] Fix Column to copy 'self.index' to location of 'self.storage' only on read, and use kwargs.

- src/graph/heterograph_capi.cc
- tests/compute/test_heterograph.py
The C implementation of `FindSrcDstNtypes` is incorrect, causing bugs in `is_unibipartite`.  Mentioned in https://discuss.dgl.ai/t/dgl-cuda-is-unibipartite-differs-from-dgl-cpu-build/1400
> [Bug] Fix bug in is_unibipartite

- docs/source/guide/nn-forward.rst
Some of SAGEGraph equation has typos as I mentioned in 0.5.x
> [Doc] Same typos as 0.5.x

- docs/source/api/python/dgl.dataloading.rst
- python/dgl/dataloading/async_transferer.py
- src/runtime/cuda/cuda_device_api.cc
This expand the documentation of the AsyncTransferer class from #2284. It also changes the behavior of new streams created, so as not to block with legacy default streams.
> [Doc][Dataloading] Expand documentation of AsyncTransferer

- python/dgl/backend/backend.py
- python/dgl/backend/mxnet/tensor.py
- python/dgl/backend/pytorch/tensor.py
- python/dgl/backend/tensorflow/tensor.py
- python/dgl/view.py
Create the arange on the target device directly using the backend, rather than creating it on the CPU, and copying it the target device.
The `arange` method in the backends was modified to accept a device context, and the HeteroNodeView was modified to make use of this, to avoid generating the range on the CPU, and then synchronously copying it up to the GPU.
> [Performance] In HeteroNodeView, build arange on target device, instead of on CPU and copying it

- examples/pytorch/ogb/README.md
- examples/pytorch/ogb/sign/.gitignore
- examples/pytorch/ogb/sign/README.md
- examples/pytorch/ogb/sign/dataset.py
- examples/pytorch/ogb/sign/sign.py
SIGN implementation for node predictions on ogbn-products, ogbn-arxiv and ogbn-mag.
Accuracy (10 runs, Tesla T4)
| Dataset         | Test Accuracy   | Validation Accuracy   | # Params    |
| :-------------: | :-------------: | :-------------------: | :---------: |
| ogbn-products   | 0.8052±0.0016   | 0.9299±0.0004         | 3,483,703   |
| ogbn-arxiv      | 0.7195±0.0011   | 0.7323±0.0006         | 3,566,128   |
| ogbn-mag        | 0.4046±0.0012   | 0.4068±0.0010         | 3,724,645   |
> [Model] SIGN for OGB dataset

- src/array/cuda/ge_spmm.cuh
- src/array/cuda/spmm.cu
- src/array/cuda/spmm.cuh
GE-SpMM is a SC2020 paper targets improving the performance of SpMM when dealing with scalar shape edge features.
The performance of GE-SpMM is better than cusparse in some settings. This PR implements GE-SpMM in DGL.
> [kernel] Select GE-SpMM when feature size is large.

- docs/source/api/python/dgl.dataloading.rst
- python/dgl/dataloading/async_transferer.py
- tests/compute/test_async_transferer.py
Disable using AsyncTransferer for copying to anywhere but the GPU, to avoid the failing unit. Will diagnose and create new PR re-enabling functionality once issue is identified.
Made AsyncTransferer.copy_async() raise a ValueError if the destination context is not the GPU.
Change the unit test to expect an a ValueError when the destination is not a GPU.
> [BugFix][Dataloading] Disable AsyncTransferer copying to anywhere but the GPU

- python/dgl/data/knowledge_graph.py
> [Doc] "bool" spell error in knowledge_graph.py

- CMakeLists.txt
- Jenkinsfile
- cmake/modules/CUDA.cmake
- cmake/util/FindCUDA.cmake
- src/array/cpu/array_op_impl.cc
This PR makes sure to include CUB/Thrust in our submodules rather than the system ones if CUDA version is no greater than 11.0.  It also removes a redundant NonZero implementation.
> [Bug] Multiple fixes for CUDA 11 support

- examples/pytorch/graphwriter/utlis.py
In the bucket sampler, the length array should be recovered after random picking samples. The previous implementation uses the permuted length array, so its value is wrong. 
[Examples] Fix a bug in the Bucket Sampler class of GraphWriter Example
> [Examples] Fix a bug in the training iterator of GraphWriter

- CMakeLists.txt
- cmake/modules/CUDA.cmake
GCC 5.4 is not fully compatible with CXX14 features (issues in #2291 ) while the latest CUB/Thrust library in CUDA requires CXX14. This is an attempt to use two sets of compiler flags.
> [Build] Use different flags for NVCC and CC

- .gitmodules
- CMakeLists.txt
- docs/source/env_var.rst
- include/intel/cpu_support.h
- include/intel/meta_utils.h
- src/array/cpu/spmm.h
- src/array/cpu/spmm_binary_ops.h
- tests/cpp/test_spmm.cc
* support AVX512
* env DGL_CPU_INTEL_KERNEL_ENABLED=1
* env DGL_CPU_INTEL_KERNEL_LOG=1
* Add unittest test_spmm.cc
Co-authored-by: Izabela Mazur <izabela.mazur@intel.com>
Co-authored-by: Michal Szarmach <michal.szarmach@intel.com>
In contrast to previous version,
1.	We decided to change the concept , the cache will be assign to static variable instead of thread_local ( btw. easy to change if we need).
2.	The kernel SpMMSumCsr supports all Ops ( CopyRhs , CopyLhs, Sum , Div … ) 
3.	Added unit tests (tests/cpp/test_spmm.cc).
4.	The kernel will be activated if dimension is greater than 16 and DGL_CPU_INTEL_KERNEL_ENABLED is set.
Our tests showed that there is no significant benefit to use the kernel for size less than 16.
This kernel is dedicated for larger dimensions.   
5.	 For any …
> [Performance] Dynamic cpu kernel V2 for SpMMSumCsr all Ops

- python/dgl/backend/backend.py
- python/dgl/backend/mxnet/sparse.py
- python/dgl/backend/mxnet/tensor.py
- python/dgl/backend/pytorch/sparse.py
- python/dgl/backend/pytorch/tensor.py
- python/dgl/backend/tensorflow/sparse.py
- python/dgl/backend/tensorflow/tensor.py
- python/dgl/ops/__init__.py
- python/dgl/ops/segment.py
- python/dgl/sparse.py
- src/array/cpu/segment_reduce.cc
- src/array/cpu/segment_reduce.h
- src/array/cpu/spmm.cc
- src/array/cuda/functor.cuh
- src/array/cuda/segment_reduce.cu
- src/array/cuda/segment_reduce.cuh
- src/array/kernel.cc
- src/array/kernel_decl.h
- tests/compute/test_sparse.py
Previously we created a pseudo graph and applied SpMM to get graph readout results, and introduced graph creation overhead. Thus PR implements segment operators to lower this (and corresponding coo/csr conversion) overhead.
> [Performance] Use segment operators for graph readout.

- python/dgl/batch.py
- python/dgl/utils/checks.py
Batching is slow in some of the Benchmarking GNN experiments.  This PR fixes that.
> [Performance] Accelerate batching

- src/array/cpu/spmat_op_impl_coo.cc
Remove the loop used to improve indptr in COOToCSR(), instead use CreateView() to enter the correct values at once.
> [Performance]: Remove indptr correction for CooToCSR

- src/array/cuda/spmm.cu
On g3 instance the performance of gespmm is 2x slower than cusparse.
> [hotfix] Disable gespmm because of performance degredation in g3 instance.

- docs/source/api/python/dgl.ops.rst
- python/dgl/backend/backend.py
- python/dgl/ops/segment.py
- python/dgl/sparse.py
- src/array/cpu/segment_reduce.h
- src/array/cuda/sddmm.cuh
- src/array/cuda/segment_reduce.cuh
- src/array/cuda/spmm.cuh
In #2361 we missed some docstring for segment operators. This PR add these docstrings and reveal the `dgl.ops.segment_reduce` API in DGL documentation.
> [doc] Add docstring for segment reduce.

- docs/source/guide/training-edge.rst
- python/dgl/convert.py
- tutorials/basics/1_first.py
- tutorials/models/1_gnn/1_gcn.py
1. The documentation of `heterograph` now mentions that DGL internally decides a deterministic order for node types and canonical edge types, which does not necessarily follow the order in `data_dict` argument. This has been requested by [thread 1555](https://discuss.dgl.ai/t/whta-is-the-order-of-c-etype-in-hetero-graph/1555/3).
2. Replace deprecated APIs (`dgl.DGLGraph`, `dgl.function.copy_u`, `dgl.data.citation_graph.load_cora`) in the tutorial and user guide.
3. The user guide section on edge classification/regression should not mention "or even whether an edge exists or not between two given nodes" as the scenario is for link prediction.
> [Doc, UG, Tutorial] Misc Fix

- python/dgl/core.py
The variable name 'eid' should be 'nid' in doc-string of function `invoke_node_udf`
> [Doc] Fix doc mistake in dgl/core.py

- tutorials/basics/3_pagerank.py.bak
I'm receiving register_message_func and register_reduce_func are deprecated error. I have updated the code such that message and reduce functions are passed to g.send and g.recv
> [Doc] Some functions used in the tutorial are deprecated

- src/rpc/rpc.cc
change msg_seq from int to int_64 to avoid potential bugs.
> [Rpc] change msg_seq from int to int_64

- src/array/cpu/array_op_impl.cc
Currently we parallelize DGL's arithmetic operations using OpenMP.  However the workload size of those operations are usually very light:
* For Benchmarking GNNs, the workload size is around 10k for SBM-PATTERN 100k experiments, and less than 100 for ZINC 100k experiments.
* For OGB products, the workload size is usually 1.
Using OpenMP to parallelize these operations will incur lots of overhead in thread spawning and scheduling, which is the main reason why Benchmarking GNNs experiments slowed down in 0.5+, especially in parallel experiments.
Here is the comparison of training time (seconds per epoch) on a g3.16x AWS instance between removing and keeping the OpenMP routines in Benchmarking GNNs experiments and OGB experiments:
```
0.4.2	0.5.3	0.5.3 No OMP
ZINC
GCN		2.1130	2.4221	2.1997 …
```
> [Performance][Hotfix] Disable openmp in arithmetic operation

- src/rpc/network/tcp_socket.cc
Currently, when a socket that binds to a port is closed, the socket cannot be reused for a few minutes. This is because the closed socket is in a wait status in the Linux kernel. More details can be found here: https://hea-www.harvard.edu/~fine/Tech/addrinuse.html
The fix is to make the socket reusable after the socket is closed.
> [RPC] Make the port reusable after the socket is closed.

- CMakeLists.txt
- cmake/config.cmake
- src/array/cpu/spmm.h
- tests/cpp/test_spmm.cc
> [hotfix] Make USE_AVX a flag in cmake to avoid compilation error for arm user

- CMakeLists.txt
- cmake/config.cmake
Set the `USE_AVX` flag's default value to `ON`.
> [hotfix] Enable AVX opt by default.

- python/dgl/dataloading/async_transferer.py
There is a small typo in python/dgl/dataloading/async_transferer.py.
Should read `transfer` rather than `tranfer`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, tranfer -> transfer

- python/dgl/heterograph.py
- tests/compute/test_basics.py
Previously when a computation graph is generated in `send_and_recv` or `pull` and message passing computation is computed, the results are written to the recipient nodes directly.  The recipient nodes may not have the same order as the output nodes in the generated graph.
Fixes #2484.
> [Bug] send_and_recv and pull may write to wrong places

- python/dgl/dataloading/dataloader.py
- python/dgl/dataloading/pytorch/__init__.py
- python/dgl/distributed/dist_graph.py
- tests/pytorch/test_dataloader.py
As requested in #2461 .
For semi-supervised learning with very few labels, creating a label tensor with the same size as the number of nodes wastes memory.  This change introduces the optional argument `return_indices` that allows the DataLoader to additionally return the indices of seed nodes/edges sampled in the minibatch.
```python
g = dgl.rand_graph(100, 1000)
sampler = dgl.dataloading.MultiLayerNeighborSampler([4])
dl = dgl.dataloading.NodeDataLoader(
g, torch.arange(0, 100, 5), sampler, batch_size=5, return_indices=True, shuffle=True)
next(iter(dl))
```
Output:
```
(tensor([15, 20,  0, 95, 35,  8, 78, 99, 73, 97,  6, 40,  2, 14, 92, 54, 16, 23,
30, 71, 50, 94, 93]),
tensor([15, 20,  0, 95, 35]),
tensor([ 3,  4,  0, 19,  7]),
[Block(num_src_nodes=23, num_dst_nodes=5, num_edges=20)]) …
```
> [Performance] Allow DataLoaders to return indices of the seed array

- examples/pytorch/metapath2vec/test.py
the code of examples/pytorch/metapath2vec/test.py has 2 bugs
Fix1,  add the venue label filepath, it's `file_1` that miss in code
Fix2, there are some redundant code for split the train and test data； 
annotate the print in loop of authors which is much more print information；
> [Examples] add venue label filepath; delete redundant code

- docs/Makefile
- new-tutorial/1_introduction.py
- python/dgl/nn/__init__.py
This PR fixes docserver crashes when importing `dgl.nn` on the docserver with PyTorch backend imports Tensorflow NN modules instead.
@jermainewang Our current doc server resides on a CPU machine so running sphinx gallery with GPU code will crash.  Should we upgrade that to a GPU machine?  If so, what about multi-GPU sphinx gallery examples in the future?
> [Doc] fix docserver build for tutorials

- docs/source/api/python/dgl.function.rst
We have got rid of `send` and `recv` API. We shouldn't explain our message passing with these two APIs any more.
> [Doc] avoid explaining message passing with `send` and `recv`

- README.md
- python/dgl/data/tu.py
- Fix undefined var bug in LegacyTUDataset. The `hidden_size` is undefined when we use constant node features.
- Fix cache file name bug in TUDataset.
@hetong007
> [Bug Fix] Fix undefined var bug in LegacyTUDataset

- docs/source/install/backend.rst
- python/dgl/backend/pytorch/tensor.py
> Fix pytorch version check

- python/dgl/dataloading/dataloader.py
This removes creating CSC and CSR matrices in the NodeDataloader. This essentially transfers work from the worker processes, to the training process, which helps to alleviate bottlenecks occurring in mini-batch generation. When training is done on the GPU, this avoids transferring 2 of the 3 copies of the graph to the GPU, in addition to shifting more work to the GPU.
When combined with #2391, this can lead to a larger performance improvement.
> [Performance] Don't create extra formats in dataloader

- python/dgl/backend/pytorch/sparse.py
- python/dgl/heterograph.py
- python/dgl/transform.py
This PR improves the docstring and fix the erroneous behavior of `dgl.reverse` in DGL's kernel (the formats should not change in message-passing phase).
> [doc][fix] Improve the docstring and fix its behavior in DGL's kernel

- python/dgl/backend/mxnet/sparse.py
- python/dgl/backend/pytorch/sparse.py
- python/dgl/backend/tensorflow/sparse.py
- python/dgl/heterograph.py
- python/dgl/sparse.py
This PR refactors the code to fix the formats behavior in message-passing, and mention this in the docstring.
This PR also fix the behavior in Tensorflow and MXNet.
It's the following PR of #2563 .
> [feature] Refactor code for retaining formats in message-passing.

- docs/source/api/python/nn.pytorch.rst
- python/dgl/function/message.py
- python/dgl/nn/pytorch/conv/__init__.py
- python/dgl/nn/pytorch/conv/ginconv.py
- python/dgl/nn/pytorch/conv/graphconv.py
- python/dgl/nn/pytorch/conv/sageconv.py
- tests/pytorch/test_nn.py
- tests/test_utils/graph_cases.py
This PR is for https://github.com/dmlc/dgl/issues/1281
I might need help on adding proper unit tests.
> [NN] Support scalar edge weight for GraphConv, SAGEConv and GINConv

- include/dgl/aten/array_ops.h
- src/array/array.cc
- src/array/array_op.h
- src/array/cpu/array_sort.cc
- src/array/cpu/spmat_op_impl_coo.cc
- src/array/cuda/array_sort.cu
- src/array/cuda/coo2csr.cu
- src/array/cuda/coo_sort.cu
- src/graph/unit_graph.cc
- tests/cpp/test_spmat_coo.cc
- tests/cpp/test_spmat_csr.cc
Avoid unnecessarily sort CSR columns, reduces the amount of work done when rows are sorted, and avoids synchronizing to double check if a COO is not sorted. It also parallelizes the conversion of an unsorted COO to CSR on the CPU, which can significantly reduce startup time (when the formats are generated for the global graph).
On `examples/pytorch/rgcn/entity_classify_mp.py` with the `ogb-mag` dataset, using the master branch with the PyTorch allocator, sorting on the GPU looks like:
And here it is with this PR:
With this PR, you can see, the check for if the matrix is sorted is removed, and the number of radix sort iterations is significantly reduced.
Changes UnitGraph to …
> [Performance] Improve COO to CSR, and sort columns of CSR only when necessary.

- src/array/cpu/spmat_op_impl_coo.cc
- src/runtime/cuda/cuda_common.h
* CUDA 9.2 fails building due to unintentional usage of `cusparseIndexType_t`.
* Mac fails building due to inclusion of `<omp.h>`.
> [Build] fix build problems

- examples/pytorch/metapath2vec/metapath2vec.py
Related issue [#2571](https://github.com/dmlc/dgl/issues/2571)
🐛 Bug
https://github.com/dmlc/dgl/blob/a613ad880690a8b155537117ea038a9de14111ed/examples/pytorch/metapath2vec/metapath2vec.py#L39
I'm using `pytorch=1.7.1` and it occurs:
```shell
File "metapath2vec.py", line 81, in <module>
m2v.train()
File "metapath2vec.py", line 39, in train
optimizer = optim.SparseAdam(self.skip_gram_model.parameters(), lr=self.initial_lr)
File "/home/S22/anaconda3/envs/stapy/lib/python3.8/site-packages/torch/optim/sparse_adam.py", line 49, in __init__
super(SparseAdam, self).__init__(params, defaults)
File "/home/S22/anaconda3/envs/stapy/lib/python3.8/site-packages/torch/optim/optimizer.py", line 47, in __init__
raise ValueError("optimizer got an empty parameter list") …
```
> Fix sparseadam bug in metapath2vec(pytorch)

- python/dgl/backend/mxnet/sparse.py
- python/dgl/backend/pytorch/sparse.py
- python/dgl/backend/tensorflow/sparse.py
- tests/compute/test_sparse.py
When apply `segment_sum` on segments with trailing zeros. The backward function would trigger out-of-boundary issue because we tried to access the `m`'th element of indices, which does not exist (the largest available index in `indices` is `m-1`).
The right solution would be adding a pseudo element in `indices` array and remove it after `scatter` and `cumsum`.
This PR also adds a unittest for this case.
> [bugfix] Solve the boundary issue in backward function of segment sum

- python/dgl/dataloading/dataloader.py
- python/dgl/dataloading/pytorch/__init__.py
- tests/pytorch/test_dataloader.py
Reverting the PR #2495 as requested by @jermainewang .
This functionality is deemed unnecessary since the memory consumption of labels is usually not a bottleneck.
> Revert PR #2495

- examples/pytorch/rgcn/experimental/get_mag_data.py
- tools/convert_partition.py
We now use relative paths for files of the partitioned data. We need to adjust the distributed partitioning script. This is to fix a bug after the PR that uses relative paths https://github.com/dmlc/dgl/pull/2690
> [Distributed] Fix the path for distributed partitioning.

- examples/pytorch/diffpool/README.md
- examples/pytorch/diffpool/model/dgl_layers/gnn.py
- examples/pytorch/diffpool/model/encoder.py
- examples/pytorch/diffpool/model/tensorized_layers/graphsage.py
- examples/pytorch/diffpool/train.py
* Fix bug in Diffpool: the wrong `assign_dim` param
* Improve efficiency of DiffPool, make the model independent of batch size. Remove redundant computation.
Details:
**efficiency**
On V100-SXM2 16GB
| Experiments       | Train time per epoch(s) | Memory usage(MB) |
| ----------------- | -----------------------: | ----------------: |
| Original-DD-bs=20 | OOM                     | OOM              |
| Original-DD-bs=10 | 21.302                  | 5274.620         |
| Original-ENZYMES  | 1.749                   | 25.685           |
| Improved-DD-bs=20 | 44.682                  | 10088.889        |
| Improved-DD-bs=10 | 17.282                  | 2928.568         |
| Improved-ENZYMES  | 1.685                   | 21.909           |
The accuracy is not affected by this improvement. I will list …
> [Example][Bug Fix] Improve DiffPool

- python/dgl/nn/mxnet/conv/agnnconv.py
- python/dgl/nn/mxnet/conv/edgeconv.py
- python/dgl/nn/mxnet/conv/gatconv.py
- python/dgl/nn/mxnet/conv/gmmconv.py
- python/dgl/nn/mxnet/conv/graphconv.py
- python/dgl/nn/mxnet/conv/sgconv.py
- python/dgl/nn/pytorch/conv/agnnconv.py
- python/dgl/nn/pytorch/conv/dotgatconv.py
- python/dgl/nn/pytorch/conv/edgeconv.py
- python/dgl/nn/pytorch/conv/gatconv.py
- python/dgl/nn/pytorch/conv/gmmconv.py
- python/dgl/nn/pytorch/conv/graphconv.py
- python/dgl/nn/pytorch/conv/sgconv.py
- python/dgl/nn/tensorflow/conv/gatconv.py
- python/dgl/nn/tensorflow/conv/graphconv.py
- python/dgl/nn/tensorflow/conv/sgconv.py
Fix typos in `zero-in-degree`, which were misspelled as `zere-in-degree`.
+ `dgl.nn.pytorch`
+ `dgl.nn.mxnet`
+ `dgl.nn.tensorflow`
> [Doc] Fix typos in `zero-in-degree`

- examples/pytorch/rgcn/link_predict.py
When running RGCN link prediction example, sometimes specified  number of epochs is exceeded.  
Issue reference: [https://github.com/dmlc/dgl/issues/2752](url)
Moved indentation of the conditional `break` statement left, so it no longer needs to satisfy the condition `if mrr < best_mrr` in order to break out of the training/evaluation loop.
> Bug fix for RGCN Link Prediction Example Exceeding Specified Epochs

- tutorials/blitz/4_link_predict.py
The number of edges should be same as posive eids.
With the description above, the number of negative edges should be the same as the number of positive edges.
Check live tutorial here: [Prepare training and testing sets](https://docs.dgl.ai/tutorials/blitz/4_link_predict.html#prepare-training-and-testing-sets)
> [Tutorial] Fix tutorial - blitz 4 link prediction

- README.md
- python/dgl/nn/pytorch/conv/sageconv.py
- tests/pytorch/test_nn.py
Use A(XW) instead of (AX)W when output feature dimensionality is greater than input feature dimensionality. This optimization was used in our GraphConv module but not in SAGEConv module: https://discuss.dgl.ai/t/gpu-kernels-while-running-graphsage-model/1449/4 .
@mufeili , @BarclayII please verify if it's equivalent to the original implementation.
> [performance] Optimize the association order of AXW in GraphSAGE.

- docs/source/guide/distributed-preprocessing.rst
Fix an error in the doc that explains the original node/edge IDs and clarify the explanation of 'orig_id' and `dgl.NID`
> [Doc] Clarify 'orig_id' and `dgl.NID` in distributed training

- docs/source/guide/minibatch-custom-sampler.rst
- docs/source/guide_cn/minibatch-custom-sampler.rst
- python/dgl/dataloading/dataloader.py
The 'return_eids' of dgl.dataloading.BlockSampler requires a default value. 
Otherwise when following the instructions of  [Chap6.4 of User Guide](https://docs.dgl.ai/en/0.6.x/guide/minibatch-custom-sampler.html#guide-minibatch-customizing-neighborhood-sampler). This error would occor:
File "/Users/hengruz/opt/anaconda3/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 163, in __init__
self.return_eids = return_eids
NameError: name 'return_eids' is not defined
Also, there is a mior mistake in MultiLayerDropoutSampler class in Chap6.4,  I've fixed it in this PR
> [Bugfix] add default value for BlockSampler

- src/array/cuda/array_cumsum.cu
- src/array/cuda/array_nonzero.cu
- src/array/cuda/array_sort.cu
- src/array/cuda/csr_sort.cu
- src/array/cuda/dgl_cub.cuh
- src/array/cuda/utils.cu
- src/runtime/cuda/cuda_hashtable.cu
This wraps all cub usages with CUB_NS_PREFIX, and removes the one use of thrust. This prevents symbol collision when linking against PyTorch 1.8.
This adds `/src/array/cuda/dgl_cub.cuh`, which should be included in place of `cub/cub.cuh`, and it wraps it in the appropriate namespace.
This also changes the implementation of NonZero to use [cub::DeviceSelect::If](https://nvlabs.github.io/cub/structcub_1_1_device_select.html#abec3c5afa3f1ca08e7b4fe3fd8990c39) instead of thrust.
> [Bugfix] Wrap cub with CUB_NS_PREFIX and remove dependency on Thrust to linking issues with Torch 1.8

- examples/pytorch/graphsage/load_graph.py
Method `dataset.num_labels` has been deprecated and replaced by `dataset.num_classes`.  
Updating the method name to avoid runtime warning.
> [Doc] Update deprecated method name in load_graph.py

- examples/pytorch/seal/sampler.py
Function coalesce_graph is undefined and unused.
So It occurs an error while running an example.
- [x ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
> [Example] remove unused and undefined function for running an example

- python/dgl/distributed/dist_dataloader.py
When a process exits, the sampler process pool will be closed. When we delete the data loader, we should double-check if the process pool has been closed or not.
> [Distributed] Cleanup the process pool correctly when the process exits.

- python/dgl/data/qm9_edge.py
When QM9EdgeDataset was downloaded and processed for the first time (not cached), there was a typo in `self.process` that caused a `KeyError`.
```python
from dgl.data import QM9EdgeDataset
ds = QM9EdgeDataset(force_reload=True)
```
```
KeyError: 'target is not a file in the archive'
```
This PR fixes that and also removes duplicate code so this can't happen in the future.
> [Bugfix] Fix processing of QM9EdgeDataset

- tools/launch.py
When running more than one trainer in a machine, the number of OMP thread will be set to 1 by default. This makes CPU training very slow. This PR adds an argument to the launch script to customize the number of OMP threads in trainers.
> [Distributed] Automatically setting the number of OMP threads for trainers

- python/dgl/convert.py
- src/graph/unit_graph.cc
This makes `g.create_formats_()` significantly faster for large graphs such as OGB-MAG240M.
> [Performance] Prefer parallelized conversion to CSC from COO instead of transposing CSR

- examples/pytorch/graphsage/experimental/README.md
- examples/pytorch/rgcn/experimental/README.md
- python/dgl/distributed/dist_dataloader.py
- tools/launch.py
Multiprocessing sampling may hang in distributed training when python version is 3.8. https://github.com/dmlc/dgl/issues/2315
For some reason, we need to create a barrier whenever we need it instead of using the one we created previously.
> [Distributed] Fix a bug in multiprocessing sampling.

- examples/pytorch/ogb_lsc/MAG240M/train_multi_gpus.py
- examples/pytorch/ogb_lsc/MAG240M/utils.py
the code is similar to https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_sampling_multi_gpu.py
related discussion:https://discuss.dgl.ai/t/will-mag240ms-baseline-code-use-multi-gpus-training-bring-efficiency-improvements/1878
Points that may need attention:
1. It may be necessary to perform performance testing again on the DGL server. The first Epoch may be slower because the feature needs to be cached.
2. I did not adjust the parameters (such as learning rate), which may cause the final accuracy rate to change.
3. Maybe the README should be updated.
> [example] multi gpus training for mag240m

- python/dgl/distributed/partition.py
- python/dgl/partition.py
- tests/compute/test_transform.py
- tests/distributed/test_mp_dataloader.py
- tests/distributed/test_partition.py
When we partition a graph, we reshuffle node/edge IDs. Sometimes users need this ID mapping between shuffled IDs and the original IDs so that they can adjust other data related to the partitioned graph.
> [Distributed] Return the ID mapping in graph partitioning.

- examples/pytorch/ogb_lsc/PCQM4M/main.py
As mentioned in #2349 , to use 4 workers in data loading can increase CPU memory usage with limited gain.
> [Example] Use 0 workers for PCQM4M by default

- python/dgl/nn/pytorch/conv/gatconv.py
- tests/pytorch/test_nn.py
Previously the forward computation of `GATConv` fails if `in_feats=out_feats` and `residual=True`.
> [NN] Fix GATConv for Broadcasting with Residual Connections

- python/dgl/dataloading/pytorch/__init__.py
- tests/pytorch/test_dataloader.py
Makes all loader iters return `self` in `__iter_` to enable type-checking with `collections.abc.Iterator`
This allows checks in Libraries like PyTorch Lightning (https://github.com/PyTorchLightning/pytorch-lightning/issues/7164)
- Add `__iter__` to all Iterators
> [Dataloading] Make loader iters iterator

- python/dgl/heterograph.py
- tests/compute/test_graph.py
- tutorials/models/1_gnn/4_rgcn.py
PyCharm accesses the `__len__` method for every variable during debugging, which will output lots of warning messages for DGLGraph objects.  Very uncomfortable.
Fixes #2901 .
> Remove __len__ method from DGLGraph

- python/dgl/nn/mxnet/conv/gatconv.py
- python/dgl/nn/pytorch/conv/gatconv.py
- python/dgl/nn/tensorflow/conv/gatconv.py
This PR enables GAT for inputs with axes greater than 2.  The computation will parallelize on the second to second-to-last axes.
Useful for batch computation on graphs with the same structure.  From now on, people can just do:
```python
x = torch.randn(num_nodes, batch_size, feat_dim)
m = dglnn.GATConv(feat_dim, out_dim, num_heads)
y = m(g, x)   # gives a (num_nodes, batch_size, num_heads, out_dim) tensor
```
Note that modules like `GraphConv` and `SAGEConv` already supports such semantics.
> [Feature] Support multidimensional features for GAT

- examples/pytorch/GATNE-T/src/main_sparse_multi_gpus.py
- examples/pytorch/gcmc/train_sampling.py
- examples/pytorch/graphsage/train_cv_multi_gpu.py
- examples/pytorch/graphsage/train_sampling_multi_gpu.py
- examples/pytorch/graphsage/train_sampling_unsupervised.py
- python/dgl/dataloading/pytorch/__init__.py
This PR adds a new flag `use_ddp` to the DataLoaders to handle shuffling and splitting using PyTorch's `DistributedSampler`.  Otherwise deadlocks might occur under some particular configurations of number of GPUs and batch size.
Also fixes a bunch of example models to use PyTorch's `DistributedSampler`.
Fixes #2539.
> [Feature] Add a use_ddp flag to PyTorch Node/Edge/GraphDataLoaders for multi-GPU training

- python/dgl/nn/pytorch/conv/gatconv.py
A linear layer (res_fc) is used to reshape features to the shape of the output feature of GATConv (in dimensions of out_feats * num_heads) for the residual connection. However, the previous conditional check failed to cover this.
> Fixing issue #2921

- tutorials/blitz/4_link_predict.py
There is a typo in the sample codes for the section Prepare training and testing sets.
```
train_size = g.number_of_edges() - test_size
test_pos_u, test_pos_v = u[eids[:test_size]], v[eids[:test_size]]
train_pos_u, train_pos_v = u[eids[test_size:]], v[eids[test_size:]]
```
[V] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
[V] Changes are complete (i.e. I finished coding on this PR)
[V] Related issue is referred in this PR
> [Doc] Fix a typo in the tutorial for link prediction

- python/dgl/nn/mxnet/conv/gatconv.py
- python/dgl/nn/pytorch/conv/gatconv.py
- python/dgl/nn/pytorch/conv/sageconv.py
- python/dgl/nn/tensorflow/conv/gatconv.py
- tests/mxnet/test_nn.py
- tests/pytorch/test_nn.py
- tests/tensorflow/test_nn.py
- tests/test_utils/graph_cases.py
This is a reopen of #2947 (originally from @jxgu1016).
The test case was spelled wrong, and as a result some of cases are never tested.
> [Bug] Fix shape mismatch with block inputs for multiple modules

- tutorials/large/L0_neighbor_sampling_overview.py
Fix a typo in the tutorial for "Introduction of Neighbor Sampling for GNN Training".
There is a typo in the text. The term is inconsistent with the gif demo.
[V] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
[V] Changes are complete (i.e. I finished coding on this PR)
[V] Related issue is referred in this PR
> [Doc] Fix a typo in the tutorial for Neighbor Sampling

- examples/pytorch/rgcn/link_predict.py
Related to issue #2956 
corrected docstring, the model uses two R-GCN layers
-  [x] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).
> [Doc]Update link_predict.py docstring

- README.md
Starting from May 26th 2021 the nightly builds are uploaded to https://data.dgl.ai/wheels-test/repo.html.
> [Build] Update nightly installation locations

- CMakeLists.txt
Sometimes when you installed an older NCCL in system but plan to use NCCL submodules it will crash with an error:
```
/mnt/b/gq/dgl/src/runtime/cuda/nccl_api.cu(580): error: identifier "ncclSend" is undefined
detected during instantiation of "void dgl::runtime::cuda::NCCLCommunicator::AllToAllV(const DType *, const int64_t *, DType *, const int64_t *, cudaStream_t) [with DType=int32_t]"
(591): here
/mnt/b/gq/dgl/src/runtime/cuda/nccl_api.cu(584): error: identifier "ncclRecv" is undefined
detected during instantiation of "void dgl::runtime::cuda::NCCLCommunicator::AllToAllV(const DType *, const int64_t *, DType *, const int64_t *, cudaStream_t) [with DType=int32_t]"
(591): here
... (and more)
```
> [Build] Fix NCCL building crashes when using submodules but with system NCCL installed

- python/dgl/convert.py
- tests/compute/test_heterograph.py
- tests/compute/test_pickle.py
- tests/compute/utils.py
Previously calling `to_homogeneous` and then `to_heterogeneous` again will return a graph which is not identical to the original graph.  This is because `numpy.argsort` by default is not stable.  Although `to_heterogeneous` stores a mapping to the homogeneous graph, which *technically* allows constructing back to the original graph using some inverse mapping, this is a huge hassle when performing (1) homogeneous neighbor sampling (see https://discuss.dgl.ai/t/multilayerneighborsampler-usage-in-heterogenous-graph/1993/5), or (2) computing on heterogeneous graph and homogeneous representation in parallel (I remember @Theheavens has an example).
This PR fixes the issue by making `to_heterogeneous(to_homogeneous(hg))` return a graph identical to `hg`.
Please feel free to remove inapplicable …
> [Feature] Make to_heterogeneous(to_homogeneous(hg)) return hg

- examples/pytorch/gcmc/README.md
- examples/pytorch/gcmc/data.py
When reproducing [GCMC example](https://github.com/dmlc/dgl/tree/master/examples/pytorch/gcmc) using the newer version of PyTorch (1.8+) with torchtext 0.9+ I kept getting the following error:
```
Total user number = 943, movie number = 1682
File "train.py", line 241, in <module>
train(args)
File "train.py", line 71, in train
dataset = MovieLens(args.data_name, args.device, use_one_hot_fea=args.use_one_hot_fea, symm=args.gcn_agg_norm_symm,
File "/workspace/gcmc/data.py", line 175, in __init__
self.movie_feature = th.FloatTensor(self._process_movie_fea()).to(self._device)
File "/workspace/gcmc/data.py", line 517, in _process_movie_fea
TEXT = torchtext.data.Field(tokenize='spacy', tokenizer_language='en_core_web_sm')
AttributeError: module 'torchtext.data' …
```
> [Model] Fixed AttributeError in GCMC example with new version of torchtext (0.9+).

- docs/source/guide/message-efficient.rst
- docs/source/guide_cn/message-efficient.rst
Specifying output dimension of 1 may be too special and misleading. It can be more clear, if we change it to a variable "out_dim", which is similar to the "node_feat_dim". @zhjwy9343 
> [Doc] changing of output dimension

- include/dgl/runtime/parallel_for.h
This PR implements `parallel_for`, a function wrapper that allows controlling number of threads executing OpenMP parallel region by setting grain size, a number of iterations a single OpenMP thread will execute.
> [CPU Parallel] implementation of parallel_for with grain size

- src/graph/sampling/randomwalks/metapath_randomwalk.h
Added a special implementation for MetapathBasedRandomWalkStep for the Uniform randomwalk case
There is a big performance issue with the implementation of the `MetapathRandomWalkStep` function. Specifically with the lines - 
```
FloatArray prob_etype = prob[etype];
IdxType idx = 0;
if (IsNullArray(prob_etype)) {
```
The copy constructor and destructors of type FloatArray update the reference count for the underlying data buffer. This is an atomic operation since FloatArray is supposed to be thread safe. But when `MetapathRandomWalkStep` function is called from multiple threads potentially running on multiple cores, the same integer value (refcount) is read and written concurrently from all the threads. This leads to cache ping-ponging and a severe performance hit. The first change in this …
> [Performance][Kernel] Eliminating ctor&dtor zand IsNullArray overhead in random walks

- examples/pytorch/graphsage/train_sampling_multi_gpu.py
The training set was being silently cut down to a single batch in the example. This restores training on the whole training set, and adds `ogbn-products` dataset.
> [Bugfix][Examples] Fix graphsage multigpu training example training set size

- include/dgl/runtime/parallel_for.h
- src/runtime/parallel_for.cpp
This PR introduces implementation of `parallel_for` function with default grain size.
Default grain size is set to 1 in which case `parallel_for` acts as OpenMP parallel for pragma with static scheduling, or can be globally set to a value controlled with environment variable `DGL_PARALLEL_FOR_GRAIN_SIZE`.
The idea behind this implementation is that user could start parallelizing code with `parallel_for` with default grain size, and set grain size either through environment variable or by using `parallel_for` with grain size parameter when performance requirements are not satisfied.
> [CPU, Parallel] parallel_for with default grain size

- examples/pytorch/rgcn/entity_classify_mp.py
Make it so that test_acc will always be computed at the last epoch, so as to have the final reported test accuracy actually reflect the final accuracy, as well as prevent errors when the test accuracy does not get computed:
```
UnboundLocalError: local variable 'test_acc' referenced before assignment
```
> [bugfix][example] Fix RGCN example so that test_acc is always computed at last epoch

- python/dgl/nn/pytorch/sparse_emb.py
- python/dgl/partition.py
- tests/pytorch/test_sparse_emb.py
This renames the method `NodeEmbedding.gather_embedding()` to `NodeEmbedding.all_get_embedding()` to make its usage more clear, and adds the method `NodeEmbedding.all_set_embedding()`, which is needed by tests in #3034, for initializing the embedding to the same values as a pytorch embedding.
> [Feature][GPU] Add function for setting weights of a sparse embedding on multiple GPUs.

- python/dgl/nn/pytorch/conv/graphconv.py
in https://docs.dgl.ai/en/0.6.x/api/python/nn.pytorch.html#edgeweightnorm
we can't see two math formulas that would be displayed to us.
`math:` to `math::`
> EdgeWeightNorm Fix doc

- src/runtime/cuda/nccl_api.cu
If a process has no elements to update in an iteration, it try to launch a kernel with zero threads, which results in an error. This conditionally launches the kernel if there are elements to process.
> [Bugfix] Handle case where process has no elements to update, in NCCL communicator

- python/dgl/data/tu.py
Fixes #2915 .  This is not really a fix but it does put a note on the discrepancy between DGL and other frameworks such as PyTorch Geometric for fair studies.
@HenryKenlay
> [Doc] Add a note on possible duplicate edges in TUDataset

- python/dgl/transform.py
fix minor docstring issue. such part is not correctly displayed: 
https://docs.dgl.ai/generated/dgl.to_block.html#dgl.to_block
> [Doc] fix docstring in to_block()

- docs/source/api/python/dgl.rst
- docs/source/api/python/dgl.sampling.rst
- docs/source/conf.py
- python/dgl/sampling/neighbor.py
- python/dgl/transform.py
- tests/compute/test_sampling.py
- tests/compute/test_sort.py
- Fixed the missing API doc for `dgl.sampling.sample_neighbors_biased`, `dgl.sort_in_edges` and `dgl.sort_out_edges`.
- Also fixed some formatting issue.
**One question:** the `dgl.sort_in_edges` and `dgl.sort_out_edges` APIs are designed quite specifically. Shall we have a more specific name? For example, `dgl.sort_graph_csr_by_in_edges` ? @BarclayII 
> [Doc] Add docstring for missing APIs

- include/dgl/runtime/c_runtime_api.h
- include/dgl/runtime/tensordispatch.h
- python/dgl/_ffi/base.py
- src/array/cuda/spmm.cu
- src/runtime/c_runtime_api.cc
- src/runtime/tensordispatch.cc
Two things related to building in one PR:
1. Current heterogeneous SPMM crashes on Windows build because we put a `#if` in `SWITCH_BITS` apparently.  Worked around that.
2. Add an attribute `dgl._ffi.base.tensor_adapter_loaded` indicating whether tensor adapter library is correctly loaded.
> [Build] Tensoradapter indicator and Windows builds

- src/array/cuda/rowwise_sampling.cu
This causes problem with pytorch 1.9 on cuda11.1
> [Fix] Fix wrong cub include problem

- CMakeLists.txt
Remove `-march=native` option since it will optimize for the current CPU instruction set, which may crash on other CPUs.
Observed on current CI failures.
> [Build] Remove native flag

- docs/source/gen_dataset_stat.py
- python/dgl/data/__init__.py
- python/dgl/data/gnn_benchmark.py
DGL removes the duplicate edges after adding the reverse edges, thus giving a different number from the original dataset.
Also fixes a long-standing typo.  Surprised that nobody noticed including myself.
> [Doc] Fix CoraFull number of edges inconsistency in doc

- src/graph/sampling/randomwalks/metapath_randomwalk.h
- src/graph/sampling/randomwalks/node2vec_randomwalk.h
We have noticed that random walks have a speed regression of around 30%.  The reason was the repetitive call of `CSRHasData`.
With this fix, random walks on livejournal with 1000 nodes and length 10 reduces from 2213μs to 334μs per call (averaged over 5000 calls) on g3.16x.
Previously @VoVAllen warned us about this regression but somehow I failed to reproduce it last time so I dismissed it...
> [Regression] Speed up random walks

- python/dgl/dataloading/pytorch/dataloader.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
- tests/distributed/test_mp_dataloader.py
This PR makes `EdgeDataLoader` work on a distributed graph. In addition, it enables `find_edges` on distributed heterogeneous graphs and `edge_subgraph` on distributed heterogeneous graphs.
> [Distributed] Enable distributed EdgeDataLoader

- python/dgl/optim/pytorch/sparse_optim.py
In python 1.8, when `non_blocking=True` in a GPU->CPU copy, the output tensor is allocated in pinned memory (the cause of #2760). However, this now results in a performance regression between 0.6 and 0.7 when using torch>=1.8.
This PR re-enables using pinned memory for those transfers, while synchronizing afterwards to ensure correctness. This cuts time in the optimizer dramatically (on my system nearly 2x--but it will vary from system to system):
Used cuda events to allow specifying `non_blocking=True` when transferring from the gradient computation device (GPU) to the state storage device (CPU).
This also re-arranges some operations in order to better in order to reduce the …
> [Performance] Enable using pinned memory for transfers in SparseAdam optimizer.

- tests/tools/test_launch.py
- tools/launch.py
This PR fixes `tools/launch.py` to correctly handle udf_commands like: `python3.7 train_dist.py`.
Context: Currently, `tools/launch.py` will incorrectly mangle a udf_command like: `python3.7 train_dist.py` into something like:
```
python3 -m torch.distributed.launch [TORCH DIST ARGS] .7 train_dist.py
python3.7 -m torch.distributed.launch [TORCH DIST ARGS] train_dist.py
```
This is because in the `tools/launch.py` code, it does a blind string replace for a substring like "python3" and replaces it with "python3 " (note the space).
This PR somewhat generalizes the way it does the search+replace by first searching for more specific binary names like "python3.7, python3.8" before falling back to more generic "python3, python" binary names.
Testing: I've written unit tests to validate the …
> [Tools] Refactor tools/launch.py to handle more python binary names

- python/dgl/dataloading/pytorch/dataloader.py
It looks like when we refactored in #3046, we changed the check for `num_workers == 0` to `num_workers != 0`. This PR restores the original functionality introduced in #2716, such that when the output device is on the GPU and the number of workers is 0, a pytorch tensor will be used to store the batch, rather than a python list.
This fix results in a ~2x reduction in the runtime of the dataloader, depending on the size of the fanouts.
Changed the check for number of workers.
> [bugfix] Fix check for num_workers for using _ScalarDataBatcher

- src/runtime/tensordispatch.cc
- tensoradapter/pytorch/CMakeLists.txt
This fixes #3220.
Currently, the tensoradapter is linked against all the of the dependencies of libtorch, including specific cuda libraries, despite only depending on symbols in libtorch (as far as I can tell).
This PR changes it to only depend on libtorch, which on systems without the exact same cuda version that DGL was built against, enables the tensoradapter, where it previously was silently being disabled.
Change the CMakeLists.txt to only link against libtorch.
Add a warning message if `dlopen` fails.
> [bugfix] Only link the pytorch tensordispatcher against libtorch

- docs/source/guide/nn-construction.rst
- docs/source/guide/training-edge.rst
- docs/source/guide/training-graph.rst
- python/dgl/nn/pytorch/utils.py
While going through your user guide I found some typos I'd like to fix.
> [Doc] fixed typos in docs and docstring

- python/dgl/nn/pytorch/conv/graphconv.py
formula in EdgeWeightNorm is not displayed as expected in docs.dgl.ai. fix it.
> [Doc] fix formula display issue in EdgeWeightNorm

- src/array/cuda/cuda_filter.cu
Currently the master branch will fail to compile on CUDA 10.2 and 11.1 because it cannot recognize `OrderedHashTable` as a template.
> [Build] Fix weird CUDA 10.2 and 11.1 compilation issues

- include/dgl/runtime/parallel_for.h
- src/array/cpu/array_op_impl.cc
- src/array/cpu/array_pack.cc
- src/array/cpu/array_scatter.cc
- src/array/cpu/csr_get_data.cc
- src/array/cpu/csr_mm.cc
- src/array/cpu/csr_sort.cc
- src/array/cpu/csr_sum.cc
- src/array/cpu/csr_union.cc
- src/array/cpu/rowwise_pick.h
- src/array/cpu/sddmm.h
- src/array/cpu/segment_reduce.h
- src/array/cpu/spmat_op_impl_coo.cc
- src/array/cpu/spmat_op_impl_csr.cc
- src/array/cpu/spmm.h
- src/graph/graph_op.cc
- src/graph/heterograph_capi.cc
- src/graph/network.cc
- src/graph/sampler.cc
- src/graph/sampling/randomwalks/randomwalks_cpu.h
- src/graph/transform/cpu/knn.cc
- src/graph/transform/partition_hetero.cc
- src/random/random.cc
- src/rpc/rpc.cc
The PR replaces uses of OpenMP `parallel for` pragma with `parallel_for` primitive wherever it was possible (no `reduction`, `atomic`, `critical` or `barrier` clauses). 
This PR continues and includes work introduced by #3023 and #3027. The mentioned PRs contain initial benchmarking and information about performance regressions. This PR includes commits from earlier PRs and replaces additional pragmas. The earlier PR are going to be closed.
> [Performance, CPU] Rewriting OpenMP pragmas into parallel_for

- python/dgl/dataloading/dataloader.py
When both `g` and `g_sampling` are specified, the edge IDs to exclude should be from `g_sampling` rather than `g`.
> [Bug] Fix edge ID exclusion when both g and g_sampling are specified in EdgeDataLoader

- python/dgl/geometry/fps.py
- src/geometry/cuda/geometry_op_impl.cu
- tests/pytorch/test_geometry.py
I fix two bugs in `farthest_point_sampler` and add a test case for `start_idx`.
> [Bugfix] Fix bugs of `farthest_point_sampler`

- src/array/cpu/spmat_op_impl_coo.cc
- tests/cpp/test_spmat_coo.cc
fix the potential huge memory consumption issue when converting coo to csr. refer to https://github.com/dmlc/dgl/issues/3307 for more details.
Implementation and Complexity details. N: num_nodes, NNZ: num_edges, P:
num_threads.
1. If row is sorted in COO, SortedCOOToCSR<> is applied. Time: O(NNZ/P).
Space: O(1).
2. If row is NOT sorted in COO and graph is sparse (low average degree),
UnSortedSparseCOOToCSR<> is applied. Time: O(NNZ/P + N/P + P^2), space O(NNZ +
P^2).
3. If row is NOT sorted in COO and graph is dense (medium/high average
degree), UnSortedDenseCOOToCSR<> is applied. Time: O(NNZ/P + N/P), space O(NNZ +
N*P).
> [Performance] improve coo2csr space complexity when row is not sorted

- src/array/cpu/spmat_op_impl_coo.cc
- tests/compute/test_transform.py
- tests/cpp/test_spmat_coo.cc
bug fix for https://github.com/dmlc/dgl/pull/3326. coo.data was not initialized when converting row sorted coo to csr on cpu.
> [BugFix] initialize data if null when converting from row sorted coo to csr

- examples/pytorch/graphsage/model.py
This provides a speedup during the validation/testing of the graphsage example by letting `to_block` be performed on the GPU when the number of workers is zero, and does not shuffle the dataset in validation/testing.
> [Example][Performance] Enable faster validation for pytorch graphsage example

- python/dgl/data/fakenews.py
Fix typo in variable name (train_mask -> test_mask)
> [BugFix] fix typo in variable name

- tools/launch.py
This PR will all users to pass-in arbitrary environment variables when launching distribute training tasks.
For example:
```
python3 -u ~/dgl/tools/launch.py --workspace <workspace> --extra_envs  "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" "NCCL_DEBUG=INFO"  --num_trainers 8 ...
```
> [Distributed] Allow user to pass-in extra env parameters when launching a distributed training task.

- CMakeLists.txt
- python/dgl/distributed/rpc.py
- src/graph/network.cc
- src/rpc/network/communicator.h
- src/rpc/network/msg_queue.cc
- src/rpc/network/msg_queue.h
- src/rpc/network/socket_communicator.cc
- src/rpc/network/socket_communicator.h
- src/rpc/network/socket_pool.cc
- src/rpc/network/socket_pool.h
- src/rpc/network/tcp_socket.cc
- src/rpc/network/tcp_socket.h
- src/rpc/rpc.cc
- src/runtime/semaphore_wrapper.cc
- src/runtime/semaphore_wrapper.h
- tests/cpp/socket_communicator_test.cc
Implement one thread multiple socket with epoll on linux platform. 
Current SocketSender and SocketReceiver will create one thread for each socket. When number of nodes, number of servers/trainers/samplers in each node increase, there will be several thousands of threads created for socket communicating. That is a waste of resources because creating threads requires some memory, and context switch between threads takes time.
* Add an argument of max_thread_count for socket communicator's sender and receiver. They will create at most max_thread_count threads instead of one thread for each socket. If max_thread_count is set to zero (by default), it will fallback to one thread per socket.
* Add a class SocketPool to maintain a group of sockets. The sockets in SocketPool will be set to …
> [Feature] Implement one thread multiple socket

- python/dgl/data/utils.py
- tests/compute/test_data.py
reported in https://discuss.dgl.ai/t/extract-archive-does-not-extract-file-in-target-folder-when-using-gz-file/2365
extracted gz file is not placed in user specified target dir.
> [BugFix] extract gz into target dir

- src/array/cuda/dgl_cub.cuh
New in CUB 11.5 is the requirement to define `CUB_NS_QUALIFIER`. This PR adds this definition and is backwards compatible.
> [bugfix] Fix compilation with CUDA 11.5's CUB

- src/array/array.cc
- src/array/cuda/array_op_impl.cu
- src/graph/heterograph.cc
- tests/compute/test_subgraph.py
- tests/cpp/test_aten.cc
This implements `aten:Relabel_()` for the GPU, which thus enables `g.edge_subgraph()/in_subgraph()/out_subgraph()` with `relabel_node=True`, as well as `EdgeDataLoader(negative_sampler=None)`, run on the GPU.
The ordered hashtable in CUDA is used for node mapping and relabeling.
Fix this issue https://github.com/dmlc/dgl/issues/3216.
- Modify `src/array/array.cc`: enable switch for the GPU version
- Modify `src/array/cuda/array_op_impl.cu`: CUDA implementation of `Relabel_()`
- Modify `src/graph/heterograph.cc`: enable `g.edge_subgraph()` with `preserve_nodes=False` for graphs on the GPU
- Modify `tests/cpp/test_aten.cc`: enable the unit test for `aten::Relabel_()` on the GPU
- Modify `tests/compute/test_subgraph.py`: enable unit tests …
> [Feature] aten::Relabel_() for the GPU

- python/dgl/dataloading/dataloader.py
- src/graph/sampling/neighbor/neighbor.cc
- tests/pytorch/test_dataloader.py
This fixes several bugs in the GPU sampling and thus enables unit tests `tests/pytorch/test_dataloader.py` for the GPU. 
`node_dataloader()/edge_dataloder()/neighbor_sampler_dataloder()` now pass the GPU unit tests.
- Modify `python/dgl/dataloading/dataloader.py`: fix several bugs for GPU sampling
- Modify `src/graph/sampling/neighbor/neighbor.cc`: fix a corner case for GPU sampling
- Modify `tests/pytorch/test_dataloader.py`: enable unit tests for the GPU
> [BugFix] Fix bugs in GPU sampling and enable unit tests for dataloaders on the GPU

- tutorials/large/L2_large_link_prediction.py
Add a tutorial section for evaluating link prediction models on link prediction task.
> [Doc] Evaluation Tutorial for Link Prediction

- tests/pytorch/test_dataloader.py
In a previous PR https://github.com/dmlc/dgl/pull/3474, I accidentally disabled/skipped the test of the underlying sampled frontier copy from CPU to GPU in the dataloader. This PR reverts the related codes.
The unit tests for `node/edge_dataloader()` are responsible for the correctness of the output device, while the functionality tests for the sampler and collator (on both CPU and GPU) are covered by `test_neighbor_sampler_dataloader()`.
Thanks for @Rhett-Ying's correction.
> [BugFix] Fix test dataloader

- src/graph/sampling/randomwalks/randomwalks_cpu.h
This PR fixes an off-by-one bug in `GenericRandomWalk()`. The `traces_data` is a tensor with shape=[num_seed_nodes, trace_length] which is supposed to store the visited node ids for each seed node.
The line in question is supposed to something like:
```
dgl_id_t curr;  // current node_id in rwalk
int64_t i;  // current step iter
...
// perform an rwalk step()
const auto &succ = step(&traces_data[seed_id, :], curr, i);
```
However, in the current implementation the indexing into `traces_data` is incorrect: it's off by one, so traces from other seed nodes can clobber other seed node traces.
Anecdotally, when I was implementing a new Step() function where I needed to read into the passed in `traces_data`, I observed a memory corruption bug (leading to crashes), which led me to this bug. …
> [Randomwalk] Fix off-by-one bug in GenericRandomWalk()

- python/dgl/dataloading/negative_sampler.py
Fix the example code of the negative sampler, where the argument `eid` is required to be `Tensor or dict[etype, Tensor]`.
> [Doc] Fix the example code of negative sampler

- python/dgl/nn/pytorch/conv/gatv2conv.py
Added inputs slicing to choose destination node feats from mini-batch. This fix error with wrong size of `resval` tensor when residual connections are used in mini-batch training.
> [NN] Fix GATv2Conv residual for mini-batch

- docs/source/api/python/dgl.dataloading.rst
- docs/source/guide/distributed-apis.rst
- docs/source/guide_cn/distributed-apis.rst
- docs/source/guide_ko/distributed-apis.rst
- examples/pytorch/graphsage/experimental/train_dist_unsupervised.py
- examples/pytorch/rgcn/experimental/entity_classify_dist.py
- examples/pytorch/tgn/dataloading.py
- examples/pytorch/tgn/train.py
- python/dgl/dataloading/pytorch/__init__.py
- python/dgl/dataloading/pytorch/dataloader.py
- python/dgl/dataloading/pytorch/dist_dataloader.py
- tests/distributed/test_mp_dataloader.py
- tutorials/dist/1_node_classification.py
This PR is to split the logic for distributed graphs from `{Node,Edge}DataLoader` into a new class `Dist{Node,Edge}DataLoader`.
> [Sampling] Separate DistNodeDataLoader from NodeDataLoader

- python/dgl/nn/pytorch/conv/gatv2conv.py
Number of heads needs to be considered for the transformation of the destination features. Otherwise this will crash if residual==True.
> [Model] Fix output dimensions of residual connection for GATv2Conv

- python/dgl/heterograph.py
Convert frame to dict will explicitly trigger all the lazy copy to be performed, which is not ideal
> Fix unnecessary trigger of lazy copy

- python/dgl/function/reducer.py
#2278
Some modules like GINConv are not pickleable and thus, cannot be saved as a whole model, because their `__qualname__` is still the original ones (i.e., `_gen_reduce_builtin.<locals>.func`).
> [Bug Fix] Make modules using reducers like GINConv pickleable

- src/c_api_common.h
Minor updates to the implementation and doc of `CopyVectorToNDArray` so that it works for any DType that is convertible to IdType. Relevant post [here](https://discuss.dgl.ai/t/copyvectortondarray-in-src-c-api-common-h/2570?u=hiracatus).
> Fix CopyVectorToNDArray in src/c_api_common.h

- docker/pods/ci-cpu.yaml
- tests/compute/test_apply_edges_hetero.py
To update the edge features of a heterogeneous graph, DGL invokes separate python kernels for each relation types, e. g., `apply_edge(binary_func('h', 'h', 'm')), etype=relation_type)`. `binary_func` can be either of `add`, `sub`, `mul`, `div`, or `dot`. This PR allows user to use `apply_edges()` directly on the heterogeneous graph, e.g., `g.apply_edges(binary_func('h', 'm')) `
This PR only adds unit-test for binary operators. DGL already had the required functionality support.
> [Feature] Add builtin binary op support in `apply_edges()` for heterogeneous graph

- examples/pytorch/graphsage/experimental/train_dist.py
Current train_dist.py does not support 'nccl' backend. Add 'nccl' backend in arguments and fix `pad_data` function bug accordingly.
- [ Example ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ Y ] Changes are complete (i.e. I finished coding on this PR)
- [ Y ] All changes have test coverage
- [ Y ] Code is well-documented
Add 'nccl' backend in train_dist.py. After adding this backend, train_nid should be placed in GPU if using 'nccl' backend. Fix this bug as well.
> Add 'nccl' backend in train_dist.py and fix pad_data function cuda bug

- src/array/cuda/csr_mm.cu
The CUDA 11.0+ CSRGEMM APIs had trouble handling certain cases (see #3444) so I'm disabling it.
> [Bugfix?] Disabling CUDA 11.0+ CSRGEMM APIs

- CMakeLists.txt
This turns on tensorpipe's `TP_BUILD_LIBUV` option.  Can turn it off in CMake if you want to use system's libuv.
> [Build] Fix compiler crashes when system's libuv-devel is older than required

- examples/pytorch/graphsage/experimental/train_dist.py
- python/dgl/transform.py
Currently our `to_bidirected` semantics do not require the graph to be a simple graph in documentation, and the implementation uses `to_simple`.  However, in the code we still check for whether the graph is a multigraph.  This PR lifts this restriction.
> [Bugfix?] Remove simple graph requirement for to_bidirected

- src/array/cuda/negative_sampling.cu
- tests/compute/test_sampling.py
Noticed two bugs in GPU's global negative sampling code:
(1) Type casting from uint4 to int8 messed up, always returning 0s in CUDA kernels.
(2) The cuRAND RNG I used actually generates 96-bit random numbers instead of 128-bit.
@VoVAllen This should fix your problem.
> [Bugfix] Fix GPU global negative sampling code

- docs/source/env_var.rst
- python/dgl/__init__.py
- python/dgl/_ffi/base.py
- python/dgl/backend/__init__.py
- python/dgl/logging.py
Now the logging info when `import dgl` is disabled by default. User can set 'DGL_LOG_DEBUG=1' to enable it if needed.
This makes dgl-enter's log clearer
> Disable tensoradapter and "using backend: xxx" log by default

- python/dgl/_ffi/object.py
- python/dgl/convert.py
- python/dgl/distributed/graph_partition_book.py
- python/dgl/distributed/nn/pytorch/sparse_emb.py
- python/dgl/distributed/rpc_client.py
- python/dgl/distributed/rpc_server.py
- tests/distributed/utils.py
- tests/lint/pylintrc
This is a PR migrating from pylint 2.3.0 to 2.6.0 because our minimum Python version supported is 3.6, we are migrating our permitted syntax to 3.6, but pylint 2.3.0 crashes on Python 3.6 shipped by Ubuntu 18.04.
This allows us to use f-strings and other syntaxes.
> [CI] Migrate to pylint 2.6.0

- docker/Dockerfile.ci_lint
- python/dgl/distributed/graph_partition_book.py
Turns out that pylint 2.6.0 has a bug that will print the same error multiple times.  So I upgraded it to 2.7.0.
> [CI] Migrate to Pylint 2.7.0

- CMakeLists.txt
libnop depends on the helper type `decay_t` that was only introduced in C++14 (https://en.cppreference.com/w/cpp/types/decay). When building with gcc 9.3.0:
```
[ 13%] Building CXX object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o
cd /workspace/dgl/build/third_party/tensorpipe/tensorpipe && /usr/bin/c++ -DDGL_USE_CUDA -DENABLE_PARTIAL_FRONTIER=0 -I/usr/local/cuda/include -I/workspace/dgl/third_party/METIS/GKlib -I/workspace/dgl/third_party/METIS/include -I/workspace/dgl/third_party/tensorpipe -I/workspace/dgl/build/third_party/tensorpipe -I/workspace/dgl/third_party/tensorpipe/third_party/libnop/include -I/workspace/dgl/third_party/tensorpipe/third_party/libuv/include -fopenmp -O2 -Wall -fPIC -std=c++11  -DUSE_AVX -DUSE_LIBXSMM …
```
> [bugfix] Change standard to c++14 to be compatible to tensorpipe's dependencies

- python/dgl/backend/set_default_backend.py
- tests/compute/test_backend.py
The PR #3696 introduced a keyword for os.makedirs() with typo (I was testing it incorrectly, and none of our unit tests covered it). This PR adds a unit test for the function `set_default_backend()` and fixes the typo: `exists_ok=True` -> `exist_ok=True`.
> [bugfix] Fix set_default_backend() keyword

- python/dgl/nn/mxnet/conv/sageconv.py
- python/dgl/nn/pytorch/conv/sageconv.py
- python/dgl/nn/tensorflow/conv/sageconv.py
This PR fixes docs on GraphSAGE normalization.
It is `h_{i}^{(l+1)}` that should be normalized, not `h_{i}^{l}`.
I used DGL in my research.
I found that DGL implementation is easy to extend and very useful.
Thanks to the DGL maintainers and contributors!
> [Doc] Fix docs on GraphSAGE normalization

- README.md
- examples/README.md
Added a link to the RNAglib homepage in the _DGL-powered-projects_ section of the main `README.md`
Added a link to our repository in the 2021 examples section of the `examples/README.md`
> Add links to RNAGlib in the DGL Readme

- python/dgl/nn/pytorch/conv/appnpconv.py
- python/dgl/nn/pytorch/conv/gcn2conv.py
- python/dgl/nn/pytorch/conv/sgconv.py
- python/dgl/nn/pytorch/conv/tagconv.py
`edge_weight` is updated which will skip `feat=feat*dst_norm`
pls help check whether this is what expected.
> [Fix] normalize by dst if edge_weight is None

- src/array/cpu/spmm_blocking_libxsmm.h
This was a bug in the optimized spmm code that only manifests when number of edges of a graph are greater than integer limit. In that case since total_nnz is declared as an "int", it would be negative and the function would return without performing spmm.
> Fixes the bug when total_nnz is > integer limit

- examples/pytorch/rgcn/entity_sample_multi_gpu.py
Fix a bug in `examples/pytorch/rgcn/entity_sample_multi_gpu.py` introduced in #3774.
@BarclayII
> [Bugfix] Fix RGCN Example

- src/graph/sampling/randomwalks/randomwalk_gpu.cu
There's some declaration like `T a[num_etypes]` which is not a good practice anyway.
> [Build or bug?] Fix VS2019 compilation error in randomwalk GPU kernel

- examples/pytorch/graphsage/advanced/train_lightning.py
- examples/pytorch/graphsage/advanced/train_lightning_unsupervised.py
- examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py
- examples/pytorch/graphsage/dist/partition_graph.py
- examples/pytorch/graphsage/distgnn/partition_graph.py
enable to run `train.py` under any path such as `//dgl/` : `python3 examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py`
> [Examples] fix path for load_graph

- python/dgl/distributed/nn/pytorch/sparse_emb.py
- python/dgl/distributed/optim/pytorch/sparse_optim.py
> [BugFix] fix incorrect name when fetch data in sparse optim

- src/rpc/tensorpipe/tp_communicator.cc
- tests/distributed/test_rpc.py
dist training may hang in DistGraph.__init__() when many trainers are booted. The direct cause seems to be that some rpc messages from clients fail to arrive at servers.
needs more confirmations.
> [BugFix] send rpc messages blockingly in case of congestion

- include/dgl/aten/coo.h
- include/dgl/aten/csr.h
- include/dgl/base_heterograph.h
- python/dgl/utils/checks.py
- src/graph/heterograph.cc
- src/graph/heterograph.h
- src/graph/immutable_graph.cc
- src/graph/pickle.cc
- src/graph/unit_graph.cc
- src/graph/unit_graph.h
* Removed `SetCOOMatrix` and similar methods since they are not necessary.
* Fix `CopyToSharedMem` assuming that all relation graphs are homogeneous.
* Fix #3802 by maintaining `is_pinned` flag in the GraphIndex rather than checking for the arrays' pinned memory status every time.
> [Bugfix] Fix multiple bugs and code refactor

- python/dgl/base.py
The current implementation of `dgl_warning` calls `warnings.warn` with `stacklevel=1`, which always returns the file `python/dgl/core.py`.
This PR sets `stacklevel=2`, such that it returns the location of the actual caller.
Reference: https://docs.python.org/3/library/warnings.html?highlight=stacklevel#warnings.warn
> [bugfix] Set `stacklevel=2` for `dgl_warning`

- examples/pytorch/gat/gat.py
- examples/pytorch/gat/train.py
- examples/pytorch/gat/train_ppi.py
Change to GAT example to account for the number of layers in the module as per the input layers argument following the GraphSAGE [example](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/advanced/model.py)
@VoVAllen 
Fix #3746 
> [Example] layers number fix in GAT example

- python/dgl/dataloading/dataloader.py
DGL 0.8 support custom dataset and we can parse a customize "TensorizedDataset" in the indices field. However here cause an error that indices_device will not be created if a customize dataset is parsed. @BarclayII 
> [BugFix] involve indices_devices for other dataset object.

- examples/pytorch/pagerank.py
There is a redundant reference of `nx` (nextworkx) in `examples/pytorch/pagerank.py` which will produce the error: `AttributeError: module networkx has no attribute nx` .
> [BugFix] Remove redundant reference of networkx package in pagerank.py

- docs/source/api/python/dgl.rst
- docs/source/api/python/nn-pytorch.rst
- python/dgl/nn/pytorch/factory.py
- python/dgl/transforms/functional.py
- tests/pytorch/test_nn.py
Function and module for creating the radius graph from the point set. Implemented in vanilla PyTorch by constructing NxN pairwise distance matrix. It's fully vectorized, but can consume a lot of memory for huge graphs, so it's more suited for molecules, proteins, small point clouds etc.
Functionalities:
- possibility to include self-loops
- possibility to change power of Minkowski metric
- optionally returns distances for the constructed edges
- returns graph on the same device as point set
> [Feature] Radius Graph

- tensoradapter/pytorch/CMakeLists.txt
On systems where `python` refers to `python2`, it breaks building DGL from source with `-DBUILD_TORCH=ON`. This PR makes it so `python3` is explicitly called in finding the pytorch to build the memory pool allocator against.
> [bugfix] Make source build work for systems where the default is python2

- tests/compute/test_transform.py
This PR fixes the `HeatKernel` unit test `test_module_heat_kernel` that could fail due to numerical inconsistencies across systems in SciPy's `expm` result.
It addresses the issues described in details in #3922
> [Bugfix] Fix test_module_heat_kernel test

- python/dgl/dataloading/dataloader.py
The situation is described in slack channel (with the same OP of https://discuss.dgl.ai/t/heterogenous-graph-edge-sampling-on-gpu/2892).  Basically when doing edge classification with multi-GPU pure GPU sampling it crashes with a device mismatch error.  This is caused by the indices not being copied to GPU in the collate wrapper.
> [Bug] Fix multi-GPU edge classification crashing with pure GPU sampling

- examples/pytorch/graphsage/dist/train_dist.py
- python/dgl/distributed/dist_context.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/rpc.py
- python/dgl/distributed/rpc_client.py
- python/dgl/distributed/rpc_server.py
- src/graph/network.cc
- src/rpc/net_type.h
- src/rpc/network/communicator.h
- src/rpc/network/socket_communicator.cc
- src/rpc/network/socket_communicator.h
- src/rpc/rpc.cc
- src/rpc/rpc.h
- src/rpc/rpc_msg.h
- src/rpc/tensorpipe/tp_communicator.cc
- src/rpc/tensorpipe/tp_communicator.h
- tests/cpp/socket_communicator_test.cc
- tests/distributed/test_rpc.py
`socket` is enabled back which was the main rpc backend in `0.7.x`. This is supposed to fix the hang issue mentioned in https://github.com/dmlc/dgl/issues/3881.
Try with below command and it works well with `net_type='socket'`:
`DGL_HOME=/home/ubuntu/workspace/dgl_p0 DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=.:$DGL_HOME/python:$PYTHONPATH python3 ~/workspace/dgl_p0/tools/launch.py --workspace ~/workspace/dgl_p0/examples/pytorch/graphsage/dist/ --num_trainers 4 --num_samplers 4 --num_servers 4 --part_config data/ogb-product.json --ip_config ~/workspace/ip_config.txt " python3 train_dist.py --graph_name ogb-product --ip_config ~/workspace/ip_config.txt --num_epochs 5 --batch_size 256 --eval_every 5"`
or have been fixed to be …
> [Feature] enable socket net_type for rpc

- python/dgl/nn/pytorch/hetero.py
Added ability to use `torch.nn.Linear` without `bias`. This can be useful for residual connections and linear projections.
- Added `bias` argument to HeteroLinear constructor
> [NN] Add bias argument to HeteroLinear

- tests/scripts/build_dgl.sh
The pull request: https://github.com/dmlc/dgl/pull/3983 requested a change to support CMakelist.txt to remove AVX-specific optimization by default. The following script enables arch-specific optimization in the build.sh determined at run-time based on the underlying ISA. 
Updates to the build script.  The updated script proposed one way to enable arch-specific optimization in the build_dgl.sh determined at run-time based on the underlying ISA.
> [Build Script]Supporting DGL build with arch specific optimization

- python/dgl/dataloading/negative_sampler.py
> [Doc] default value typo fix in GlobalUniform negative sampler

- examples/pytorch/gcmc/data.py
- examples/pytorch/gcmc/model.py
Duplicate from PR  #4020 
To fix https://github.com/dmlc/dgl/issues/4019
Updated the API of accessing tokenizer in the latest version of torchtext. Using module torchtext.legacy causes the crash with torchtext 0.13.
Revert the changes of model.py from 74f01405
> [Bugfix] Fix GCMC examples

- src/array/cuda/cuda_filter.cu
- src/graph/sampling/randomwalks/frequency_hashmap.cu
- src/graph/transform/cuda/cuda_map_edges.cuh
- src/runtime/cuda/cuda_hashtable.cu
- src/runtime/cuda/nccl_api.cu
This PR wraps all CUDA kernel calls with the `CUDA_KERNEL_CALL` macro, except for those in `src/array/cuda/rowwise_sampling.cu`, which are covered by #4064.
> [Fix] Wrap all CUDA kernel calls with macro

- python/dgl/transforms/functional.py
Added `to_half`, `to_float`, and `to_double` to `__all__`, from which they were mistakenly missing for dgl.transforms.functional, so that they can be imported properly, as mentioned in https://github.com/dmlc/dgl/issues/4087
> [Bug] Fixed missing dgl.transforms.functional `__all__` entries

- Jenkinsfile
Recently, I find torch cpu win64 test failed due to timeout: http://dgl-jenkins-eksvpc-2136217999.us-west-2.elb.amazonaws.com/blue/organizations/jenkins/dgl/detail/PR-4098/5/pipeline/292.
Anyone knows why? I just loose to 30min which is the value for tests on linux.
> [CI] loose time liimit for unit tests on Win64

- src/array/cuda/atomic.cuh
This disable implementations of atomic functions that are not atomic.
Fixes #4031.
> [Bugfix] Disable non-atomic atomic operations

- README.md
Hi, I have create a Python package called gtrick (https://github.com/sangyx/gtrick) to collect and test tricks for Graph Neural Networks. It is built on DGL and PyG and I want to add this repo in DGL-powered projects to let others know it.
> [Doc] Add gtrick in DGL-powered projects

- python/dgl/distributed/graph_services.py
fix for one of the issues mentioned in https://github.com/dmlc/dgl/issues/4150.
I think `etype_sorted` should be an attribute of `DGLGraph` which is recorded when loading/saving graphs.
> [Dist] etype is not  guaranteed to be sorted

- examples/pytorch/correct_and_smooth/README.md
- examples/pytorch/correct_and_smooth/main.py
BugFix discussed in Issue #4102 with @mufeili. Correct&Smooth example was using validation labels when it shouldn't be. This led to incorrectly reporting an increase in performance over the authors' code. Without the validation labels, the hyperparameters reported in the README underperformed "Plain Linear + C&S" from the authors' implementation, so I changed the hyperparameters in the README to be the same as the author's. Doing this allows for replication of the Plain Lienar + C&S results.
I added a comment to specify that this implementation does not allow for spectral or diffusion embeddings, making it an implementation of what the authors refer to as "Plain Linear + C&S". In their code and paper "Linear + C&S" describes the method using spectral embeddings for feature augmentation. …
> [BugFix] Fix Correct&Smooth (#4102)

- python/dgl/dataloading/dataloader.py
- python/dgl/frame.py
Fix that `pin_prefetcher` is not actually enabled.
1. Set `pin_memory=self.pin_prefetcher` to enable pin memory for returned indices. Note: subgraph is still not pinned.
2. Correctly enable pin memory for column fetching.
> [Bug] Fix that pin_prefetcher is not actually enabled

- include/dgl/runtime/ndarray.h
- src/array/cuda/array_index_select.cu
- src/array/cuda/array_op_impl.cu
- src/array/cuda/array_scatter.cu
- src/array/cuda/csr_get_data.cu
- src/array/cuda/csr_mm.cu
- src/array/cuda/csr_sum.cu
- src/array/cuda/cusparse_dispatcher.cuh
- src/array/cuda/spmm.cuh
- src/array/cuda/utils.h
- src/runtime/ndarray.cc
* Continuation of adding more missing FP16 specializations after PR #4029 , which addressed the specific case from issue #3988
* Added missing specializations for `__half` of `DLDataTypeTraits`, `IndexSelect`, `Full`, `Scatter_`, `CSRGetData`, `CSRMM`, `CSRSum`
* Fixed casting issue in `_LinearSearchKernel` that was preventing it from supporting `__half`
* Added more specific error messages for unimplemented FP16 specializations of `Xgeam`, `CSRGEMM`, and `CSRGEAM`, which would require functions that aren't provided by cublas
> [Bug][Feature] Added more missing FP16 specializations

- tests/compute/test_transform.py
@yaox12 It seems that all the failed test cases in #4163 have `torch.matmul` inside `assert`. I separate them in this PR and let's see if the issues will disappear or there will be more clear error messages.
> [Transform] Fix Unit Test for SIGN Diffusion

- tests/compute/test_transform.py
Originally `torch.allclose` uses `1e-08` for `atol`, which fails about every 10 times I invoke the unit test locally. I've changed it to `1e-06`, which passed the unit test locally for 10000 times. See also issue #4163 .
> [Test] Relax Threshold for AllClose in Testing SIGN Diffusion (#4163)

- examples/pytorch/appnp/train.py
- examples/pytorch/dgi/train.py
- examples/pytorch/gat/train.py
- examples/pytorch/gatv2/train.py
- examples/pytorch/gcn/gcn_mp.py
- examples/pytorch/gcn/train.py
- examples/pytorch/graphsage/train_full.py
- examples/pytorch/hardgat/train.py
- examples/pytorch/model_zoo/citation_network/run.py
- examples/pytorch/monet/citation.py
- examples/pytorch/sgc/sgc.py
- examples/pytorch/sgc/sgc_reddit.py
Recently, DGL completely deprecated `data.graph`, yet many examples still use this out-dated API, which causes various crashes like, `AttributeError: 'CoraGraphDataset' object has no attribute 'graph'`. 
This PR fix crashes and make these cases (appnp, dgi, gat, gcn, gatv2, graphsage, hardgat, model_zoo, monet, sgc) run through. It also fixes a bug in gatv2 case due to mis-calling `evaluate` function
- data.graph --> data[0]
- bugfix for gatv2 case (function argument misplacement)
> [Example][Bugfix] Fix various example crashes due to recent DGL API update

- src/array/cpu/rowwise_pick.h
- tests/compute/test_sampling.py
follow-up fix for https://github.com/dmlc/dgl/issues/4150
> [BugFix] check whether etype sorted when sampling

- examples/pytorch/dgi/train.py
Use DGL remove_self_loop()/add_self_loop() function, instead of remove_edges_from()/add_edges_from(), from networkx.graph module, to add self-loop for a given graph.
- remove_edges_from/add_edges_from  --> remove_self_loop/add_self_loop
- `python3 train.py --dataset=cora --gpu=0 --self-loop`
```
Test Accuracy 0.8170
```
> [Example][Bugfix] Bugfix for dgi example

- include/dgl/runtime/device_api.h
- src/random/random.cc
- src/runtime/cuda/cuda_device_api.cc
Add `IsAvailable()` to device API. Check CUDA context availability before setting curand seed to fix #4216. 
> [Bugfix] Add CUDA context availability check before setting curand seed

- examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py
- examples/pytorch/graphsage/multi_gpu_node_classification.py
- examples/pytorch/graphsage/node_classification.py
- examples/pytorch/rgcn/entity_sample.py
- examples/pytorch/rgcn/entity_sample_multi_gpu.py
- python/dgl/dataloading/dataloader.py
To address https://github.com/dmlc/dgl/issues/4234, this PR fixes the crashing example cases, rgcn and graphsage, due to recent [pytorch update](https://github.com/pytorch/pytorch/commit/7b3a0ff87a91c98574ddfd98532062d78c49b2c7)
Move index to the same device as data.
> [Bugfix] Accessing data from the indexes stored in same device

- src/array/cuda/sddmm_hetero_coo.cu
- src/array/cuda/sddmm_hetero_csr.cu
Split `sddmm_hetero.cu` into two files to limit the object file size.
> [Build] Fix Windows complication crash with FP16 enabled due to large object files

- examples/pytorch/graphsage/node_classification.py
node_classification.py still fails due to the same issue https://github.com/dmlc/dgl/issues/4234.
This PR fixes node_classification.py runs under all modes (--mode = `cpu`, `mixed`, `puregpu`)
- test_idx always on cpu
- Accuracy calculation `MF.accuracy` always on cpu
> [Example][Bugfix] graphsage node classification example

- examples/pytorch/rgcn-hetero-ogbn-mag/main.py
- python/dgl/dataloading/dataloader.py
To fix https://github.com/dmlc/dgl/issues/4296, the problem is `_id_tensor` always copied back to master process to allow the access from every device through UVA, as the result of calling `call_once_and_share()`. Thus, `_id_tensor` will then be in a different device (CPU) as `indices` and `self._device` (GPU), and in L242, `id_tensor = self._id_tensor[indices.to(self._device)]` triggers the crash.
1. Bugfix in the training script, i.e., `out_nodes` should be in same device as labels
2. `self._id_tensor[indices.to(self._device)]`  --> `self._id_tensor[indices.to(self._id_tensor.device)]` 
1. In the example `example/pytorch/rgcn-hetero-ogbn-mag/main.py`, enable `use_ddp`, …
> [Bugfix] Fix dataloader pytorch cuda indexing 

- include/dgl/immutable_graph.h
Fix the fatal log output in COO class
> [Bugfix] Fixed fatal log output in COO class

- examples/pytorch/graphsage/node_classification.py
The device here was typed in the string, which ended up pin_memory being false anyway to lead to issues in the CPU device case.
https://github.com/dmlc/dgl/blob/2cf05c53420546443a267d91ec624887d0078278/examples/pytorch/graphsage/node_classification.py#L42-L43
Fixed the example code for torch-GraphSAGE
> [Example] Fixed device type in GraphSAGE inference

- python/dgl/distributed/dist_graph.py
- tests/distributed/test_dist_graph_store.py
add tests for `edge_subgraph` and fix bug related to canonical etype.
> [BugFix] fix etype check in DistGraph.edge_subgraph

- tools/distpartitioning/data_shuffle.py
- tools/distpartitioning/globalids.py
- tools/distpartitioning/gloo_wrapper.py
…er testing
1. Replaced alltoallv gloo wrapper call with alltoall message.
2. All the messages are padded to be of same length
3. Receiving side unpads the messages and continues processing.
> [Distributed] use alltoall fix to bypass gloo - alltoallv bug in distributed partitioning

- tools/distpartitioning/convert_partition.py
…fault for very large partitions
1. Removed three graph dgl objects and we create the final dgl object directly by maintaining the following constraints
a) nodes are reordered so that local nodes are placed in the beginning of the nodes list compared to non-local nodes.
b)Edges order are maintained as passed into this function.
c) src/dst end points are mapped to target values based on the reshuffle'd nodes order.
> [Distributed] reduce memory consumption in distributed graph partitioning.

- python/dgl/ops/edge_softmax.py
- python/dgl/sparse.py
- tests/compute/test_edge_softmax_hetero.py
Fixes `edge_softmax_hetero` crashes when (1) a unidirectional bipartite graph is given, or (2) a graph with no node features is given.
> [Bug] A bunch of fixes in edge_softmax_hetero

- src/array/cuda/rowwise_sampling_prob.cu
This is to fix that `static_assert` requires a second parameter - the error message - before C++17.
> [Bug] Fix broken static_assert

- src/runtime/cuda/cuda_device_api.cc
- tests/compute/test_heterograph.py
- tests/compute/test_pin_memory.py
- tests/pytorch/test_pin_memory.py
When users try to pin empty tensors or graphs, do nothing instead of raising an error. This is also the default behavior of PyTorch.
Fix #4390.
> [Bugfix] Fix pinning empty tensors and graphs

- src/runtime/ndarray.cc
Check the `pinned_by_dgl_` flag before unpinning to avoid CUDA calls.
I have tested it offline and it fixes https://github.com/dmlc/dgl/issues/4340. Not sure how to include it in the unit test because the dataloader (where the error occurs) is for the PyTorch backend only, for which we always enable the tensoradaptor.
> [Bug] Fix unpinning when tensoradaptor is not available

- examples/pytorch/dgi/train.py
- python/dgl/data/citation_graph.py
- python/dgl/data/gnn_benchmark.py
- python/dgl/data/karate.py
- python/dgl/data/knowledge_graph.py
- python/dgl/data/reddit.py
- python/dgl/data/tree.py
- tutorials/models/1_gnn/6_line_graph.py
- tutorials/models/1_gnn/9_gat.py
- tutorials/models/2_small_graph/3_tree-lstm.py
Remove the dataset attributes deprecated in v0.5. I have not updated the deprecated examples that use these deprecated APIs.
> [Deprecation] Dataset Attributes

- tests/cugraph/test_basics.py
- tests/scripts/cugraph_unit_test.sh
What i think is happening is that after the Pytests are passed (see [logs](https://github.com/dmlc/dgl/issues/4324#issuecomment-1255212794) and all other logs (https://github.com/dmlc/dgl/pull/4597, https://github.com/dmlc/dgl/pull/4534)  during cleanup there seems to be an segfault occuring. 
On attaching GDB it seems to be stemming from libcugraph.so .
```
Thread 1 "python3.9" received signal SIGSEGV, Segmentation fault.
0x00007fe6d91b42fc in std::_Hashtable<std::thread::id, std::pair<std::thread::id const, std::weak_ptr<raft::interruptible> >, std::allocator<std::pair<std::thread::id const, std::weak_ptr<raft::interruptible> > >, std::__detail::_Select1st, std::equal_to<std::thread::id>, std::hash<std::thread::id>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, …
```
> [Bugfix][Hotfix] Fix cugraph Pytorch CI failures 

- python/dgl/subgraph.py
> [Subgraph] State in docstring that nodes cannot have any duplicate value when inducing a subgraph.

- examples/pytorch/model_zoo/geometric/mnist.py
To fix https://github.com/dmlc/dgl/issues/4630, this PR aligns the float type between node feats and edge feats and also removes some insignificant print-out msgs.
1. Use dict to look up correct torch types
2. Remove meaningless print-outs.
> [Example][Bugfix] Fix MNIST examples

- python/dgl/distributed/partition.py
> [Doc] Fix the doc for the partition_graph function

- tests/cugraph/test_basics.py
fix the bug imported by sorting module import: #4694 
as mentioned at the top of the file, cugraph must be imported before torch due to https://github.com/rapidsai/cugraph/issues/2718
> [BugFix] cugraph must be imported before torch

- tests/tools/create_chunked_dataset.py
- tests/tools/test_dist_part.py
- tools/distpartitioning/utils.py
Previously, I reported a bug of edge feature support in dist part pipeline: https://github.com/dmlc/dgl/issues/4681. I just found it's not fixed yet.
> [Dist] fix etype issue in dist part pipeline

- docs/source/guide/distributed-preprocessing.rst
This seems a copy paste type for the paper:cites:paper edge type.
> [Doc] Fix typo distributed-preprocessing.rst

- tools/distpartitioning/parmetis_preprocess.py
The rank of the process was incorrect in a multi-node setting. Now updated the key to use from the environment
dictionary to retrieve the rank of the process correctly.
> ParMETIS preprocessing is failing in a multi-node cluster because of the incorrect rank of the process

- Jenkinsfile
Updating to cugraph 22.12 nightly image to allow us to unlock  https://github.com/dmlc/dgl/pull/4743 and https://github.com/dmlc/dgl/pull/4701 . 
@tingyu66  and I have tested that it passes cugraph tests locally by following :
```DockerFile
FROM rapidsai/cugraph_nightly_torch-cuda:11.5-base-ubuntu18.04-py3.9-pytorch1.12.0-rapids22.12
RUN cd / && git clone https://github.com/dmlc/dgl.git 
RUN cd / && cd dgl && git submodule update --init --recursive 
RUN cd /dgl && git fetch origin pull/4743/head:b_4737 && git checkout b_4737
RUN cd /dgl && bash tests/scripts/build_dgl.sh cugraph
```
```python3
cd /dgl && bash tests/scripts/cugraph_unit_test.sh cugraph
```
> Update to cugraph 22.12 nightly image

- src/array/cuda/array_index_select.cu
- src/array/cuda/csr_get_data.cu
- src/array/cuda/rowwise_sampling.cu
- src/array/cuda/rowwise_sampling_prob.cu
- src/array/cuda/spmat_op_impl_csr.cu
- src/array/cuda/uvm/array_index_select_uvm.cu
Resolves #4726.
The device attribute `cudaDevAttrCanUseHostPointerForRegisteredMem` of K80 is 0, so we cannot access the host pointer directly from the device even with UVA. We should get the corresponding device pointer via `cudaHostGetDevicePointer`.
For devices whose `cudaDevAttrCanUseHostPointerForRegisteredMem` is 1, the device pointer returned by `cudaHostGetDevicePointer` will match the original host pointer.
1. All functions with the `ATEN_CSR_SWITCH_CUDA_UVA` dispatcher
2. `IndexSelect()`
3. `IndexSelectCPUFromGPU()` and `IndexScatterGPUToCPU()`
> [Bugfix] Fix that UVA cannot work on old GPUs

- python/dgl/distributed/graph_partition_book.py
A follow-up PR to fix max length introduced by https://github.com/dmlc/dgl/pull/4777
> [Dist] fix max length to 80 introduced in deprecate etype PR

- src/graph/transform/cuda/cuda_to_block.cu
- src/rpc/network/msg_queue.h
Fix the follow lint error.
Checking code style of C++ codes...
src/graph/transform/cuda/cuda_to_block.cu:46:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]
src/rpc/network/msg_queue.h:97:  Constructors callable with one argument should be marked explicit.  [runtime/explicit] [5]
Issue identified when running CI in https://github.com/dmlc/dgl/pull/4810.
> [Misc] Fix the lint error by marking constructor explicit

- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
- tests/distributed/test_dist_graph_store.py
- tests/distributed/test_distributed_sampling.py
we should always use canonical etypes as canonical etype is fully supported in DistDGL.
> [Dist] enable access DistGraph.edges via canonical etype

- tools/distpartitioning/dataset_utils.py
- tools/distpartitioning/dist_lookup.py
Default reading of large files using pyarrow, treating it as a single chunk takes very large amounts of memory footprints. In addition, this memory lingers in the VmData space and does not return to the system memory. 
To avoid this situation and to reduce the memory footprint of pyarrow reading csv files we now use Chunked reading of csv files  using pyarrow and allowing it to read one chunk at a time. 
In addition, if storing a slice of the numpy array read from a large file is resulting in original numpy array not getting released back to the system and stays throught out the execution in the VmData space. We now do a copy.deepcopy() of the slice which will create a separate memory block and when the original numpy array gets out-of-scope it gets released to the system. 
Please feel …
> [Dist] Pyarrow reading large csv files memory optimization

- tools/distpartitioning/dist_lookup.py
In an all to all message, if the return value (tensor) from a node is empty tensor then None was returned to the function caller which is causing the torch.cat() to fail. Apparently torch concatenate function cannot handle None values in the input list of tensors.
Now, with the fix, if the return'ed tensors are 0-sized tensors (please note that here we perform padding, so we need to remove padding and compare the sizes appropriately) then it instead of returning None, it does include None in the list of tensors to the invoking function.
> [Dist] alltoall gloo wrapper primitive returns None values in the output list of tensors which fails the torch.cat function

- tools/distpartitioning/globalids.py
- tools/distpartitioning/gloo_wrapper.py
When retrieving SHUFFLE_GLOBAL_NID's for src and dst end points of the local edges in the current graph partition we used to send both the source and destination end points as a single list to the distributed lookup service. For Fe_large graph this message size is becoming about 50GB+ (3.2 billion edges). This increases the pressure on the memory used to send/receive such a large message and in the case of fe_large graph the process is getting killed. 
Now, we batch the outgoing message to distributed lookup service and ensure that the in each iteration we only send a message of maximum size of 250 MILLION entries (which is about 2 GB). This will reduce the memory need to support this operation and with this change fe_large graph is able to run correctly. 
Also another optimization is to …
> [DIST] Message size to retrieve SHUFFLE_GLOBAL_NIDs is resulting in very large messages and resulting in killed process

- src/array/cuda/functor.cuh
- src/array/cuda/segment_reduce.cuh
- src/array/cuda/spmm.cuh
- src/runtime/cuda/cuda_common.h
- tests/compute/test_sparse.py
Resolve https://github.com/dmlc/dgl/issues/4674 by using float32 accumulators for half-precision SpMM.
- Add float32 accumulators for half-precision SpMM.
- Update SpMM kernels.
Run the example in #4674, now the result is
```bash
tensor([6617.6919, 6586.2812, 6619.5034, 6558.4487, 6553.0786, 6624.6333,
6560.0791, 6557.0645, 6509.3472, 6568.6904, 6587.9985, 6597.6553,
6595.7559, 6583.3838, 6578.9878, 6595.5063, 6539.8848, 6558.6309,
6590.0713, 6601.4785, 6588.4810, 6520.0093, 6593.1357, 6583.6230,
6572.8008, 6606.7241, 6598.8960, 6533.9819, 6569.7227, 6629.5200,
6628.0483, 6561.9619], device='cuda:0')
tensor([6616., 6588., 6620., 6560., 6552., 6624., 6560., 6556., 6508., 6568.,
6588., 6596., 6596., 6584., 6580., 6596., 6540., …
```
> [Bugfix] Fix that half-precision SpMM produce incorrect results

- src/array/cpu/array_index_select.cc
This parallelizes `find_edges`, which could mitigate the low CPU utilization in link prediction compared to node classification (#4357 ).
> Parallel find edges

- src/array/cpu/array_utils.h
`IdHashMap::Map` is executed sequentially.  So I make it parallelizable.  This should mitigate the low CPU utilization in distributed training (#4357 ) to some extent.
> [Performance] Make IdHashMap parallel

- src/array/cpu/array_utils.h
Reverts dmlc/dgl#4881 because they did not work as expected.
> Revert "[Performance] Make IdHashMap parallel"

- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/_cython/base.pxi
- python/dgl/_ffi/_cython/function.pxi
Change enumeration name in DGLObjectTypeCode to avoid conflict with Pytorch
> [Sparse][FFI] Change enumeration name in DGLObjectTypeCode

- CMakeLists.txt
- cmake/modules/CUDA.cmake
- dgl_sparse/CMakeLists.txt
- dgl_sparse/include/sparse/dgl_headers.h
- dgl_sparse/include/sparse/elementwise_op.h
- dgl_sparse/include/sparse/sparse_format.h
- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_format.cc
- dgl_sparse/src/sparse_matrix.cc
- dgl_sparse/src/utils.h
- tests/pytorch/mock_sparse2/test_sparse_matrix.py
Resolve #4852.
1. Build C++ sparse library in DGL CMakeLists.txt and link it to DGL. 
2. Move the definitions of sparse formats to a separate file.
3. Add a CSRToCOO conversion using DGL implementation with test.
> [Sparse] Link to DGL

- tools/distpartitioning/dist_lookup.py
Fix a bug in the parallel data partitioning (described in https://docs.dgl.ai/en/0.9.x/guide/distributed-preprocessing.html ).
This PR fixes #4907
> [Dist] Fix parallel Dist partitioning and add test

- Jenkinsfile
For now, only the CI tests are disabled.
How about deprecating all code/script that are for MXNet?
> [CI] deprecate CI tests for MXNet

- python/dgl/batch.py
- tests/compute/test_batched_heterograph.py
Remove ```node_attrs``` and ```edge_attrs``` from dgl.batch API argument list.
> [API Deprecation]Remove node_attrs and edge_attrs in batch.py

- python/dgl/nn/pytorch/sparse_emb.py
- python/dgl/optim/pytorch/sparse_optim.py
Remove ```emb_tensor``` in dgl.nn,  function definition is in sparse_emb.py.
> [API Deprecation] Remove emb_tensor in dgl.nn

- python/dgl/mock_sparse/elementwise_op_sp.py
- python/dgl/mock_sparse/sp_matrix.py
Otherwise the example SIGN `examples/sparse/sign.py` will fail with GPU.
> [Sparse] Misc Fix for GPU

- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_partition_book.py
- python/dgl/distributed/standalone_kvstore.py
- tests/distributed/test_dist_graph_store.py
fix for #4887 && #4463
The direct cause of the crash is `NodeDataView` with `ntype=None` is always instantiated in `DistGraph.__init__()` and assigned to `g._ndata`. For a heterogeneous graph, instantiating with `ntype=None` will merge all data for all ntypes into single dict instead of `a dict of dict`. This is what we expect for heterogeneous graph.
as for this fix, I think we don't need to always instantiate and assign `g._ndata` in `__init__()`. It's ok to delay it.
> [Dist] init node/edge data store for Node/EdgeDataView in appropriate place

- Jenkinsfile
Recently we find dist test often fails due to timeout. Root cause is not found yet.
> [CI] Enlarge timeout limit for dist test

- examples/README.md
- examples/sparse/hgnn.py
Add HGNN example (https://arxiv.org/pdf/1809.09401.pdf).
Closes #4870.
I listed a question and a small suggestion in the code and I'll list here as well:
* Make `DGLGraph.adj()` return a DGL sparse matrix instead of PyTorch sparse matrix, or do we have a convenient conversion function?
* Have an `eye()` function to construct identity sparse matrix.
> [Sparse] Add HGNN example

- examples/mxnet/monet/citation.py
- examples/pytorch/dgmg/model.py
- examples/pytorch/ogb/cluster-sage/main.py
- python/dgl/heterograph.py
- tests/compute/test_graph.py
- tests/compute/test_heterograph.py
- tests/compute/test_pickle.py
- tests/compute/test_sampling.py
- tests/compute/test_shared_mem.py
- tests/compute/test_transform.py
- tests/compute/utils.py
- tutorials/models/3_generative_model/5_dgmg.py
Remove ```has_edge_between```  ```has_node``` ```in_degree``` ```is_readonly```  ```out_degree``` in ```DGLGraph```.
> [API Deprecation]Remove 5 APIs in DGLGraph

- examples/pytorch/ogb/deepwalk/reading_data.py
- examples/pytorch/ogb/line/reading_data.py
- python/dgl/heterograph.py
- tests/distributed/test_distributed_sampling.py
Remove formxxx, multixxx, readonly, registerxxx, send, recv, group_apply_edges
> [API Deprecation]Remove APIs in old dgl section in DGLGraph

- python/dgl/heterograph.py
Remove ```function adjacency_matrix_scipy``` and ```in_place``` argument in ```push```,```pull```,```apply_edges```, ```apply_nodes``` and ```send_and_recv```
> [API Deprecation]Remove adjacency_matrix_scipy and inplace args in candidates 

- src/array/cuda/spmm.cu
- src/array/cuda/spmm.cuh
- src/array/cuda/spmm_hetero.cu
Since the `IndexSelect` in `array_op.h` has support fp16, remove the duplicated `_IndexSelect` function and corresponding kernels in `spmm.cuh`.
> [Cleanup] Remove duplicated _IndexSelect

- tests/dist/python/run_dist_objects.py
- tests/dist/test_dist_objects.py
This PR adds a blacklisting mechanism for the multi-node DistDGL tests.
The existing DIST_DGL_TEST_OBJECT_TYPE can now be a comma-separated list of targets to run.
Example:
```
export DIST_DGL_TEST_OBJECT_TYPE="DistTensor,DistGraph"
```
The new DIST_DGL_TEST_OBJECT_TYPE_BLACKLIST can be used the same way, such as:
```
export DIST_DGL_TEST_OBJECT_TYPE_BLACKLIST="DistGraph,DistOptimizer"
```
> [Dist][Test] Add blacklisting mechanism + misc fixes in DistDGL tests

- tests/pytorch/test_nn.py
Fixes #4947.  Until we handle #3431, the workaround is to ensure that the seed nodes generated do not have duplicates.
> [Test] Fix duplicate seed generation in unit test

- examples/sparse/hypergraphatt.py
Implements hypergraph attention in https://arxiv.org/pdf/1901.08150.pdf.
The hypergraph convolution there is identical to the HGNN example in #4917 .
Closes #4871 .
> [Example] Hypergraph attention

- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_matrix.cc
- python/dgl/mock_sparse2/diag_matrix.py
- python/dgl/mock_sparse2/sparse_matrix.py
- tests/pytorch/mock_sparse2/test_sparse_matrix.py
In addition, there is a minor fix for `SparseMatrix.indices()`.
> [Sparse] Add val_like and Disable Setting Nonzero Values

- tensoradapter/pytorch/torch.cpp
Some recent changes to PyTorch's CUDA allocator will break `recordStream` in TensorAdaptor. This PR is to fix it while keeping backward compatibility.
> [Fix] Fix `record_stream` for next PyTorch release

- examples/pytorch/gcn/train.py
Correction as mentioned in #4969 
I noticed that there is a normalisation step on line 97 while the normalised values are not used downstream. Even if this was meant to show the normalisation step, it would not be calculating the normalisation step described in the CGN paper. The paper considers both in and out degrees while the normalisation in the code only describes normalisation using the in degrees. In the end, the normalised values are assigned to g.ndata["norm"] but these values are not used afterwards.
Having a normalisation step here is also unnecessary since the GraphConv layer that is used already takes care of the normalisation. https://docs.dgl.ai/en/0.9.x/_modules/dgl/nn/pytorch/conv/graphconv.html#GraphConv
It confused me for a second thinking that I had to do the …
> [Examples] GCN example correction (#4969)

- python/dgl/dataloading/dist_dataloader.py
fix for #4290 
`NodeCollator` and `EdgeCollator` are moved from `//python/dgl/_dataloading/dataloader.py`.
> [Dist] remove dependency on deprecated _dataloading

- src/array/cuda/csr_mm.cu
Since next cuda release will deprecate `cusparse<t>csrgemm` functions, DGL build will fail by the time. I noticed that we choose to use old API instead of new `cusparseSpgemm` due to this failure https://github.com/dmlc/dgl/issues/3444. 
This PR re-enables  `cusparseSpgemm` API for `__CUDACC_VER_MAJOR__> 12 `, while ~~tentatively sticks to CUSPARSE_SPGEMM_ALG3~~ adaptively picks different algorithms  to alleviate memory pressure as well as avoid compromising speed a lot. As such, it can pass this case: https://github.com/dmlc/dgl/issues/3444
Note that the algorithm flags `CUSPARSE_SPGEMM_ALG3` and `CUSPARSE_SPGEMM_ALG2` will be introduced in the next release, because of lack of documentation at this moment, I can briefly describe perf. diff among cusparse spgemm algorithms (`default`, …
> Add support for next cusparse release

- docs/source/api/python/dgl.dataloading.rst
- docs/source/api/python/dgl.sampling.rst
Fixes #4967 by adding LaborSampler to dgl.dataloading doc index and sample_labors to dgl.sampling doc index.
> [Doc] Add Labor Sampler documentation

- python/dgl/_ffi/base.py
- python/dgl/dataloading/dataloader.py
Try to fix https://github.com/dmlc/dgl/issues/4982.
`use_alternate_streams` requires `record_stream` to be stream-safe, which is only available when TensorAdaptor is enabled.
> [Bugfix] Turn off `use_alternate_stream` when TensorAdaptor is not enabled

- tools/distpartitioning/data_shuffle.py
Fix a printing bug in [data_shuffle.py](https://github.com/dmlc/dgl/compare/master...classicsong:dgl:fix-data-shuffle?expand=1#diff-22f392bed959e7c4b021499e57b49c4c6ad40eaa552154ffcb61debb4d6271f0)
> [Bug fix] Fix bug when feature_tid is empty

- include/dgl/aten/macro.h
- include/dgl/runtime/device_api.h
- src/array/cuda/array_index_select.cu
- src/array/cuda/csr_get_data.cu
- src/array/cuda/rowwise_sampling.cu
- src/array/cuda/rowwise_sampling_prob.cu
- src/array/cuda/spmat_op_impl_csr.cu
- src/array/cuda/utils.h
- src/array/cuda/uvm/array_index_select_uvm.cu
- src/runtime/c_runtime_api.cc
- src/runtime/cuda/cuda_device_api.cc
- src/runtime/ndarray.cc
- tests/compute/test_subgraph.py
Fix #5004.
The root causes are two aspects:
1. Empty tensors might be treated as pinned though they're not.
2. When an empty CSR matrix is pinned, it has the `is_pinned=true` flag, but the underlying `indices` could be not pinned (empty). We should avoid calling `cudaHostGetDevicePointer` on it.
This PR fixes the above two issues and enhances the unit tests for them.
> [Bugfix] Fix empty tensors may being treated as pinned

- python/dgl/mock_sparse2/elementwise_op_diag.py
- python/dgl/mock_sparse2/elementwise_op_sp.py
- tests/pytorch/mock_sparse2/test_elementwise_op_diag.py
- Fix the indent of the doc.
- Replace `DiagMatrix` with `diag` in doc examples.
- Replace `SparseMatrix` with `create_from_coo` in doc examples.
- Properly handle other types of objects in `diag_add`, `diag_sub`, `diag_mul`.
- Properly handle diagonal matrix shape in `diag_add`, `diag_sub`, `diag_mul`, `diag_div`.
- Forbid adding a diagonal matrix to sparse matrix due to the lack of support for adding sparse matrices of different sparsity.
- Forbid adding two sparse matrices of different sparsity due to the same reason above.
- Extend unit tests to properly handle diagonal matrix shape and device.
- I will continue the rest effort with additional PRs.
One question, should we import all operators in `elementwise_op.py`? For example, currently it only imports `diag_add` from …
> [Sparse] Misc fix for existing elementwise ops

- python/dgl/nn/pytorch/conv/gatv2conv.py
Gatv2 has different weight in src and dst, the code using same one when graph is block. 
> [Model] Fix bug of gatv2 when input is block

- python/dgl/backend/mxnet/tensor.py
- python/dgl/data/fakenews.py
- python/dgl/data/fraud.py
- python/dgl/data/minigc.py
- python/dgl/data/qm9.py
Replace `np.bool/int` with `np.bool_/int64`. Numpy complains `np.bool/int` are just alias of Python built-in data types (`bool`/`int`), users should either use built-in data types or more specific `np.bool_` and `np.int32/int64`.
Besides, there're many warnings on the use of `np.int` and `np.float` (should be either `np.float32` or `np.float64`) in unit tests and examples, but they are not raised in the core lib so I don't fix them.
> [Fix core lib warning] Fix numpy dtype

- dgl_sparse/include/sparse/sparse_format.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/sparse_format.cc
- dgl_sparse/src/sparse_matrix.cc
- python/dgl/mock_sparse2/__init__.py
- python/dgl/mock_sparse2/diag_matrix.py
- python/dgl/mock_sparse2/elementwise_op.py
- python/dgl/mock_sparse2/elementwise_op_diag.py
- python/dgl/mock_sparse2/elementwise_op_sp.py
- python/dgl/mock_sparse2/sparse_matrix.py
- tests/pytorch/mock_sparse2/test_elementwise_op.py
- tests/pytorch/mock_sparse2/test_elementwise_op_diag.py
- tests/pytorch/mock_sparse2/test_elementwise_op_sp.py
- `A1 + A2`: Add two sparse matrices with different sparsity using PyTorch's implementation for COO matrices. The CSR support of PyTorch is still in beta phase, so I think it's better to wait for a few more versions.
- `D + A` and `A + D` using `A1 + A2`
- `DiagMatrix.dense`
- Fix of `SparseMatrix.dense` to handle dtypes other than float
> [Sparse] Add Two Sparse Matrices with Different Sparsity, DiagMatrix.dense, Add SparseMatrix and DiagMatrix

- tests/distributed/test_dist_graph_store.py
- tests/distributed/test_distributed_sampling.py
- tests/distributed/test_mp_dataloader.py
Some distributed tests using Python multiprocess were missing the exitcode check, which could lead to hangs when some subprocesses fail.
This PR adds asserts to check the exit codes of subprocesses in distributed tests.
> [Dist][Test] Add exitcode asserts in distributed tests

- python/dgl/mock_sparse/sddmm.py
torch_csr_tensor does not have backward for some common operators, so it should be converted to sparse_coo_tensor as soon as possible.
> [Sparse] Fix the sddmm backward problem in mock_sparse.

- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_matrix.cc
- dgl_sparse/src/sparse_matrix_coalesce.cc
- dgl_sparse/src/spspmm.cc
- python/dgl/mock_sparse2/sparse_matrix.py
- tests/pytorch/mock_sparse2/test_matmul.py
- tests/pytorch/mock_sparse2/test_sparse_matrix.py
Closes #5072 
Follow up of #5050
* Add two methods `coalesce()` and `has_duplicate` to the `SparseMatrix` class.
* Add two properties `row()` and `col()` for accessing row and column indices more easily.
* Add check for duplicate values in `spspmm` to avoid unfriendly CUDA errors.
> [Sparse] Add coalesce and has_duplicate to SparseMatrix

- python/dgl/mock_sparse2/diag_matrix.py
- python/dgl/mock_sparse2/sparse_matrix.py
- tests/pytorch/mock_sparse2/test_diag.py
- tests/pytorch/mock_sparse2/test_sparse_matrix.py
Part of #4962 . Remaining task is to refactor all the docstrings/docpages.
Print a `SparseMatrix`:
```
SparseMatrix(indices=tensor([[1, 1, 3],
[2, 1, 3]]),
values=tensor([1., 1., 2.]),
size=(4, 4), nnz=3)
```
Print a CUDA `SparseMatrix`:
```
SparseMatrix(indices=tensor([[1, 1, 3],
[2, 1, 3]], device='cuda:0'),
values=tensor([1., 1., 2.], device='cuda:0'),
size=(4, 4), nnz=3)
```
Print a CUDA `SparseMatrix` that requires grad for its values:
```
SparseMatrix(indices=tensor([[1, 1, 3],
[2, 1, 3]], device='cuda:0'),
values=tensor([1., 1., 2.], device='cuda:0', grad_fn=<ToCopyBackward0>),
size=(4, 4), nnz=3)
```
Print a CUDA `SparseMatrix` with vector-shape values:
```
SparseMatrix(indices=tensor([[1, 1, 3],
[2, 1, 3]], device='cuda:0'),
values=tensor([[ 0.2468, -0.7525],
[ 0.7526, -0.4141], …
```
> [Sparse] New print for SparseMatrix and DiagMatrix

- docs/source/guide/mixed_precision.rst
- tests/compute/test_sparse.py
Enable bf16 tests only when `torch.cuda.is_bf16_supported() == True`.
Update the doc to stress on it.
> [Bugfix] Fix bf16 tests

- tests/tools/test_dist_part.py
- tests/tools/utils.py
- tools/distpartitioning/array_readwriter/parquet.py
[Spark ML feature processing](https://spark.apache.org/docs/latest/ml-features) will commonly produce DataFrames, and by extension Parquet files, that contain columns whose elements are vectors instead of single values.
Example:
```python
>>> table.to_pandas()
vector
0  [1, 2, 3]
1  [4, 5, 6]
>>> table.shape
(2, 1)
```
This PR adds the capability to the Parquet reader to read such files by transforming them to regular Numpy matrices, converting each vector to one row of the matrix.
@classicsong @Rhett-Ying  requested for review
> [Dist] Allow reading and writing single-column vector Parquet files.

- src/array/cpu/spmat_op_impl_coo.cc
The wrong number of threads (always 1) was taken into account when selecting the COOdoCSR algorithm.
After the change, there is a significant performance improvement.
Microbenchmark (created as modification of [tests/cpp/test_spmat_coo.cc](https://gist.github.com/anko-intel/7e86c74342e3d45233c4cb849ace76eb)) gives following results on r6i.16xlarge (Intel(R) Xeon(R) Platinum 8375C) run with:
`numactl --physcpubind=0-31 ./build/runUnitTests --gtest_filter=*Big*`
index type | N | NNZ | 100%-sparsity | before [us] | after[us] | before/after
-- | -- | -- | -- | -- | -- | --
int32 | 5 111 000 | 2 612 233 | 0.00001% | 38 654 | 3 436 | 11.2
int64 | 5 111 000 | 2 612 233 | 0.00001% | 133 154 | 9 529 | 14.0
int32 | 12 000 333 | 14 400 800 | 0.00001% | 204 931 | 49 575 | 4.1
int64 | 12 000 333 | 14 …
> [Performance] Fix for number of threads in COOToCSR

- python/dgl/nn/pytorch/conv/sageconv.py
without this fix, below exception is thrown:
```
File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/site-packages/dgl-1.0-py3.10-linux-x86_64.egg/dgl/nn/pytorch/conv/sageconv.py", line 258, in forward
if self.bias is not None:
File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
raise AttributeError("'
{}
' object has no attribute '
{}
'".format(
AttributeError: 'SAGEConv' object has no attribute 'bias'
```
> [BugFix] fix unexpected exception when agg_type is GCN and bias disabled

- python/update_version.py
This adds another environment variable `DGL_VERSION_SUFFIX` to enable attaching [local version identifiers](https://peps.python.org/pep-0440/#local-version-identifiers) for CUDA versions (e.g. `1.0.0` versus `1.0.0+cu102`) in the nightly build and release pipeline.
> [Release] Update versioning with local CUDA version suffix

- python/dgl/backend/pytorch/sparse.py
Avoid initializing CUDA context at importing DGL.
To fix https://github.com/dmlc/dgl/issues/5129.
> [Bugfix] Avoid initializing CUDA context at importing

- python/dgl/data/utils.py
- tests/compute/test_data.py
This is to fix https://github.com/dmlc/dgl/issues/5138 and the last argument `numeric_owner` can only be assigned using keyword.
Ref: https://docs.python.org/3/library/tarfile.html#:~:text=TarFile.extractall(path%3D%27.%27%2C%20members%3DNone%2C%20*%2C%20numeric_owner%3DFalse)
This PR also adds an unit test  for `tar.extractall() ` method.
> [Bugfix] Fix the call of tar.extractall() method

- python/update_version.py
Starting in 1.0 we will be using local versions to indicate CUDA support (e.g. `1.0.0+cu102`).  However, `update_version.py` did not cover this case.  The consequence is that during nightly builds, if `__version__` already has a local version (e.g. `1.0.0+cu102`), executing `update_version.py` with a new local version like `1.0.0+cu116` will make the version something like `1.0.0+cu116+cu102`, which doesn't make sense.
This PR changes the regex pattern for replacement to include `+` and `_` so that the local version suffixes are properly replaced as well.
> [Build] Change regex pattern to include local versions in update_version.py
