dmlc/dgl

graph.py
model.py

graph draft

---

python/dgl/contrib/sampling/sampler.py

The documentation of the return value of NeighborSampler is broken.

[Doc] fix documentation of NeighborSampler.

---

README.md

[Doc] fix link in README

---

CONTRIBUTING.md
NEWS.md
conda/dgl/meta.yaml
include/dgl/runtime/c_runtime_api.h
python/dgl/_ffi/libinfo.py
python/setup.py
python/update_version.py
tutorials/models/1_gnn/4_rgcn.py
tutorials/models/1_gnn/6_line_graph.py
tutorials/models/1_gnn/8_sse_mx.py
tutorials/models/1_gnn/README.txt
tutorials/models/2_small_graph/3_tree-lstm.py
tutorials/models/2_small_graph/README.txt
tutorials/models/3_generative_model/5_dgmg.py
tutorials/models/3_generative_model/README.txt
tutorials/models/4_old_wines/2_capsule.py
tutorials/models/4_old_wines/7_transformer.py
tutorials/models/4_old_wines/README.txt

For 0.1.3 patch release.
* Update version: 0.1.2->0.1.3
* Add news.md
* Modify contributing.md

[Release] update version

---

README.md

Add links to docs, tutorials and discussion forum.

[Doc] Readme update

---

.github/ISSUE_TEMPLATE/questions-help-support.md

Minor change on the issue template.

[Github] change template to suggest using discussion forum more

---

examples/mxnet/gat/gat_batch.py
examples/pytorch/gat/gat.py

cora: dgl pygat: 84.1% dgl mxgat: 82.9% original paper: 83.0 ± 0.7%
citeseer : dgl pygat : 70.10% dgl mxgat: 74% original paper: 72.5 ± 0.7%
pubmed: dgl pygat: 77.6% dgl mxgat: 75%  original paper: 79.0 ± 0.3%

[Model] fix bugs in pygat and mxgat.

---

tutorials/basics/README.txt

[Doc] Update README.txt

---

docs/source/api/python/transform.rst

[Doc] small fix on the doc ref

---

docs/source/index.rst

[Doc] fix broken link in doc

---

examples/mxnet/gcn/README.md
examples/pytorch/gat/train.py
examples/pytorch/gcn/README.md
python/dgl/graph_index.py

Fix the residual shape problem in #354.

[Bugfix] Fix gat residual bug

---

include/dgl/immutable_graph.h
src/c_api_common.cc
src/graph/graph.cc
src/graph/graph_apis.cc
src/graph/immutable_graph.cc

[GraphIndex][Fix] signed and unsigned integer conversion

---

src/c_api_common.cc
src/graph/graph_apis.cc

This small pr fix the compilation error in Mac OS X.

[Bugfix] 'const size_t' (aka 'const unsigned long') is ambiguous on MacOS

---

README.md

[Readme] Fix broken link

---

tutorials/basics/4_batch.py

Some hotfix for the tutorial on batched graph classification

[Tutorial] Hotfix for Batched Graph Classification

---

examples/pytorch/jtnn/jtnn/datautils.py
examples/pytorch/jtnn/jtnn/jtnn_dec.py

Fixes issue #370 along with other bugs due to changes on zero shaped tensor in PyTorch 1.0.0.

[Model][Hotfix] JTNN: Fixing zero shaped tensor problems for PyTorch 1.0.0

---

examples/mxnet/gcn/README.md

The readme is out-of-date. gcn_concat.py doesn't show better performance on our datasets. Let's remove it to avoid confusion from users.

[Doc] Update README in MXNet GCN.

---

docs/source/install/index.rst

Instructions using MSBuild to compile from source on Windows
Related to #293

[Doc] MSBuild instructions

---

examples/pytorch/transformer/dataset/__init__.py
examples/pytorch/transformer/dataset/utils.py
examples/pytorch/transformer/modules/models.py
examples/pytorch/transformer/translation_test.py
examples/pytorch/transformer/translation_train.py

See changes for details.
1. Add length normalization in beam search (this trick is proposed in GNMT paper and used in tensor2tensor(official repo of transformer)), which helps to decode longer sequences.
2. The dataset we used as wmt14 is actually wmt16 (which has a similar size), I've uploaded the new data (thanks to GluonNLP) and make corresponding changes to the code.

[Model] Fix two problems of Transformer

---

docs/source/api/python/data.rst
examples/pytorch/gat/README.md
examples/pytorch/gat/gat.py
examples/pytorch/gat/train.py
examples/pytorch/gat/train_ppi.py
python/dgl/data/__init__.py
python/dgl/data/ppi.py

1. PPI dataloader.
2. Training script.

[Model]PPI dataloader and inductive learning script.

---

python/dgl/graph.py
python/dgl/graph_index.py
src/graph/graph.cc
tests/compute/test_pickle.py

Currently pickling a readonly graph throws errors.

[BUG] Fixing bug in pickling readonly graphs

---

docs/source/api/python/graph.rst

[Doc Fix] Fix group_apply_edges docs

---

src/graph/sampler.cc

It seems the SSE tutorial fails undeterministically. It's probably caused by the empty neighbor list in the neighbor sampling.

[Bugfix] Fix the SSE tutorial in CI.

---

tutorials/models/1_gnn/9_gat.py
tutorials/models/1_gnn/README.txt

Tutorial for graph attention network.

[Doc] Tutorial for GAT

---

README.md
examples/pytorch/README.md
examples/pytorch/sgc/README.md
examples/pytorch/sgc/sgc.py

upon discussed in #398, this PR contains a cached variable version example implementation of SGC.

[Model] Simplifying Graph Convolutional Networks.

---

CONTRIBUTORS.md

[Doc] Update contributors

---

python/dgl/nn/mxnet/conv.py
python/dgl/nn/pytorch/conv.py

[Doc] fix equation in nn.conv

---

docs/source/api/python/index.rst
docs/source/api/python/subgraph.rst
python/dgl/contrib/sampling/sampler.py

* Update docstring of neighbor sampler.
* Fix subgraph doc.

[Doc] update doc string of sampler

---

README.md

Update performance numbers in readme (#302 )

[Release] Update readme performance number

---

python/setup.py

Fix setup script to allow cython ext.

[Build] fix setup script to allow cython ext

---

python/dgl/runtime/scheduler.py
tests/compute/test_function.py

DGL scheduler did not correctly handle the case when message function for send is a builtin. This PR fixes bug and adds tests.

[BugFix] Handle case when calling send with builtin message function

---

python/dgl/frame.py
python/dgl/utils.py
tests/compute/test_pickle.py
tests/pytorch/test_pickle.py

Two bugs w.r.t. pickling (Issue #438 ):
* Pickling `torch.dtype` sometimes fails. So always use our own pickling method.
* `utils.index` is not properly pickled when it represents a slice data.

[Bugfix] fix bug in pickling

---

examples/pytorch/rgcn/link_predict.py

Fix a wrong representation of test_relation tensor. This bug generates a run time error during the evaluation stage.  

[Bugfix] Fix shape of test_relation tensor in RGCN

---

CONTRIBUTORS.md
docs/source/contribute.rst

[Doc]Fix 'git remote' command in contribution doc

---

python/dgl/contrib/sampling/dis_sampler.py
python/dgl/network.py
src/graph/network.cc
src/graph/network/communicator.h
src/graph/network/socket_communicator.cc
src/graph/network/socket_communicator.h

Small fix for the inner API of distributed sampler.

[Fix] Update inner API of distributed sampler

---

examples/mxnet/gcn/README.md
examples/mxnet/gcn/train.py
examples/pytorch/gcn/README.md
examples/pytorch/gcn/train.py

Reddit is stored in scipy csr. It doesn't allow adding a self loop.

[BUGFIX] Fix GCN for reddit

---

src/graph/network/msg_queue.h
src/graph/network/socket_communicator.cc

This is to fix the compilation warnings in the source code of distributed sampler.

Fix warnings in the distributed sampler.

---

examples/pytorch/appnp/README.md
examples/pytorch/appnp/appnp.py
examples/pytorch/appnp/train.py

This PR implement dgl version of APPNP model according to the paper of "Predict then Propagate: Graph Neural Networks meet Personalized PageRank " and its original code [https://github.com/klicperajo/ppnp](https://github.com/klicperajo/ppnp). .
This PR uses DGL's API to implement APPNP model.

[Model] Add APPNP model

---

examples/pytorch/jtnn/jtnn/datautils.py

[BUG] Update URL for JTNN dataset

---

examples/mxnet/sampling/dis_sampling/README.md
examples/mxnet/sampling/dis_sampling/gcn_ns_sampler.py
examples/mxnet/sampling/dis_sampling/gcn_trainer.py
examples/mxnet/sampling/dis_sampling/run_sampler.sh
examples/mxnet/sampling/dis_sampling/run_trainer.sh
python/dgl/contrib/sampling/dis_sampler.py
python/dgl/network.py
src/graph/network.cc
src/graph/network/communicator.h
src/graph/network/socket_communicator.cc
src/graph/network/socket_communicator.h
tests/compute/test_dis_sampler.py

This PR refactoring the networking APIs for better support to distributed kvstore and ZMQ.

[RPC] Refactoring networking APIs 

---

examples/mxnet/sampling/README.md
examples/mxnet/sampling/gcn_cv_sc.py
examples/mxnet/sampling/gcn_ns_sc.py
examples/mxnet/sampling/graphsage_cv.py
examples/mxnet/sampling/train.py

This PR is to refactor the code of the sampling examples to make it run faster and prepare them for distributed training.

[Model] Refactor the sampling examples

---

CONTRIBUTORS.md
examples/mxnet/sampling/README.md
examples/mxnet/sampling/gcn_cv_sc.py
examples/mxnet/sampling/gcn_ns_sc.py
examples/mxnet/sampling/graphsage_cv.py
examples/mxnet/sampling/train.py
examples/pytorch/appnp/README.md
examples/pytorch/appnp/appnp.py
examples/pytorch/appnp/train.py

This PR add edge dropout to the dgl implementation of APPNP model.
Add edge/adjacency dropout to the propagation step of APPNP Model.

[Model] Add edge dropout to APPNP

---

examples/pytorch/dgi/README.md
examples/pytorch/dgi/dgi.py
examples/pytorch/dgi/gcn.py
examples/pytorch/dgi/train.py
python/dgl/data/citation_graph.py

This PR implement dgl version of DGI model according to the paper of "DEEP GRAPH INFOMAX" and its original code and test on three popular graph dataset cora, citeseer & pubmed.
Essentially, this PR uses DGL's API to implement DGI model.
And fix a small bug of "_normalize" function in data/citation_graph

[Model] Add DGI Model

---

tutorials/models/1_gnn/1_gcn.py
tutorials/models/1_gnn/9_gat.py

Add self-edges in tutorials of GCN and GAT.

fix tutorial

---

python/dgl/data/__init__.py

The error message is confusing when users don't specify the dataset.

[BUGFIX] fix the error message in the data loader.

---

src/graph/network.cc
src/graph/network/communicator.h
src/graph/network/socket_communicator.cc
src/graph/network/socket_communicator.h

[RPC] Use private buffer instead of global buffer

---

examples/pytorch/sampling/README.md

PyTorch consumes too much memory for reddit.
```
File "gcn_ns_sc.py", line 264, in <module>
main(args)
File "gcn_ns_sc.py", line 227, in main
pred = infer_model(nf)
File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
result = self.forward(*input, **kwargs)
File "gcn_ns_sc.py", line 105, in forward
layer)
File "/home/ubuntu/.local/lib/python3.6/site-packages/dgl/nodeflow.py", line 817, in block_compute
Runtime.run(prog)
File "/home/ubuntu/.local/lib/python3.6/site-packages/dgl/runtime/runtime.py", line 10, in run
exe.run()
File "/home/ubuntu/.local/lib/python3.6/site-packages/dgl/runtime/ir/executor.py", line 472, in run
C = F.spmm(spA, B)
File …
```

[Model] [PyTorch] remove reddit in readme of pytorch sampling

---

examples/mxnet/sampling/gcn_cv_sc.py
examples/mxnet/sampling/gcn_ns_sc.py
examples/mxnet/sampling/graphsage_cv.py
python/dgl/contrib/graph_store.py
python/dgl/graph.py
tests/compute/test_graph.py
tests/mxnet/test_shared_mem_store.py

This PR is to update the graph store API to make sure that users won't misuse the graph store API.

[API] update graph store API.

---

examples/mxnet/gat/README.md
examples/mxnet/rgcn/README.md
examples/mxnet/sampling/README.md
examples/mxnet/tree_lstm/README.md
examples/pytorch/appnp/README.md
examples/pytorch/capsule/README.md
examples/pytorch/dgi/README.md
examples/pytorch/dgmg/README.md
examples/pytorch/gat/README.md
examples/pytorch/gcn/README.md
examples/pytorch/gin/README.md
examples/pytorch/graphsage/README.md
examples/pytorch/line_graph/README.md
examples/pytorch/sampling/README.md
examples/pytorch/sgc/README.md
examples/pytorch/transformer/README.md
examples/pytorch/tree_lstm/README.md

All demo use python-3

---

examples/mxnet/sampling/dis_sampling/README.md
examples/mxnet/sampling/dis_sampling/dis_gcn_cv_sc.py
examples/mxnet/sampling/dis_sampling/dis_gcn_ns_sc.py
examples/mxnet/sampling/dis_sampling/dis_graphsage_cv.py
examples/mxnet/sampling/dis_sampling/run_sampler.sh
examples/mxnet/sampling/dis_sampling/run_trainer.sh
examples/mxnet/sampling/dis_sampling/sampler.py
examples/mxnet/sampling/dis_sampling/train.py

[DEMO] Reproduce numbers of distributed training in AMLC giant graph paper

---

include/dgl/immutable_graph.h
tests/compute/test_basics.py
tests/compute/test_graph_index.py
tests/mxnet/test_shared_mem_store.py

[BUGIFX] fix a bug in edge_ids

---

examples/pytorch/sampling/README.md
examples/pytorch/sampling/dis_sampling/README.md
examples/pytorch/sampling/dis_sampling/gcn_cv_sc_train.py
examples/pytorch/sampling/dis_sampling/gcn_ns_sc_sampler.py
examples/pytorch/sampling/dis_sampling/gcn_ns_sc_train.py
examples/pytorch/sampling/dis_sampling/sampler.py

[DEMO] Add Pytorch demo for distributed sampler

---

examples/mxnet/sampling/run_store_server.py
python/dgl/contrib/graph_store.py
python/dgl/graph_index.py
src/graph/graph_apis.cc
tests/compute/test_graph_index.py

There are still various bugs that cause segfault when running GCN on giant graphs.

[BUGFIX] fix bugs for running GCN on giant graphs.

---

examples/mxnet/sampling/README.md
examples/mxnet/sampling/dis_sampling/README.md
examples/pytorch/sampling/dis_sampling/README.md

[DEMO] Update demo of distributed sampler

---

tests/cpp/graph_index_test.cc
tests/cpp/message_queue_test.cc
tests/cpp/tcp_socket_test.cc

[TEST] Add network cpp test

---

src/graph/network/socket_communicator.h
tests/cpp/socket_communicator_test.cc
tests/cpp/tcp_socket_test.cc

Add unittest for C++ RPC

---

examples/mxnet/sampling/dis_sampling/README.md
examples/pytorch/sampling/dis_sampling/README.md

We add more detailed usage in README.md for the demo of the distributed sampler.

Update README.md for the demo of distributed sampler

---

Jenkinsfile
python/dgl/backend/mxnet/tensor.py
tests/mxnet/test_shared_mem_store.py

The MXNet in CI breaks some of the models. Let's disable the broken test first. In addition, we retry connecting to the DGL graph store server.

[Test] fix CI.

---

python/dgl/contrib/sampling/randomwalk.py
python/dgl/contrib/sampling/sampler.py
python/dgl/graph_index.py
python/dgl/network.py

Add `int()` conversion for all CAPI calls so it could support `numpy.int32` integer types.
Related issues: #538 .

[Bugfix] fix numpy integer bug

---

examples/mxnet/sampling/README.md

Provide more explicit instructions to run multi-processing training.

[Doc] A little update on README.md

---

examples/mxnet/sampling/dis_sampling/README.md
examples/pytorch/sampling/dis_sampling/README.md

We provide more detailed README.md for the demo of distributed sampler.

[DEMO] Update README.MD of demo for distributed sampler

---

tutorials/models/5_giant_graph/2_giant.py

This tutorial introduces the components for giant graph.

[Doc] tutorial of components for giant graph

---

Jenkinsfile

Hotfix the win lib name problem in #592 .

[CI] Fix win64 CI

---

python/dgl/contrib/graph_store.py
tests/mxnet/test_shared_mem_store.py

The tests on shared-memory store still somtimes fail with various errors.

[Test] Fix tests in test_shared_mem_store.

---

tutorials/models/5_giant_graph/2_giant.py

[Doc] Tutorial minor fix

---

tests/compute/test_traversal.py

Essentially a redo of PR #612 which is erased by git merge somehow.

[BUG][Test] Fix random BFS traversal failures

---

python/dgl/nodeflow.py
tests/compute/test_nodeflow.py

https://github.com/dmlc/dgl/pull/584 fixes some of the problems. This is a followup PR to fix more NodeFlow APIs to handle negative layer id and block id.

[BUGFIX] handle more negative layer id and block id.

---

docs/source/api/python/nn.rst
docs/source/contribute.rst
docs/source/features/builtin.rst
docs/source/index.rst
docs/source/install/index.rst
tutorials/basics/3_pagerank.py
tutorials/models/5_giant_graph/2_giant.py

* Doc page for builtin functions.
* Update install from source. Include cuda build.

[Doc] doc page for builtin functions

---

docs/source/api/python/graph_store.rst
docs/source/api/python/nodeflow.rst
python/dgl/graph.py
python/dgl/nodeflow.py
tutorials/models/5_giant_graph/1_sampling_mx.py
tutorials/models/5_giant_graph/2_giant.py

[Doc] fix some document warnings

---

src/graph/sampler.cc
tests/compute/test_nodeflow.py

When we sample neighbors with self loop enabled, we need to make sure it gets right edge id if the self loop exists in the parent graph.

[BUGFIX] fix a bug when sampling neighbors with self loop.

---

cmake/util/FindCUDA.cmake
conda/dgl/bld.bat
conda/dgl/build.sh
conda/dgl/meta.yaml
include/dgl/runtime/c_runtime_api.h
python/dgl/_ffi/libinfo.py
python/update_version.py

0.3 release.
EDIT: Will merge after PR #634

[Release] Bump up version

---

Jenkinsfile

* Remove mx GPU tutorial test (there is no such thing).
* Temporarily disable mx tutorial test due to large dataset size so we can test other PR.
* Cleanup workspace after build & test
@zheng-da 

[CI] workspace and disable mx tutorial

---

examples/pytorch/sgc/README.md
examples/pytorch/sgc/sgc_reddit.py

provide an example of training SGC on the Reddit dataset.

[Example] Add reddit example for SGC. 

---

tests/compute/test_removal.py

don't import pytorch in test explicitly.

[TEST] fix test.

---

docs/source/install/index.rst

install a specific MXNet nightly build.

[Doc] fix install.

---

examples/pytorch/rgcn/link_predict.py

[BUG][Model] Fix dtype issue in R-GCN

---

python/dgl/function/message.py
python/dgl/nn/pytorch/softmax.py
tests/pytorch/test_nn.py

Fix the doc of `src_mul_edge` and `edge_softmax`.
Add a gradient check of edge_softmax in unittest.

[Fix] Bugfix in docs and check gradient of edge_softmax in test

---

examples/pytorch/diffpool/data_utils.py
examples/pytorch/diffpool/model/dgl_layers/aggregator.py
examples/pytorch/diffpool/model/dgl_layers/bundler.py
examples/pytorch/diffpool/model/dgl_layers/gnn.py
examples/pytorch/diffpool/model/encoder.py
examples/pytorch/diffpool/model/loss.py
examples/pytorch/diffpool/model/model_utils.py
examples/pytorch/diffpool/model/tensorized_layers/diffpool.py
examples/pytorch/diffpool/model/tensorized_layers/graphsage.py
examples/pytorch/diffpool/train.py
python/dgl/data/tu.py

A small PR fix on DiffPool, last two formatting commit were not included in the previous PR.

[Model][Hotfix] DiffPool formatting fix

---

docs/source/install/index.rst

The original MXNet version in the installation guide has a small bug. We should use the newer version.

[Doc] use a newer version of MXNet.

---

docs/source/install/index.rst

MXNet 1.5 is released. Users can install the official release instead of using the nightly build.

Fix MXNet install doc

---

docs/source/api/python/nn.mxnet.rst
docs/source/api/python/nn.pytorch.rst
python/dgl/nn/mxnet/softmax.py
python/dgl/nn/pytorch/softmax.py

There are some errors and missing parts of dgl.nn.*.softmax modules.
- python/dgl/nn/mxnet/softmax.py
- python/dgl/nn/pytorch/softmax.py
- docs/source/api/python/nn.mxnet.rst
- docs/source/api/mxnet/nn.pytorch.rst

[Doc] Improve the docstring of dgl.nn.softmax modules.

---

python/dgl/data/__init__.py
python/dgl/data/chem/__init__.py
python/dgl/data/chem/csv_dataset.py
python/dgl/data/chem/tox21.py
python/dgl/data/chem/utils.py
python/dgl/data/utils.py

@mufeili If you are fine with the code, I'll add the documentation soon.

[Dataset] Tox21

---

examples/pytorch/model_zoo/README.md
examples/pytorch/model_zoo/chem/property_prediction/README.md
examples/pytorch/model_zoo/chem/property_prediction/classification.py
examples/pytorch/model_zoo/chem/property_prediction/inference_pretrained.ipynb
examples/pytorch/model_zoo/chem/property_prediction/utils.py
python/dgl/data/chem/README.md
python/dgl/data/chem/csv_dataset.py
python/dgl/data/chem/tox21.py
python/dgl/data/chem/utils.py
python/dgl/model_zoo/API.md
python/dgl/model_zoo/__init__.py
python/dgl/model_zoo/chem/README.md
python/dgl/model_zoo/chem/__init__.py
python/dgl/model_zoo/chem/gcn.py
python/dgl/model_zoo/chem/pretrain.py

Refactor PR #753. Already reviewed when merging the #765 within the branch.

[Model Zoo] Refactor GCN on Tox21

---

examples/pytorch/rgcn/link_predict.py
examples/pytorch/rgcn/utils.py

Fixing issue #757. 
Passing test_triples size to `perturb_and_get_rank` instead of `num_entities`. I also changed the variable names accordingly and adapted it to the calls from link_predict during validation and test.

[BUGFIX] Fixing RGCN evaluation bug

---

python/dgl/data/chem/csv_dataset.py
python/dgl/data/chem/tox21.py

Change reading dataframe to file path

[Dataset] Fix CSVDataset Interface

---

examples/pytorch/model_zoo/chem/README.md
examples/pytorch/model_zoo/chem/generative_models/dgmg/utils.py

[Model Zoo] Hotfix for examples

---

python/dgl/nn/pytorch/conv.py

[Doc]Update conv.py

---

python/dgl/nn/pytorch/conv.py

- [] Related issue is referred in this PR

[docs]update conv.py

---

tests/backend/mxnet/__init__.py

[Fix test backend] Fix softmax in mxnet backend

---

README.md

We have uploaded our RLGM paper to ArXiv: https://arxiv.org/pdf/1909.01315.pdf.
This PR adds a cite section in README and provides the bibtex for this paper to be cited.
README.md

[Doc] Add cite section in README

---

docs/source/install/index.rst

[Docs] Update install in doc.dgl.ai

---

python/dgl/convert.py
src/graph/unit_graph.cc

Fix a bug in `to_hetero` when metagraph is given. Add more comments to the code.

[Bugfix][Hetero] fix to_hetero when metagraph is given

---

include/dgl/graph_interface.h
python/dgl/contrib/sampling/sampler.py
src/graph/sampler.cc
tests/compute/test_sampler.py

When creating negative edges, we need to check if the negative edges are true negative edges.

[Feature] find the existence of negative edges.

---

python/dgl/convert.py

Don't know why it passed the merging test...

[Bugfix][Hetero] Fix typo

---

tutorials/models/5_giant_graph/1_sampling_mx.py

The sampling tutorial is written in MXNet, but the default backend is Pytorch. Users are confused why they see errors when running the tutorial when their DGL backend is Pytorch. The tutorial should set the backend to MXNet.

[Tutorial] change the backend to mxnet.

---

src/graph/sampler.cc

[BUGFIX] fix compile error on Mac.

---

apps/kg/README.md

[Doc] Fix KG readme

---

apps/kg/eval.py
apps/kg/train.py

We should use PBG sampler for testing. The computation will be much more efficient.

[KG] use PBG sampler for testing.

---

apps/kg/models/mxnet/tensor_models.py
apps/kg/models/pytorch/tensor_models.py

The file names used for loading and saving were mismatched.

[KG] save embeddings in NumPy

---

apps/kg/README.md
apps/kg/config/best_config.sh

[Doc] Update kg readme

---

src/graph/heterograph.cc

VS2015 would throw an internal compiler error otherwise

[WIP][Windows] Working around a mysterious VS2015 error

---

README.md

I found the web link of D2L has been changed to gluon.ai

update the web link of d2l

---

apps/kg/README.md

Explicitly mention that DGL-KE is adapted from the KnowledgeGraphEmbedding package.

[KG] a little update on readme.

---

docs/source/features/builtin.rst

[Doc] minor spelling updates

---

tutorials/basics/1_first.py

Voice and tone updates for readability

---

tests/compute/test_kvstore.py

Add more unit tests to kvstore. 

[KVStore] Add more test to kvstore

---

python/dgl/data/chem/utils.py

[Chemistry] Hot fix

---

docs/source/api/python/data.rst
docs/source/api/python/model_zoo.rst
examples/pytorch/model_zoo/chem/property_prediction/README.md
examples/pytorch/model_zoo/chem/property_prediction/classification.py
examples/pytorch/model_zoo/chem/property_prediction/configure.py
examples/pytorch/model_zoo/chem/property_prediction/regression.py
examples/pytorch/model_zoo/chem/property_prediction/utils.py
python/dgl/data/chem/__init__.py
python/dgl/data/chem/pubchem_aromaticity.py
python/dgl/data/chem/tox21.py
python/dgl/model_zoo/chem/__init__.py
python/dgl/model_zoo/chem/attentive_fp.py
python/dgl/model_zoo/chem/pretrain.py

Add a model AttenttiveFP from [Pushing the Boundaries of Molecular Representation for Drug Discovery with the Graph Attention Mechanism](https://pubs.acs.org/doi/abs/10.1021/acs.jmedchem.9b00959).

[Model Zoo] AttentiveFP

---

examples/pytorch/cluster_gcn/run_reddit.sh
examples/pytorch/dgmg/README.md
examples/pytorch/model_zoo/chem/README.md

1. Fix a confusing setting in cluster-GCN
2. Update some READMEs

[Misc] Update README(s)

---

docs/source/faq.rst

simple readability and style changes

---

tests/compute/test_kvstore.py

Add unit test of shared-memory on kvstore.

[KVStore] Test shared-mem on kvstore

---

examples/mxnet/dis_kvstore/client.py
examples/pytorch/dis_kvstore/client.py
python/dgl/contrib/dis_kvstore.py
tests/compute/test_kvstore.py

Small change for kvstore pull_wait() API. 

Small change for kvstore api

---

examples/pytorch/gcn/train.py

AWS DLC test use these two examples.

[Example]Make print of GCN example of mxnet and pytorch exact same.

---

tutorials/basics/2_basics.py

In the opening paragraph, it would be helpful to provide some overall scenario and the prerequisites you expect readers to have completed before they start here. "This tutorial assumes you have already..." Add a link to Install DGL topic perhaps and any other framework or IDE or even specialized knowledge. With this context, you help readers to succeed by setting expectations.
Better to group all tutorials (this, PageRank with, Batched Graph, Working with) at the same level in the left navigation rail and all as subsections of DGL Basics.

Edit for grammar and style

---

tutorials/basics/3_pagerank.py

Can you add a link for the download to this sentence: You can also `download <location?>` and run the different code examples...
As with other tutorial topics, it would be helpful to add an opening section paragraph about assumptions or prerequisites. Sub-head ==Prerequisites==
Edit for readability in the narrative text. Feedback welcome @aaronmarkham

[Doc] PageRank with DGL message passing Edit for grammar and style

---

tutorials/hetero/1_basics.py

Edit pass for grammar and style. 
* A great value-add would be to provide assumptions and prerequisites in the opening section. This helps readers understand what they need to have in place in order to make use of your tutorial steps.
* The wikidata knowledge graph could be improved with a smaller font for the Zuckerberg circle.
Edit pass for grammar and style

[Doc] Edit for readability

---

docs/source/install/index.rst

The current installation instruction for Mac doesn't work.

[Doc] fix installation instruction.

---

python/dgl/heterograph.py
tests/compute/test_heterograph.py

[Bug] Fix DGLHeteroGraph.edge_type_subgraph

---

examples/pytorch/cluster_gcn/modules.py

fix minor error: GCNLayerSAGE->GraphSAGELayer

[Bug] fix minor error: GCNLayerSAGE->GraphSAGELayer

---

docs/source/install/index.rst

In the opening paragarph, it would also be great to provide some rationale for why you recommend conda or pip.

[Doc] Grammar and style edit pass

---

tutorials/basics/4_batch.py

As with other tutorials, it would help the reader if you add a paragraph in the opening section about assumptions or prerequisites.
Does this refer to SageMaker Ground Truth feature? "...assigns its ground truth label..." If yes, phrase it thus: assigns its Amazon SageMaker Ground Truth label
Edit voice and tone to improve readability.

[Doc] Edit for grammar and style

---

docs/source/features/builtin.rst

Edit pass for readability. 
Can you clarify: "are of different, but shapes that can be broadcast." Are they of different shapes, but both can be broadcast?
Edit for grammar and style.

[Doc] Grammatical updates

---

docs/source/features/nn.rst

Improve the flow and readability
Edit for grammar and style

[Doc] NN Modules Edit for grammar and style

---

tutorials/models/1_gnn/README.txt

[Doc] Graph neural network and its variant Edit for grammar and style

---

tutorials/models/1_gnn/4_rgcn.py

[Doc] Relational Graph Convolutional Network Tutorial Edit for readability

---

python/dgl/graph.py
python/dgl/heterograph.py
tests/compute/test_basics.py

[Bug] Fix #1036

---

tutorials/models/1_gnn/6_line_graph.py

Updates for grammar and readability

[Doc] 6_line_graph.py Edit pass

---

docs/source/contribute.rst

New contribution guideline that *should* lower the bar for third-party contributors... at least a little bit.
In response to @MilkshakeForReal 's ~~sacrifice~~ experience in #964 .  Please check if anything is missing or still not good enough.

[RFC][Doc] Contribution Guideline updates

---

tutorials/models/1_gnn/8_sse_mx.py

Revisions for grammar and style

[Doc] Stochastic steady-state embedding (SSE) Edit for readability

---

tutorials/models/4_old_wines/7_transformer.py

Edit pass for grammar and style

[Doc] Transformer tutorial, edit for readability

---

tutorials/models/4_old_wines/2_capsule.py

[Doc] Capsule network tutorial, edit pass

---

apps/kg/dataloader/KGDataset.py

the tqdm package isn't necessary.

[KG] remove tqdm

---

docs/source/install/index.rst

It's not necessary to apt install build-dep in Ubuntu.

[Doc] update installation instruction.

---

tutorials/models/3_generative_model/README.txt

Edit pass for grammar and style
Change format to .rst instead of current .txt?

[Doc] Generative models readme.txt, edit for readability

---

tutorials/models/3_generative_model/5_dgmg.py

Edit for grammar and style. Can you clarify "Instead of and/or"? @mli or @aaronmarkham

[Doc] Generative models, edit pass

---

python/dgl/data/karate.py

[Fix] Fix karate due to networkx version change

---

tutorials/models/2_small_graph/README.txt

Edit for grammar and style. Should this be an .rst on .txt?

[Doc] Small graphs readme.txt, edit pass

---

README.md
python/dgl/data/gnn_benckmark.py

Fix https://github.com/dmlc/dgl/issues/1078, https://github.com/dmlc/dgl/issues/1077

[Fix] Fix #1078, #1077 and add nightly build to readme

---

python/dgl/convert.py
python/dgl/nn/mxnet/conv/appnpconv.py
python/dgl/nn/pytorch/conv/appnpconv.py

Fix some typos in our docstring: #1079 .
- python/dgl/convert.py
- python/nn/*/conv/appnp.py

[hotfix] APPNP formula and dgl.bipartite

---

tutorials/models/1_gnn/1_gcn.py

The last layer shouldn't have activation. Otherwise, there is a significant performance drop. Also, add evaluation to show how we usually evaluate performance of a GNN model.

[Doc] Fix gcn tutorial

---

python/dgl/transform.py

Fix the bug reported in #1081 

[Bug Fix] Reverse

---

docs/source/api/python/sampler.rst

The document of EdgeSampler was missing.

[Doc] add document of EdgeSampler.

---

apps/kg/eval.py
apps/kg/models/general_models.py
apps/kg/tests/test_score.py
apps/kg/train.py

We need to set a default backend if a user doesn't define DGLBACKEND.

[KG] set default backend.

---

examples/pytorch/recommendation/README.md

Fixed the training file

---

python/dgl/backend/numpy/tensor.py

As requested by @VoVAllen for TF integration #978 . This PR implements topk and argtopk for numpy backend,

[Hotfix] topk and argtopk for numpy backend

---

examples/pytorch/model_zoo/chem/binding_affinity_prediction/README.md

[DGL-Chem] Hotfix for README

---

tests/compute/test_kernel.py

[Fix] Add error message

---

apps/kg/eval.py
apps/kg/train.py
apps/kg/train_mxnet.py
apps/kg/train_pytorch.py

When we trained KGE with multiple processes, we evaluated them separately in each process. We need to merge all evaluation results to have a better understanding of the model performance.

[KG] merge eval results in all processes.

---

apps/kg/dataloader/sampler.py
apps/kg/eval.py
apps/kg/models/pytorch/tensor_models.py
apps/kg/train.py

We should reduce the number of works for sampling during the evaluation when multiprocessing is used. This can reduce memory consumption by sampling and allow us to evaluate with a larger batch size.

[KG] More fixes on eval

---

docs/source/env_var.rst
python/dgl/data/utils.py

[Dataset] Change download repo to cdn

---

examples/pytorch/recommendation/rec/datasets/movielens.py

Fixes #1182 .
This is embarrassing.

[BUG] Fix MovieLens feature assignment

---

examples/pytorch/han/README.md

[Doc] Note on duplicate author in ACM heterograph dataset

---

python/dgl/heterograph_index.py
python/dgl/utils.py
tests/compute/test_pickle.py

Quick implementation for pickling heterographs.  Fixes #1070 .
Note that this code would be eventually cleaned up since we intend to unify `DGLGraph` and `DGLHeteroGraph` (see #1153 ).  Nevertheless, one waiting for pickle support could quickly try this out in nightly builds after this code is merged into master branch.

[Feature] Pickle support for heterograph

---

apps/kg/dataloader/sampler.py
apps/kg/models/pytorch/tensor_models.py
apps/kg/train.py
apps/kg/train_pytorch.py
python/dgl/contrib/sampling/sampler.py
src/graph/sampler.cc

There are various overheads in the sampler.

[KG] Accelerate the sampler

---

apps/kg/train.py
apps/kg/train_pytorch.py

Fix cal result

---

apps/kg/train.py
apps/kg/train_pytorch.py

Kg hot dev

---

apps/kg/models/general_models.py
apps/kg/models/pytorch/score_fun.py
apps/kg/train.py
apps/kg/train_pytorch.py

Kge mgpu transr

---

apps/kg/dataloader/sampler.py
apps/kg/train.py
apps/kg/train_pytorch.py

Balanced relation partition

---

python/dgl/contrib/sampling/sampler.py

Let's make sure the doc is consistent with the implementation. https://github.com/dmlc/dgl/issues/1223

[Doc] Fix the doc of NeighborSampler.

---

python/dgl/nn/pytorch/softmax.py

Fixes #1237 where HAN example was broken.

[Bug] Fix regression on HAN example

---

README.md

By James Zhang and many others.

[Doc] New README

---

conda/dgl/meta.yaml
python/dgl/data/utils.py
python/setup.py

Consider the wide use of the `requests` package in our project and the fact that it is a well-known package, making it as our package dependency. This will take effect in the next release.
Copy @VoVAllen and @BarclayII since you might want to be aware of this when configuring CI and release scripts.
Related thread: https://discuss.dgl.ai/t/somthing-wrong-with-downloading-data/704/2

[Misc] add requests as the package dependency

---

apps/kg/README.md
apps/kg/dataloader/KGDataset.py
docker/README.md
examples/pytorch/graphwriter/README.md
examples/pytorch/graphwriter/prepare_data.sh
examples/pytorch/metapath2vec/download.py
examples/pytorch/model_zoo/chem/generative_models/dgmg/README.md
examples/pytorch/model_zoo/chem/property_prediction/README.md
examples/pytorch/pointcloud/main.py
examples/pytorch/recommendation/README.md
examples/pytorch/rrn/sudoku_data.py
examples/pytorch/rrn/sudoku_solver.py
examples/pytorch/transformer/dataset/utils.py
python/dgl/contrib/sampling/sampler.py
python/dgl/nodeflow.py
tutorials/basics/1_first.py
tutorials/basics/4_batch.py
tutorials/basics/5_hetero.py
tutorials/models/1_gnn/8_sse_mx.py
tutorials/models/1_gnn/9_gat.py
tutorials/models/3_generative_model/5_dgmg.py
tutorials/models/4_old_wines/7_transformer.py
tutorials/models/5_giant_graph/1_sampling_mx.py
tutorials/models/5_giant_graph/2_giant.py

Change s3 links to data.dgl.ai for better user experience

[Fix] Change s3 links to data.dgl.ai

---

CMakeLists.txt
python/dgl/function/message.py

Provide better explanation of builtin functions.

[Doc] Fix the docstring of builtin functions.

---

docs/source/developer/ffi.rst
python/dgl/data/graph_serialize.py
python/dgl/graph.py
python/dgl/model_zoo/chem/gnn.py
tests/compute/test_transform.py

Remove the remnants of BatchedDGLGraph that should have been deleted in #1216 and update some of the docstrings.

[hotfix] Remove the remnants of BatchedDGLGraph and update the docstring.

---

asv.conf.json

[Fix] Fix regression result

---

docs/source/install/index.rst

The introduced METIS submodules also has submodules. We need to pull them also. Fix instructions in build from source in doc.

[Doc] Fix submodule has submodules

---

apps/kg/models/general_models.py
apps/kg/train.py

We need to save config when saving model embeddings.

[KG] save config when saving the model

---

apps/kg/config/best_config.sh
apps/kg/dataloader/sampler.py
apps/kg/distributed/freebase_complex.sh
apps/kg/distributed/freebase_distmult.sh
apps/kg/distributed/freebase_transe_l2.sh
apps/kg/eval.py
apps/kg/kvclient.py
apps/kg/train.py
apps/kg/train_pytorch.py
apps/kg/utils.py

We need to allow users to specify arbitrary batch size, neg sample size. One solution is to adjust them in the training code.

[KG] make batch size compatible with neg sample size

---

apps/kg/dataloader/KGDataset.py

KG Dataloader fail on build in Freebase

Fix for dataloader

---

python/dgl/graph.py
python/dgl/heterograph.py
python/dgl/nn/mxnet/conv/sageconv.py
python/dgl/nn/pytorch/conv/sageconv.py
python/dgl/nn/pytorch/softmax.py
python/dgl/nn/tensorflow/conv/sageconv.py
tests/mxnet/test_nn.py
tests/pytorch/test_nn.py
tests/tensorflow/test_nn.py

1. Make PyTorch `edge_softmax` work on bipartite graphs as well.
2. Make `SAGEConv` work on graphs constructed by `dgl.graph` again.
3. Make `SAGEConv` support bipartite graphs for MXNet and Tensorflow as well.

[Bug] Multiple fixes

---

examples/pytorch/graphsage/train_sampling.py
tutorials/basics/1_first.py
tutorials/basics/2_basics.py
tutorials/basics/4_batch.py
tutorials/models/1_gnn/1_gcn.py
tutorials/models/1_gnn/4_rgcn.py
tutorials/models/1_gnn/9_gat.py
tutorials/models/4_old_wines/2_capsule.py

Did a sweep on our tutorials and update the stale APIs.
* Remove all the usage of `add_nodes` and `add_edges`. Explain more about various efficient ways of constructing a DGLGraph.
* Replace the `torch.eye` with `nn.Embedding` in the First Glance tutorial to avoid pitfalls.
* Use our NN modules as much as possible throughout the tutorials.
* Use DGL's built-in message passing functions as much as possible.

[Doc] Patch tutorial

---

python/dgl/data/bitcoinotc.py
python/dgl/data/citation_graph.py
python/dgl/data/gdelt.py
python/dgl/data/gnn_benckmark.py
python/dgl/data/icews18.py
python/dgl/data/karate.py
python/dgl/data/qm7b.py
python/dgl/data/reddit.py
python/dgl/data/tree.py
python/dgl/data/tu.py

The dataset scripts load dgl. This causes can cause issues.

[BUGFIX] don’t import dgl in the package.

---

Jenkinsfile
tests/compute/test_batched_graph.py
tests/compute/test_graph.py
tests/compute/test_heterograph.py
tests/compute/test_random.py
tests/compute/test_to_device.py

Patch https://github.com/apache/incubator-mxnet/issues/16099

[MXNet] Patch mxnet unittest

---

Jenkinsfile

[CI] Tensorflow ci

---

README.md

[README] New stuffs from 0.4.3

---

docs/Makefile
python/dgl/nn/__init__.py

[Docs] Fix doc build doesn't work for nn.tensorflow and nn.mxnet

---

python/dgl/graph.py
tutorials/models/1_gnn/9_gat.py

[Doc and Tutorial] Fix dgl.batch and GAT

---

python/dgl/graph.py
tutorials/models/1_gnn/9_gat.py

[Doc & Tutorial] Fix dgl.batch and GAT

---

.gitignore
asv.conf.json
tests/regression/README.md
tests/regression/asv_data/README.md
tests/regression/bench_gcn.py
tests/regression/bench_sage.py
tests/regression/build_dgl_asv.sh
tests/regression/install_dgl_asv.sh
tests/regression/publish.sh
tests/regression/run.sh
tests/regression/utils.py

[Regression] Fix regression test

---

examples/pytorch/transformer/README.md

[Example] Update README of transformers for multi-gpu support

---

examples/pytorch/gcmc/train.py

[BUG Fix] Fix update LR for gcmc example

---

python/dgl/contrib/dis_kvstore.py
python/dgl/network.py
src/graph/network.cc
src/graph/network.h
tests/compute/test_kvstore.py

1. fix dtype bug
2. support both tuple and list as data shape
3. only client-0 send shutdown message.

[KVStore] Bug fix

---

examples/pytorch/graphsage/train_cv_multi_gpu.py

This PR shares the history tensor storage across trainer processes, as requested by @jermainewang .
Turns out that the reduction in memory is minor for Reddit itself since the hidden dimension is only 16.
Although there would be a data race in updating histories, it turned out that such data race did not impact model performance.

[Model] Shared memory history tensor for multi-gpu training of control variate methods

---

python/dgl/backend/backend.py
python/dgl/backend/mxnet/tensor.py
python/dgl/backend/pytorch/tensor.py
python/dgl/backend/tensorflow/tensor.py
tests/compute/test_frame.py

Bool data type is missing in our backend, causing problems when pickle/unpickle graph data. #1448 

[Bugfix] Add bool data type to backend.

---

python/dgl/contrib/dis_kvstore.py
python/dgl/data/gindt.py
python/dgl/network.py
src/graph/network.cc
src/graph/network.h
tests/compute/test_kvstore.py

[KVStore] Fix bug of get_meta() API

---

Jenkinsfile
docker/install/conda_env/tensorflow_cpu.yml
docker/install/conda_env/tensorflow_gpu.yml
python/dgl/backend/tensorflow/tensor.py
tests/scripts/build_dgl.sh

TF just released 2.2.0, which means we can turn to the official tf's dlpack implementation.

[Backend] Turn to official dlpack for Tensorflow

---

examples/pytorch/ogb/README.md
examples/pytorch/ogb/ogbn-products/graphsage/README.md
examples/pytorch/ogb/ogbn-products/graphsage/main.py

I suggest from now on all OGB submissions put in the OGB directory.
Also, the code is mostly duplicated from those in GraphSAGE.

[Model] OGB products submission

---

python/dgl/transform.py

remove_edges can be slow. We need to warn users.

[Doc] write warning for remove_edges.

---

python/dgl/distributed/kvstore.py
python/dgl/distributed/rpc_server.py
src/rpc/rpc.cc

Init server_state during get_server_state().

[RPC] Init server_state during get_server_state()

---

examples/pytorch/sign/README.md
examples/pytorch/sign/dataset.py
examples/pytorch/sign/sign.py

Model from the paper [SIGN: Scalable Inception Graph Neural Networks](https://arxiv.org/pdf/2004.11198.pdf).
Testing accuracy on Reddit and Ogbn-products dataset (semi-supervised setting):
- Reddit: mean mean 0.78672, std 0.00059
- Ogbn-products: mean 0.96326, std 0.00010

[Model] Add SIGN model to example

---

apps/life_sci/examples/generative_models/jtnn/README.md
apps/life_sci/examples/generative_models/jtnn/vocab.py
tutorials/models/1_gnn/4_rgcn.py

As requested in #1553 , we now allow users to generate a vocabulary from their own dataset.

[DGL-LifeSci] Allow Generating Vocabulary from a New Dataset

---

examples/pytorch/stgcn_wave/main.py

[Example] Minor Fix

---

python/dgl/distributed/kvstore.py

Remove `Freeze` flag in kvstore.

[KVStore] Remove Freeze flag

---

python/dgl/distributed/partition.py

Fix partition CI

---

examples/pytorch/deepwalk/README.md
examples/pytorch/deepwalk/deepwalk.py
examples/pytorch/deepwalk/reading_data.py

Provide two built in dataset: youtube and blog. Both the training file and testing files are avaliable, please refer to Readme for more details.
#1611 #1609 

[Example] Provide builtin dataset for deepwalk example

---

python/dgl/distributed/dist_graph.py
python/dgl/distributed/graph_partition_book.py
python/dgl/distributed/kvstore.py
python/dgl/distributed/shared_mem_utils.py
tests/compute/test_sampler.py
tests/distributed/test_dist_graph_store.py
tests/distributed/test_new_kvstore.py

Refactor the distributed graph store for the new kvstore.

Refactor distributed graph store

---

python/dgl/distributed/kvstore.py
python/dgl/distributed/rpc.py
python/dgl/distributed/rpc_client.py
src/rpc/rpc.cc
src/rpc/rpc.h
tests/compute/test_rpc.py

Add send_request_to_machine() and remote_call_to_machine() APIs.

[RPC] Add send_request_to_machine() and remote_call_to_machine()

---

src/array/cpu/rowwise_topk.cc
src/graph/network.cc
src/graph/sampling/randomwalks/metapath_randomwalk.h
src/scheduler/scheduler.cc

[Lint] Fix Clang warnings

---

CONTRIBUTORS.md

Add ShawXh as Contributors

---

tests/distributed/test_dist_graph_store.py
tests/distributed/test_graph_partition_book.py
tests/distributed/test_new_kvstore.py
tests/distributed/test_partition.py
tests/distributed/test_rpc.py

[CI] Use spawn in unittest instead of fork

---

python/dgl/backend/backend.py
python/dgl/backend/mxnet/tensor.py
python/dgl/backend/pytorch/tensor.py
python/dgl/backend/tensorflow/tensor.py
python/dgl/graph.py
python/dgl/heterograph.py

Temporary fix of #1547 . Will support non-blocking later(I suppose it's only restricted to PyTorch).

[bugfix] Quick fix of #1547

---

python/dgl/distributed/kvstore.py
python/dgl/distributed/rpc.py
python/dgl/distributed/rpc_server.py
src/rpc/rpc.cc
tests/distributed/test_new_kvstore.py

[KVStore] Add fast-pull for kvstore

---

python/dgl/distributed/rpc.py
python/dgl/distributed/rpc_server.py
src/rpc/rpc.cc

Add HandleCtrlC Register for handling Ctrl+C event in C++.

[RPC] HandleCtrlC Register for handling Ctrl+C event.

---

python/dgl/data/dgl_dataset.py
python/dgl/data/utils.py

Basic template for DGL Dataset

[Dataset] Basic template for DGL Dataset

---

python/dgl/distributed/partition.py
tests/distributed/test_partition.py

When shuffling node Ids, we need to shuffle the node data and edge data as well.

[BUGFIX] reshuffle node features in range partitioning.

---

python/dgl/distributed/partition.py

Provide more description of partitioned graphs.

[Doc] fix a doc for partition_graph.

---

python/dgl/data/dgl_dataset.py
python/dgl/data/graph_serialize.py
python/dgl/data/minigc.py
python/dgl/data/utils.py

Following https://github.com/dmlc/dgl/pull/1654, I modified the simplest `MiniGCDataset`.
The tutorial is not affected by this update.

[Dataset] Update MiniGCDataset 

---

python/dgl/transform.py

Number of nodes in knngraph does not match with the number of feature of  #1667 

[Bugfix]fix the bug for knngraph (#1667)

---

python/dgl/distributed/kvstore.py

[KVStore] Fix a small bug

---

python/dgl/distributed/graph_partition_book.py
tests/distributed/test_partition.py

The output of partition book should be integers. This PR also adds more tests to verify the dtype of outputs of a partition book.

[BUGFIX] fix a bug in partition book.

---

python/dgl/transform.py
tests/pytorch/test_geometry.py

Also included are the unit tests for both modules.

[Bug] Multiple bugs in KNNGraph and SegmentedKNNGraph

---

python/dgl/data/dgl_dataset.py
python/dgl/data/minigc.py

1. Add `verbose` to base class
2. Update behavior of `_load`

[Dataset] Update base class

---

python/dgl/data/__init__.py
python/dgl/data/dgl_dataset.py
python/dgl/data/gnn_benckmark.py
python/dgl/data/karate.py

- New gnn-benchmark dataset inherits from DGLDataset. It has GNNBenchmarkDataset as base class for each dataset.
- There are 3 datasets in it: CoraFullDataset, CoauthorDataset, AmazonCoBuyDataset
- Keep the original name for each dataset in gnn-benchmark and KarateClub dataset.

[Dataset] New GNN-Benchmark dataset

---

python/dgl/data/__init__.py
python/dgl/data/dgl_dataset.py
python/dgl/data/gnn_benckmark.py
python/dgl/data/karate.py

Revert "[Dataset] New GNN-Benchmark dataset"

---

examples/pytorch/ogb/deepwalk/README.md
examples/pytorch/ogb/deepwalk/deepwalk.py
examples/pytorch/ogb/deepwalk/load_dataset.py
examples/pytorch/ogb/deepwalk/model.py
examples/pytorch/ogb/deepwalk/reading_data.py
examples/pytorch/ogb/deepwalk/utils.py

Experimental results.
- [*] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [*] All changes have test coverage
- [*] Code is well-documented
- [*] To the my best knowledge, examples are either not affected by this change,
- [*] Related issue is referred in this PR
* do experiments for 10 runs (before that some are 5)
* provide APIs to count the model parameters
* download ogbl-datasets by DglLinkPropPredDataset
* deal with invalid nodes in a graph

[Example] Experimental results of deepwalk on ogb datasets

---

examples/mxnet/gat/train.py
examples/mxnet/gat/utils.py
examples/mxnet/gcn/train.py
examples/pytorch/gat/train.py
examples/pytorch/gat/utils.py
examples/pytorch/gcn/train.py
examples/tensorflow/gat/train.py
examples/tensorflow/gat/utils.py
examples/tensorflow/gcn/train.py
python/dgl/data/__init__.py
python/dgl/data/citation_graph.py
python/dgl/data/dgl_dataset.py
python/dgl/data/synthetic_graph.py
python/dgl/data/utils.py
tests/distributed/test_distributed_sampling.py

Citation dataset with new interface.

[Dataset] Citation graph

---

python/dgl/distributed/kvstore.py
tests/distributed/test_new_kvstore.py

Test multi-server and multi-client in unittest.

[KVStore] Test multi-server and multi-client

---

tests/distributed/test_dist_graph_store.py

In check_server_client of test_dist_graph_store.py. client may start earlier than server.
Serialize the init order of server and client.

[Bug Fix][CI] Serialize server and client start for dist_graph_store test

---

python/dgl/distributed/__init__.py
tests/distributed/test_dist_graph_store.py

Add RangePartitionBook to __init__

[Fix] Add RangePartitionBook to __init__

---

examples/pytorch/graphsage/README.md
examples/pytorch/graphsage/load_graph.py
examples/pytorch/graphsage/train_sampling.py
examples/pytorch/graphsage/train_sampling_multi_gpu.py

We have received multiple requests on inductive GNN examples.  Here is an inductive GraphSAGE example on Reddit and OGB-products.
The idea is very simple: we train on a subgraph consisting of only the training nodes, and evaluate on the graphs with training and validation nodes.

[Model] GraphSAGE inductive example

---

src/rpc/network/socket_communicator.cc
src/rpc/network/tcp_socket.cc
tests/cpp/socket_communicator_test.cc
tests/distributed/test_new_kvstore.py
tests/distributed/test_rpc.py

Client will retry connection until the server starts.

[RPC] Client will retry connection until the server starts.

---

python/dgl/data/heterograph_serialize.py
python/dgl/data/minigc.py
python/dgl/data/rdf.py
python/dgl/data/utils.py
tests/compute/test_data.py
tutorials/basics/4_batch.py

[Dataset] RDF Dataset

---

python/dgl/data/citation_graph.py
python/dgl/data/dgl_dataset.py
python/dgl/data/gindt.py
python/dgl/data/gnn_benckmark.py
python/dgl/data/karate.py
python/dgl/data/minigc.py
python/dgl/data/qm7b.py
python/dgl/data/rdf.py
python/dgl/data/tu.py

- Update `GINDataset` with `DGLDataset` class.
- Remove the input argument `self.raw_path` in `process()` call.

[Dataset] GINDataset

---

python/dgl/batched_heterograph.py
python/dgl/data/heterograph_serialize.py
python/dgl/heterograph.py
tests/compute/test_batched_heterograph.py
tests/compute/test_heterograph.py
tests/compute/test_serialize.py

[BugFix] Fix #1779

---

examples/pytorch/gcmc/train.py
python/dgl/data/__init__.py
python/dgl/data/movielens.py

[Dataset] Movielens

---

python/dgl/data/graph_serialize.py
python/dgl/data/minigc.py

[Dataset] Patch graph serialize with filesys check

---

examples/pytorch/rgcn/link_predict.py
python/dgl/data/__init__.py
python/dgl/data/knowledge_graph.py

[Dataset] Knowledge graph datasets use new Dataset template.

---

examples/pytorch/han/main.py
examples/pytorch/han/model.py
examples/pytorch/han/model_hetero.py

The meta-path attention should be shared across all nodes according to the paper.

[Example] Fix HAN

---

python/dgl/nn/mxnet/conv/sageconv.py
python/dgl/nn/pytorch/conv/sageconv.py
python/dgl/nn/tensorflow/conv/sageconv.py
tests/mxnet/test_nn.py
tests/pytorch/test_nn.py
tests/tensorflow/test_nn.py

See #1754 , currently SAGEConv fails to handle graphs without edges.

[NN] Handle Graphs without Edges for SAGEConv

---

python/dgl/data/reddit.py

[Dataset] Reddit Dataset

---

examples/pytorch/cluster_gcn/cluster_gcn.py
python/dgl/data/ppi.py

[Dataset] PPI Dataset

---

tests/compute/test_sparse.py

[bugfix] Further relax the tolerance of min/max reducer in test_sparse

---

python/dgl/data/__init__.py
python/dgl/data/icews18.py

[Dataset] ICEWS18Dataset

---

Jenkinsfile
docker/Dockerfile.ci_cpu
docker/Dockerfile.ci_gpu
docker/install/conda_env/mxnet_cpu.yml
docker/install/conda_env/mxnet_gpu.yml
docker/install/conda_env/torch_cpu.yml
docker/install/conda_env/torch_cpu_pip.txt
docker/install/conda_env/torch_gpu.yml
docker/install/conda_env/torch_gpu_pip.txt

[CI] Update PyTorch in CI image to 1.5.1

---

examples/mxnet/tree_lstm/train.py
examples/pytorch/tree_lstm/train.py
examples/pytorch/tree_lstm/tree_lstm.py
python/dgl/data/__init__.py
python/dgl/data/tree.py
tutorials/models/2_small_graph/3_tree-lstm.py

[Dataset] SSTDataset

---

examples/pytorch/cluster_gcn/cluster_gcn.py
python/dgl/data/__init__.py
python/dgl/data/gdelt.py
python/dgl/data/ppi.py

[Dataset] GDELTDataset

---

examples/pytorch/cluster_gcn/README.md
examples/pytorch/cluster_gcn/cluster_gcn.py
examples/pytorch/cluster_gcn/partition_utils.py
examples/pytorch/cluster_gcn/sampler.py
examples/pytorch/gat/train_ppi.py
python/dgl/data/ppi.py

[Dataset] PPIDataset

---

examples/pytorch/line_graph/README.md
tutorials/models/1_gnn/README.txt

Update the links for the work as suggested by the author @zhengdao-chen
- [  ] All changes have test coverage
- [  ] Code is well-documented

[Example] Update Links for Supervised Community Detection with Graph Neural Networks

---

examples/pytorch/graphsage/load_graph.py
python/dgl/distributed/partition.py
python/dgl/transform.py

The example code of partitioning a graph doesn't work for OGB paper100M. Also it's nice to print timing for each stage of partitioning.

[Distributed] Fix partition

---

tools/launch.py

The launch script cannot launch more than one client per machine correctly. To launch k clients per machine, it tends to launch k^2 clients per machine.

[Distributed] Fix the launch script

---

include/dgl/graph_interface.h
python/dgl/backend/mxnet/tensor.py
python/dgl/backend/tensorflow/tensor.py
python/dgl/distributed/graph_partition_book.py
python/dgl/distributed/partition.py
python/dgl/graph_index.py
python/dgl/transform.py
src/graph/graph_op.cc
tests/compute/test_transform.py
tests/graph_index/test_subgraph.py

Currently, memory consumption is quite high in graph partitioning. This is to cut memory consumption as much as possible.

[Distributed] Reduce memory consumption in graph partitioning

---

python/dgl/convert.py
python/dgl/heterograph.py
tests/compute/test_heterograph.py

[Graph] Mutation for Heterograph

---

python/dgl/distributed/kvstore.py
tests/distributed/test_new_kvstore.py

User can call client.delete_data('data_name') to delete tensor on kvstore.

[KVStore] Support delete_data() api on client

---

python/dgl/data/dgl_dataset.py
python/dgl/data/utils.py

Providing a basic template of building a Dataset object for DGL. 
#1776

[Dataset] Basic class for dgl dataset

---

README.md

[Doc] d2l link

---

python/dgl/data/__init__.py
python/dgl/data/dgl_dataset.py

[Dataset] Show DGLGraph class to users to support customized dataset

---

src/rpc/network/socket_communicator.cc

Increase seconds for showing the tcp re-connect message

[RPC] Increase seconds for showing the tcp re-connect message

---

python/dgl/data/graph_serialize.py

Add sanity check for load_graphs, save_graphs and load_labels
#1826 #1776 

[Dataset] Fix #1826

---

python/dgl/partition.py
python/dgl/transform.py
src/graph/transform/metis_partition_hetero.cc
src/graph/transform/partition_hetero.cc
tests/compute/test_transform.py
tests/distributed/test_partition.py

[HeteroGraph] Metis partition for hetero

---

examples/pytorch/graphsage/experimental/train_dist.py
python/dgl/partition.py
python/dgl/transform.py
src/graph/metis_partition.cc
src/graph/transform/metis_partition_hetero.cc

Two optimizations:
* Support on-disk option to reduce memory consumption.
* balance in-degrees for different node types.

[Distributed] update Metis

---

python/dgl/heterograph_index.py
tests/pytorch/test_ipc.py

Problem: https://github.com/pytorch/pytorch/issues/32351
Have to set the tensor to be pickled as instance attribute

[Torch] Fix inter-process communication for PyTorch

---

python/dgl/partition.py
python/dgl/transform.py

There was a bug in Metis. It's fixed in the newer version of metis.

[Distributed] upgrade metis

---

examples/pytorch/graphsage/experimental/README.md
tools/launch.py

[Distributed] Small fix on launch script

---

python/dgl/heterograph.py

[Hot fix] Remove debug print

---

python/dgl/distributed/dist_graph.py
python/dgl/distributed/graph_services.py
python/dgl/distributed/server_state.py
python/dgl/heterograph.py
src/graph/heterograph.cc
src/graph/shared_mem_manager.cc
tests/distributed/test_dist_graph_store.py
tests/distributed/test_distributed_sampling.py
tests/distributed/test_new_kvstore.py
tests/distributed/test_partition.py
tests/scripts/task_unit_test.sh

[Distributed] Refactor distributed training to new DGLGraph.

---

python/dgl/data/rdf.py

[BUGFix] RDF dataset hot fix

---

python/dgl/distributed/kvstore.py
tests/distributed/test_new_kvstore.py

[KVStore] Fix bug in barrier.

---

python/dgl/data/citation_graph.py

[Dataset] Hot Fix docstring

---

python/dgl/data/knowledge_graph.py

[Hot Fix]Builtin knowledge graph dataset

---

python/dgl/data/dgl_dataset.py
tests/compute/test_data.py

This patch replaces `hash` with `hashlib.sha1` for a deterministic behavior.
https://github.com/dmlc/dgl/issues/1776
https://github.com/dmlc/dgl/pull/1894

[Dataset] Update dataset hash with deterministic function

---

examples/pytorch/graphsage/train_cv.py
examples/pytorch/graphsage/train_sampling.py

[Example] Fix profiling time estimation for graphsage

---

python/dgl/partition.py
python/dgl/transform.py
tests/compute/test_transform.py

to_bidirected keeps the same as 0.4.3
The new to_bidirected is renamed as add_reverse_edges

[Transform] Add add_reverse_edges

---

examples/pytorch/graphsage/train_full.py

... to make the style consistent with the documentation and user guide.

[Model] Rewrite GraphSAGE example

---

examples/pytorch/rgcn-hetero/entity_classify_mb.py
python/dgl/backend/pytorch/sparse.py

[hotfix] Remove dead code

---

python/dgl/data/knowledge_graph.py

[Hot fix][Dataset] knowledge graph dataset statistics output

---

python/dgl/distributed/dist_dataloader.py
tests/distributed/test_mp_dataloader.py

DistDataLoader doesn't support multiple instances. We need to ensure that multiple DistDataLoader can register themselves in the sampler processes.

[Distributed] Fix dataloader

---

examples/pytorch/graphsage/train_sampling_unsupervised.py

Reported in a [discussion thread](https://discuss.dgl.ai/t/error-while-trying-to-run-graphsage-train-sampling-unsupervised-py-example/1177/3).

[Examples] Fix GraphSAGE Unsupervised

---

tools/launch.py

The launch script needs to know the number of trainers and samplers in order to launch the right number of clients and have the servers know the correct number of clients.
The launch script should also check the correctness of the input and the configuration.

[Distributed] Fix the launch script.

---

python/dgl/data/knowledge_graph.py

[Dataset] Hotfix

---

python/dgl/data/reddit.py

[Dataset]Hotfix #1958

---

python/dgl/distributed/partition.py
src/runtime/utils.cc

The original package could not be built on Mac OS as Clang does not support OpenMP.

[Fix] OpenMP compatibility issues

---

docs/source/guide/index.rst
docs/source/guide/message.rst
docs/source/guide/nn.rst
docs/source/index.rst

Add User Guide for Message Passing and NN Module. Local build looks reasonable. Need to update external links after all docs are uploaded.

[Doc] Message passing and NN User Guide

---

examples/pytorch/gcmc/model.py
examples/pytorch/gcmc/train_sampling.py

Fixes various broken code in GCMC

[Model] Fix GCMC broken code

---

examples/pytorch/graphsage/experimental/README.md

[Distributed] Small fix on README.md

---

docs/source/api/python/dgl.rst

Add save_graphs/load_graphs to dgl doc pages

---

docs/source/api/python/dgl.DGLGraph.rst
docs/source/api/python/dgl.dataloading.rst
docs/source/api/python/dgl.rst
docs/source/api/python/nn.mxnet.rst
docs/source/api/python/nn.pytorch.rst
docs/source/api/python/nn.tensorflow.rst
docs/source/guide/data.rst
docs/source/guide/message.rst
docs/source/guide/minibatch.rst
docs/source/guide/nn.rst
docs/source/guide/training.rst
python/dgl/dataloading/dataloader.py

Also included some more API reference entries:
```
DGLHeteroGraph.__getitem__
DGLHeteroGraph.number_of_src_nodes
DGLHeteroGraph.number_of_dst_nodes
DGLHeteroGraph.srcdata
DGLHeteroGraph.dstdata
DGLHeteroGraph.srcnodes
DGLHeteroGraph.dstnodes
```
I would recommend to create reference tags for hyperlinks to our own pages in the future:
```restructuredtext
.. _your-tag-name:
Section header
==============
```
and then refer it like this to render it to "Section header"
```restructuredtext
:ref:`your-tag-name`
```
or "Custom title"
```restructuredtext
:ref:`Custom title <your-tag-name>`
```
instead of using external links.  I have fixed some of them, but I intend to go through all of them again later.

[Doc] User guide section 5 and 6

---

tests/pytorch/test_nn.py
tests/tensorflow/test_nn.py

Replace random graph in some tests with get_cases. Fixing build fails in test_sgc_conv.

[NN][Fix] Replace random graph in some tests with get_cases

---

tests/compute/test_randomwalk.py

`metapath_random_walk` is deprecated.

[Test] Remove Test for metapath_random_walk

---

docs/source/api/python/nn.mxnet.rst
python/dgl/nn/mxnet/conv/agnnconv.py
python/dgl/nn/mxnet/conv/chebconv.py
python/dgl/nn/mxnet/conv/edgeconv.py
python/dgl/nn/mxnet/conv/gatconv.py
python/dgl/nn/mxnet/conv/gatedgraphconv.py
python/dgl/nn/mxnet/conv/gmmconv.py
python/dgl/nn/mxnet/conv/graphconv.py
python/dgl/nn/mxnet/conv/sgconv.py
python/dgl/nn/pytorch/conv/agnnconv.py
python/dgl/nn/pytorch/conv/atomicconv.py
python/dgl/nn/pytorch/conv/chebconv.py
python/dgl/nn/pytorch/conv/dotgatconv.py
python/dgl/nn/pytorch/conv/edgeconv.py
python/dgl/nn/pytorch/conv/gatconv.py
python/dgl/nn/pytorch/conv/gatedgraphconv.py
python/dgl/nn/pytorch/conv/gmmconv.py
python/dgl/nn/pytorch/conv/graphconv.py
python/dgl/nn/pytorch/conv/nnconv.py
python/dgl/nn/pytorch/conv/sageconv.py
python/dgl/nn/pytorch/conv/sgconv.py
python/dgl/nn/pytorch/conv/tagconv.py
python/dgl/nn/tensorflow/conv/chebconv.py
python/dgl/nn/tensorflow/conv/densechebconv.py
python/dgl/nn/tensorflow/conv/gatconv.py
python/dgl/nn/tensorflow/conv/graphconv.py
python/dgl/nn/tensorflow/conv/sgconv.py

Fix some issue in mxnet doc.
Change "Notes" to "Note" to highlight after build html.

[NN] [Doc] Fix nn api doc

---

examples/mxnet/gin/dataloader.py
examples/mxnet/gin/main.py
python/dgl/data/gindt.py

[HotFix] Fix mxnet GIN

---

examples/mxnet/tree_lstm/README.md
examples/mxnet/tree_lstm/tree_lstm.py
python/dgl/data/tree.py

[HotFix] MXNet tree lstm

---

python/dgl/sampling/neighbor.py

remove debug information

---

python/dgl/distributed/rpc.py
src/rpc/rpc.cc

Fix a small bug on the kvstore. 
This bug doesn't influence current tasks.

[BugFix] Fix a small bug on kvstore

---

python/dgl/data/tu.py

I mistakenly left the manual hash value assignment in this dataset. Now its base-class should be able to handle it.

[Dataset]Fix TU Dataset

---

examples/pytorch/ogb/deepwalk/README.md

[Example] Update Readme of deepwalk

---

python/dgl/backend/pytorch/tensor.py

Update version check of PyTorch to 1.5

---

tests/mxnet/test_nn.py

CI Crash randomly when the generated graph have zero-degree nodes.

[BugFix] Add selfloop for test_sgc_nn

---

CMakeLists.txt

Fix build error with hdfs and update dmlc-core

---

docs/migrate-guide-0.5.md
python/dgl/data/gindt.py
python/dgl/data/graph_serialize.py

Fix https://github.com/dmlc/dgl/issues/2087

Fix GINDT and #2087

---

python/dgl/heterograph.py

Add check for zero edge graph
#2076

[Bugfix] Fix #2076

---

examples/pytorch/graphsage/experimental/train_dist.py
examples/pytorch/graphsage/experimental/train_dist_unsupervised.py
tools/launch.py

For now, the arguments _num_workers_ and _num_samplers_ should be the same value. 

[Distributed] Check num_workers and num_samplers

---

src/graph/unit_graph.cc
tests/compute/test_graph.py
tests/compute/test_heterograph.py
tests/compute/test_sampling.py

Duplicate of #2120 , add some tests.

[hotfix] Disable hypersparse memory optimization.

---

docs/source/env_var.rst
tutorials/models/1_gnn/README.txt

Remove SSE in tutorial

---

docs/source/guide/minibatch-link.rst
examples/pytorch/gcmc/train_sampling.py
examples/pytorch/graphsage/train_cv.py
examples/pytorch/graphsage/train_cv_multi_gpu.py
examples/pytorch/graphsage/train_sampling.py
examples/pytorch/graphsage/train_sampling_multi_gpu.py
examples/pytorch/graphsage/train_sampling_unsupervised.py
examples/pytorch/ogb/cluster-sage/sampler.py
examples/pytorch/ogb/ogbn-products/gat/main.py
examples/pytorch/ogb/ogbn-products/graphsage/main.py
python/dgl/dataloading/dataloader.py
python/dgl/heterograph.py
python/dgl/heterograph_index.py
tests/compute/test_heterograph.py

rename create_format_ to create_formats_

---

examples/pytorch/gcmc/train_sampling.py
examples/pytorch/graphsage/train_cv_multi_gpu.py
examples/pytorch/graphsage/train_sampling.py
examples/pytorch/graphsage/train_sampling_multi_gpu.py
examples/pytorch/graphsage/train_sampling_unsupervised.py
examples/pytorch/ogb/cluster-sage/sampler.py
examples/pytorch/ogb/ogbn-products/gat/main.py
examples/pytorch/ogb/ogbn-products/graphsage/main.py
examples/pytorch/rgcn/entity_classify_mp.py

[Code Doc] update some code comments

---

examples/pytorch/graphsage/experimental/README.md
examples/pytorch/rgcn/experimental/README.md

Update READMe.md of distributed training example.

[Distributed] update README.md

---

python/dgl/data/tu.py

[Bug fix] fix #2161

---

python/dgl/backend/mxnet/sparse.py
python/dgl/backend/pytorch/sparse.py
python/dgl/backend/tensorflow/sparse.py
python/dgl/ops/edge_softmax.py

[hotfix] fix the behaviour of edge_softmax on a subset of edges

---

python/dgl/transform.py

The bug in #1453 resurfaced as I implement auto-slicing for node and edge features.

Fix #1453 again

---

docs/source/api/python/dgl.DGLGraph.rst
examples/pytorch/ogb/ogbn-arxiv/gcn.py

Fix https://github.com/dmlc/dgl/issues/2183

Fix `create_format_` to `create_formats`

---

python/dgl/data/graph_serialize.py

Fix https://github.com/dmlc/dgl/issues/2106

Fix hdfs error when writing big data

---

examples/pytorch/graphsage/experimental/partition_graph.py

Change 'dgl.to_bidirected_stale' to 'dgl.to_bidirected'

[Distributed Example] Change 'dgl.to_bidirected_stale' to 'dgl.to_bidirected'

---

examples/pytorch/graphsage/experimental/train_dist.py

The pytorch backward will do Allreduce automatically. 

[Distributed Example] Remove AllReduce from train_dist.py

---

docs/source/guide/message.rst

Fix link in message passing user guide doc.

[Doc]fix link in message passing doc

---

src/array/cpu/spmm.h

As observed by @kira-lin, our current implementation of SpMMCsr on CPU is not efficient, and by exchanging the loop order of feature axis and neighbor axis we access the node/edge feature in a consecutive way, thus greatly improve the speed of this kernel.

[performance] Exchange the loop order of feature axis and neighbor axis in SpMMCsr on CPU.

---

examples/pytorch/graphsage/experimental/train_dist.py
examples/pytorch/graphsage/experimental/train_dist_unsupervised.py

Check args.num_servers with DGL_NUM_SERVER

[Distributed Example] Check args.num_servers with DGL_NUM_SERVER

---

docs/source/guide/training-graph.rst
python/dgl/dataloading/pytorch/__init__.py
python/dgl/heterograph.py
src/array/cpu/spmm.h

[Doc and User Guide] Minor Fix

---

examples/pytorch/ogb/ogbn-arxiv/README.md
examples/pytorch/ogb/ogbn-arxiv/gat.py
examples/pytorch/ogb/ogbn-arxiv/gcn.py
examples/pytorch/ogb/ogbn-arxiv/models.py

[Example] GAT on ogbn-arxiv

---

python/dgl/data/gindt.py

This PR updates doc for `GINDataset` based on a user's [feedback](https://discuss.dgl.ai/t/questions-regarding-the-graph-classification-tutorial-on-dgl-website-gcn-vs-gin/1300).

[Doc] Update Doc for GINDataset

---

src/rpc/network/socket_communicator.cc

Closer server_socket when receive the shutdown message.

[Bug Fix] Closer server_socket when receive the shutdown message.

---

docs/source/guide/message-efficient.rst

[User Guide] Minor Fix for 2.2

---

python/dgl/frame.py

- Fix some typos in `python/dgl/frame.py`

[Bugfix][Frame] Fix typos

---

docs/source/guide/message.rst

Heterogenueous --> Heterogeneous

[Doc]Typo in User Guide about Message Passing(line 246)

---

docs/source/guide/distributed.rst

Equations for SAGEConv has some typos.

[Doc] Typos in nn.rst

---

examples/pytorch/graphsage/experimental/train_dist.py
examples/pytorch/graphsage/train_sampling.py
examples/pytorch/graphsage/train_sampling_multi_gpu.py
examples/pytorch/graphsage/train_sampling_unsupervised.py
examples/pytorch/ogb/cluster-gat/main.py
examples/pytorch/ogb/cluster-sage/main.py
examples/pytorch/ogb/ogbn-products/gat/main.py
examples/pytorch/ogb/ogbn-products/graphsage/main.py

refer to https://github.com/dmlc/dgl/issues/2293

[Info] Fix print info

---

examples/pytorch/graphsage/train_sampling_unsupervised.py

To make removing reverse edges really work, the dataset should not contain self-loop.
Test F1-micro is 0.9114.

[Bug] Fix reddit self loop in GraphSAGE unsupervised learning example

---

src/array/cuda/sddmm.cuh

Further accelerate the SDDMM-dot operator with loop unroll.

[kernel] loop unroll for cross warp aggregation in SDDMM-dot.

---

examples/pytorch/rgcn/entity_classify_mp.py
examples/pytorch/rgcn/model.py

Fix for enabling r-gcn training for CPU device in entity_classify_mp.py

[Fix] Enable mini-batch r-gcn for CPU

---

src/array/cuda/ge_spmm.cuh

[bugfix] Address potential illegal mem access issue in GE-SpMM

---

python/dgl/backend/pytorch/sparse.py

[hotfix] Remove redundant print information in #2361

---

docs/source/guide/distributed.rst

Update distributed.rst (#2249)

---

README.md

We have released dgl 0.5.3, which is compatible with cu11. This PR updates the commands to install cu11 version via pip/conda in README. 

[README] Update README.md

---

README.md

Add a list of papers using DGL in readme.

[Readme] Add paper list

---

python/dgl/core.py

Fix #2386 .
@jermainewang @BarclayII I forget why we ignore message passing for empty graphs, should we generate a warning here?

[hotfix] Produce empty tensor in data frame for emtpy graphs.

---

README.md

[Papers] Added 5 more

---

README.md

Add GraphHINGE paper (Conference Version (KDD'20) and Journal Version) in Awesome Papers Using DGL.

[Readme] Update Awesome Papers Using DGL

---

docs/source/guide/training-graph.rst

Add a code example for [User Guide 5.4](https://docs.dgl.ai/guide/training-graph.html) as a pointer to the relevant API for the readers.

[Doc]Add example graph batch code to graph classification guide

---

README.md

Add the CG-MuAlign paper for entity alignment.

[README] add more papers.

---

examples/pytorch/hgt/model.py

Correct error when using enisum

---

README.md

[Papers] One more

---

docs/source/guide/minibatch-link.rst

some simple problem found while I reading the Doc
I feel confusing while I try to initialize the dataloader, the description of 'eids_dict' is fuzzy. After I read the code in 'dataloader.EdgeCollator' I adding the generated code.
`    eids : Tensor or dict[etype, Tensor]
The edge set in graph :attr:`g` to compute outputs.`
and the example negative sampler cannot work well
I modify a few lines of code to make it can run 
the etype in hetero graph should be name of edges
self.weights = {
etype: g.in_degrees(etype=etype).float() ** 0.75
for _, etype, _ in g.canonical_etypes
}
the original code will give etype a Tuple format, it cannot apply to the next processing:
self.weights[etype].multinomial(len(src), replacement=True)
and I add the part which confusing me to generate eid_dict
Please …

[Doc]modify the wrong code in initialize the hetero_graph negative sampler

---

python/dgl/data/citation_graph.py
python/dgl/data/dgl_dataset.py

Fix a bug of citation data loading process.
Also print out error message if loading data from the saved cache failed.

[BugFix] Fix citation data loading

---

README.md

[Doc]Add four papers to the awesome list

---

docs/source/api/python/nn.pytorch.rst
python/dgl/nn/pytorch/glob.py

Previously some of the docstrings for global pooling layers are missing, and user might find It hard to understand how to use them (e.g. GlobalAttentionPooling), and this PR complete these docstrings.

[documentation] Improve the docstring of global pooling layer

---

tensoradapter/pytorch/build.bat
tensoradapter/pytorch/build.sh

This is for nightly build where we should build PyTorch libraries with all common archs.

[Build] Option to disable CUDA arch autodetection for PyTorch

---

README.md

Added three papers using DGL:
NHK_STRL at WNUT-2020 Task 2: GATs with Syntactic Dependencies as Edges and CTC-based Loss for Text Classification
Relation-aware Graph Attention Networks with Relational Position Encodings for Emotion Recognition in Conversations
PGM-Explainer: Probabilistic Graphical Model Explanations for Graph Neural Networks

[Papers] Update papers using DGL

---

python/dgl/data/knowledge_graph.py

[BugFix] Fix kg dataset len()

---

examples/pytorch/metapath2vec/metapath2vec.py

fix this question：https://discuss.dgl.ai/t/the-code-of-metapath2vec-examples-pytorch-metapath2vec-py/1649
fix 1：
the code of examples/pytorch/metapath2vec.py,
every iteration will generated a new optimizer and scheduler, this will accumulate the GPU memory. because the optimizer will copy the parameters of the model.  in my machine， this code will consume more 10G GPU memory。 if fixed，just 5G GPU memory。
fix 2：
the save_embedding function use in every iteration is unnecessary

update the code of examples/pytorch/metapath2vec.py

---

docs/source/install/index.rst
tensoradapter/pytorch/build.sh

Right now tensoradapter building script crashes on Mac.
Also fixes installation instructions on Mac.

[Build] Fix building script for tensoradapter on mac

---

benchmarks/benchmarks/model_speed/bench_gat_ns.py

[Test] Regression speed test for GAT neighbor sampler

---

README.md

Fix icon in readme

---

docs/source/api/python/dgl.DGLGraph.rst
docs/source/api/python/dgl.rst
python/dgl/heterograph.py

Correcting errors in `set_batch_num_edges` docstring and dgl.DGLGraph.rst.

[Doc] Hotfix on docstring of set_batch_num_edges

---

docs/source/api/python/dgl.dataloading.rst
python/dgl/dataloading/dataloader.py
python/dgl/dataloading/pytorch/__init__.py
tests/pytorch/test_dataloader.py

This PR adds `GraphDataLoader` for graph classification/regression tasks, and saves users' effort to repeatedly implement their own collate function to batch the graphs.
After this PR's merged, I'll update the relevant examples/tutorials with this new `GraphDataLoader`.

[Feature] Add GraphDataLoader implementation 

---

examples/pytorch/jtnn/jtnn/nnutils.py

[Examples][Bug] fix a silly typo in JTNN

---

README.md

[Doc] Add one paper to the awesome list

---

python/dgl/nn/pytorch/conv/relgraphconv.py
tests/pytorch/test_nn.py

[Bug fix] Fix relgraphconv norm

---

python/dgl/nn/pytorch/conv/gatconv.py

https://github.com/dmlc/dgl/issues/2532

[NN] Fix GATConv parameter space

---

src/array/cuda/spmm.cu

@yzh119 identified that SPMM was running slower in CUDA11 using `cusparseSpMM()` + `CUSPARSE_SPMM_CSR_ALG1,` than using `cusparseScsrmm2()`.
This PR uses CUSPARSE_SPMM_CSR_ALG2 in SPMM when using CUDA11 instead of CUSPARSE_SPMM_CSR_ALG1. This results in a large reduction in runtime as ALG2 operates on row-major matrices, and can take advantage of the memory layout for larger numbers of features. This also avoids transposing the output.
For https://github.com/dglai/dgl-0.5-benchmark/blob/master/end-to-end/full-graph/node-classification/main_dgl_reddit_sage.py I have seen a ~4x reduction in the SpMM kernel time on a Titan V.
~1.84s for ALG1
~0.459s for ALG2
The tests in …

[Performance] Use ALG2 for SpMM in cuSparse

---

docs/source/api/python/dgl.rst
python/dgl/convert.py
python/dgl/transform.py
tests/compute/test_heterograph.py

Added two functions `dgl.create_block` and `dgl.block_to_graph` to create a DGLBlock object and convert a DGLBlock object to a DGLGraph object.

[Feature] Converting a block to a graph and allow block construction

---

include/dgl/aten/array_ops.h

[Doc] Fix docstring of aten::Sort

---

python/dgl/data/dgl_dataset.py

https://github.com/dmlc/dgl/issues/2530
This change affects users from using their own hash functions, but I can't think of any scenario that they'll need to do that.
@classicsong 

[Dataset] Remove self._hash_func from DGLDataset

---

python/dgl/backend/mxnet/sparse.py
python/dgl/backend/pytorch/sparse.py
python/dgl/backend/tensorflow/sparse.py
python/dgl/heterograph.py
python/dgl/sparse.py

Revert "[feature] Refactor code for retaining formats in message-passing."

---

python/dgl/backend/pytorch/sparse.py

After discussion we decide not to retain graph formats information in backprop.
The PR reverts the change in PyTorch backend.

Revert part of #2563

---

docs/source/api/python/dgl.function.rst

Rewrite the page and update with more examples about broadcasting.

[Doc] Update doc of dgl.function

---

python/dgl/nn/pytorch/conv/dotgatconv.py
tests/pytorch/test_nn.py

[NN] add multihead in DotGatConv

---

python/dgl/sparse.py

[hotfix] Add data type check for kernels.

---

examples/pytorch/rgcn/README.md
examples/pytorch/rgcn/entity_classify_mp.py

[Bug Fix] Fix some training scripts in Readme of rgcn example.

---

new-tutorial/5_graph_classification.py
new-tutorial/L1_large_node_classification.py
new-tutorial/L2_large_link_prediction.py
new-tutorial/L4_message_passing.py
tests/scripts/task_pytorch_tutorial_test.sh

The pushed tutorials for large graphs runs code on GPU which crashes the current doc server.  This is a workaround by adding a device toggle.
It also switches from OGB Products to OGB Arxiv due to limited hard drive space on the doc server.
Also fixes some other problems.

[Doc] Fix inconsistencies and GPU code

---

python/dgl/nn/mxnet/utils.py
python/dgl/nn/pytorch/conv/relgraphconv.py
python/dgl/nn/tensorflow/utils.py
tests/mxnet/test_nn.py
tests/pytorch/test_nn.py
tests/tensorflow/test_nn.py

Fixes #2615.
Turns out that MXNet and Tensorflow has the same issue.
Also added unit tests for those border cases where output dimension is 1.

[Bug] Fix #2615

---

examples/pytorch/graphsage/experimental/README.md
examples/pytorch/rgcn/experimental/README.md

[Distributed] add warning for a bug in README

---

python/dgl/nn/mxnet/conv/edgeconv.py
python/dgl/nn/pytorch/conv/edgeconv.py

Fixes #2668 (Thanks @pmorerio)

Fix bug in EdgeConv implementation

---

python/dgl/sampling/neighbor.py

[bugfix] Fix the behavior of select_topk

---

python/dgl/view.py

Fixes issue in https://discuss.dgl.ai/t/how-to-get-the-node-id-in-edge-dataloader/1732

[Bug] Change __repr__ of ndata and edata

---

examples/pytorch/graphsage/experimental/README.md
examples/pytorch/rgcn/experimental/README.md

[Example] Provide instructions of setting up passwordless SSH login.

---

examples/pytorch/rgcn/experimental/README.md
examples/pytorch/rgcn/experimental/entity_classify_dist.py
python/dgl/distributed/sparse_emb.py

Two updates:
* enable GPU training;
* remove unnecessary arguments for updating the dense parameters.

[Example] Update the example of distributed GNN training of RGCN

---

docker/install/conda_env/mxnet_gpu.yml
docker/install/conda_env/torch_cpu_pip.txt
docker/install/conda_env/torch_gpu_pip.txt

Adding OGB, Pandas and Scikit-learn to Docker images since they are used by the tutorials.
Also MXNet 1.6 CUDA 10.1 disappeared from PyPI so moved forward to 1.7.

[Docker] Add Dependency Packages for CI

---

src/array/cuda/spmm.cuh

[Doc] fix doc typo

---

examples/pytorch/graphsage/experimental/README.md
examples/pytorch/graphsage/experimental/train_dist.py
examples/pytorch/graphsage/experimental/train_dist_unsupervised.py
examples/pytorch/rgcn/experimental/README.md
examples/pytorch/rgcn/experimental/entity_classify_dist.py
examples/pytorch/rgcn/experimental/get_mag_data.py
examples/pytorch/rgcn/experimental/write_mag.py
tools/convert_partition.py

Remove pyinstrument from the code related to distributed training.

Remove pyinstrument in distributed training code

---

src/rpc/network/tcp_socket.cc

We need to print errors with more informative messages instead of just error numbers.
This can help users understand the errors.

Print error messages when using TCP socket

---

examples/README.md
examples/pytorch/mvgrl/README.md
examples/pytorch/mvgrl/graph/dataset.py
examples/pytorch/mvgrl/graph/main.py
examples/pytorch/mvgrl/graph/model.py
examples/pytorch/mvgrl/graph/utils.py
examples/pytorch/mvgrl/node/dataset.py
examples/pytorch/mvgrl/node/main.py
examples/pytorch/mvgrl/node/main_sample.py
examples/pytorch/mvgrl/node/model.py
python/dgl/data/qm9_edge.py

This PR is the implementation of the model in the paper: Contrastive Multi-View Representation Learning on Graphs --> @zhjwy9343 

[Example] Add implementation of mvgrl

---

python/dgl/geometry/mxnet/fps.py
python/dgl/geometry/pytorch/fps.py

Add `random_start` option for FPS. 

[Model] Add random_start option for Farthest Point Sampler

---

python/dgl/ops/spmm.py

Fix for this #2777
- [x ] Code is well-documented
- [x ] Related issue is referred to in this PR
In the case of a graph having all nodes zero-degree, the reduce functions will not produce nans.
Please, can you advise what is the best place to put a unit test for that? I did not find where this function is tested in isolation. There is apparently some other structure in place for testing this change? 
After that, I will add a unit test and we can merge it.

[BUG] fix for zero degree nodes

---

python/dgl/convert.py

The tensor range is already checked inside `graphdata2tensors` function. No need to check again in `create_from_edges `

[Fix] Remove duplicate validation in dgl.graph creation

---

examples/pytorch/hgt/model.py

[Bug] Fix HGT example where relation-specific value tensors are overwritten

---

examples/pytorch/pinsage/README.md

process_nowplaying_rs.py is the right name under this folder.
Also, torchtext requires a lower version. e.g. when on most recent 0.9, I ran into error saying "AttributeError: module 'torchtext.data' has no attribute 'Example'". Re-install using 0.5 fixed the issue.
- [ X] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ X] Changes are complete (i.e. I finished coding on this PR)
- [ X] All changes have test coverage
- [ X] Code is well-documented
- [ X] To the my best knowledge, examples are either not affected by this change,

[Doc] Typo in command example.

---

python/dgl/dataloading/dataloader.py
python/dgl/dataloading/pytorch/__init__.py

Fix discrepancy in dgl.dataloading.EdgeDataLoader

---

examples/pytorch/hgt/train_acm.py

bug fix type mismatch

---

README.md

[Doc] Add 4 papers to Awesome Paper List

---

python/dgl/distributed/kvstore.py
tests/distributed/test_dist_graph_store.py

We need to support graphs without node/edge data. Previously we will throw an exception.
The bug was previously reported here: https://github.com/dmlc/dgl/issues/2366

[Distributed] Fix a bug for graphs without node/edge data.

---

examples/README.md
examples/pytorch/rect/README.md
examples/pytorch/rect/classify.py
examples/pytorch/rect/label_utils.py
examples/pytorch/rect/main.py
examples/pytorch/rect/model.py
examples/pytorch/rect/utils.py

A proposal of a new GNN model coming from TKDE 2020: https://ieeexplore.ieee.org/document/8979355
The original implementation is: https://github.com/zhengwang100/RECT
This is initial proposal of the model. There are five files: `utils.py` which loads dataset and preprocesses node features, `label_utils.py` which removes the unseen classes and gets the class-center (semantic knowledge) of each seen class, `model.py` which implements GCN model and RECT-L model, `main.py` which shows training process, and `classify.py` which defines a logistic regression classifier to evaluate the quality of embedding results.
We use two DGL's build-in datasets (Cora and Citeseer) with their default train/val/test settings. The performance results are are as follows:
| **Datasets/Models** | **NodeFeats** | …

[Model] Add RECT example

---

examples/pytorch/rect/README.md

Change the format of  README.md
Add blank lines to adjust the format.

[Doc] Change the format of  README.md

---

Jenkinsfile

[CI] Fix regression trigger

---

examples/README.md
examples/pytorch/dtgrnn/README.md
examples/pytorch/dtgrnn/dataloading.py
examples/pytorch/dtgrnn/dcrnn.py
examples/pytorch/dtgrnn/gaan.py
examples/pytorch/dtgrnn/model.py
examples/pytorch/dtgrnn/train.py
examples/pytorch/dtgrnn/utils.py

[Example] DCRNN and GaAN

---

src/graph/serialize/dglgraph_serialize.cc
src/graph/serialize/heterograph_serialize.cc

Fix https://discuss.dgl.ai/t/heterograph-loading-in-parallel-with-joblib-issue/1871/7

[Serialization] Better error message when idx_list out of bound

---

python/dgl/data/citation_graph.py

[Bugfix] Fixes typo in CoraBinary

---

src/array/cuda/cusparse_dispatcher.cuh

[Bug fix] Fix cu11 compile bug

---

tools/launch.py

Right now if training fails for any reason, we have to login to each machine to kill the training jobs. This is very inconvenient. This PR adds the functionality in the launch script so that when a user kills the training script with ctrl+c, the launch script will kill all training jobs in the cluster.

[Distributed] Kill training jobs in distributed training

---

docs/source/guide/distributed-preprocessing.rst

There is a small typo in the graph partitioning doc.

[Doc] Fix a typo in the doc.

---

README.md

[Doc] Add 1 Paper to Awesome Paper List

---

README.md

**Characterizing and Forecasting User Engagement with In-app Action Graph: A Case Study of Snapchat** from USC (https://github.com/INK-USC/temporal-gcn-lstm)

[README] Add new paper

---

src/random/cpu/choice.cc

reservoir algorithm is memory efficient, but not computationally efficient. This PR uses a new sampling algorithm, which is strictly faster than reservoir algorithm in terms of computation complexity, to speed up random number generation in the most common case in neighbor sampling.
when `num`=10, `population`=90, this new sampling algorithm gets roughly 7.5x speedup on a single core of Intel(R) Xeon(R) Platinum 8259CL.

Speed up random number generation.

---

python/dgl/distributed/dist_graph.py

[Doc] Minor fix on the distributed training doc.

---

docs/source/guide/message-efficient.rst
docs/source/guide_cn/message-efficient.rst
python/dgl/data/fraud.py

Correct the matrix multiplication symbols from '*' to '@' in user guide 2.2 both English and Chinese version.
@BarclayII

[Doc] correct the matrix multiplication symbols

---

python/dgl/data/fakenews.py
python/dgl/data/fraud.py

Added number of positive items, number of negative items, and positive-negative ratio in statistics. @zhjwy9343 

[Feature] add positive negative statistics

---

tutorials/blitz/3_message_passing.py

1. Although the 1D weight vector works in DGL built-in message function, it doesn't fit in Numpy broadcasting rule, and it result in error if we replace the built-in message function with user defined message function. Converting the weight into 2D matrix can solve this problem.
2. Previous sections in the tutorial use mean as reduce function, but in customized message function example use sum. It's better to keep a consistent reduce message function.
@zhjwy9343 

[Doc] Revised Two Issues in Message Passing Tutorial

---

README.md

[Doc] Add Contrast-Reg to awesome papers

---

python/dgl/nn/pytorch/conv/gatedgraphconv.py
tests/pytorch/test_nn.py

[NN] Add fast path for GateGCNConv when it has only one edge type

---

python/dgl/heterograph.py
tests/compute/test_heterograph.py

[Fix] Fix to_homo for graph with zero nodes ntype

---

python/dgl/data/tu.py
tests/compute/test_data.py

[Dataset] Fix TUDataset with regression data 

---

python/dgl/data/dgl_dataset.py

Fixed typo in dataset class (see #2977 )

[Doc] Fix typo in DGL base dataset class (#2977)

---

benchmarks/benchmarks/utils.py
benchmarks/run.sh
docker/pods/ci-lint.yaml
tutorials/dist/1_node_classification.py

Fix distributed training tutorials that blocks the doc build

[Fix] Fix lint resource usage & Fix Docs

---

README.md

Add "VIKING: Adversarial Attack on Network Embeddings via Supervised Network Poisoning" and "Knowledge Graph Embedding using Graph Convolutional Networks with Relation-Aware Attention" in awesome paper list.

[Doc] Update VIKING and KGE-RAA in awesome list

---

benchmarks/benchmarks/api/bench_sample_neighbors.py
cmake/modules/CUDA.cmake

[Benchmark] Enable sample neighbors gpu benchmark

---

src/random/random.cc

[Bug] Fix cuRAND initializing on irrelevant devices

---

tutorials/blitz/4_link_predict.py

[Tutorial] update typo in line 175

---

README.md

[Docs] Add SLAPS and Haystacks in awesome papers

---

python/dgl/distributed/dist_graph.py
python/dgl/distributed/dist_tensor.py
python/dgl/distributed/kvstore.py
python/dgl/distributed/optim/pytorch/sparse_optim.py
python/dgl/distributed/standalone_kvstore.py
tests/distributed/test_dist_graph_store.py

[Distributed] Fix a few bugs in distributed API

---

docs/source/api/python/dgl.rst

Previously dgl.partition APIs does not appear in the documentation.

[doc] Expose dgl.partition APIs

---

examples/pytorch/hilander/README.md

[Example ] fix faiss issue on k 3 for hilander model

---

python/dgl/distributed/rpc_client.py

Fix https://discuss.dgl.ai/t/pages-of-error-ip-address-not-available-for-interface/2125/3

[Fix] Use logging to print warning message in socket creation

---

tutorials/blitz/1_introduction.py
tutorials/blitz/2_dglgraph.py
tutorials/blitz/3_message_passing.py
tutorials/blitz/4_link_predict.py
tutorials/blitz/5_graph_classification.py
tutorials/blitz/6_load_data.py
tutorials/large/L0_neighbor_sampling_overview.py
tutorials/large/L1_large_node_classification.py
tutorials/large/L2_large_link_prediction.py
tutorials/large/L4_message_passing.py
tutorials/multi/1_graph_classification.py
tutorials/multi/2_node_classification.py

Also change the word "courtesy" (not correct) to "credits".

[Doc] Add thumbnails to multi-GPU tutorials

---

docs/source/index.rst
docs/source/performance.rst

This is the part of effort to cleanup the current README. I created a standalone page for hosting the benchmark results we have so far. We could keep updating it in the future.

[Doc] Note for performance benchmarks

---

src/array/cpu/spmm.cc

Remove redundant fill in SPMM kernel

---

examples/pytorch/hilander/README.md

[Model] change hilander numbers to use concat bce

---

docs/source/performance.rst

A little clarification on the benchmark version.

[Doc] Fix perf doc

---

python/dgl/backend/tensorflow/tensor.py

Bug fix: change th to tf

---

docs/source/api/python/nn.pytorch.rst
examples/pytorch/seal/main.py

Fix https://github.com/dmlc/dgl/issues/3183
Also fix https://github.com/dmlc/dgl/issues/3162 

[Doc] Fix WeightBasis documentation 

---

examples/README.md
examples/pytorch/caregnn/README.md
examples/pytorch/caregnn/main.py
examples/pytorch/caregnn/main_sampling.py
examples/pytorch/caregnn/model.py
examples/pytorch/caregnn/model_sampling.py
examples/pytorch/caregnn/utils.py
python/dgl/data/fakenews.py

add model example CAmouflage-REsistant GNN from paper [Enhancing Graph Neural Network-based Fraud Detectors against Camouflaged Fraudsters](https://arxiv.org/pdf/2008.08692.pdf).
@zhjwy9343 

[Model] add model example CARE-GNN

---

docker/pods/ci-cpu.yaml
docker/pods/ci-gpu.yaml

Fix shared memory in unit test

---

examples/README.md
examples/pytorch/geniepath/README.md
examples/pytorch/geniepath/model.py
examples/pytorch/geniepath/ppi.py
examples/pytorch/geniepath/pubmed.py

add model example GeniePath from paper [Geniepath: Graph neural networks with adaptive receptive paths](https://arxiv.org/abs/1802.00910). @zhjwy9343 

[model] add model example GeniePath

---

tools/launch.py

This PR adds the `--ssh_username` flag to the distributed launcher `tools/launch.py`.
Context: `tools/launch.py` issues remote commands via the `ssh` command, in the following way:
```
ssh -o StrictHostKeyChecking=no -p {port} {ip} '{cmd}'
```
By default, this `ssh` command will use the username inherited by the caller. However, sometimes it's necessary to explicitly change the ssh username to avoid SSH permission errors, eg `ssh bob@1.2.3.4` vs `ssh 1.2.3.4`.
This PR allows the user to optionally pass in an `--ssh_username=bob` so that the above ssh command turns into:
```
ssh -o StrictHostKeyChecking=no -p {port} bob@{ip} '{cmd}'
```
From the CLI, the usage is:
```
python3.7 tools/launch.py \
--workspace {workspace_dir_nfs} \
...
--ssh_username bob
```
If not provided, `--ssh_username` …

[Feature] Adds --ssh_username to tools/launch.py

---

README.md

[Doc] Add a Paper

---

README.md

[Readme] Add pytorch direct to Awesome Papers Using DGL

---

python/dgl/sampling/randomwalks.py

[Doc] Fix random_walk documentation inconsistency

---

README.md

[Doc]add four dgl papers

---

src/array/cuda/rowwise_sampling.cu

This gives each thread it's own curandState object, instead of sharing one across a threadblock. This impacts both the "replace=True" and "replace=False" cases of neighbor sampling.
Fixes #3172
- Fix curand_init calls.
- Expand the number of rows each thread works on, to better amortize the cost of `curand_init()`.

[bugfix] Fix curand_init() calls in rowwise sampling

---

python/dgl/data/citation_graph.py

[Doc Fix] Hot Fix for Citation Networks

---

python/dgl/distributed/dist_graph.py

https://github.com/dmlc/dgl/pull/3131 did not deal with homogeneous graph correctly.
#3193 

[Bugfix] Fix bug introduced by https://github.com/dmlc/dgl/pull/3131

---

python/dgl/transform.py

Fixed small typo in knn_graph() documentation.

[Doc] Fix small typo in knn_graph() documentation

---

examples/pytorch/diffpool/model/encoder.py

[Model] fix diffpool.

---

python/dgl/backend/pytorch/sparse.py

This is a simple optimization which remove activation cache if not required.
For example, in $Y = AX$, if A doesn't require gradient, we can avoid caching X, thus saving some GPU memory footprint.

[perf] Remove activation cache if not required.

---

src/array/cuda/spmm.cu
tests/compute/test_heterograph.py

With CUDA 11.1 the following code will crash:
```
In [8]: g = dgl.graph(([0, 0, 0, 0, 0], [1, 1, 1, 1, 1]))
In [9]: g = g.to('cuda')
In [10]: g.ndata['x'] = torch.ones(2, 5).cuda()
In [11]: g.update_all(dgl.function.copy_u('x', 'm'), dgl.function.sum('m', 'y'))
** On entry to cusparseCreateCsr(): dimension mismatch, nnz (5) > matrix size (4)
```
The reason is that apparently `cusparseCreateCsr` does not allow nnz to be larger than matrix size, even if duplicate entries are allowed.
I worked around it by adding a check on NNZ versus the matrix size, and falling back to general kernel implementation if NNZ is larger than matrix size.

[Bugfix] Fix CUDA 11.1 crashing when number of edges is larger than number of node pairs

---

python/dgl/nn/pytorch/conv/dotgatconv.py

The bug of DotGatConv when compute the edge_softmax. Related to #3267.

[bugfix] fix the bug of DotGatConv when compute the edge_softmax

---

examples/pytorch/geniepath/README.md
examples/pytorch/geniepath/model.py

According to the author paper, a tanh function is used after each GAT layer. Which here should consider.

GeniePath model add a Tanh.

---

docs/source/install/index.rst

Fix installation guide for MacOS

---

tutorials/models/1_gnn/4_rgcn.py

There is some misleading text.

[Doc] Update 4_rgcn.py

---

python/dgl/nn/pytorch/conv/relgraphconv.py

clarify **norm** in RelGrapConv::forward() as mentioned in https://discuss.dgl.ai/t/applying-rel-conv-with-edge-weights/2253

[Doc] fix formula in RelGraphConv

---

python/dgl/distributed/graph_services.py
tests/distributed/test_distributed_sampling.py

The current code in distributed sampling cannot handle empty frontiers correctly.

[Distributed] Fix a bug in sampling an empty frontier

---

Jenkinsfile

[Jenkins] add Rhett-Ying into authorized trigger

---

examples/pytorch/correct_and_smooth/README.md
examples/pytorch/correct_and_smooth/main.py
examples/pytorch/correct_and_smooth/model.py

There are some problems in DGL implementation of C&S, including:
1. wrong variable usage in Smooth:
```
self.prop2 = LabelPropagation(num_smoothing_layers,
smoothing_alpha,
correction_adj)
```
2. autoscale does not work:
```
cs = CorrectAndSmooth(num_correction_layers=args.num_correction_layers,
correction_alpha=args.correction_alpha,
correction_adj=args.correction_adj,
num_smoothing_layers=args.num_smoothing_layers,
smoothing_alpha=args.smoothing_alpha,
smoothing_adj=args.smoothing_adj,
scale=args.scale)
```
The metrics in example README.MD should be updated, here are my results:
* **MLP + C&S**
```bash
python main.py --dropout 0.5
python main.py --pretrain --correction-adj DA --smoothing-adj AD --autoscale
```
* **Linear + C&S**
```bash
python main.py --model linear --dropout 0.5 …
```

[Bugfix] Fix Correct&Smooth

---

src/array/cpu/spmm_blocking_libxsmm.h

This PR fixes the bug reported in issue #3312

Fixes bug #3312

---

python/dgl/optim/pytorch/sparse_optim.py

[Bugfix]  Fix #3291

---

tools/launch.py

[Bugfix] And PYTHONPATH in server launch.

---

python/dgl/readout.py

This PR tries to fix https://github.com/dmlc/dgl/issues/3349.

[Bugfix] Fix broadcast tensor dim

---

examples/pytorch/ogb_lsc/README.md

Added md5sum checksum details for OGB-LSC dataset to validate the correctness of downloaded files.  
More details on the issue: https://github.com/snap-stanford/ogb/issues/253
Updates to the readme in OGB-LSC folder.

[Doc] Added md5sum info for OGB-LSC dataset

---

include/dgl/runtime/parallel_for.h
src/graph/sampling/randomwalks/metapath_randomwalk.h
src/graph/sampling/randomwalks/node2vec_randomwalk.h
src/graph/sampling/randomwalks/randomwalks_cpu.h
tests/compute/test_sampling.py

This PR ports PyTorch's OpenMP C++ exception handling so that DGL will not crash if a managed C++ exception (e.g. `LOG(FATAL)`, `CHECK`, etc.) is thrown.
Also added boundary checks in OpenMP random walks as a demonstration.  This also fixes #3338 .

[Feature] Graceful handling of exceptions thrown within OpenMP blocks

---

examples/pytorch/graphsage/train_cv_multi_gpu.py

This PR tries to fix https://github.com/dmlc/dgl/issues/3369.

[Bugfix] Fix torch import in examples

---

README.md
docs/source/api/python/nn.pytorch.rst
examples/README.md
examples/pytorch/gatv2/README.md
examples/pytorch/gatv2/gatv2.py
examples/pytorch/gatv2/train.py
python/dgl/nn/pytorch/conv/__init__.py
python/dgl/nn/pytorch/conv/gatv2conv.py
tests/pytorch/test_nn.py

* Added GATv2Conv operator (pytorch)
* Added an example of GATv2 (pytorch)

[NN][Model] GATv2

---

examples/pytorch/rgcn/experimental/README.md
examples/pytorch/rgcn/experimental/verify_mag_partitions.py
examples/pytorch/rgcn/experimental/write_mag.py
tools/convert_partition.py

fix for https://github.com/dmlc/dgl/issues/3421, https://github.com/dmlc/dgl/issues/3420, https://github.com/dmlc/dgl/issues/3443.
combined from https://github.com/dmlc/dgl/pull/3366, https://github.com/dmlc/dgl/pull/3456.
Verified manually as follows:
1. python3 write_mag.py
2. pm_dglpart mag 2           or          $(which mpirun) --hostfile ~/workspace/ip_config.txt -np 2 pm_dglpart mag 1
3. python3  convert_partition.py --input-dir . --graph-name mag --workspace /tmp/ --output outputs --schema mag.json --num-node-weights 4 --num-parts 2 --removed-edges mag_removed_edges.txt
4. python3 get_mag_data.py
5. python3 verify_mag_partitions.py
6. DGL_HOME=/home/ubuntu/workspace/dgl_toSharedMem DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=..:.:$DGL_HOME/python:$PYTHONPATH DGLBACKEND=pytorch …

Remove self-loops and duplicate edges before ParMETIS and restore when converting to DGLGraph

---

python/dgl/nn/pytorch/conv/gatv2conv.py

Small update in gatv2conv.py docstring

[NN] Update gatv2conv.py doc string 

---

Jenkinsfile

[Jenkins] Add Israt Nisa into authorized regression trigger list

---

docs/source/guide/graph-heterogeneous.rst
docs/source/guide/message-api.rst
docs/source/guide/message-efficient.rst
docs/source/guide/nn-construction.rst
docs/source/guide/nn-forward.rst
docs/source/guide_cn/graph-heterogeneous.rst
docs/source/guide_cn/message-api.rst
docs/source/guide_cn/message-efficient.rst
docs/source/guide_cn/nn-construction.rst
docs/source/guide_cn/nn-forward.rst

- [1.5]  `tensor([0, 1, 2, 0, 1, 2])` should be output instead of code
- [2.1]  `updata_all_example()` should be `update_all_example()`
- [2.2]  `cat_feat` need to concatenate with `dim=1` for the # edge features to match # edges
- [3.1, 3.2] all `max_pool` in the aggregator type of `SAGEConv` should be `pool` instead

Fix User Guide EN and CN typo

---

docs/source/faq.rst

Changed 'questios' to 'questions'

Made a spelling correction

---

python/dgl/dataloading/pytorch/dataloader.py
tests/pytorch/test_dataloader.py

part of https://github.com/dmlc/dgl/issues/3294.
In this part, async data transfer is enabled in NodeDataLoader for homograph.
feature/label prefetch is also enabled.
async_load is independent of load_input/output.

[Feature] enable async transfer in NodeDataLoader for homograph

---

examples/pytorch/model_zoo/geometric/mnist.py

This PR fixes the bug reported in issue [3527](https://github.com/dmlc/dgl/issues/3527)

[Bugfix] issue #3527

---

examples/pytorch/pinsage/layers.py
examples/pytorch/pinsage/model.py

fix for https://github.com/dmlc/dgl/issues/3523
`python3 model.py data.pkl --num-epochs 300 --num-workers 2 --device cuda:0 --hidden-dims 64` has been running for more than 12 hours and no error/crash...[to be updated]

[BugFix] fix dimension unmatch issue and legacy issue of torchtext

---

python/dgl/data/tu.py

An improvement for docs of TUDataset to address #3548 
Add a note and reorganize the document of `TUDataset`

[Doc] Add a note about the order of TUDataset

---

examples/pytorch/tgn/dataloading.py

Fix tgn example

---

.gitmodules
CMakeLists.txt

Bring back thrust for backward compatibility

---

python/dgl/nn/pytorch/conv/twirlsconv.py
tests/pytorch/test_nn.py

[BugFix] Fix a bug in TWIRLS, add unittest

---

tutorials/cpu/cpu_best_practises.py

Typo fix in CPU best practices docs section.
Fix typo in training on CPU docs section

[DOC] Fix typo in CPU best practices section

---

docker/pods/ci-cpu.yaml

[CI] Increase CI cpu machine cpus

---

examples/pytorch/graphsage/experimental/train_dist.py

Fix train_dist.py

---

include/dgl/runtime/ndarray.h
include/dgl/runtime/shared_mem.h
include/dgl/runtime/threading_backend.h
src/runtime/ndarray.cc
src/runtime/shared_mem.cc
src/runtime/thread_pool.cc
src/runtime/threading_backend.cc
tests/compute/test_shared_mem.py

Also fixed a compilation error with Windows SDKs later than 10.0.18362.0.

[Windows] Support NDArray in shared memory on Windows

---

python/dgl/backend/tensorflow/tensor.py
python/dgl/transform.py

Fix KNN graph on tensorflow
Fix #3623 

Fix #3623 KNN graph on tensorflow

---

include/dgl/runtime/parallel_for.h
src/array/cpu/negative_sampling.cc

Pass the std:min argument's type, to avoid the compilation error.

---

python/dgl/data/__init__.py

Without this fix, if anyone sync with latest code, third-party modules introduced by `DGLCSVDataset` may not be found.

Do not import DGLCSVDataset in default in case of dependency issue

---

tests/compute/test_data.py

[FIX] fix compute/test_data.py::test_csvdataset

---

python/dgl/distributed/partition.py
python/dgl/partition.py

The PR measures the peak memory used at each stage in graph partitioning.

[Distributed] Measure peak memory size in graph partitioning

---

examples/pytorch/rgcn/experimental/verify_mag_partitions.py

A few bugs are fixed in ParMETIS. Add more verification code to ensure the partitioned results are correct.

[Distributed] Fix verification for distributed partitioning.

---

tests/distributed/test_rpc.py

Fix test failure in multithread rpc test

---

python/dgl/enter/pipeline/edgepred/edgepred.jinja-py
python/dgl/enter/pipeline/edgepred/gen.py
python/dgl/enter/pipeline/nodepred/gen.py
python/dgl/enter/pipeline/nodepred/nodepred.jinja-py
python/dgl/enter/pipeline/nodepred_sample/gen.py
python/dgl/enter/pipeline/nodepred_sample/nodepred-ns.jinja-py
python/dgl/enter/utils/factory.py

New data register way

---

examples/pytorch/graphsage/experimental/README.md

[Distributed] Fix a typo in readme

---

docs/source/guide/minibatch-custom-sampler.rst

Fix sampling tutorials

---

python/dgl/_ffi/base.py

Fix wrong logging level

---

python/dgl/distributed/dist_dataloader.py

fix for https://github.com/dmlc/dgl/issues/3693
In the previous impl, a large list of tensors(each tensor has single value) will be created and sharing such large list of tensors between processes could run out of file descriptors and crashed with `too many open files`.
For now, we merge such a list of tensor into single tensor.
pls refer to https://pytorch.org/docs/stable/multiprocessing.html#file-descriptor-file-descriptor for more details.

[Fix] too many open files

---

python/dgl/backend/set_default_backend.py
python/dgl/transform/functional.py
tests/compute/test_transform.py

[Transform] Allow Disabling Adding Reverse Edges for Self Loops 

---

examples/pytorch/graphsage/experimental/train_dist.py

Pad node ids by repeating node ids with shuffling is likely to cause duplicate node ids within same batches, which is not supported in current scenario. Default set to False to avoid potential problems.

Fix dist example padding problem

---

docs/source/index.rst

[DOC] list transform in api reference

---

tests/scripts/task_unit_test.sh

Add unbuffered to distributed test

---

python/dgl/data/bitcoinotc.py
python/dgl/data/citation_graph.py
python/dgl/data/csv_dataset.py
python/dgl/data/dgl_dataset.py
python/dgl/data/fakenews.py
python/dgl/data/fraud.py
python/dgl/data/gdelt.py
python/dgl/data/gindt.py
python/dgl/data/gnn_benchmark.py
python/dgl/data/icews18.py
python/dgl/data/karate.py
python/dgl/data/knowledge_graph.py
python/dgl/data/minigc.py
python/dgl/data/ppi.py
python/dgl/data/qm7b.py
python/dgl/data/qm9.py
python/dgl/data/qm9_edge.py
python/dgl/data/rdf.py
python/dgl/data/reddit.py
python/dgl/data/tree.py
python/dgl/data/tu.py
tests/compute/test_data.py

[Dataset] Add transform argument to built-in datasets

---

python/dgl/nn/pytorch/conv/egatconv.py

[doc] fix error in example

---

python/dgl/nn/pytorch/explain/gnnexplainer.py

[doc] fix error in example results

---

python/dgl/nn/pytorch/link/transr.py

[doc] fix module typo

---

docs/source/api/python/dgl.data.rst
docs/source/guide/data-loadcsv.rst
docs/source/guide/data.rst
python/dgl/data/csv_dataset.py
tutorials/blitz/6_load_data.py

[Doc] add doc for DGLCSVDataset

---

docker/install/conda_env/torch_cpu_pip.txt
docker/install/conda_env/torch_gpu_pip.txt
docker/pods/ci-cpu.yaml
docker/pods/ci-gpu.yaml

[CI] Try torch 1.9.0 in CI

---

examples/pytorch/__temporary__/graphsage/ddp.py
python/dgl/dataloading/dataloader.py
python/dgl/heterograph_index.py

This is a leftover issue from #3727.
Thanks @Rhett-Ying for the idea.

[Bugfix] Fix graph being duplicated in multi-GPU and CPU dataloader workers

---

docs/source/api/python/dgl.data.rst

toctree typo for dataset adapters

---

docs/source/api/python/dgl.data.rst
python/dgl/data/adapter.py
tests/compute/test_data.py

Add for `AsNodePredDataset` only, as `AsLinkPredDataset` has already corresponding attributes.

[Dataset] add train_idx/val_idx/test_idx as dataset attributes

---

python/dgl/data/adapter.py

[Doc] fix example in docstring

---

python/dgl/transform/functional.py

[Doc] refine docstring and examples for reorder_graph

---

include/dgl/aten/array_ops.h
python/dgl/__init__.py
python/dgl/sampling/neighbor.py
tutorials/multi/1_graph_classification.py
tutorials/multi/2_node_classification.py

Should fix #3780.  @Rhett-Ying Please take a look.

[Bugs] Fix distributed example error and import error

---

docs/source/api/python/dgl.data.rst
docs/source/api/python/dgl.rst
docs/source/api/python/nn-pytorch.rst

[Doc] Misc fix for doc

---

docs/source/guide/minibatch-gpu-sampling.rst

Update doc for GPU and UVA sampling to be compatible with the current interface.

[Doc] Update doc for GPU and UVA sampling

---

Jenkinsfile
docker/pods/ci-cpu.yaml

Remove unnecessary jenkins part

---

Jenkinsfile
tests/pytorch/test_optim.py

Fix jenkins

---

docs/source/api/python/nn-pytorch.rst
python/dgl/nn/pytorch/conv/__init__.py
python/dgl/nn/pytorch/conv/grouprevres.py
tests/pytorch/test_nn.py

[NN] Grouped reversible residual connections for GNNs

---

docs/source/api/python/dgl.distributed.rst

[Doc] fix display issue of node/edge_split

---

docs/source/guide/message-api.rst

[Doc] Update message-api.rst

---

python/dgl/dataloading/dataloader.py
python/dgl/utils/internal.py
tests/pytorch/test_dataloader.py

[Bug] Fix dtype mismatch in heterogeneous DataLoader

---

python/dgl/dataloading/graphsaint.py

[Doc] Hotfix for GraphSAINT Doc

---

docs/source/api/python/nn-pytorch.rst
python/dgl/dataloading/graphsaint.py
python/dgl/nn/pytorch/conv/__init__.py
python/dgl/nn/pytorch/conv/egnnconv.py
python/dgl/nn/pytorch/conv/pnaconv.py
tests/pytorch/test_nn.py

[NN] Add EGNN & PNA

---

python/dgl/nn/pytorch/conv/egnnconv.py

Previously the equations were not rendered properly. I've validated this fix by building the doc locally.

[Doc] Fix Doc for EGNNConv

---

docs/source/api/python/dgl.multiprocessing.rst
python/dgl/multiprocessing/__init__.py
python/dgl/multiprocessing/pytorch.py

[Doc] Fix documentation in dgl.multiprocessing namespace

---

docs/source/api/python/nn-pytorch.rst
python/dgl/nn/pytorch/conv/__init__.py
python/dgl/nn/pytorch/conv/gineconv.py
tests/pytorch/test_nn.py

[NN] GINEConv

---

examples/pytorch/gnn_explainer/explain_main.py

Fixed bug #3944 
optimizer needs to be defined only on the mask since the model is fixed.
@mufeili @zhjwy9343

[Bug] Fixed optimizer definition in gnn_explainer (#3944)

---

tests/scripts/ci_report/status.py

pls check the new status results examples in https://github.com/dmlc/dgl/pull/3954

[CI] refine status check

---

Jenkinsfile
tests/scripts/ci_report/status.py

1. If new PR is merged into master, the following CI on master branch will be marked as `failed` due to `pullRequest` not available. details is shown below:
```
Full logs at [link](https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/master/544/544/logs/cireport.log)
No such property: pullRequest for class: groovy.lang.Binding
```
2. pipeline status is refined to catch aborted stages.

[BugFix] fix job status in master CI

---

tests/scripts/ci_report/status.py

Below case should be regarded as `SUCCESS`.
```
"name": "Regression Test Trigger",
"execNode": "",
"status": "NOT_EXECUTED",
```
```
❌ CI test failed in Stage [Regression Test Trigger]. 
```

[BugFix] fix CI status

---

Jenkinsfile
dglgo/dglgo/model/node_encoder/gat.py
dglgo/dglgo/model/node_encoder/gcn.py
dglgo/dglgo/model/node_encoder/gin.py
dglgo/dglgo/model/node_encoder/sage.py
dglgo/dglgo/model/node_encoder/sgc.py
tests/go/test_config.py
tests/go/test_model.py
tests/go/test_pipeline.py
tests/scripts/build_dgl.sh
tests/scripts/task_go_test.sh

[DGL-Go] CI for DGL-Go

---

python/dgl/transforms/functional.py

[Doc] Fix compact_graphs example docstring

---

Jenkinsfile

[CI] Increase Timeout Limit for DGL-Go

---

examples/pytorch/pinsage/README.md

`torchtext.legacy.data` is used in Pinsage [model.py](https://github.com/dmlc/dgl/blob/master/examples/pytorch/pinsage/model.py#L55-L61) . However, `torchtext.legacy.data` is  released in 0.9.0 instead of 0.5. [Here](https://github.com/pytorch/text/releases/tag/v0.9.0-rc5) is a release note about torchtext 0.9.0.

[Doc] Update pinsage readme: torchtext>=0.9.0

---

tests/scripts/ci_report/status.py

We'd like to print more info so as to we can easily know which commit fails.

[CI] print commit/build ID into comment

---

examples/pytorch/gat/train.py

[Bugfix] Fix conditional judgment of cuda (#4026)

---

examples/pytorch/graphsage/lightning/node_classification.py

[Example][BugFix] Fix Lightning GraphSAGE examples (dmlc#4046)

---

benchmarks/benchmarks/utils.py
docs/source/api/python/dgl.data.rst
examples/pytorch/pinsage/README.md
examples/pytorch/pinsage/model.py
examples/pytorch/pinsage/model_sparse.py
examples/pytorch/pinsage/process_movielens1m.py
examples/pytorch/pinsage/process_nowplaying_rs.py

Replace pickling `train_g` with `save_graphs` to avoid breaking backward compatibility in regression test and update the script for the regression test.
@Rhett-Ying Could you try building the graph on the regression machine and invoking the benchmark?

[Bugfix] Fix PinSAGE Benchmark

---

src/array/cpu/spmat_op_impl_csr.cc
tests/compute/test_heterograph.py

Reports an appropriate error message in #4047

[Bug] add sanity check for in_edges/out_edges on empty graphs

---

docs/source/api/python/dgl.data.rst
docs/source/guide/data-loadcsv.rst
docs/source/guide/data-process.rst
docs/source/guide_cn/data-process.rst
docs/source/guide_ko/data-process.rst
python/dgl/data/__init__.py
python/dgl/data/adapter.py
python/dgl/data/csv_dataset.py
python/dgl/data/csv_dataset_base.py
python/dgl/data/gindt.py
python/dgl/data/qm7b.py
python/dgl/data/qm9.py
python/dgl/data/qm9_edge.py
python/dgl/data/synthetic.py
python/dgl/data/tu.py
tests/compute/test_data.py

Separate code related to `AsGraphPredDataset` from #3927 

[Data] AsGraphPredDataset

---

examples/pytorch/ogb/cluster-gat/main.py

Found some typos in the python script for cluster-gat example. Have them fixed.
Reported issue link: https://github.com/dmlc/dgl/issues/4067 
- To fix "Expected all tensors to be on the same device" (line 122), make a cpu-cpy to label
- "g.ndata.pop('feat').to(device)" presents within outermost loop of rerun; move it out of the loop to avoid redundant "pop"
- Similar to (1), move best_test_acc to cpu

[Bugfix] Fix cluster-gat example

---

examples/README.md
examples/pytorch/bgrl/README.md
examples/pytorch/bgrl/eval_function.py
examples/pytorch/bgrl/main.py
examples/pytorch/bgrl/model.py
examples/pytorch/bgrl/utils.py

[Example] Add BGRL example

---

README.md

They have been there for a while but we didn't add them into the README.

Update README.md to include OpenHGNN and TGL

---

tests/scripts/task_unit_test.sh
tests/tools/test_launch.py
tools/launch.py

[Dist] master port should be fixed for all trainers

---

docs/source/api/python/dgl.rst

* Added functions from dgl.transforms.functional that were missing from the list for documentation in dgl.rst for Issue #4087 
* Sorted transform ops list in dgl.rst in alphabetical order

[Doc] Updated transform ops list in dgl.rst (Issue #4087)

---

python/dgl/distributed/dist_context.py
python/dgl/distributed/dist_graph.py
python/dgl/distributed/rpc_client.py
python/dgl/distributed/rpc_server.py
tests/distributed/test_rpc.py

[Dist] set socket as default backend for RPC

---

src/rpc/network/socket_communicator.cc

One RPCMessage is split into meta message and ndarray message and sent in independent socket calls. So they may arrive at peer with some delay. So we have to re-try. 

[Dist] re-try to receive rpc ndarray msg

---

README.md

Hi there, ArangoDB is currently maintaining an adapter to allow users to export their graphs into DGL and vice-versa. Would be cool to have it listed if possible!

[Doc] Add ArangoDB-DGL in DGL-powered projects

---

docs/source/api/python/dgl.distributed.rst
python/dgl/distributed/__init__.py
python/dgl/distributed/dist_graph.py
python/dgl/distributed/partition.py
tests/distributed/test_partition.py

CPU RAM is tight sometimes, let's defer loading of node/edge feats to lower the peak memory consumption.

[Dist] defer to load node/edge feats

---

Jenkinsfile
docker/Dockerfile.ci_cpu
docker/Dockerfile.ci_gpu
docker/install/conda_env/tensorflow_cpu.yml
docker/install/conda_env/tensorflow_gpu.yml

1. upgrade ubuntu from 16.04 to 18.04
2. upgrade tensorflow from 2.2.0 to 2.3.0
https://github.com/dmlc/dgl/pull/4180 depends on this PR.

[CI] Upgrade software version of CI docker image

---

tools/distpartitioning/convert_partition.py
tools/distpartitioning/globalids.py

These are the bug fixes identified during testing with 'mag_lsc' dataset. Since this is a larger dataset compared to "mag" we were running into peculiar issues as following:
When creating dgl partition objects, in the convert_partition.py, for some partitions unique node-ids in the edge list were not completely representing all the nodes in that partition. To resolve this we need to change the dgl function call appropriately to pass "num_nodes" argument in the argument list.
When creating a Tensor, for a very large integer list, torch.Tensor() function call used earlier. This was working for small integer list, but when it exceeds certain size we were noticing data corruption in the tensor generate from this function call. This was a very tricky bug to solve. Changed this function call …

code changes for bug fixes identified during mag_lsc dataset

---

python/dgl/dataloading/dataloader.py

[Doc] fix typo

---

Jenkinsfile
tests/cugraph/test_basics.py
tests/scripts/build_dgl.sh
tests/scripts/cugraph_unit_test.sh
tests/scripts/task_unit_test.sh

https://github.com/dmlc/dgl/pull/4166 depends on this for CI test.
As suggested, the base is `nvcr.io/nvidia/pytorch:22.04-py3` which includes `cuda11.6`, `pytorch1.12.0a0+bd13bc6`, `rapids 22.02`.

[CI] Add new CI stage for testing cugraph

---

examples/pytorch/eges/README.md

Regarding issue #4205, update README file to be more specific...
- Specify the actual link to download data
- Simplify README file

[Example] Update README file of eges example 

---

tests/dist/python/run_dist_objects.py

Improves DistTensor sanity test when num_part id > 2.

[Dist][Test] Improves DistTensor test for num_part id > 2

---

tests/dist/python/run_dist_objects.py
tests/dist/test_dist_objects.py

Add tests for `DistEmbedding` and in a multi-node environment.

[Dist][Test] Add tests for multi-node DistEmbedding

---

src/rpc/network/tcp_socket.cc
tests/cpp/socket_communicator_test.cc

for for https://github.com/dmlc/dgl/issues/3388

[Log] fix confusing error log in TCPSocket::Bind()

---

Jenkinsfile
docker/install/conda_env/mxnet_cpu.yml
docker/install/conda_env/mxnet_gpu.yml
docker/install/conda_env/tensorflow_cpu.yml
docker/install/conda_env/tensorflow_gpu.yml
docker/install/conda_env/torch_cpu.yml
docker/install/conda_env/torch_gpu.yml
tests/scripts/task_unit_test.sh

[CI] upgrade python version to 3.7.0

---

Jenkinsfile
docker/Dockerfile.ci_cpu
docker/install/ubuntu_install_core.sh

`ssh` is required in distributed test. Let's enable it within docker. `ssh key` is generated as well.
https://github.com/dmlc/dgl/pull/4394 depends on this PR.

[CI] enable ssh in docker image for dist test

---

docs/source/guide/distributed-preprocessing.rst

This PR fixes various minor issues in the doc, including the ones surfacing from the discussion in #4394 

[Doc] Misc Fix for User Guide 7.1 Data Preprocessing

---

tutorials/blitz/2_dglgraph.py

fix for https://github.com/dmlc/dgl/issues/4458

[Doc] fix print issue in tutorial

---

docs/source/guide/minibatch-node.rst
docs/source/guide_cn/minibatch-node.rst
docs/source/guide_ko/minibatch-node.rst

[doc] fix invalid link in user guide

---

tutorials/blitz/3_message_passing.py

[Doc] Clarify the message name, which is 'm', in 3_message_passing.py

---

python/dgl/view.py

Auto fix view.py to conform to the PEP 8 style guide.

[Readability] Auto fix view.py.

---

Jenkinsfile
tests/scripts/ci_report/report.py
tests/scripts/ci_report/status.py

[CI] use https instead of http

---

python/dgl/transforms/functional.py
tests/compute/test_transform.py
tutorials/blitz/3_message_passing.py

[BugFix] fix crash due to incorrect dtype in dgl.to_block()

---

docs/README.md

The current documentation build does not work for Sphinx 5.1.1.

[Build][Doc] Specify the sphinx version

---

Jenkinsfile

[CI] only known devs are authorized to trigger CI

---

python/setup.py
python/update_version.py

Auto fix update-version.py to conform to the PEP 8 style guide.

[Readability] Auto fix setup.py and update-version.py

---

tests/tools/test_dist_part.py
tools/dispatch_data.py
tools/distpartitioning/constants.py
tools/distpartitioning/data_proc_pipeline.py
tools/distpartitioning/data_shuffle.py

fix for https://github.com/dmlc/dgl/issues/4515.

[DistPart] expose timeout config for process group

---

Jenkinsfile
tests/scripts/build_dgl.sh

Revert "[Feature][REVIEW] Enable DGL cugaph nightly CI "

---

.github/workflows/pylint.yml
python/update_version.py

The original workflow was not triggered to test what's run, trying the canonical workflow.

[Misc] Try use official pylint workflow.

---

Jenkinsfile

[CI] refine stage logic

---

.github/workflows/pylint.yml

[Misc] Update the python version in Pylint workflow for flake8.

---

.github/workflows/pylint.yml

[Misc] Update pylint.

---

.github/workflows/pylint.yml

[Misc] Use another workflow.

---

examples/pytorch/graphsage/dist/train_dist.py

* [examples]educe memory consumption
* reffine help message
* refine

[examples]Reduce memory consumption (#4558)

---

tools/dispatch_data.py

add ssh port config for dispatchdata

---

docs/source/api/python/dgl.sparse_v0.rst
python/dgl/mock_sparse/diag_matrix.py
python/dgl/mock_sparse/sp_matrix.py
tests/pytorch/mock_sparse/test_transpose.py

Migrate the transposition operator from temporary repo to dgl repo.

[Sparse] Add Transposition for SparseMatrix and DiagMatrix

---

tests/tools/test_dist_part.py
tools/dispatch_data.py
tools/distpartitioning/convert_partition.py
tools/distpartitioning/data_proc_pipeline.py
tools/distpartitioning/data_shuffle.py
tools/distpartitioning/utils.py

[Dist] save original node/edge IDs into separate files

---

examples/pytorch/mock_sparse/gcn/README.md
examples/pytorch/mock_sparse/gcn/train.py

[Sparse] Add GCN example

---

.github/workflows/stale.yml

- Disable automatic issue closing
- Correct the labels to exempt.

[Github] Update Github stale bot

---

examples/pytorch/mock_sparse/gcn/train.py

[Sparse] Replace `gcn_norm` with `pow` operator

---

python/dgl/mock_sparse/diag_matrix.py
python/dgl/mock_sparse/sp_matrix.py
tests/pytorch/mock_sparse/test_sparse_matrix.py

[Sparse] Add SparseMatrix unittest and fix docstring problem

---

docs/source/api/python/dgl.sparse_v0.rst
examples/pytorch/mock_sparse/gcn/train.py

Resolves [Issue#4654](https://github.com/dmlc/dgl/issues/4654)

[Sparse] Improve API docs

---

python/dgl/distributed/dist_tensor.py
python/dgl/distributed/kvstore.py
python/dgl/distributed/standalone_kvstore.py
tests/distributed/test_dist_graph_store.py
tests/distributed/test_dist_tensor.py
tests/distributed/utils.py

This is a part of the distributed link prediction pipeline.  Resolves #4614.
NOTE: I'm not sure whether we have finished the distributed unit test pipeline.  So I manually trigger the following script and it worked for me: https://gist.github.com/BarclayII/458005e8be8ef23e1c617b1f8b9a5ad8

[DistTensor] add bitwise or function

---

conda/dgl/meta.yaml
include/dgl/runtime/c_runtime_api.h
python/dgl/_ffi/libinfo.py
python/setup.py
python/update_version.py

Bumps the development version to 0.10 to re-enable nightly build.

bump version

---

docs/source/guide/distributed-partition.rst
docs/source/guide/distributed-preprocessing.rst

[doc] add doc for saving original node/edge IDs in dist part pipeline

---

.clang-format

Mostly auto generated from "clang-format -style=Google -dump-config > .clang-format"

[Misc] Add clang-format.

---

tests/scripts/ci_report/report.py
tests/scripts/ci_report/status.py
tests/tensorflow/test_basic.py
tests/tensorflow/test_nn.py
tests/test_utils/__init__.py
tests/test_utils/checks.py
tests/tools/test_dist_part.py
tests/tools/test_launch.py
tools/chunk_graph.py
tools/copy_files.py
tools/dispatch_data.py
tools/launch.py
tools/partition_algo/random_partition.py
tools/utils/__init__.py
tools/utils/array_readwriter/__init__.py
tools/utils/array_readwriter/csv.py

[Misc] Black auto fix.

---

src/array/cpu/rowwise_pick.h
tests/compute/test_sampling.py

fix for https://github.com/dmlc/dgl/issues/4711. 

handle fanout=-1 differently from fanout>0 in sample_etype_neighbors()

---

.github/PULL_REQUEST_TEMPLATE.md

[Misc] Update PULL_REQUEST_TEMPLATE.md

---

tests/tools/create_chunked_dataset.py
tests/tools/test_dist_part.py
tools/distpartitioning/convert_partition.py
tools/distpartitioning/dataset_utils.py

This PR includes fix for https://github.com/dmlc/dgl/issues/4658 and https://github.com/dmlc/dgl/issues/4681. 

[Dist] decouple num_chunks and num_parts for graphs with edge feature

---

tutorials/large/L1_large_node_classification.py

Revert "[Misc] Isort tutorials/large/L1_large_node_classification.py"

---

python/dgl/distributed/dist_graph.py
python/dgl/distributed/partition.py
tests/distributed/test_distributed_sampling.py
tests/distributed/test_partition.py
tests/tools/test_dist_part.py
tools/dispatch_data.py
tools/distpartitioning/data_proc_pipeline.py
tools/distpartitioning/data_shuffle.py
tools/distpartitioning/utils.py

Below 2 action items that are requested in https://github.com/dmlc/dgl/issues/4514 are implemented in this PR:

[Dist] Reduce startup overhead: sort etypes and save in specified formats

---

tests/dist/python/run_dist_objects.py
tests/dist/test_dist_objects.py

Add tests for DistGraph in a multi-node environment.
Implement https://github.com/dmlc/dgl/issues/4374

[Dist][Test] Add tests for multi-node DistGraph

---

tools/change_etype_to_canonical_etype.py

[Dist] remove dependecy of load_partition_book in change tool

---

include/dgl/base_heterograph.h
include/dgl/runtime/c_runtime_api.h
include/dgl/runtime/container.h
src/array/cpu/rowwise_pick.h
src/array/cuda/segment_reduce.cuh
src/array/cuda/utils.h
src/array/libra_partition.cc
src/graph/heterograph.h
src/graph/sampling/randomwalks/metapath_randomwalk.h
src/graph/sampling/randomwalks/node2vec_impl.h
src/graph/sampling/randomwalks/node2vec_randomwalk.h
src/graph/sampling/randomwalks/randomwalks_cpu.h
src/graph/sampling/randomwalks/randomwalks_impl.h

[Misc] Minor code style fix.

---

src/array/cpu/spmm_blocking_libxsmm.h
src/array/cuda/bf16.cuh
src/graph/heterograph.h
src/graph/serialize/dglstream.h
src/graph/traversal.cc
src/runtime/cuda/cuda_hashtable.cu

[Misc] clang-format auto fix.

---

tools/distpartitioning/parmetis_preprocess.py

Here, we check if the <graph_name>_stats.txt does not exist then creates one in the current directory. 
<graph_name>_stats.txt file has one single line with 3 columns (num_nodes, num_edges and num_constraints). 
num_constraints is the sum of number of node types in the graph (represented as 1-hot vector) and one each for train/test/val masks. 
stats file will be created in the current working directory. 

[Dist] Create <graph_name>_stats.txt file if it does not exist before ParMETIS execution

---

src/array/cpu/spmm_blocking_libxsmm.h

[Misc] Add // NOLINT for the very long code.

---

dgl_sparse/include/sparse/elementwise_op.h
dgl_sparse/include/sparse/sparse_matrix.h
dgl_sparse/src/elemenwise_op.cc
dgl_sparse/src/python_binding.cc
dgl_sparse/src/sparse_matrix.cc
dgl_sparse/src/utils.h

[Misc] Update the latest created cpp files.

---

dgl_sparse/include/sparse/elementwise_op.h
dgl_sparse/include/sparse/sparse_matrix.h
dgl_sparse/src/elemenwise_op.cc
dgl_sparse/src/python_binding.cc
dgl_sparse/src/sparse_matrix.cc
dgl_sparse/src/utils.h

[Sparse] Lint C++ files

---

tools/distpartitioning/parmetis_preprocess.py

Fix typo of metis preprocessing

---

examples/pytorch/ogb/ogbn-mag/hetero_rgcn.py

To fix https://github.com/dmlc/dgl/issues/4838, this PR ensures the indexing always from same device or `cpu`, in this example.

[Example][Bugfix] Fix ogb/ogbn-mag/heter-RGCN example

---

tests/lint/lint.py

[Misc] Update cpplint.

---

tests/dist/python/run_dist_objects.py

Add tests for DistDataLoader, DistNodeDataLoader and DistEdgeDataLoader in a multi-node environment.
This PR implements #4376

[Dist][Test] Add tests for multi-node dist dataloaders.

---

src/array/cpu/array_index_select.cc

Reverts dmlc/dgl#4878 as it did not work as expected.

Revert "Parallel find edges"

---

docs/source/api/python/transforms.rst
python/dgl/transforms/module.py
python/dgl/utils/internal.py
tests/compute/test_transform.py

close #4613 
fix #4883 
Provide a toLevi transform to convert a graph to a corresponding Levi graph (convert original edges into nodes in the new graph).
Fix parameter typo in `extract_edge_subframes`.

[Transform] Add ToLevi transform

---

python/dgl/distributed/graph_partition_book.py
tests/distributed/test_partition.py

[Dist] fix is_node check according to policy

---

CMakeLists.txt
dgl_sparse/CMakeLists.txt
dgl_sparse/include/sparse/dgl_headers.h

[Sparse] Be compatible with Pytorch 1.13 and later version

---

python/dgl/heterograph.py
tests/compute/test_basics.py
tests/compute/test_batched_graph.py
tests/compute/test_graph.py
tests/compute/test_kernel.py
tests/compute/test_propagate.py
tests/compute/test_removal.py
tests/compute/test_specialization.py
tests/compute/test_subgraph.py

[API Deprecation] Remove add_edge in DGLGraph

---

examples/pytorch/graph_matching/ged.py

[Misc] Auto fix by black.

---

examples/sparse/appnp.py
examples/sparse/sgc.py
examples/sparse/sign.py

[Misc] Small tweak for the example.

---

dgl_sparse/include/sparse/sparse_format.h
dgl_sparse/include/sparse/sparse_matrix.h
dgl_sparse/src/sparse_format.cc
dgl_sparse/src/sparse_matrix.cc
dgl_sparse/src/utils.h
python/dgl/mock_sparse2/sparse_matrix.py
tests/pytorch/mock_sparse2/test_diag.py
tests/pytorch/mock_sparse2/test_elementwise_op_sp.py
tests/pytorch/mock_sparse2/test_sparse_matrix.py

[Sparse] Support sparse format conversion

---

tools/change_etype_to_canonical_etype.py

[Dist] fix argument consistent with help message

---

dgl_sparse/include/sparse/sparse_format.h
dgl_sparse/include/sparse/sparse_matrix.h
dgl_sparse/src/python_binding.cc
dgl_sparse/src/sparse_format.cc
dgl_sparse/src/sparse_matrix.cc
python/dgl/mock_sparse2/sparse_matrix.py
tests/pytorch/mock_sparse2/test_diag.py
tests/pytorch/mock_sparse2/test_elementwise_op_diag.py
tests/pytorch/mock_sparse2/test_elementwise_op_sp.py
tests/pytorch/mock_sparse2/test_sparse_matrix.py
tests/pytorch/mock_sparse2/test_transpose.py

[Sparse] Add SparseMatrix transposition

---

tools/distpartitioning/parmetis_preprocess.py

The current distributed partition preprocess only works with mpich. This PR extend it to support openmpi.

[Bugfix] Make preprocess compatible with openmpi

---

python/dgl/sparse.py

[Bug] fix typo

---

tests/pytorch/mock_sparse2/test_diag.py
tests/pytorch/mock_sparse2/test_elementwise_op_diag.py
tests/pytorch/mock_sparse2/test_elementwise_op_sp.py
tests/pytorch/mock_sparse2/test_sparse_matrix.py
tests/pytorch/mock_sparse2/test_transpose.py
tests/pytorch/mock_sparse2/test_unary_op_sp.py

[Sparse] Update TODO Style

---

examples/sparse/gcn.py

[Misc] Small fix in sparse GCN example.

---

CMakeLists.txt
dgl_sparse/include/sparse/dgl_headers.h
dgl_sparse/include/sparse/sddmm.h
dgl_sparse/include/sparse/sparse_format.h
dgl_sparse/include/sparse/spmm.h
dgl_sparse/src/python_binding.cc
dgl_sparse/src/sddmm.cc
dgl_sparse/src/sparse_format.cc
dgl_sparse/src/spmm.cc
include/dgl/kernel.h
python/dgl/mock_sparse2/__init__.py
python/dgl/mock_sparse2/matmul.py
src/array/kernel.cc
tests/pytorch/mock_sparse2/test_mm.py

[Sparse] Add SpMM and SDDMM.

---

Jenkinsfile
tests/tools/test_parmetis.py
tools/distpartitioning/parmetis_postprocess.py

please remember to prepend `tools` into `PYTHONPATH` when calling `//toos/distpartitioning/parmetis_postprocess.py` like below:
```
export PYTHONPATH=/data/rying_dgl_test/tools:$PYTHONPATH
```

[Dist] generate partition meta for ParMETIS pipeline

---

include/dgl/aten/coo.h
include/dgl/aten/csr.h
src/array/array.cc

[Sparse] Add SpMM and SDDMM on CSR and COO in dgl include headers

---

python/dgl/convert.py
python/dgl/distributed/dist_graph.py
python/dgl/nn/mxnet/conv/gmmconv.py
python/dgl/nn/mxnet/conv/graphconv.py
python/dgl/nn/mxnet/conv/nnconv.py
python/dgl/nn/mxnet/conv/sageconv.py
python/dgl/nn/pytorch/conv/dotgatconv.py
python/dgl/nn/pytorch/conv/edgeconv.py
python/dgl/nn/pytorch/conv/gmmconv.py
python/dgl/nn/pytorch/conv/nnconv.py
python/dgl/nn/pytorch/conv/sageconv.py
python/dgl/nn/tensorflow/conv/graphconv.py
python/dgl/nn/tensorflow/conv/sageconv.py

Deprecate candidates in convert module

[API Deprecation] Deprecate candidates in convert module

---

examples/sparse/gcnii.py

The GCNII example code https://github.com/dmlc/dgl/issues/4932 using sparse matrix API
Ref to the full-supervised.py in the repo https://github.com/chennnM/GCNII
|dataset |  val acc| test acc|
| - |   -|  -|
| Cora |  0.8 | 0.85 |

[Sparse] GCNII example

---

tests/pytorch/mock_sparse2/test_matmul.py
tests/pytorch/mock_sparse2/test_sddmm.py

[Sparse] Fix SpMM and SDDMM test precision problem

---

python/dgl/mock_sparse/sddmm.py

[Sparse] Add mock_bsddmm

---

dgl_sparse/CMakeLists.txt
dgl_sparse/include/sparse/spspmm.h
dgl_sparse/src/matmul.cc
dgl_sparse/src/matmul.h
dgl_sparse/src/python_binding.cc
dgl_sparse/src/sddmm.cc
dgl_sparse/src/spspmm.cc
python/dgl/mock_sparse2/matmul.py
python/dgl/mock_sparse2/sddmm.py
tests/pytorch/mock_sparse2/test_matmul.py
tests/pytorch/mock_sparse2/test_sddmm.py
tests/pytorch/mock_sparse2/utils.py

[Sparse] Add SpSpMM for sparse-sparse and sparse-diag matrix multiplication.

---

python/dgl/_sparse_ops.py
python/dgl/backend/mxnet/sparse.py
python/dgl/backend/pytorch/sparse.py
python/dgl/backend/tensorflow/sparse.py
python/dgl/distgnn/partition/libra_partition.py
tests/compute/test_csrmm.py

[Sparse] Rename existing DGL sparse module.

---

python/dgl/mock_sparse2/elementwise_op_sp.py
tests/pytorch/mock_sparse2/test_elementwise_op_sp.py

[Sparse] Elementwise multiplication of a SparseMatrix object by a scalar

---

examples/sparse/gcn.py

[Sparse] Rename theta to W to keep the notation consistent with the paper.

---

dgl_sparse/include/sparse/sddmm.h
dgl_sparse/include/sparse/spmm.h
dgl_sparse/src/matmul.cc
dgl_sparse/src/sddmm.cc
dgl_sparse/src/spmm.cc
python/dgl/mock_sparse2/matmul.py
python/dgl/mock_sparse2/sddmm.py
tests/pytorch/mock_sparse2/test_matmul.py
tests/pytorch/mock_sparse2/test_sddmm.py
tests/pytorch/mock_sparse2/utils.py

[Sparse] Support BSpMM and BSDDMM

---

dgl_sparse/include/sparse/dgl_headers.h
dgl_sparse/src/sparse_format.cc
dgl_sparse/src/sparse_matrix.cc
dgl_sparse/src/spmm.cc
dgl_sparse/src/spspmm.cc
dgl_sparse/src/utils.h

[Sparse] Change all CHECK to TORCH_CHECK

---

examples/sparse/appnp.py
examples/sparse/c_and_s.py
examples/sparse/gat.py
examples/sparse/gcn.py
examples/sparse/gcnii.py
examples/sparse/hgnn.py
examples/sparse/hypergraphatt.py
examples/sparse/sgc.py
examples/sparse/sign.py
examples/sparse/twirls.py
python/dgl/mock_sparse2/softmax.py
tests/pytorch/mock_sparse2/test_example.py
tests/scripts/task_unit_test.bat
tests/scripts/task_unit_test.sh

[Sparse] Add tests for sparse examples; Migrate from mock_sparse to mock_sparse2

---

dgl_sparse/src/spspmm.cc

[Sparse] Avoid using macros in DGL headers

---

tests/pytorch/sparse/test_matmul.py
tests/pytorch/sparse/utils.py

[Sparse] Use Pytorch dense instead of sparse computation in SpMM tests

---

cmake/modules/CUDA.cmake

[CMake] Update CMake for CUDA12

---

CMakeLists.txt
dgl_sparse/CMakeLists.txt
dgl_sparse/build.bat
dgl_sparse/build.sh
dgl_sparse/src/sparse_matrix.cc

[Sparse] Change CMakeFiles to build DGL Sparse for multiple PyTorch versions

---

Jenkinsfile
benchmarks/benchmarks/api/bench_add_self_loop.py
benchmarks/run.sh
benchmarks/scripts/build_dgl_asv.sh
benchmarks/scripts/generate_excel.py
benchmarks/scripts/install_dgl_asv.sh
benchmarks/scripts/publish.sh
benchmarks/scripts/torch_gpu_pip.txt
docker/Dockerfile.ci_benchmark
docker/install/ubuntu_install_conda.sh

[CI] updgrade pytorch version for benchmark CI

---

python/dgl/convert.py
python/dgl/distributed/dist_graph.py
python/dgl/distributed/graph_partition_book.py
python/dgl/distributed/partition.py
python/dgl/nn/mxnet/conv/gmmconv.py
python/dgl/nn/mxnet/conv/graphconv.py
python/dgl/nn/mxnet/conv/nnconv.py
python/dgl/nn/mxnet/conv/sageconv.py
python/dgl/nn/pytorch/conv/dotgatconv.py
python/dgl/nn/pytorch/conv/edgeconv.py
python/dgl/nn/pytorch/conv/gmmconv.py
python/dgl/nn/pytorch/conv/nnconv.py
python/dgl/nn/pytorch/conv/sageconv.py
python/dgl/nn/tensorflow/conv/graphconv.py
python/dgl/nn/tensorflow/conv/sageconv.py
tests/dist/python/run_dist_objects.py
tests/distributed/test_dist_graph_store.py
tests/distributed/test_distributed_sampling.py
tests/distributed/test_mp_dataloader.py
tests/distributed/test_new_kvstore.py
tests/distributed/test_partition.py
tests/pytorch/test_dist_optim.py

[API Deprecation]Deprecate  candidates in dgl.distributed

---

benchmarks/benchmarks/model_acc/bench_rgcn_ns.py
benchmarks/benchmarks/model_acc/bench_sage_ns.py
benchmarks/benchmarks/model_speed/bench_gat_ns.py
benchmarks/benchmarks/model_speed/bench_rgcn_hetero_ns.py
benchmarks/benchmarks/model_speed/bench_rgcn_homogeneous_ns.py
benchmarks/benchmarks/model_speed/bench_sage_ns.py
benchmarks/benchmarks/multigpu/bench_multigpu_sage.py
examples/pytorch/gas/main_sampling.py
examples/pytorch/gcmc/train_sampling.py
examples/pytorch/graphsage/advanced/train_lightning_unsupervised.py
examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py
examples/pytorch/hilander/PSS/test_subg_inat.py
examples/pytorch/hilander/PSS/train_subg_inat.py
python/dgl/dataloading/base.py
python/dgl/dataloading/dataloader.py
python/dgl/dataloading/dist_dataloader.py
tests/pytorch/test_dataloader.py
tutorials/large/L4_message_passing.py
tutorials/multi/2_node_classification.py

[API Deprecation] Deprecation candidates in dataloader

---

docs/source/api/python/dgl.sparse_v0.rst
python/dgl/sparse/diag_matrix.py
python/dgl/sparse/sparse_matrix.py
tests/pytorch/sparse/test_diag.py
tests/pytorch/sparse/test_elementwise_op_diag.py
tests/pytorch/sparse/test_sparse_matrix.py

[Sparse] Remove SparseMatrix.indices and add device/dtype conversions

---

docs/source/api/python/dgl.sparse_v0.rst
python/dgl/sparse/elementwise_op_diag.py
python/dgl/sparse/elementwise_op_sp.py

[Sparse] Remove unnecessary API exposure.

---

docs/source/api/python/dgl.sparse_v0.rst
python/dgl/sparse/elementwise_op.py

[Sparse] Update doc string of element-wise ops for DiagMatrix and SparseMatrix.

---

python/dgl/sparse/elementwise_op.py

Not sure whether it will render correctly, just a try.

Update python doc for elementwise_op.

---

benchmarks/benchmarks/multigpu/bench_multigpu_rgcn.py
benchmarks/benchmarks/utils.py
benchmarks/scripts/build_dgl_asv.sh
benchmarks/scripts/publish.sh
docker/Dockerfile.ci_benchmark

cherry-picked from https://github.com/dmlc/dgl/pull/5132. Let's merge it into master first, then to `1.0.x`. That should be much cleaner.
This PR depends on https://github.com/dmlc/dgl/pull/5134. We need to rebase on it to make sure multi-gpu benchmarks works as expected.
This PR covers:
1. Arg `low_mem` has already been removed from `dgl.nn.pytorch.RelGraphConv`, let's just remove it from benchmark tests as well.
2. enable `USE_NCCL` for multi-gpu communications. and unset `CUDA_VISIBLE_DEVICES=0` as it will hide other GPUs when running on instance with multiple GPUs.

[CI] fix bugs for multigpu benchmarks

---

python/dgl/sparse/elementwise_op.py

[Sparse] Add elementwise mul and div method, and polish the python doc.
