- docs/source/api/python/dgl.sparse_v0.rst
- python/dgl/sparse/elementwise_op.py
> [Sparse] Further polish the doc string.

- python/dgl/sparse/elementwise_op.py
> [Sparse] Further polish.

- docs/source/api/python/dgl.sparse_v0.rst
> [Sparse] Update the order of the method list in doc to group mathematically method together.

- dgl_sparse/src/elemenwise_op.cc
> [Sparse] Reduce peak memory of SpSpAdd.

- python/dgl/sparse/matmul.py
- tests/pytorch/sparse/test_matmul.py
> [Sparse] Use efficient implementation for diagonal and sparse matrices multiplication.

- benchmarks/benchmarks/api/bench_edge_subgraph.py
- benchmarks/benchmarks/api/bench_in_subgraph.py
- benchmarks/benchmarks/api/bench_node_subgraph.py
- benchmarks/benchmarks/api/bench_sample_neighbors.py
some benchmark tests are not really run on GPU, let's fix them.
> [CI] fix device configure when run on GPU

- docs/source/api/python/dgl.dataloading.rst
> [Doc] remove deprected Node/EdgeDataLoader

- python/dgl/sparse/sddmm.py
> [Sparse] Fix sddmm docstring

- python/dgl/sparse/elementwise_op.py
- python/dgl/sparse/elementwise_op_diag.py
- python/dgl/sparse/elementwise_op_sp.py
- python/dgl/sparse/utils.py
- tests/pytorch/sparse/test_elementwise_op_diag.py
- tests/pytorch/sparse/test_elementwise_op_sp.py
> [Sparse] Make functions compatible with PyTorch scalar tensors

- docs/source/api/python/dgl.sparse_v0.rst
- python/dgl/sparse/matmul.py
- tests/pytorch/sparse/test_matmul.py
> [Sparse] Refactor matmul interface.

- python/dgl/sparse/elementwise_op.py
- python/dgl/sparse/elementwise_op_diag.py
- python/dgl/sparse/elementwise_op_sp.py
- tests/pytorch/sparse/test_elementwise_op_sp.py
> [Sparse] Support sparse matrix dividing scalar

- CMakeLists.txt
- benchmarks/scripts/build_dgl_asv.sh
- tests/scripts/build_dgl.sh
> enable dgl sparse build in default

- docs/source/conf.py
- docs/source/index.rst
- docs/source/notebooks/sparse/index.rst
- docs/source/notebooks/sparse/quickstart.nblink
- notebooks/sparse/quickstart.ipynb
* Added two new sphinx extensions: nbsphinx and nblink for rendering jupyter notebooks in sphinx.
* Added the first notebook under the `notebooks` folder.
Note:
* The colab link will not work until this PR is merged.
> [Doc] sparse lib tutorial and colab links

- python/dgl/sparse/diag_matrix.py
- python/dgl/sparse/sparse_matrix.py
> [Sparse] Polish diag_matrix.py and sparse_matrix.py.

- notebooks/sparse/quickstart.ipynb
Comment out pip install to pass doc build.
> [Doc] Update notebook

- python/dgl/sparse/sparse_matrix.py
> [Sparse] Polish the docstring of SparseMatrix.csr() and SparseMatrix.csc()

- notebooks/sparse/quickstart.ipynb
Currently our doc build server does not support GPU, so we only demo CPU for now.
> [Colab Example] Move to CPU instead of GPU.

- python/dgl/sparse/reduction.py
> [Sparse] Polish reduction.py.

- python/dgl/sparse/matmul.py
- python/dgl/sparse/sddmm.py
> [Sparse] polish strings of matmul.py and sddmm.py.

- python/dgl/sparse/softmax.py
>  [Sparse] Polish softmax.py.

- docs/source/notebooks/sparse/gcn.nblink
- docs/source/notebooks/sparse/hgnn.nblink
- docs/source/notebooks/sparse/index.rst
- notebooks/sparse/gcn.ipynb
- notebooks/sparse/graph_diffusion.ipynb
- notebooks/sparse/graph_transformer.ipynb
- notebooks/sparse/hgnn.ipynb
> [Doc] other colab tutorials

- tutorials/requirements.txt
> [Doc] fix NDArray.numpy() issue

- docs/source/conf.py
- tutorials/requirements.txt
> [Doc] ignore tutorial files for non-pytorch backend

- docs/source/conf.py
> [Doc] add include/exclude_patterns when build sphinx

- tutorials/blitz/1_introduction.py
- tutorials/blitz/2_dglgraph.py
- tutorials/blitz/3_message_passing.py
- tutorials/blitz/5_graph_classification.py
- tutorials/blitz/6_load_data.py
- tutorials/dist/1_node_classification.py
- tutorials/dist/2_link_prediction.py
- tutorials/large/L1_large_node_classification.py
- tutorials/large/L2_large_link_prediction.py
- tutorials/large/L4_message_passing.py
- tutorials/models/1_gnn/1_gcn.py
- tutorials/models/1_gnn/4_rgcn.py
- tutorials/models/1_gnn/6_line_graph.py
- tutorials/models/1_gnn/9_gat.py
- tutorials/models/2_small_graph/3_tree-lstm.py
- tutorials/models/3_generative_model/5_dgmg.py
- tutorials/models/4_old_wines/2_capsule.py
- tutorials/multi/1_graph_classification.py
- tutorials/multi/2_node_classification.py
> [Doc] specify backend as pytorch for tutorials

- python/dgl/sparse/reduction.py
> [Sparse] Update Doc of Reduce Operations

- docs/source/api/python/dgl.sparse_v0.rst
> Update dgl.sparse rst.

- python/dgl/sparse/diag_matrix.py
- python/dgl/sparse/elementwise_op.py
- python/dgl/sparse/sparse_matrix.py
> Change size to shape in print.

- python/dgl/sparse/sparse_matrix.py
> [Sparse] Polish the docstring of sparse_matrix.py

- python/dgl/sparse/sparse_matrix.py
> [Sparse] Add spmatrix creation function

- notebooks/sparse/gcn.ipynb
- notebooks/sparse/graph_diffusion.ipynb
- notebooks/sparse/hgnn.ipynb
> [Doc] fix math and link display issue

- python/dgl/sparse/diag_matrix.py
- python/dgl/sparse/sparse_matrix.py
> [Misc] Example -> Examples

- docs/source/api/python/dgl.sparse_v0.rst
> Update the canonical example for SparseMatrix.

- python/dgl/sparse/diag_matrix.py
- python/dgl/sparse/sparse_matrix.py
> Emphasize float32 and int32 in datatype.

- examples/sparse/appnp.py
- examples/sparse/c_and_s.py
- examples/sparse/gat.py
- examples/sparse/gcn.py
- examples/sparse/gcnii.py
- examples/sparse/graph_transformer.py
- examples/sparse/hgnn.py
- examples/sparse/hypergraphatt.py
- examples/sparse/sgc.py
- examples/sparse/sign.py
- examples/sparse/twirls.py
> Update example with spmatrix.

- python/dgl/sparse/elementwise_op.py
- python/dgl/sparse/elementwise_op_sp.py
- python/dgl/sparse/matmul.py
- python/dgl/sparse/reduction.py
- python/dgl/sparse/sddmm.py
- python/dgl/sparse/softmax.py
- python/dgl/sparse/sparse_matrix.py
- python/dgl/sparse/unary_op_sp.py
> [Doc] Update all canonical creation example from from_coo to spmatrix.

- python/dgl/sparse/diag_matrix.py
- python/dgl/sparse/matmul.py
- python/dgl/sparse/reduction.py
- python/dgl/sparse/softmax.py
- python/dgl/sparse/sparse_matrix.py
> [Doc] Update with Mono font to keep doc string consistent.

- python/dgl/sparse/sparse_matrix.py
> [Sparse] Swap examples of from_coo and spmatrix.

- docs/source/notebooks/sparse/index.rst
A brief introduction to unblock release.
> [Doc] Update sparse/index.rst

- python/dgl/dataloading/labor_sampler.py
fix display issue in https://docs.dgl.ai/en/latest/generated/dgl.dataloading.LaborSampler.html#laborsampler
> [Doc] fix docstring issue

- dgl_sparse/build.sh
- tensoradapter/pytorch/build.sh
> [Misc] Remove unnecessary clean up before build to accelerate incremental build.

- script/create_dev_conda_env.sh
- script/dgl_dev.yml.template
> [Dev] Create canonical dev conda environment.

- script/create_dev_conda_env.sh
> [Misc] Polish shell.

- script/build_dgl.sh
The script works the best under canonical conda environment.
> [Dev] Create a script for building dgl from source.

- .gitignore
> Ignore the dataset/ in git, which are automatically created when running pytest.

- python/dgl/distributed/dist_context.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/dist_tensor.py
- python/dgl/distributed/graph_partition_book.py
- python/dgl/distributed/graph_services.py
- python/dgl/distributed/id_map.py
- python/dgl/distributed/kvstore.py
- python/dgl/distributed/nn/pytorch/sparse_emb.py
- python/dgl/distributed/optim/pytorch/sparse_optim.py
- python/dgl/distributed/partition.py
- python/dgl/distributed/shared_mem_utils.py
- python/dgl/distributed/standalone_kvstore.py
> [Misc] Auto re-format distributed/.

- python/dgl/nn/mxnet/conv/chebconv.py
- python/dgl/nn/mxnet/conv/edgeconv.py
- python/dgl/nn/mxnet/conv/gatconv.py
- python/dgl/nn/mxnet/conv/gmmconv.py
- python/dgl/nn/mxnet/conv/graphconv.py
- python/dgl/nn/mxnet/conv/nnconv.py
- python/dgl/nn/mxnet/conv/sageconv.py
- python/dgl/nn/mxnet/conv/tagconv.py
- python/dgl/nn/pytorch/__init__.py
- python/dgl/nn/pytorch/conv/chebconv.py
- python/dgl/nn/pytorch/conv/dgnconv.py
- python/dgl/nn/pytorch/conv/dotgatconv.py
- python/dgl/nn/pytorch/conv/edgeconv.py
- python/dgl/nn/pytorch/conv/egatconv.py
- python/dgl/nn/pytorch/conv/gatconv.py
- python/dgl/nn/pytorch/conv/ginconv.py
- python/dgl/nn/pytorch/conv/gmmconv.py
- python/dgl/nn/pytorch/conv/graphconv.py
- python/dgl/nn/pytorch/conv/hgtconv.py
- python/dgl/nn/pytorch/conv/nnconv.py
- python/dgl/nn/pytorch/conv/sageconv.py
- python/dgl/nn/pytorch/conv/twirlsconv.py
- python/dgl/nn/pytorch/explain/gnnexplainer.py
- python/dgl/nn/pytorch/factory.py
- python/dgl/nn/pytorch/network_emb.py
- python/dgl/nn/pytorch/utils.py
- python/dgl/nn/tensorflow/conv/chebconv.py
- python/dgl/nn/tensorflow/conv/gatconv.py
- python/dgl/nn/tensorflow/conv/graphconv.py
- python/dgl/nn/tensorflow/conv/sageconv.py
> [Misc] Auto reformat nn/.

- tools/distpartitioning/data_shuffle.py
- tools/distpartitioning/dist_lookup.py
- tools/distpartitioning/parmetis_preprocess.py
> [Misc] auto-format tools.

- pytest_cugraph.xml
- tests/cugraph/test_basics.py
- tests/dist/python/rpc_basic.py
- tests/dist/python/run_dist_objects.py
- tests/dist/test_dist_objects.py
- tests/distributed/test_dist_graph_store.py
- tests/distributed/test_dist_tensor.py
- tests/distributed/test_distributed_sampling.py
- tests/distributed/test_mp_dataloader.py
- tests/distributed/test_new_kvstore.py
- tests/distributed/test_partition.py
- tests/distributed/test_rpc.py
- tests/distributed/utils.py
- tests/go/test_model.py
- tests/lint/lint.py
- tests/test_utils/graph_cases.py
- tests/tools/test_change_etype_to_canonical_etype.py
- tests/tools/test_dist_part.py
- tests/tools/test_parmetis.py
> [Misc] Auto-reformat test/.

- python/dgl/data/citation_graph.py
- python/dgl/data/csv_dataset.py
- python/dgl/data/csv_dataset_base.py
- python/dgl/data/gindt.py
- python/dgl/data/gnn_benchmark.py
- python/dgl/data/graph_serialize.py
- python/dgl/data/heterograph_serialize.py
- python/dgl/data/karate.py
- python/dgl/data/knowledge_graph.py
- python/dgl/data/qm7b.py
- python/dgl/data/qm9.py
- python/dgl/data/qm9_edge.py
- python/dgl/data/reddit.py
- python/dgl/data/tree.py
- python/dgl/data/tu.py
> [Misc] Auto reformat data/.

- script/dgl_dev.yml.template
> [CI] add boto3 to interactive with AWS services like batch

- python/dgl/dataloading/dataloader.py
- python/dgl/transforms/functional.py
- python/dgl/transforms/module.py
> [Misc] Auto format with manual fix of 3 files and add pylint: disable= too-many-lines for functional.py.

- python/dgl/mpops/edgewise.py
- python/dgl/ndarray.py
- python/dgl/ops/edge_softmax.py
- python/dgl/ops/sddmm.py
- python/dgl/ops/spmm.py
- python/dgl/partition.py
- python/dgl/propagate.py
- python/dgl/random.py
- python/dgl/readout.py
- python/dgl/sampling/labor.py
- python/dgl/sampling/negative.py
- python/dgl/sampling/neighbor.py
- python/dgl/sampling/node2vec_randomwalk.py
- python/dgl/sampling/pinsage.py
- python/dgl/sampling/randomwalks.py
- python/dgl/sampling/utils.py
- python/dgl/storages/numpy.py
- python/dgl/subgraph.py
- python/dgl/traversal.py
- python/dgl/utils/internal.py
- python/setup.py
- python/update_version.py
> [Misc] Autoformat python dgl (Part 2).

- python/dgl/dataloading/base.py
- python/dgl/dataloading/dist_dataloader.py
- python/dgl/dataloading/labor_sampler.py
- python/dgl/dataloading/neighbor_sampler.py
- python/dgl/dataloading/shadow.py
- python/dgl/function/message.py
- python/dgl/generators.py
- python/dgl/geometry/capi.py
- python/dgl/graph_index.py
- python/dgl/heterograph.py
- python/dgl/heterograph_index.py
> [Misc] Autoformat python dgl.

- tests/scripts/ci_report/status.py
> [Misc] Update Jenkins status.

- tests/scripts/ci_report/status.py
> [Misc] Revert jenkins update change and add build url in log.

- tests/scripts/ci_report/status.py
> [Misc] Print jenkins response for test.

- tests/scripts/ci_report/status.py
> [Misc] Add debug output to avoid silent failure.

- tests/scripts/ci_report/status.py
> [Misc] Revert status.py

- tests/scripts/ci_report/status.py
> [Misc] Fix status.py.

- Jenkinsfile
- tests/scripts/ci_report/status.py
> [Misc] Abort previous CI.

- Jenkinsfile
> [CI] use more light-weight node for lint check

- Jenkinsfile
> [Misc] All overrun on master CI.

- tests/scripts/ci_report/status.py
> [Misc] Treat aborted as failure in Jenkins.

- tests/scripts/ci_report/status.py
> [Misc] Fix typo in status.py

- tests/examples/test_sparse_examples.py
> [Sparse] Lower the accuracy requirement of test_twirls in test.

- dgl_sparse/include/sparse/sparse_format.h
- dgl_sparse/src/reduction.cc
- dgl_sparse/src/sparse_format.cc
- dgl_sparse/src/sparse_matrix.cc
- dgl_sparse/src/spspmm.cc
> [Sparse] Stack SparseMatrix COO row and column coordinates into one tensor

- dgl_sparse/include/sparse/softmax.h
- dgl_sparse/src/matmul.cc
- dgl_sparse/src/matmul.h
- dgl_sparse/src/softmax.cc
- python/dgl/sparse/softmax.py
- tests/python/pytorch/sparse/test_softmax.py
> [Sparse] Support column-wise softmax

- docs/source/api/python/dgl.rst
- python/dgl/__init__.py
- python/dgl/homophily.py
- tests/python/common/test_homophily.py
I'll implement the rest two measures once everyone is comfortable with the practice in this PR.
> [Utils] Node homophily measure

- script/create_dev_conda_env.sh
> [CI] add always_yes mode for conda evn creation

- script/create_dev_conda_env.sh
- script/dgl_dev.yml.template
Below features are added:
1. `dry_run`. we can run in dry mode which does not really create conda env.
2. `force_create`. If we have already created a conda env, `conda env create` fails due to existing env. `--force` should be appended then.
3. `output yaml`. Sometimes we'd like to save conda yaml into a specified file.
4. `python_version`. Sometimes we'd like to specify the python version for conda env.
> [CI] enable more options for conda env creation

- docs/source/guide/minibatch-edge.rst
- docs/source/guide_cn/minibatch-edge.rst
- docs/source/guide_ko/minibatch-edge.rst
> [Doc] Fix typos in minibatch-edge.rst

- .github/workflows/stale.yml
A better stale bot policy for open issues. First classify the labels into two groups:
* **Category labels**: bug:confirmed, bug:unconfirmed, feature request, help wanted, RFC, Work Item
* Any issues with those labels will be *exempted* from stale bot scanning except bug:unconfirmed which will remind the owner to further investigate the root cause.
* The "Work Item" label will be automatically added for all issues created from the Work Item issue template. This helps locate community issues more quickly.
* **Topic labels**: you can create as many as you want. They all start with "topic:", e.g., "topic: CI/CD"
* They are usually used as a secondary label to mark the topic of the issue, similar to the [XXX] prefix.
Recommended workflow:
* When triaging an issue, feel free to add any topic …
> [Misc] Update stale bot policy

- script/build_dgl.sh
Sometimes dev would like to add more cmake arguments.
> [Dev] Enable to append more cmake arguments for build

- python/dgl/nn/pytorch/sparse_emb.py
> [Misc] Follow up on the missing comment in PR#4989.

- python/dgl/dataloading/neighbor_sampler.py
> [Doc] Fix Typo in the Doc of MultiLayerFullNeighborSampler

- examples/pytorch/tgn/README.md
> [Example] Add a link about the removed TGN example

- include/dgl/aten/coo.h
> [Misc] Fix C++ comment style.

- Jenkinsfile
> Authorize daniil-sizov, itaraban to trigger CI.

- Jenkinsfile
> Add more ppl to CI trigger allowlist.

- python/dgl/distgnn/partition/libra_partition.py
- python/dgl/distgnn/tools/tools.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/dist_tensor.py
- python/dgl/distributed/graph_services.py
- python/dgl/distributed/nn/pytorch/sparse_emb.py
- python/dgl/distributed/partition.py
> [Misc] Rename number_of_edges and number_of_nodes to num_edges and num_nodes in dist related python files.

- python/dgl/data/citation_graph.py
- python/dgl/data/gindt.py
- python/dgl/data/gnn_benchmark.py
- python/dgl/data/heterograph_serialize.py
- python/dgl/data/knowledge_graph.py
- python/dgl/data/rdf.py
- python/dgl/data/reddit.py
- python/dgl/data/tu.py
- python/dgl/nn/mxnet/conv/appnpconv.py
- python/dgl/nn/mxnet/conv/gmmconv.py
- python/dgl/nn/mxnet/conv/sageconv.py
- python/dgl/nn/mxnet/hetero.py
- python/dgl/nn/mxnet/utils.py
- python/dgl/nn/pytorch/conv/appnpconv.py
- python/dgl/nn/pytorch/conv/atomicconv.py
- python/dgl/nn/pytorch/conv/ginconv.py
- python/dgl/nn/pytorch/conv/gmmconv.py
- python/dgl/nn/pytorch/conv/graphconv.py
- python/dgl/nn/pytorch/conv/sageconv.py
- python/dgl/nn/pytorch/conv/twirlsconv.py
- python/dgl/nn/pytorch/hetero.py
- python/dgl/nn/pytorch/sparse_emb.py
- python/dgl/nn/pytorch/utils.py
- python/dgl/nn/tensorflow/conv/appnpconv.py
- python/dgl/nn/tensorflow/conv/sageconv.py
- python/dgl/nn/tensorflow/hetero.py
> [Misc] Rename number_of_edges and number_of_nodes to num_edges and num_nodes.

- python/dgl/nn/pytorch/conv/gatconv.py
- tests/python/pytorch/nn/test_nn.py
related to issue #5459 
- add `edge_weight` parameter
- add test for `edge_weight` 
> [NN] add gatconv edge_weight

- docs/README.md
> [Doc] Update doc folder README

- docs/source/api/python/dgl.data.rst
- python/dgl/data/__init__.py
- python/dgl/data/geom_gcn.py
- tests/python/common/data/test_geom_gcn.py
> [Dataset] WisconsinDataset

- src/graph/transform/cuda/knn.cu
- tests/python/pytorch/geometry/test_geometry.py
Fix https://github.com/dmlc/dgl/issues/5448
- Fix unsync block threads of cuda kernel.
- Fix delete before last usage behavior of `num_block_prefixsum`
> [BugFix] Fix unstable behavior of beuteforce-sharemem KNN

- dgl_sparse/include/sparse/elementwise_op.h
- dgl_sparse/include/sparse/matrix_ops.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/matrix_ops.cc
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_matrix_coalesce.cc
- python/dgl/sparse/elementwise_op_sp.py
- tests/python/pytorch/sparse/test_elementwise_op.py
- tests/python/pytorch/sparse/test_elementwise_op_sp.py
- tests/python/pytorch/sparse/utils.py
Resolve #5368 . Support spspmul by concatenation and unique on two COO matrices.
> [Sparse] Support spspmul

- docs/source/install/index.rst
> [Misc] Update build from source doc to use the script in linux.

- docs/README.md
- script/build_doc.sh
- script/dgl_dev.yml.template
Following the discussion in #5495 
- Add a new script `script/build_doc.sh`
- Update the dev conda environment to include all the dependencies.
@frozenbugs Please help me test it locally.
P.S. Should we update the "install from source" section (https://docs.dgl.ai/install/index.html#install-from-source) ? 
P.S.S. Sometimes it is difficult to ask a contributor to build from source if they only modify the python part. Should consider a better setup.
> [Doc] Update script for building doc

- python/dgl/nn/pytorch/conv/egatconv.py
- tests/python/pytorch/nn/test_nn.py
related to issue #5459
add edge_weight parameter
add test for edge_weight
> [NN] add egatconv edge_weight

- dgl_sparse/include/sparse/elementwise_op.h
- dgl_sparse/include/sparse/sparse_format.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_format.cc
- python/dgl/sparse/elementwise_op_sp.py
- tests/python/pytorch/sparse/test_elementwise_op.py
- tests/python/pytorch/sparse/test_elementwise_op_sp.py
- tests/python/pytorch/sparse/test_softmax.py
> [Sparse] Support spspdiv

- docs/source/api/python/dgl.sparse_v0.rst
- python/dgl/sparse/__init__.py
- python/dgl/sparse/broadcast.py
- tests/python/pytorch/sparse/test_broadcast.py
> [Sparse] Support broadcasting operators

- docs/source/install/index.rst
Inspired by https://github.com/dmlc/dgl/issues/5558. Let's add it into doc page.
> [Doc] add how to build Cython extension

- examples/sparse/han.py
> [Example] Sparse Example for HAN

- python/dgl/dataloading/dataloader.py
cpu_affinity is not avalible on drawin. Refer to https://psutil.readthedocs.io/en/latest/index.html#psutil.Process.cpu_affinity. This fix may save 5 mininutes for macos users like me.
> [LOG] check whether cpu_affinity is avaible on the platform

- Jenkinsfile
> [CI] authorize more contibutors

- docs/source/contribute.rst
> [Doc] fix lint configuration path

- benchmarks/benchmarks/model_acc/bench_rgcn_base.py
- benchmarks/benchmarks/model_speed/bench_rgcn_base.py
> [benchmarks] fix torchmetrics accuracy

- src/array/cpu/spmm.h
Resolves https://github.com/dmlc/dgl/issues/5611
> [Fix] restore SpMMSumCsrNaive function for float and double

- CMakeLists.txt
- src/array/cpu/spmm_blocking_libxsmm.h
Resolves https://github.com/dmlc/dgl/issues/5610
> [Fix] fix libxsmm build issues on Mac OS

- notebooks/sparse/quickstart.ipynb
> Update tutorial cu116 -> cu118.

- notebooks/sparse/gcn.ipynb
- notebooks/sparse/graph_diffusion.ipynb
- notebooks/sparse/graph_transformer.ipynb
- notebooks/sparse/hgnn.ipynb
- notebooks/sparse/quickstart.ipynb
> Update comment from 11.6 to 11.8.

- notebooks/sparse/quickstart.ipynb
> Polish Tutorial

- python/dgl/nn/pytorch/conv/chebconv.py
- python/dgl/nn/tensorflow/conv/chebconv.py
Fix the performance issued mentioned in #5642 in PyTorch backend and TensorFlow backend.
It seems that MxNet backend uses a slightly different logic, thus that issue does not apply to it.
> [NN] Fix #5642

- docs/source/install/index.rst
Previously the instructions involve
```
mkdir build
cd build
```
hence we need `cd ../python`. This is no longer the case.
> [Doc] Update for building from source on Linux

- docs/source/api/python/nn-pytorch.rst
- python/dgl/nn/pytorch/conv/__init__.py
- python/dgl/nn/pytorch/conv/gatedgcnconv.py
- tests/python/pytorch/nn/conv/test_gatedgcnconv.py
- tests/python/pytorch/nn/test_nn.py
add GatedGCNConv
GatedGCN example: https://github.com/dmlc/dgl/pull/5570
> [NN] GatedGCNConv

- tools/distpartitioning/README.md
> [Doc] Make readme more readable for markdown

- python/dgl/__init__.py
- python/dgl/dataloading2/__init__.py
- python/dgl/dataloading2/itemset.py
- tests/python/pytorch/dataloading2/test_itemset.py
> [GraphBolt] add ItemSet

- examples/core/gat/README.md
- examples/core/gat/train.py
- examples/pytorch/gat/train.py
to be utilized for benchmark test
> [Benchmark] log train time and test accuracy, choose device

- src/array/cpu/spmm.h
Resolves https://github.com/dmlc/dgl/issues/5647
> [Misc] Disable BF16 LibXSMM SpMM for AVX2 platforms

- python/dgl/__init__.py
- python/dgl/dataloading2/__init__.py
- python/dgl/dataloading2/data_fetcher/base.py
- python/dgl/dataloading2/dataloader.py
- python/dgl/dataloading2/itemset.py
- python/dgl/dataloading2/minibatch_sampler/base.py
- python/dgl/dataloading2/negative_sampler/base.py
- python/dgl/dataloading2/subgraph_sampler/base.py
- tests/python/pytorch/dataloading2/test_itemset.py
> Merge Graphbolt to master

- graphbolt/CMakeLists.txt
- graphbolt/find_cmake.py
Add cmake file for graph bolt.
> [GraphBolt] Add cmake file

- graphbolt/include/csc_sampling_graph.h
> [GraphBolt] Fix lint

- graphbolt/include/csc_sampling_graph.h
- graphbolt/include/serialize.h
- graphbolt/include/utils.h
- graphbolt/src/csc_sampling_graph.cc
> [GraphBolt] enable load/save for CSCSamplingGraph

- graphbolt/include/csc_sampling_graph.h
- graphbolt/include/serialize.h
> [misc] fix the comment format.

- Jenkinsfile
- python/setup.py
Add missing part for install graphbolt and jkenkins config.
> [GraphBolt]CI patch

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/include/graphbolt/serialize.h
- graphbolt/src/csc_sampling_graph.cc
> [Graphbolt] Move headers to include/graphbolt & add include guard

- Jenkinsfile
> [Doc] Update Jenkinsfile

- graphbolt/src/csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
> [GraphBolt] add in_subgraph() API at the python level

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/include/graphbolt/shared_memory.h
- graphbolt/src/csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- graphbolt/src/shared_memory.cc
- graphbolt/src/shared_memory_utils.cc
- graphbolt/src/shared_memory_utils.h
One of the work items in #5690. <strike> This PR depends on #5737. Please review #5737 first. </strike>
> [Graphbolt] Read/write CSCSamplingGraph on shared memory.

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/csc_sampling_graph.cc
> [Misc] Add const reference for Tensor in FromCSC.

- tutorials/blitz/1_introduction.py
change the print format to f-strings.
> [DOC format]Update 1_introduction.py

- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
Resolve #5690. <strike> This PR depends on #5738. Please review #5738 first. </strike>
> [Graphbolt] Enable CSCSamplingGraph copy to/load from shared memory and add unittests in Python

- python/setup.py
Resolves https://github.com/dmlc/dgl/issues/5745. Can you try this? @chang-l 
> [Bugfix] Fix setup.py

- python/dgl/distributed/partition.py
DistDGL does not necessarily require `GraphBolt` for now, let's import it when necessary to fix #5753 
> [GraphBolt] import when necessary for DistDGL

- examples/distributed/graphsage/README.md
- examples/distributed/graphsage/node_classification.py
- examples/distributed/graphsage/partition_graph.py
migrated from `//examples/pytorch/graphsage/dist/train_dist.py`
> [Benchmark] relocate distributed node classification

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/include/graphbolt/serialize.h
- graphbolt/src/csc_sampling_graph.cc
- graphbolt/src/serialize.cc
- graphbolt/src/shared_memory_utils.cc
- graphbolt/src/shared_memory_utils.h
> [Graphbolt] Avoid transitive inclusion (include what you need)

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
Define API interface for graphbolt sampling.
>  [Graphbolt] Define API for Neighbor sampling

- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
> [Misc] Fix typo.

- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
A patch add checking between number of types and fanouts.
> [Graphbolt] Add fanout check

- Jenkinsfile
jingyu's first commit after get "write"
> [CI] authorize new contributor

- Jenkinsfile
> [Misc] Update Jenkins.

- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu_pip.txt
> [CI] install torchdadta in docker CI

- Jenkinsfile
- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu_pip.txt
> [CI] update CI docker images

- docs/source/install/index.rst
Modify the expression in "Install from source" part for Linux.
Line 63 and 69 in : docs/source/install/index.rst
> [doc] modify some expression in docs

- python/dgl/graphbolt/minibatch_sampler.py
- tests/python/pytorch/graphbolt/test_minibatch_sampler.py
> [GraphBolt] support DictItemSet in MinibatchSampler

- python/dgl/graphbolt/itemset.py
- python/dgl/graphbolt/minibatch_sampler.py
- tests/python/pytorch/graphbolt/test_itemset.py
- tests/python/pytorch/graphbolt/test_minibatch_sampler.py
> [GraphBolt] rename DictItemSet as ItemSetDict

- examples/pytorch/graphsage/dist/train_dist.py
> [Examples] fix lint

- docs/source/api/python/dgl.sparse_v0.rst
> [Doc] Cleanup DiagMatrix related definitions.

- python/dgl/graphbolt/itemset.py
- python/dgl/graphbolt/minibatch_sampler.py
following pytorch typing hint style.
> [GraphBolt] add typing hint for ItemSet/ItemSetDic/MinibatchSampler

- python/dgl/transforms/module.py
Correct an erroneous case for AddSelfLoop function.
Modify in file: dgl/python/dgl/transforms/module.py
> [CI] Fix a description bug for AddSelfLoop

- examples/pytorch/rgcn-hetero/test_classify.py
[fix]: ImportError: cannot import name 'AIFB'
Keep pace with other *.py in this dir, like `entity_classify_heteroAPI.py`,  `entity_classify_mb.py`, `entity_classify.py`.
> AIFB -> AIFBDataset

- examples/sampling/node_classification.py
> [Misc] Update the comment in examples/sampling/node_classification.py

- examples/core/graphsage/node_classification.py
- examples/pytorch/graphsage/train_full.py
1 Add highlights and flowchart for train_full.py.
2 Move train_full.py to examples/core/graphsage/node_classification.py.
3 Change some variable name in the forward function to make it more understandable.
4 Change the sting in print function to fstring.
5 Delete the dropout layer for input in the forward function.
> [CI] Add some notation for train_full.py and move it to a new directory

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/dgl/distributed/partition.py
- python/update_version.py
- tests/distributed/test_partition.py
DistDGL bug fix: https://github.com/dmlc/dgl/commit/1e886cb9cfd4cb1e5daf0534ceef69a252891d80
> [Release] cherry-pick DistDGL bug fixes and bump version

- tests/python/common/data/test_data.py
- tests/scripts/task_pytorch_tutorial_test.sh
- tutorials/large/L1_large_node_classification.py
- tutorials/large/L2_large_link_prediction.py
- tutorials/large/L4_message_passing.py
- tutorials/multi/2_node_classification.py
> [CI] Temmprarily skip ogb-related tests

- python/dgl/distributed/rpc.py
- python/dgl/distributed/rpc_client.py
- python/dgl/distributed/rpc_server.py
- src/rpc/network/socket_communicator.cc
- src/rpc/network/socket_communicator.h
- src/rpc/rpc.cc
> [TensorpipeDeprecation] remove unused arguments from wait_for_senders()

- python/dgl/nn/pytorch/gt/spatial_encoder.py
- script/create_dev_conda_env.sh
- tests/python/pytorch/nn/test_nn.py
Close the gap between SpatialEncoder3d implemented in DGL and original implementation for smooth weights remapping.
- change the graph format input to tensor format input. (the conversion will be handled by a special collator)
- update the offset of weights for scaling factors
> [NN] Refactor SpatialEncoder3d

- tests/tools/test_launch.py
- tools/launch.py
deprecate long live server which is a follow-ups of #5807 
> [TensorpipeDeprecation] remove long live server from launch

- graphbolt/src/csc_sampling_graph.cc
- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
Use binary search in neighbor sampling to accelerate the process of finding the boundary of each edge type.
> [Graphbolt] Use binary search in neighbor sample

- python/dgl/graphbolt/feature_store.py
- tests/python/pytorch/graphbolt/test_feature_store.py
> [Graphbolt] Support on-disk feature store.

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/dataset.py
- tests/python/pytorch/graphbolt/test_dataset.py
> [GraphBolt] add abstract Dataset

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/copy_to.py
- tests/python/pytorch/graphbolt/test_copy_to.py
> [GraphBolt] Datapipe for copying to given device

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/feature_fetcher.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [GraphBolt] Feature fetcher base datapipe

- python/dgl/graphbolt/feature_store.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_feature_store.py
> [Graphbolt] Remove keys in feature store.

- tests/python/common/data/test_data.py
- tutorials/large/L1_large_node_classification.py
- tutorials/large/L2_large_link_prediction.py
- tutorials/large/L4_message_passing.py
- tutorials/multi/2_node_classification.py
Reverts dmlc/dgl#5907 as ogb server is up.
> Revert "[CI] Temmprarily skip ogb-related tests"

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/dataloader.py
- tests/python/pytorch/graphbolt/test_single_process_dataloader.py
> [GraphBolt] Add single process dataloader and ux

- graphbolt/src/csc_sampling_graph.cc
- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
Fix bug in `sample_neighbors` assert for fanout length.
> [Graphbolt] Fix asseration bug

- Jenkinsfile
> [CI] disable distributed test stage

- python/dgl/graphbolt/feature_store.py
- tests/python/pytorch/graphbolt/test_feature_store.py
> [Graphbolt] Add load_feature_stores

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
> [GraphBolt] init feature data for Dataset

- Jenkinsfile
> [Misc] increase timeout for Win unittest to 50 mins.

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
> [GraphBolt] init graph topology

- examples/core/Graphormer/main.py
- examples/core/Graphormer/model.py
> [Misc] Remove redundant blank line.

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/test_dataset.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
> [GraphBolt] add misc metadata for Dataset

- python/dgl/graphbolt/impl/ondisk_dataset.py
> [GraphBolt] call preprocess function first when init OnDiskDataset

- script/create_dev_conda_env.sh
> [Dev] upgrade pytorch/cuda/python version in dev conda env

- Jenkinsfile
- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_gpu
- docker/install/conda_env/torch_cpu.yml
- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu.yml
- docker/install/conda_env/torch_gpu_pip.txt
> [CI]upgrade pytorch to 1.13+cpu_cu116

- Jenkinsfile
> Add mfbalin to Jenkins.

- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
> [Graphbolt] Fix docstring

- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
> [Graphbolt] Add exclude_edges impl and unittest.

- tests/scripts/task_distributed_test.sh
- tests/scripts/task_unit_test.bat
- tests/scripts/task_unit_test.sh
> [Misc] Use old pydantic yaml version for CI.

- graphbolt/src/csc_sampling_graph.cc
> [Misc] Simplify the comment.

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- script/dgl_dev.yml.template
- tests/python/common/data/test_data.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
- tests/scripts/task_distributed_test.sh
- tests/scripts/task_unit_test.bat
- tests/scripts/task_unit_test.sh
fix for https://github.com/dmlc/dgl/issues/6010.
> [GraphBolt] remove pydantic_yaml from dependency

- python/dgl/graphbolt/impl/ondisk_dataset.py
Let the function return a raw `str` type instead of `pathlib.Path`.
> [Graphbolt] Modify `preprocess_ondisk_dataset` function.

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
> [Graphbolt] change dataset method to property.

- graphbolt/src/csc_sampling_graph.cc
> [Misc] Polish the graphbolt code for labor sampling.

- python/dgl/graphbolt/minibatch_sampler.py
> [Graphbolt] Use dynamic buffer size for shuffle.

- python/dgl/batch.py
This is a quick pull fixing the batch index erros in the document. 
All +1 index in the document of batch.py are removed.
Fix https://github.com/dmlc/dgl/issues/6012
> [Doc] Correct batch index in batch.py

- python/dgl/heterograph_index.py
- python/dgl/subgraph.py
- src/array/libra_partition.cc
- src/graph/heterograph_capi.cc
- src/graph/sampler.cc
Fix build warnings of cpp code.
- [*] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [*] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [*] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [*] All changes have test coverage
- [*] Code is well-documented
- [*] To the best of my knowledge, examples are either not affected by this …
> [misc] Fix build warnings

- python/dgl/nn/pytorch/conv/gcn2conv.py
Follow up of https://github.com/dmlc/dgl/pull/6020
> [Misc] Further polish gcn2conv.py

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/data_format.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
> [Misc] Update variable names.

- python/dgl/graphbolt/negative_sampler.py
> [Misc] Add not-implemented error for api.

- examples/pytorch/model_zoo/citation_network/run.py
- examples/pytorch/pagerank.py
In the current PR we eliminate the following warning:
```
/usr/local/lib/python3.10/dist-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
```
> Improving the PAGERANK example.

- examples/pytorch/dimenet/qm9.py
- examples/pytorch/gas/dataloader.py
- python/dgl/data/bitcoinotc.py
- python/dgl/data/citation_graph.py
- python/dgl/data/fakenews.py
- python/dgl/data/gdelt.py
- python/dgl/data/gindt.py
- python/dgl/data/knowledge_graph.py
- python/dgl/data/pattern.py
- python/dgl/data/ppi.py
- python/dgl/data/qm9_edge.py
- python/dgl/data/sbm.py
- python/dgl/data/tree.py
- python/dgl/data/tu.py
- python/dgl/data/utils.py
- python/dgl/data/zinc.py
1 The assignment of data path name of different datasets are duplicated, and it may be easy to misspelled and may be missed somewhere when changing it.
- [.] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [.] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [.] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [.] All changes have …
> [Misc] Simplify the data path's assignment in python utils

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/test_dataset.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
most of the change is renaming and indent change.
> [GraphBolt] convert TVT from list of list to list

- examples/sparse/pagerank.py
> [Sparse] Add page rank example to DGL sparse Api.

- docs/source/api/python/dgl.sparse_v0.rst
> [Sparse] Add  SparseMatrix.indices in docs.

- dglgo/setup.py
- python/dgl/__init__.py
- python/setup.py
> [dev] remove distutils from dependency

- docs/source/install/index.rst
> [doc] remove --inplace

- docs/source/contribute.rst
- tests/scripts/build_dgl.sh
> [Misc] clean up remove --inplace.

- docs/source/contribute.rst
- tests/scripts/build_dgl.sh
> Revert "[Misc] clean up remove --inplace."

- docs/source/install/index.rst
> Revert "[doc] remove --inplace"

- Jenkinsfile
The first simple pr from intern.
Modify the Jenkinsfile file
> Add new intern

- cmake/util/Util.cmake
> [Misc] Add comment to clarify __dgl_option.

- examples/core/rgcn/hetero_rgcn.py
I've noticed that we lack examples related to heterogeneous graphs, which are often make user confused. I am working on refining a classic heterograph-related model example to address this gap.
This PR try to address this [Issue:Polish and move the follow hetero example as core dgl example. ](https://github.com/dmlc/dgl/issues/6047)
> [Example] polish the example for heterograph node classification

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_feature_store.py
- tests/python/pytorch/graphbolt/test_multi_process_dataloader.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_single_process_dataloader.py
> [GraphBolt] refactor FeatureStore and related impl

- tests/examples/test_sparse_examples.py
> [Misc] Lower the test threshold for hgnn example.

- graphbolt/src/csc_sampling_graph.cc
- python/dgl/graphbolt/impl/csc_sampling_graph.py
> [Graphbolt] Modify labor to fix inconsistencies

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] bump version to 1.1.2

- README.md
> [Doc] Update README about DGL container access from NGC

- tests/cpp/common.h
- tests/cpp/test_smart_ptr_serialize.cc
- tests/cpp/test_spmat_coo.cc
- tests/cpp/test_spmat_csr.cc
> [Misc] Small fix of cpp tests

- CMakeLists.txt
- cmake/modules/CUDA.cmake
- python/setup.py
Changing CXX standard to 17 hoping that issues similar to #6135 will be resolved.
> [Dev] Change CXX standard to 17

- CMakeLists.txt
- src/array/cuda/csr2coo.cu
This reverts commit a72284d0b4be39908e5508a55459fcafabbdeb8a.
> [release] 1.1.x revert #5648

- CMakeLists.txt
- cmake/modules/CUDA.cmake
- python/setup.py
> [Dev] Change CXX standard to 17 (#6138)

- script/build_dgl.sh
> [Misc] Support build type in build dgl script.

- tests/python/common/sampling/test_sampling.py
Suppressing the following warnings in `sampling/test_sampling.py::test_global_uniform_negative_sampling` tests:
```
tests/python/common/sampling/test_sampling.py::test_global_uniform_negative_sampling[int32]
tests/python/common/sampling/test_sampling.py::test_global_uniform_negative_sampling[int64]
/usr/local/lib/python3.10/dist-packages/dgl/sampling/negative.py:110: ComplexWarning: Casting complex values to real discards the imaginary part
src, dst = _CAPI_DGLGlobalUniformNegativeSampling(
```
> Improving sampling tests.

- examples/sampling/link_prediction.py
Polishing the GraphSAGE version link prediction example. I've highlighted the code related to sampling.
The training log is as follows:
```                                                                
Training in cpu mode.                                                                  
Loading data                                                                           
Training...                                                                                                                                               
Epoch 00000 | Loss 141.1809                                                            
Epoch 00001 | Loss 99.6935                                                             
Epoch 00002 | Loss 91.5208 …
```
> [Example] Polish GraphSAGE link prediction example and move it to sampling folder.

- src/runtime/workspace_pool.cc
> [Misc] re-enable destructor method of WorkspacePool.

- Jenkinsfile
> [CI] add more nodes for linux jobs

- Jenkinsfile
> [CI] add 4 new windows nodes

- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
A patch for fix negative sampler bugs when input is hetero
> [Graohbolt] Fix negative sampler hetero bugs

- python/dgl/nn/pytorch/conv/gcn2conv.py
- tests/python/pytorch/nn/test_nn.py
> [BugFix] remove non-existent arg

- examples/sparse/hetero-rgcn.py
Remove two datasets from example as suggested.
> [Sparse] Fix hetero-rgcn example datasets

- examples/core/rgcn/hetero_rgcn.py
> [Example] Fix core hetero-rgcn example API name.

- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
> [Misc] Better naming.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/__init__.py
- python/dgl/graphbolt/impl/basic_feature_store.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
> [Graphbolt] Add BasicFeatureStore.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
> [Misc] Always use subgraph instead of sub_graph.

- tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
> [Graphbolt] Update unit test to match the official edge format.

- python/dgl/graphbolt/data_block.py
- python/dgl/graphbolt/feature_fetcher.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_multi_process_dataloader.py
- tests/python/pytorch/graphbolt/test_single_process_dataloader.py
> [Graphbolt] Add feature fetcher udf

- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [Graohbolt] Fix  CI bug

- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/utils/__init__.py
- python/dgl/graphbolt/utils/datapipe_utils.py
> [GraphBolt] relocate utils

- script/build_dgl.sh
> [Misc] Also remove build fold in graphbolt and dgl_sparse in build_dgl.sh.

- script/build_dgl.sh
> [dev] remove buid dir of tensoradaptor

- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/sampled_subgraph.py
- python/dgl/graphbolt/utils/sample_utils.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] use str etype in graphs

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_itemset.py
added `Names` will be used to instantiate `MiniBatch`(previously called `DataBlock`).
> [GraphBolt] add names for each item in ItemSet

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/item_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
- tests/python/pytorch/graphbolt/test_multi_process_dataloader.py
- tests/python/pytorch/graphbolt/test_single_process_dataloader.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] rename MinibatchSampler as ItemSampler

- python/dgl/graphbolt/itemset.py
> [GraphBolt] update docstring of ItemSet

- tests/python/pytorch/graphbolt/test_itemset.py
> [GraphBolt] update tests of ItemSet to cover canonical cases

- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/negative_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
This PR is mainly rename data attributes. Related docstring and testcases will be updated in following PRs.
> [GraphBolt] rename data attributes in MiniBatch

- python/dgl/graphbolt/minibatch.py
> [Misc] Reorder the variables in minibatch.py.

- python/dgl/graphbolt/item_sampler.py
avoid below warning message:
```
/home/ubuntu/anaconda3/envs/dgl-dev-cpu-dgl-2/lib/python3.10/site-packages/torch/utils/data/datapipes/utils/common.py:137: UserWarning: Local function is not supported by pickle, please use regular python function or functools.partial instead.
```
[dill](https://dill.readthedocs.io/en/latest/) could be an option in the future.
> [GraphBolt] avoid warning of pickle local function

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] update names of ItemSet in OnDiskDataset testcases

- docs/source/api/python/dgl.graphbolt.rst
- docs/source/index.rst
> [Graphbolt] Introduce graphbolt doc.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_multi_process_dataloader.py
- tests/python/pytorch/graphbolt/test_single_process_dataloader.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] clean up minibatch collator in testcases and docstring

- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
> [GraphBolt] remove print() from test case

- CMakeLists.txt
> [dev] 17 is new since cmake3.8 for CXX_STANDARD

- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] fix test cases about datapipe

- python/dgl/graphbolt/feature_fetcher.py
> [GraphBolt] replace Datablock by MiniBatch

- docs/source/api/python/dgl.graphbolt.rst
> [Graphbolt] Add more class and ops to graphbolt doc.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] enable fanouts to be a list of int

- python/dgl/graphbolt/impl/neighbor_sampler.py
Swap reverse row and column mapping for fixing.
> [Graphbolt] Fix sample bugs

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
> [GraphBolt] fix type_per_edge

- examples/sampling/graphbolt/link_prediction.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [Graphbolt] Reorder the parameters of UniformNegativeSampler.

- python/dgl/graphbolt/impl/neighbor_sampler.py
> [Graphbolt]Fix docstring example

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
> [GraphBolt] skip empty mask

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] enable to download built-in dataset from s3

- Jenkinsfile
> add name to Jenkinsfile

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] enrich node types for input/output nodes of sampled subgraph

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] add available builtin datasets into docstring

- docs/source/api/python/dgl.graphbolt.rst
- python/dgl/graphbolt/impl/ondisk_dataset.py
> [GraphBolt] add BuiltinDataset into doc page

- python/dgl/graphbolt/item_sampler.py
> [GraphBolt] remove func decorator from ItemSampler

- python/dgl/graphbolt/item_sampler.py
> [Misc] Remove unused import.

- examples/graphbolt/rgcn/README.md
- examples/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] add example of heterograph node classification

- examples/sampling/graphbolt/link_prediction.py
- graphbolt/include/graphbolt/sampled_subgraph.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
Replace reverse with original.
> [Graphbolt] Replace reverse with original

- python/dgl/graphbolt/impl/ondisk_dataset.py
> [GraphBolt] add ogb-lsc-mag240m into BuiltinDataset

- examples/sampling/graphbolt/rgcn/README.md
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] enable training on ogb-lsc-mag240m

- examples/sampling/graphbolt/node_classification.py
A draft for GraphBolt node-classification example.
> [GraphBolt] GraphBolt Node Classification Example

- examples/sampling/graphbolt/rgcn/README.md
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] enable gpu train for ogbn-mag

- examples/multigpu/node_classification_sage.py
> [Example] Fix label dtype error in multigpu node classification.

- python/dgl/graphbolt/impl/ondisk_dataset.py
Update the `BuiltinDataset`:`ogbl-citation2` and subsequently update the docstring of the `BuiltinDataset` class.
> [Graphbolt] Udpate the ogbl-citation2 dataset docstring

- examples/sampling/graphbolt/rgcn/README.md
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] enable gpu train on ogb-lsc-mag240m

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [Graphbolt] Rename num_nodes and num_edges.

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
To dgl used to converting a minibatch to a dgl minbatch used for computing.
> [Graphbolt] Add to dgl

- script/run_pytest.sh
> [Misc] Add graphbolt dir for test script.

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] update URL for ogb-lsc-mag240m

- python/dgl/graphbolt/sampling_graph.py
Create `SamplingGraph` class which is designed to be the base class of `CSCSamplingGraph`, as well as the declarations of a few APIs.
> [Misc] Create SamplingGraph Class

- examples/sampling/graphbolt/rgcn/README.md
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] disable full neighbor sampling in reference stage for hetero rgcn example

- examples/core/rgcn/README.md
- examples/core/rgcn/hetero_rgcn.py
> [Examples] enable train on ogb-lsc-mag240m

- CONTRIBUTORS.md
- examples/sampling/graphbolt/link_prediction.py
> [Graphbolt] Fix link_prediction example

- python/dgl/backend/pytorch/tensor.py
As we have already enabled this in recent release, let's update here accordingly.
> [dev] update minimum pytorch version to 1.13.0

- docs/source/api/python/dgl.graphbolt.rst
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/itemset.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/minibatch_transformer.py
- python/dgl/graphbolt/negative_sampler.py
- python/dgl/graphbolt/sampled_subgraph.py
- python/dgl/graphbolt/sampling_graph.py
- python/dgl/graphbolt/subgraph_sampler.py
> [GraphBolt][Doc] update top level APIs

- docs/source/api/python/dgl.graphbolt.rst
- python/dgl/graphbolt/impl/basic_feature_store.py
- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
> [GraphBolt][Doc] update impl

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
Improve DGLMiniBatch repr layout for better legibility. The output has changed from one row to one line per attribute in DGLMiniBatch Class.
Previous Output:
```
DGLMiniBatch(blocks=[Block(num_src_nodes=6, num_dst_nodes=6, num_edges=5), Block(num_src_nodes=6, num_dst_nodes=6, num_edges=5)], input_nodes=tensor([5, 3, 1, 2, 0, 4]), output_nodes=None, node_features={'feat': tensor([[0.5160, 0.2486],
[0.8672, 0.2276],
[0.6172, 0.7865],
[0.2109, 0.1089],
[0.9634, 0.2294],
[0.5503, 0.8223]])}, edge_features=[{}, {}], labels=None, positive_node_pairs=(tensor([0, 1, 1, 1]), tensor([2, 3, 3, 1])), negative_node_pairs=(tensor([0, 1, 1, 1]), tensor([0, 3, 4, 5])))
```
Improved Output:
```
DGLMiniBatch(positive_node_pairs=(tensor([0, 1, 1, 1]), tensor([2, 3, 3, 1])),
output_nodes=None, …
```
> [GraphBolt] modify DGLMiniBatch layout.

- python/dgl/data/lrgb.py
Split https://github.com/dmlc/dgl/pull/6407 into update docstring and add COCO-SP dataset
Related issue: https://github.com/dmlc/dgl/issues/5352
> [Dataset] update docstring of LRGB

- python/dgl/graphbolt/impl/neighbor_sampler.py
> [GraphBolt] Fix intent bug of class LayerNeighborSampler DOC

- python/dgl/graphbolt/impl/neighbor_sampler.py
> [Graphbolt] Pass down the original eid.

- notebooks/graphbolt/walkthrough.ipynb
> [Graphbolt] Update walkthrough Tutorial.

- python/dgl/graphbolt/impl/neighbor_sampler.py
> [Misc] Rename the variables  in NeighborSampler for better readability.

- examples/sampling/graphbolt/link_prediction.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
> [Graphbolt] Fix fanout order

- examples/sampling/graphbolt/link_prediction.py
> [Misc] Revert un-related change in #6447.

- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
- tests/python/pytorch/graphbolt/test_itemset.py
> [GraphBolt] enable slice for integer-init ItemSet

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
> [GraphBolt] enable indexing for ItemSetDict

- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] fix feat_size fetch issue

- examples/sampling/graphbolt/rgcn/README.md
> [GraphBolt] update statistics with indexing enabled ItemSampler

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
Added `to` for CSCSamplingGraph to support copying to devices.
- Added setter for tensor attributes of CSCSamplingGraph.
- Implemented `to`.
- Added a unit test
> [GraphBolt] Add to function for CSCSamplingGraph

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] call from_csc with explicit key word arguments

- examples/sampling/graphbolt/node_classification.py
Run result:
```
$ python examples/sampling/graphbolt/node_classification.py --device=cuda
Training in cuda mode.
Loading data...
Downloading datasets/ogbn-products.zip from https://data.dgl.ai/dataset/graphbolt/ogbn-products.zip...
Extracting file to datasets
Training...
769it [01:14, 10.35it/s]
154it [00:13, 11.72it/s]
Epoch 00000 | Loss 1.6310 | Accuracy 0.8345 
769it [01:14, 10.31it/s]
154it [00:13, 11.50it/s]
Epoch 00001 | Loss 0.7233 | Accuracy 0.8627 
769it [01:14, 10.26it/s]
154it [00:13, 11.78it/s]
Epoch 00002 | Loss 0.5852 | Accuracy 0.8727 
769it [01:14, 10.32it/s]
154it [00:13, 11.77it/s]
Epoch 00003 | Loss 0.5295 | Accuracy 0.8805 
769it [01:14, 10.33it/s]
154it [00:13, 11.63it/s]
Epoch 00004 | Loss 0.4934 | Accuracy 0.8844 
769it [01:14, …
```
> [GraphBolt] Enable `node_classification.py` to run on GPU environment

- examples/sampling/graphbolt/node_classification.py
> [Misc] Avoid using Literal which requires python 3.8.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
> [Graphbolt] Add pin_memory_() support for TorrchBasedFeatureStore.

- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Modify random hetero graph generation in tests to ensure that the random graph generated through this function can be used to create a sampled subgraph correctly.
> [GraphBolt] Modify random hetero graph generation in tests.

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
> [Misc] polish the python code

- examples/sampling/graphbolt/node_classification.py
Modify the output of each epoch in order to do benchmark.
```
Training...
769it [01:12, 10.65it/s]
154it [00:12, 12.42it/s]
Epoch 00000 | Loss 1.7226 | Accuracy 0.8313 | Time 72.2404
769it [01:12, 10.64it/s]
154it [00:12, 12.12it/s]
Epoch 00001 | Loss 0.7344 | Accuracy 0.8626 | Time 72.2532
```
> [GraphBolt] Modify `node_classification` for benchmark

- script/dgl_dev.yml.template
> [Misc] Add cmake to dev conda requirement.

- examples/sampling/graphbolt/node_classification.py
- examples/sampling/node_classification.py
Modify `examples/sampling/graphbolt/node_classification.py` and `examples/sampling/node_classification.py` to make their output consistent, facilitating benchmark.
> [Misc] Modify two examples to make them consistent

- python/dgl/graphbolt/impl/ondisk_dataset.py
> [Graphbolt] Add cora to graphbolt builtin dataset.

- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
Modified multigpu node-classification example and dataset docstring.
> [Misc] Change node features type of ogbn-products to float32

- examples/sampling/graphbolt/quickstart/node_classification.py
> [Polish] Cleanup unnecessary local variable.

- script/dgl_dev.yml.template
> [Misc] Add torcheval to dgl dev conda env.

- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] add testcase for multiple tasks in OnDiskDataset

- Jenkinsfile
- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu_pip.txt
> [CI] add torcheval into CI docker

- examples/sampling/graphbolt/quickstart/node_classification.py
> [Graphbolt] Polish the quickstart node classification tasks.

- docs/source/api/python/dgl.graphbolt.rst
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/include/graphbolt/serialize.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- graphbolt/src/serialize.cc
- notebooks/graphbolt/walkthrough.ipynb
- python/dgl/distributed/partition.py
- python/dgl/graphbolt/impl/__init__.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- tests/distributed/test_partition.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_integration.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Since we will subsequently add a new class, `(non-fused)CSCSamplingGraph`, it would be better to refactor the current `CSCSamplingGraph` and its associated methods to facilitate the addition of the upcoming features.
However, two issues need to be addressed:
> [GraphBolt] Refactor CSCSamplingGraph and update the corresponding method.

- graphbolt/src/cuda/index_select_impl.cu
- graphbolt/src/cuda/utils.h
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
This PR copies the kernel optimizations from https://github.com/dmlc/dgl/blob/master/src/array/cuda/uvm/array_index_select_uvm.cu.
> [Graphbolt] Enable cuda optimizations for UVAIndexSelect.

- python/dgl/graphbolt/dataloader.py
Add default prefetcher login in dataloader. 
> [Graphbolt] Add default prefetcher

- docs/source/api/python/dgl.graphbolt.rst
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/include/graphbolt/fused_sampled_subgraph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
Refactor the `SampledSubgraph` to `FusedSampledSubgraph`.
> [GraphBolt] Refactor SampledSubgraph and update the corresponding method.

- examples/sampling/graphbolt/quickstart/node_classification.py
> [Misc] Cleanup example.

- tests/examples/test_sampling_examples.py
> [Misc] Lower the threshold to avoid accidental failing.

- examples/pytorch/bgnn/BGNN.py
- examples/pytorch/gas/dataloader.py
- examples/pytorch/ogb/cluster-gat/sampler.py
- examples/pytorch/ogb/cluster-sage/sampler.py
Related Issue #6539 
Fix bugs of deprecated variables in numpy.
1. np.float -> np.cfloat
2. np.bool -> np.bool_
Fix bugs of invalid list to np _array. In the example, the requested array has an inhomogeneous shape after 1 dimensions. So, precreate a NumPy array of object types so that the elements of the list can be of different lengths.
> [Examples] Fix bugs of numpy in examples.

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
Polish several comments in python code.
> [Misc] Update comments in python code

- examples/mxnet/scenegraph/train_freq_prior.py
- examples/pytorch/bgrl/eval_function.py
- examples/pytorch/dimenet/qm9.py
- examples/pytorch/grace/eval.py
- examples/pytorch/graphsaint/utils.py
- examples/pytorch/model_zoo/geometric/coarsening.py
- examples/pytorch/ogb/cluster-gat/main.py
- examples/pytorch/pinsage/data_utils.py
Issue #6539 
Change np.bool to np.bool_.
> [Example] Fix numpy errors in examples.

- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [GraphBolt] fix incorrect call in example

- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] add end2end tests for OnDiskDataset

- examples/sampling/graphbolt/quickstart/link_prediction.py
- tests/examples/test_sampling_examples.py
Training...
Epoch 000 | Loss 0.613
Epoch 001 | Loss 0.422
Epoch 002 | Loss 0.349
Epoch 003 | Loss 0.320
Epoch 004 | Loss 0.295
Epoch 005 | Loss 0.289
Epoch 006 | Loss 0.272
Epoch 007 | Loss 0.257
Epoch 008 | Loss 0.245
Epoch 009 | Loss 0.223
Testing...
AUC: 0.964
> [Graphbolt] Link prediction cora example.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/basic_feature_store.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
> [Graphbolt] Support feature metadata.

- examples/sparse/sampling/graphsage.py
Fix variable name as suggested.
> [Sparse] Fix example variable name

- python/dgl/graphbolt/impl/ondisk_dataset.py
> [GraphBolt] add BuiltinDataset of ogbn-arxiv

- tutorials/cpu/cpu_best_practises.py
> [doc] update cpu_best_practices

- python/dgl/dataloading/shadow.py
Fix typo in ShaDowKHopSampler sample() function parameter description.
> [Doc] Fix typo in ShaDowKHopSampler

- docs/source/graphbolt/ondisk-dataset.rst
- python/dgl/graphbolt/impl/ondisk_metadata.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] enable metadata for feature data in OnDiskDataset

- tutorials/large/L1_large_node_classification.py
> [Doc] update large node classification

- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/minibatch_transformer.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [Graphbolt] Add MiniBatchBase

- graphbolt/src/fused_csc_sampling_graph.cc
wrapped with extra `AT_DISPATCH_INTEGRAL_TYPES`.
> [GraphBolt] replace item<> with raw pointer

- tutorials/large/L2_large_link_prediction.py
> [GraphBolt][Doc] update link prediction

- python/dgl/graphbolt/impl/ondisk_metadata.py
> [GraphBolt] fix bug in pydantic 1.x

- tutorials/large/L0_neighbor_sampling_overview.py
- tutorials/large/L1_large_node_classification.py
- tutorials/large/L2_large_link_prediction.py
> [doc] rename titles

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/link_prediction.py
> [Benchmark] Align the DGL/Graphbolt link pred examples

- docs/source/index.rst
- docs/source/notebooks/stochastic_training/index.rst
- docs/source/notebooks/stochastic_training/node_classification.nblink
- notebooks/stochastic_training/node_classifcation.ipynb
- notebooks/stochastic_training/node_classification.ipynb
> [doc] add NC notebook for stochastic training

- docs/source/notebooks/stochastic_training/index.rst
- docs/source/notebooks/stochastic_training/link_prediction.nblink
- notebooks/stochastic_training/link_prediction.ipynb
> [doc] add lp notebook for stochastic training

- notebooks/stochastic_training/node_classification.ipynb
> [doc] do not save model in tutorial

- docs/source/notebooks/stochastic_training/index.rst
- docs/source/notebooks/stochastic_training/neighbor_sampling_overview.nblink
- notebooks/stochastic_training/neighbor_sampling_overview.ipynb
> [doc] add notebook for neighbor sampling overview

- tutorials/large/README.txt
> [doc] mark some docs as deprecated

- tests/integration/test_data.py
- tests/python/common/data/test_data.py
> [Misc] Move dataset_tests to an independent directory.

- examples/sampling/link_prediction.py
> [Benchmark] Fix bugs in the DGL link prediction example.

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
Modify `to_dgl` to support Sampled Subgraph Impl (csc formats).
> [GraphBolt] Modify `to_dgl` to support Sampled Subgraph Impl (csc formats)

- docs/source/_templates/graphbolt_classtemplate.rst
> [doc] sort api members in groupwise

- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/internal/utils.py
- python/dgl/graphbolt/minibatch.py
Move `get_attributes` function to internal.
> [GraphBolt] Move `get_attributes` function to internal.

- docs/source/guide/minibatch-edge.rst
> [doc] update edge classification chapter

- tutorials/multi/1_graph_classification.py
- tutorials/multi/2_node_classification.py
> [doc] add multi-gpu node classification tutorial

- tutorials/multi/1_graph_classification.py
- tutorials/multi/2_node_classification.py
> [doc] fix doc build issue

- docs/source/guide/minibatch-node.rst
> [doc] update user_guide/minibatch/node_classification

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> change version to 1.1.3

- docs/source/guide/minibatch-link.rst
> [doc] update minibatch link prediction

- python/dgl/graphbolt/subgraph_sampler.py
> [doc] add docstring for SubgraphSampler::_sample_subgraphs()

- graphbolt/CMakeLists.txt
> [Graphbolt][CUDA] Add third_party thrust and cub dependency

- docs/source/guide/minibatch-inference.rst
> [doc] update user guide 6.6

- docs/source/guide/minibatch-gpu-sampling.rst
> [doc] update user guide 6.7

- notebooks/graphbolt/walkthrough.ipynb
> [doc] fix device issue

- graphbolt/src/cuda/common.h
> [Graphbolt][CUDA] Simplify allocator class by discarding tensors

- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
Modify `exclude_edges` to support csc format.
|   | node_pair | original method | torch method |
|----|-----|-----|----|
| time(us) | 159957 | 185396196 | 178088 |
> [GraphBolt] Modify `exclude_edges` to support csc format.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
Add option to select node_pairs or csc_format.
> [GraphBolt] Add option to select node_pairs or csc_format.

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/distributed/partition.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/distributed/test_partition.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] add ntype/etype_to_id into graph and save/load()

- examples/sampling/graphbolt/sparse/graphsage.py
Embed sparse sampling in graphbolt.
> [Sparse] Polish sparse example for graphbolt

- python/dgl/graphbolt/impl/neighbor_sampler.py
> [GraphBolt] Add opt to LayerNeighborSampler.

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
> [GraphBolt] support node/edge_type_to_id in shared memory

- python/dgl/graphbolt/impl/__init__.py
- python/dgl/graphbolt/impl/dgl_dataset.py
- python/dgl/graphbolt/impl/legacy_dataset.py
- tests/python/pytorch/graphbolt/impl/test_legacy_dataset.py
Tested: RedditDataset, cora, ogbn-mag, ogbn-products, ogbn-arxiv.
> [Graphbolt] Support converting dgl node classification dataset to graphbolt.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [GraphBolt] add more APIs for SamplingGraph

- python/dgl/distributed/partition.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/distributed/test_partition.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] remove GraphMeta and update API accordingly

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
> [GraphBolt] rename FromCSC as Create in c++ API

- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
Rewrite tests from random to hard code for better bug reproduce in the future.
> [GraphBolt] Rewrite tests from random to hard code.

- notebooks/graphbolt/walkthrough.ipynb
> [GraphBolt] update fused_csc_sampling_graph()

- python/dgl/graphbolt/impl/neighbor_sampler.py
> [doc] update docstring for gb.sample_neighbor

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/minibatch_transformer.py
- python/dgl/graphbolt/negative_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
> [GraphBolt] Add functional name into docstring

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
example output + homograph:
```
FusedCSCSamplingGraph(csc_indptr=tensor([0, 1]),
indices=tensor([0]),
num_nodes=1, num_edges=1, edge_attributes={'A1': tensor([1.4310]), 'A2': tensor([-0.1958])})
.
FusedCSCSamplingGraph(csc_indptr=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 1]),
indices=tensor([14]),
num_nodes=100, num_edges=1, edge_attributes={'A1': tensor([0.4959]), 'A2': tensor([0.2798])})
.
FusedCSCSamplingGraph(csc_indptr=tensor([ 0,  9, 15, 17, 23, 24, 34, 36, 41, 41, 50]),
indices=tensor([1, 9, 0, 9, 4, 1, 8, 4, 7, 4, 5, 9, …
```
> [GraphBolt] refine graph representation

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
Modify `InSubgraphSampler` to support csc format.
> [GraphBolt] Modify `InSubgraphSampler` to support csc format.

- docs/source/api/python/dgl.graphbolt.rst
see experiment doc page for full preview.
> [doc] re-org api doc page

- docs/source/stochastic_training/index.rst
- docs/source/stochastic_training/walkthrough.nblink
> [doc] disable walkthrough notebook

- python/dgl/graphbolt/internal/sample_utils.py
- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
Add check in `unique_and_compact_csc_format` to ensure inputs are correct.
> [GraphBolt] Add check in `unique_and_compact_csc_format`.

- python/dgl/graphbolt/base.py
> [GraphBolt] Add `to` to CSCFormatBase.

- docs/source/guide/minibatch-gpu-sampling.rst
- docs/source/guide/minibatch-inference.rst
- docs/source/guide/minibatch-nn.rst
- docs/source/guide/minibatch-parallelism.rst
- docs/source/guide/minibatch-sparse.rst
- docs/source/guide/minibatch.rst
> [doc] add tutorial for train with sparse

- examples/sampling/graphbolt/sparse/graphsage.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
> [doc] add example for SubgraphSampler

- graphbolt/include/graphbolt/serialize.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/serialize.cc
- graphbolt/src/shared_memory_helper.cc
> [GraphBolt] de-duplicate code for reading data from achive

- examples/multigpu/graphbolt/node_classification.py
- examples/sampling/graphbolt/lightning/node_classification.py
- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
- examples/sampling/graphbolt/quickstart/link_prediction.py
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
- tutorials/multi/2_node_classification.py
> [GraphBolt] update to_dgl() in examples

- notebooks/graphbolt/walkthrough.ipynb
- notebooks/stochastic_training/link_prediction.ipynb
- notebooks/stochastic_training/node_classification.ipynb
> Gb to dgl nb

- docs/source/guide/minibatch-custom-sampler.rst
- docs/source/guide/minibatch-edge.rst
> [GraphBolt] update doc page about to_dgl()

- python/dgl/graphbolt/minibatch.py
> [GraphBolt] Fix MiniBatch blocks.

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
Add opt `output_cscformat` to examplesf to track time difference between csc and coo.
| | coo | csc | optimize|
|---|---|---|---|
|cpu|99160119|92849749|6.8%|
|gpu|54720143|52695974|3.8%|
| | coo | csc | optimize|
|---|---|---|---|
|cpu|180999231|178030193|1.7%|
|gpu|135746597|134269265|1.1%|
> [GraphBolt] Add opt `output_cscformat` to examples.

- graphbolt/src/fused_csc_sampling_graph.cc
With this PR, NumPickFn and PickFn is able to access the timestamp of the seed node to sample.
> [Graphbolt] Add seed_id for NumPickFn and PickFn in neighbor sampling to support temporal sampling.

- graphbolt/src/fused_csc_sampling_graph.cc
> [Graphbolt] Refactor the nonuniform pick function to make it reusable.

- docs/source/stochastic_training/ondisk-dataset.rst
- notebooks/stochastic_training/ondisk_dataset_homograph.ipynb
> [GraphBolt] update tutorial for OnDiskDataset homograph

- notebooks/stochastic_training/ondisk_dataset_heterograph.ipynb
> [GraphBolt] update OnDiskDataset heterograph tutorial

- tests/examples/test_sampling_examples.py
- tests/examples/test_sparse_examples.py
Sometimes, a PR might fail in `tests/examples/test_sampling_examples.py` or `tests/examples/test_sparse_examples.py` due to not running example(s) successfully, but the infomation we can obtain from the failure is very limited. This is why assertion message should be added, facilitating debugging.
> [Test] add assertion message for testcases in `test/examples`

- python/setup.py
- script/dgl_dev.yml.template
> [dev] add torchdata dependency into DGL requirements

- python/dgl/data/utils.py
> [dev] add progress bar for download()

- notebooks/stochastic_training/link_prediction.ipynb
> [doc] add tqdm for link prediction tutorial

- docs/source/api/python/dgl.graphbolt.rst
- docs/source/guide/minibatch-link.rst
- docs/source/guide/minibatch-parallelism.rst
- python/dgl/graphbolt/feature_fetcher.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
There are still many DGLMiniBatches left in docs and comments and some codes. This PR will remove them all.
> [Misc] Delete all the DGLMiniBatch from docs and comments.

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Add `__repr__` to `OnDiskTask`.
```
OnDiskTask(validation_set=ItemSet(items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
),
train_set=ItemSet(items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
),
test_set=ItemSet(items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
),
metadata={'name': 'node_classification'},
)
```
```
OnDiskTask(validation_set=ItemSetDict(items={'user': ItemSet(items=(tensor([0, 1, 2, 3, 4]),),
names=('seed_nodes',),
), 'item': ItemSet(items=(tensor([5, 6, 7, 8, 9]),),
names=('seed_nodes',),
)},
names=('seed_nodes',),
),
train_set=ItemSetDict(items={'user': ItemSet(items=(tensor([0, 1, 2, 3, 4]),),
names=('seed_nodes',),
), 'item': ItemSet(items=(tensor([5, …
```
> [GraphBolt] Add `__repr__` to `OnDiskTask`.

- graphbolt/include/graphbolt/shared_memory.h
> [Graphbolt]Add nominmax macro in windows

- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] exclude nothing if edge is not found in node pairs

- python/setup.py
- script/dgl_dev.yml.template
- tests/scripts/build_dgl.sh
> [GraphBolt] add torchdata into DGL dependencies

- docs/source/stochastic_training/ondisk-dataset.rst
- notebooks/stochastic_training/ondisk_dataset_heterograph.ipynb
- notebooks/stochastic_training/ondisk_dataset_homograph.ipynb
- python/dgl/graphbolt/impl/ondisk_dataset.py
> [doc] update OnDiskDataset

- python/dgl/graphbolt/impl/in_subgraph_sampler.py
Modify docstring example of `InSubgraphSampler` from coo to csc.
> [GraphBolt] Modify docstring example of `InSubgraphSampler`.

- tests/examples/test_sparse_examples.py
The test keeps failing even on unrelated PRs, e.g. #6797 and https://github.com/dmlc/dgl/pull/6738#issuecomment-1869084951
> [Sparse][Misc] Lower test_hgnn threshold to avoid spurious failures

- python/dgl/graphbolt/impl/neighbor_sampler.py
Update docstring examples of `NeighborSampler` and `LayerNeighborSampler` from coo to csc.
> [GraphBolt] Update docstring examples of `NeighborSampler` and `LayerNeighborSampler`.

- docs/source/stochastic_training/index.rst
> [Graphbolt] Add overview in doc

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Change default value from `coo` to `csc` in `FusedCSCSamplingGraph`.
> [GraphBolt] Change default value from `coo` to `csc` in `FusedCSCSamplingGraph`.

- CMakeLists.txt
> [dev] enable GraphBolt build for all build types

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/isin.cu
- graphbolt/src/isin.cc
- tests/python/pytorch/graphbolt/test_base.py
CUDA implementation of IsIn. Required to enable the Link tests of #6770, which I temporarily disabled on the GPU.
> [GraphBolt][CUDA] `gb.isin` implementation

- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [Graphbolt] Add temporal sampling unittests.

- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [GraphBolt] Fix attribute error when testing fused_csc_sampling_grpah.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] Remove coo from neighborsampler.

- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
> [GraphBolt] Remove coo from `InSubgraphSampler`.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
Update docstring in `FusedCSCSamplingGraph`.
> [GraphBolt] Update docstring in `FusedCSCSamplingGraph`.

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
> [GraphBolt] Remove coo from blocks in MiniBatch.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
> [GraphBolt][Bug] Quick fix for GPU sampling case.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] Remove coo from `FusedCSCSamplingGraph`.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
Completes #6839. Should have added these tests in the first place, I am learning why unit tests are important. Sorry about that. Let's merge this quickly.
> [GraphBolt][CUDA] Fix graph pinning and add tests

- graphbolt/CMakeLists.txt
- graphbolt/include/graphbolt/shared_memory.h
A simple fix for `nominmax` issue, and revert #6794.
> [Graphbolt]Fix windows nominmax issue

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
> [GraphBolt][CUDA] Remove unnecessary check and synchronization

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/temporal_neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [Graphbolt] Add TemporalNeighborSampler.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
Locally test `hetero_rgcn`.
Device: GPU.
Time(1 epoch): [00:59, 10.35it/s]
> [GraphBolt] Optimize `_convert_to_sampled_subgraph`.

- tests/tools/test_dist_part.py
fix CI failure such as in https://github.com/dmlc/dgl/pull/6865
> [dist] skip verify_partitions as it is out-dated

- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [GraphBolt] Remove `FusedSampledSubgraphImpl`.

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] upgrade latest vesion to 2.0

- docs/source/api/python/dgl.graphbolt.rst
> [doc] update gb utilities

- python/dgl/graphbolt/impl/__init__.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/temporal_neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [Graphbolt] Support temporal sampling in SubgraphSampler.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
> [Graphbolt] Support loading heterogeneous attributes in sampling graph.

- examples/sampling/graphbolt/rgcn/README.md
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [example] update graphbolt rgcn readme

- examples/core/rgcn/README.md
- examples/sampling/graphbolt/rgcn/README.md
> [examples] update README for RGCN examples

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Change the temporal filter condition of temporal sampler to < instead of <=.
> [Graphbolt] Change the temporal filter condition of temporal sampler.

- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [GraphBolt] Update gpu sampling tests of `sample_beighbors`.

- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [example] update docstring

- graphbolt/src/random.cc
- graphbolt/src/random.h
> [GraphBolt] Setting manual seed also sets the seed now.

- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] Add multi-fanout per layer test.

- tests/python/pytorch/graphbolt/test_base.py
Add test for `CopyTo` with `extra_attrs`
> [GraphBolt] Add test for CopyTo extra_attrs

- examples/core/rgcn/README.md
- examples/core/rgcn/hetero_rgcn.py
- examples/sampling/graphbolt/rgcn/README.md
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
- tests/python/pytorch/graphbolt/test_base.py
> [release] cherry pick missing commits

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] update version to 2.0.0

- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/fused_csc_sampling_graph.cc
For `indptr`, `indices` and `nodes` tensors, let's use `AT_DISPATCH_INDEX_TYPES`. Should fix #6911 and fix #6903, and is a much better alternative to #6907. I might have missed other files and places, will add them when we build consensus on what solution to go forward with. The CI time is down to 43 minutes from well over an hour with this PR.
> [GraphBolt] Switch to using `AT_DISPATCH_INDEX_TYPES` for graph

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Enable load tasks selectively.
**Example code:** 
```
dataset.load(["node_classification"])
```
The type of the option should be `list`.
> [GraphBolt] Add opt to load tasks selectively.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/basic_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
Get feature keys of FeatureStore.
API: FeatureStore.keys()
return: List[tuple(domain, type_name, feat_name)]
> [GraphBolt] Get feature keys of FeatureStore.

- docs/source/graphtransformer/data.rst
- docs/source/graphtransformer/index.rst
- docs/source/graphtransformer/model.rst
- docs/source/index.rst
> [Doc] Add Graph Transformer Tutorial Documentation

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] Add `force_reload` to OnDiskDataset.

- examples/sampling/pyg/node_classification.py
> [GraphBolt] PyG example typo fix

- docs/source/stochastic_training/ondisk-dataset-specification.rst
- notebooks/stochastic_training/ondisk_dataset_heterograph.ipynb
- notebooks/stochastic_training/ondisk_dataset_homograph.ipynb
> [GraphBolt] update notebooks about numpy edges

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
> [release] upgrade version to 2.1 on master

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_itemset.py
Update `__repr__` of `ItemSet` and `ItemSetDict`.
1. I believe it is not a good practice to implement `__repr__` using a function outside the classes, so I try to keep the code inside them.
2. I also refined the layout of the output string, as well as the test code. It is now more straightforward in the test code.
```
ItemSet(
items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
)
```
```
ItemSetDict(
itemsets={'user': ItemSet(
items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
), 'item': ItemSet(
items=(tensor([5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14])),
names=('seed_nodes', 'labels'),
)},
names=('seed_nodes', 'labels'),
)
```
> [GraphBolt] Update `__repr__` of `ItemSet` and `ItemSetDict`

- python/dgl/graphbolt/itemset.py
Update the docstring of `ItemSet`.
> [GraphBolt] Update the docstring of `ItemSet`

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
- tests/python/pytorch/graphbolt/test_integration.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
Add `seeds` to MiniBatch.
`seeds` is a  _**N*D**_ tensor representing _**N**_ node pairs with _**D**_ nodes or a dict of such tensors.
Following is a 3*4 tensor representing 3 hyperedges with 4 nodes.
```
seeds=torch.tensor([[1,1,1,1], [2,2,2,2], [3,3,3,3]),
```
> [GraphBolt] Add `seeds` to MiniBatch.

- python/dgl/graphbolt/itemset.py
> [GraphBolt] update the docstring

- python/dgl/graphbolt/sampled_subgraph.py
> [GraphBolt] Update docstring of `SampledSubgraph`.

- examples/multigpu/node_classification_sage.py
Regarding #6697. This is a work-around to make it runnable in benchmark.
> [Misc] DGL multi-gpu example run error work around

- Jenkinsfile
- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu_pip.txt
- script/dgl_dev.yml.template
> [CI] add pyg into CI image

- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
> [GraphBolt][CUDA] Refine pinning tests

- examples/sampling/graphbolt/node_classification.py
Align the optimizer to the DGL example.
> [GraphBolt] Update GB node classification example learning rate

- python/dgl/graphbolt/sampled_subgraph.py
> [GraphBolt] Update docstring of sampled subgraph.

- python/dgl/graphbolt/sampled_subgraph.py
> [GraphBolt] Fix docstr of `sampled_csc` in `SampledSubgraph`.

- examples/multigpu/graphbolt/node_classification.py
Temporary workaround for #7008.
> [GraphBolt][CUDA] Temporarily disable overlap for the multiGPU example.

- Jenkinsfile
- python/dgl/distributed/__init__.py
- python/dgl/distributed/partition.py
- tests/distributed/test_partition.py
- tests/scripts/cugraph_unit_test.sh
> [DistGB] refine convertion from dgl to graphbolt

- python/dgl/distributed/partition.py
- tests/distributed/test_partition.py
> [DistGB] enable to load GB partitions

- script/dgl_dev.yml.template
Add package `torch-sparse` and `torch-scatter` in build env script.
> [Env Fix] Add essential package for pyg `Neighbor sampler`

- script/dgl_dev.yml.template
> Revert "[Env Fix] Add essential package for pyg `Neighbor sampler`"

- python/dgl/distributed/partition.py
> [DistGB] add verify logic for GraphBolt partitions

- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Add hardcode testcases for `gb.preprocess_ondisk_dataset`
> [GraphBolt] Add hardcode testcases for `gb.preprocess_ondisk_dataset`

- python/dgl/distributed/partition.py
- tests/distributed/test_dist_graph_store.py
- tests/distributed/test_partition.py
> [DistGB] update partition_graph to support graphbolt

- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
fix for https://github.com/dmlc/dgl/pull/6726.
> [GraphBolt] fix testcases on warning messages

- python/dgl/graphbolt/dataloader.py
`deque` is a much more efficient container than `Queue`.
https://stackoverflow.com/a/20330499
> [GraphBolt][CUDA] Use deque instead of Queue for Bufferer.

- docs/source/install/index.rst
> [dev] update system requirements

- graphbolt/src/fused_csc_sampling_graph.cc
> [Graphbolt] Add fast path for tamporal sampling.

- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
> [DistGB] enable GB sampling on homograph

- graphbolt/src/fused_csc_sampling_graph.cc
> [GraphBolt] Add error messages for attribute size check

- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
> [DistGB] return global eids from GB sampling on homograph

- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
> [DistGB] enable GB sampling on heterograph

- python/dgl/distributed/graph_services.py
- python/dgl/distributed/partition.py
> [DistGB] use expand_indptr for csc to coo

- docs/source/guide/minibatch-node.rst
> [doc] fix undefined variable in code snippet

- tests/distributed/test_mp_dataloader.py
> [DistGB] sample with graphbolt on homograph via DistDataLoader

- python/dgl/dataloading/neighbor_sampler.py
- python/dgl/distributed/dist_graph.py
- tests/distributed/test_mp_dataloader.py
> [DistGB] sample with graphbolt on homograph via DistNodeDataLoader

- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
> [DistGB] enable sample etype neighbors on heterograph

- python/dgl/distributed/dist_graph.py
- tests/distributed/test_mp_dataloader.py
> [DistGB] sample with graphbolt on heterograph via DistNodeDataLoader

- python/dgl/graphbolt/impl/ondisk_dataset.py
This dataset is tested on node_classification with the result below.
```
Training: 1179it [03:16,  5.99it/s]
Evaluating: 123it [00:11, 10.93it/s]
Epoch 00000 | Loss 1.5612 | Accuracy 0.6158 | Time 196.9623
Training: 1179it [03:50,  5.11it/s]
Evaluating: 123it [00:21,  5.64it/s]
Epoch 00001 | Loss 1.2682 | Accuracy 0.6133 | Time 230.8359
Training: 1179it [06:37,  2.97it/s]
Evaluating: 123it [00:34,  3.58it/s]
Epoch 00002 | Loss 1.2431 | Accuracy 0.6299 | Time 397.2098
Training: 1179it [08:50,  2.22it/s]
Evaluating: 123it [00:51,  2.39it/s]
Epoch 00003 | Loss 1.2335 | Accuracy 0.6198 | Time 530.6848
Training: 1179it [10:13,  1.92it/s]
Evaluating: 123it [00:51,  2.38it/s]
Epoch 00004 | Loss 1.2280 | Accuracy 0.5944 | Time 613.3291
Training: 1179it [10:17,  1.91it/s]
Evaluating: 123it [00:52, …
```
> [Dataset] Add dataset ogbn-papers100M

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/itemset.py
> [GraphBolt][Doc] Minor fixes and clarifications.

- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
Adding GPU sampling support for the R-GCN example.
> [GraphBolt][CUDA] RGCN example

- python/dgl/distributed/id_map.py
- python/dgl/distributed/partition.py
- tests/distributed/test_partition.py
> [DistGB] enable int32 id ranges in IdMap

- Jenkinsfile
- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_gpu
- docker/install/conda_env/torch_cpu.yml
- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu.yml
- docker/install/conda_env/torch_gpu_pip.txt
- tests/python/pytorch/graphbolt/impl/test_legacy_dataset.py
> [CI] use torch 2.0.0, cu118, ubuntu2004, python310

- notebooks/stochastic_training/link_prediction.ipynb
- notebooks/stochastic_training/node_classification.ipynb
Enabled GPU sampling support for the node classification and link prediction tutorials.
> [GraphBolt][CUDA] Node classification and Link prediction tutorials GPU sampling support.

- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_partition_book.py
- python/dgl/distributed/graph_services.py
- python/dgl/distributed/id_map.py
- python/dgl/distributed/partition.py
- tests/distributed/test_distributed_sampling.py
- tests/distributed/test_mp_dataloader.py
- tests/distributed/test_partition.py
> [DistGB] format dtype when converting partition to GraphBolt format

- python/setup.py
> [dev] remove build artifacts for cleanup

- notebooks/stochastic_training/link_prediction.ipynb
Also changing the notebook metadata so that it loads a GPU colab instance by default.
> [GraphBolt][Tutorial] Fix the typo in the tutorial and colab instance type.

- python/dgl/graphbolt/impl/ondisk_dataset.py
These changes are from #7127 , but are less relative with preprocessing. So I think we can put them in another PR and merge them first.
These changes are authored by @mfbalin and suggested by @Skeleton003.
> [GraphBolt] Update `_init_all_nodes_set`

- tutorials/cpu/argo_tutorial.py
> [Doc] Created a tutorial for ARGO in the CPU section

- python/setup.py
> [dev] exclude dist dir

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [dev] bump master version to 2.2

- notebooks/stochastic_training/link_prediction.ipynb
- notebooks/stochastic_training/node_classification.ipynb
> [doc] install cpu version by default in notebooks

- graphbolt/src/expand_indptr.cc
No need to create the tensor via `arange` ourselves.
> [GraphBolt] Slight `gb.expand_indptr` improvement on CPU.

- examples/distributed/rgcn/README.md
- examples/distributed/rgcn/node_classification.py
- examples/distributed/rgcn/partition_graph.py
> [DistGB] Enable GraphBolt for node classification on heterograph

- python/dgl/graphbolt/impl/uniform_negative_sampler.py
Modify `labels` dtype from `bool` to default dtype for further use in training.
Update code as recommended in #7068 .
> [GraphBolt] Modify `labels` dtype.

- docs/source/api/python/dgl.distributed.rst
- tutorials/dist/1_node_classification.py
> [DistGB] update documentation

- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
> [DistGB] enable replacement sampling with GraphBolt API

- examples/distributed/graphsage/README.md
- examples/distributed/rgcn/README.md
> [examples] update README about partition conversion

- python/setup.py
> [release] add pandas into dependencies

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
> [GraphBolt][Doc] Update `layer_neighbor` documentation for new args.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
> [GraphBolt][Doc] Correct typo to fix rendering issue.

- examples/sampling/graphbolt/sparse/graphsage.py
Fix sparse example and add tqdm to visualise progress.
> [GraphBolt] Fix sparse example.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_base.py
> [GraphBolt] Update minibatch `to` to support seeds.

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
- examples/sampling/graphbolt/pyg/node_classification_advanced.py
- examples/sampling/graphbolt/quickstart/node_classification.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [GraphBolt] Modify `_init_all_nodes_set` to use `seeds`.

- examples/distributed/rgcn/README.md
> [DistGB] update CPU util of RGCN example

- examples/sampling/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt] PyG advanced example `torch.compile()` bug workaround.

- notebooks/stochastic_training/link_prediction.ipynb
- notebooks/stochastic_training/node_classification.ipynb
> [GraphBolt] Update notebook examples.

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/gather.cu
- graphbolt/src/cuda/neighbor_sampler.cu
> [GraphBolt][CUDA] Refactor `Gather` operation.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
> [GraphBolt][CUDA] Remove overlap graph variable hacks.

- docs/source/stochastic_training/index.rst
- docs/source/stochastic_training/multigpu_node_classification.nblink
- notebooks/stochastic_training/multigpu_node_classification.ipynb
Jupyter notebooks have the limitation that `multiprocessing.spawn` does not work. Thus, I avoid calling spawn if there is a single GPU such as in the google colab environment.
> [GraphBolt][Tutorial] MultiGPU tutorial as a notebook

- notebooks/stochastic_training/ondisk_dataset_heterograph.ipynb
- notebooks/stochastic_training/ondisk_dataset_homograph.ipynb
> [GraphBolt] Update notebooks about how to construct ondisk datasets.

- python/dgl/graphbolt/impl/legacy_dataset.py
- tests/python/pytorch/graphbolt/impl/test_legacy_dataset.py
> [GraphBolt] Update name used in `LegacyDataset`.

- python/dgl/graphbolt/impl/ondisk_dataset.py
Two diffentent variables using the same name may cause misunderstanding.
> [Misc] rename a variable

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/sampled_subgraph.py
- python/dgl/graphbolt/utils.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
- tests/python/pytorch/graphbolt/test_utils.py
`Exclude edges` based on `node_pairs` has been deleted. The input format of `exclude_edges` has changed from a tuple of two tensor to a N*2 tensor.
> [GraphBolt] Remove old version exclude edges.

- python/dgl/graphbolt/itemset.py
> [GraphBolt] Update docstring of `itemset.py`.

- python/dgl/graphbolt/impl/torch_based_feature_store.py
> [GraphBolt] Fix doc string of DiskBasedFeature

- .clang-format
> [Misc] Update clang format.

- .clang-format
> Revert "[Misc] Update clang format."

- Jenkinsfile
> [Misc] Add Triston to jenkins allowlist.

- graphbolt/src/cuda/extension/unique_and_compact_map.cu
> Revert "[GraphBolt] Quick fix for GCC 8"

- examples/multigpu/graphbolt/node_classification.py
- examples/sampling/graphbolt/node_classification.py
- examples/sampling/graphbolt/pyg/node_classification.py
- examples/sampling/graphbolt/pyg/node_classification_advanced.py
- examples/sampling/graphbolt/quickstart/node_classification.py
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
- notebooks/stochastic_training/multigpu_node_classification.ipynb
- notebooks/stochastic_training/node_classification.ipynb
- python/dgl/graphbolt/base.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_dataloader.py
- tutorials/multi/2_node_classification.py
> [GraphBolt][CUDA] Update `copy_to`.

- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/temporal_neighbor_sampler.py
> [Temporal]Fix tensor option mismatch issue

- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/minibatch.py
> [GraphBolt] Update docstring related to cleaning up `seed_nodes` and `node_pairs`.

- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
- tests/python/pytorch/graphbolt/test_itemset.py
- tests/python/pytorch/graphbolt/test_minibatch.py
> [GraphBolt] Update tests related to `seeds` refactor.

- docs/source/guide/minibatch-custom-sampler.rst
- docs/source/guide/minibatch-edge.rst
- docs/source/guide/minibatch-inference.rst
- docs/source/guide/minibatch-link.rst
- docs/source/stochastic_training/ondisk-dataset-specification.rst
- notebooks/graphbolt/walkthrough.ipynb
> [GraphBolt][Doc] Update docs related to `seeds`.

- examples/sampling/graphbolt/temporal_link_prediction.py
> [Temporal] Add link prediction example

- graphbolt/src/fused_csc_sampling_graph.cc
> [GraphBolt] Hetero CPU sampling bug fix.

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [dev] bump version to 2.3

- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [GraphBolt] Update tests to confirm FusedCSCSampling graph can solve indptr and indices with different dtype.

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] bump version to 2.2.1

- examples/sampling/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt] Fix typo in PyG advanced example for CPU runs.

- script/create_dev_conda_env.sh
> [dev] update minimum torch and cuda version when creating conda env

- examples/distributed/graphsage/README.md
- examples/distributed/rgcn/README.md
> [misc] fix path in README

- python/dgl/graphbolt/impl/gpu_cached_feature.py
> [GraphBolt] utilize torch.Tensor.nbytes

- python/dgl/graphbolt/impl/gpu_cached_feature.py
> [Misc] Fix lint.

- examples/distributed/rgcn/node_classification.py
- python/dgl/distributed/optim/pytorch/sparse_optim.py
- python/dgl/distributed/optim/pytorch/utils.py
> [DistDGL] fix device mismatch when calling all_to_all with gloo backend

- examples/distributed/graphsage/README.md
- examples/distributed/graphsage/node_classification_unsupervised.py
> [DistGB] add NC example that uses DistEdgeDataLoader for train

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/include/graphbolt/cuda_sampling_ops.h
- graphbolt/src/cuda/common.h
- graphbolt/src/cuda/cumsum.cu
- graphbolt/src/cuda/expand_indptr.cu
- graphbolt/src/cuda/extension/unique_and_compact.h
- graphbolt/src/cuda/extension/unique_and_compact_map.cu
- graphbolt/src/cuda/gather.cu
- graphbolt/src/cuda/gpu_cache.cu
- graphbolt/src/cuda/gpu_cache.h
- graphbolt/src/cuda/index_select_csc_impl.cu
- graphbolt/src/cuda/index_select_impl.cu
- graphbolt/src/cuda/insubgraph.cu
- graphbolt/src/cuda/isin.cu
- graphbolt/src/cuda/max_uva_threads.cc
- graphbolt/src/cuda/max_uva_threads.h
- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/cuda/sampling_utils.cu
- graphbolt/src/cuda/sort_impl.cu
- graphbolt/src/cuda/unique_and_compact_impl.cu
Adding the Apache 2.0 license to the files contributed by myself. The previous code was also intended to be licensed under the same terms (under the DGL project umbrella), it is just that the license was not there at the top of the files.
> [GraphBolt][Misc] Add license to cuda backend files

- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
- tests/distributed/test_mp_dataloader.py
> [DistDGL] enable exclude edges sample_neighbors()

- examples/distributed/graphsage/node_classification_unsupervised.py
- python/dgl/dataloading/dist_dataloader.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
- python/dgl/sampling/neighbor.py
- tests/distributed/test_mp_dataloader.py
> [DistDGL] enable exclude_edges for sample_etype_neighbors()

- tests/distributed/test_partition.py
> [DistGB] add testcase for etype sorted graph

- python/dgl/dataloading/neighbor_sampler.py
- tests/distributed/test_mp_dataloader.py
> [DistGB] enable graphbolt sampling for DistEdgeDataLoader

- tests/distributed/test_mp_dataloader.py
> [DistGB] enable negative sampler for graphbolt-based DistGraph

- examples/distributed/rgcn/README.md
- examples/distributed/rgcn/lp_perf.py
> [DistGB] add demo for LP with DIstGB

- examples/distributed/rgcn/README.md
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
> [DistGB] exclude edges right after sampling

- tests/distributed/test_mp_dataloader.py
> [DistGB] remove unnecessary testcases

- tests/distributed/test_mp_dataloader.py
> [DistDGL] add testcase for prob or mask sampling

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
> [GraphBolt] pass tensor directly to probs or masks in sampling C++ API

- tests/distributed/test_distributed_sampling.py
- tests/distributed/test_mp_dataloader.py
> [DistGB] add testcases for DistDGL local sampling on multiple partitions

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
> [GraphBolt] enable to set single node/edge attribute

- examples/distributed/rgcn/lp_perf.py
- python/dgl/dataloading/dist_dataloader.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
- tests/distributed/test_mp_dataloader.py
> [DistGB]enable prob/mask sampling on graphbolt partitions

- examples/distributed/rgcn/lp_perf.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/kvstore.py
- tests/distributed/test_mp_dataloader.py
> [DistGB] fix add edge attr request

- Jenkinsfile
Adding the new intern, [Stanley Yang](https://github.com/az15240/), to the contributors. 
Changed Jenkinsfile to contain Stanley's GitHub handle.
> [Dev] add new contributor to CI authority

- Jenkinsfile
- tests/distributed/test_mp_dataloader.py
> [DistGB] disable glitched testcases

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/temporal_neighbor_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
> [Temporal] Add time window support

- python/dgl/graphbolt/base.py
> [Misc] modify workaround for `DILL_AVAILABLE` in torch 2.3.0

- graphbolt/src/fused_csc_sampling_graph.cc
> [Misc] Rename seed_time_window to keep consistency.

- examples/sampling/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt][CUDA] Demonstrate GPUGraphCache usage in example.

- graphbolt/src/cuda/extension/gpu_graph_cache.cu
Fixing the replace method of the GPU graph cache and additional runtime checks.
> [GraphBolt][CUDA] Gpu graph cache cpp

- Jenkinsfile
- tests/distributed/test_mp_dataloader.py
> [CI] revert skip and shm size

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] bump version to 2.4 for nightly

- tests/scripts/task_distributed_test.sh
> [CI] disable test_mp_dataloader due to glitch

- python/dgl/graphbolt/base.py
> [GraphBolt] Fix deprecation warning

- python/setup.py
- script/dgl_dev.yml.template
> Revert "[dev] limit numpy < 2.0.0 for compatibility"

- examples/sampling/graphbolt/pyg/labor/node_classification.py
- examples/sampling/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt][PyG][Examples] Better default settings.

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/cuda/common.h
- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/macro.h
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
TemporalLayerNeighborSampler will be added in a follow-up PR.
> [GraphBolt] Add temporal labor sampling to graph.

- graphbolt/src/cache_policy.h
- graphbolt/src/circular_queue.h
Moved into its own header file and added PopN and Clear functions. PopN pops N items passed as parameter and Clear is obvious.
> [GraphBolt] Make `graphbolt::CircularQueue` reusable.

- python/dgl/graphbolt/impl/feature_cache.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
> [GraphBolt] Refine FeatureCache and increase test coverage.

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] bump version to 2.3.1

- graphbolt/src/index_select.cc
- graphbolt/src/index_select.h
- graphbolt/src/python_binding.cc
- tests/python/pytorch/graphbolt/test_base.py
> [GraphBolt] Add `index_select_async`.

- graphbolt/src/cnumpy.cc
> [GraphBolt] Better variable naming.

- graphbolt/src/cnumpy.cc
> [GraphBolt][io_uring] Refactor and potential fix for spurious failures.

- python/dgl/graphbolt/impl/torch_based_feature_store.py
> [GraphBolt] `TorchBasedFeature.read_async`. [2]

- python/dgl/graphbolt/impl/gpu_cached_feature.py
> [GraphBolt][CUDA] `GPUCachedFeature.read_async`. [3]

- python/dgl/graphbolt/impl/cpu_cached_feature.py
> [GraphBolt] `CPUCachedFeature.read_async` branch 3 [8]

- python/dgl/graphbolt/impl/cpu_cached_feature.py
> [GraphBolt] `CPUCachedFeature.read_async` branch 1 [6]

- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/basic_feature_store.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Depended on #7558. Tested with our examples. The CI should pass now.
> [GraphBolt] Refactor `FeatureFetcher` to use `read_async`.

- examples/graphbolt/pyg/labor/node_classification.py
This looks so ugly. Any suggestions @frozenbugs 
> [GraphBolt][Example] Minor bug fix.

- script/dgl_dev.yml.template
To avoid GLIBCXX_3.4.26 issue.
> [dev] install GNU C++ runtime library

- examples/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt][PyG] Support different numbers of layers.

- python/setup.py
If install DGL into a very clean and base conda env, some packages are missing.
> [dev] add more dependencies into setup

- graphbolt/CMakeLists.txt
> Dev liburing gnu

- examples/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt][Example] Refine the advanced PyG example.

- examples/graphbolt/pyg/labor/node_classification.py
Extracting the training loop helps avoid leaking minibatch when we are validating. Reduces the peak memory usage significantly.
> [GraphBolt][Example] Refine the labor example.

- graphbolt/include/graphbolt/async.h
- graphbolt/src/cnumpy.cc
> [GraphBolt] Add `graphbolt::parallel_for`.

- graphbolt/src/index_select.cc
> [GraphBolt] Use `graphbolt::parallel_for` for `IndexSelect`.

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/expand_indptr.cu
- graphbolt/src/cuda/insubgraph.cu
- graphbolt/src/expand_indptr.cc
- graphbolt/src/expand_indptr.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/base.py
- tests/python/pytorch/graphbolt/test_base.py
> [GraphBolt][CUDA] `gb.indptr_edge_ids` python API and tests.

- examples/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt[PyG] Optimize advanced example further.

- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
Advanced example was optimized in #7597. Doing the same kind of optimization for the labor example as well. 10%-20% speedup is achieved.
> [GraphBolt][PyG] Optimize LABOR example further.

- python/dgl/graphbolt/internal_utils.py
This will be needed to for example check if an object is in pinned memory.
> [GraphBolt] `recursive_apply_reduce_all`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
We might want to consider a new hash table library in the near future for better performance.
> [GraphBolt] Make `CachePolicy` hash table types generic.

- graphbolt/CMakeLists.txt
- graphbolt/src/cnumpy.cc
There is features such as [std::atomic_ref](https://en.cppreference.com/w/cpp/atomic/atomic_ref) (we can remove hacks for atomic in our unique_and_compact CPU impl) and [std::counting_semaphore](https://en.cppreference.com/w/cpp/thread/counting_semaphore) that I plan to use to write portable and performant code.
> [GraphBolt] Enable CXX20.

- graphbolt/CMakeLists.txt
- graphbolt/src/cnumpy.cc
> Revert "[GraphBolt] Enable CXX20."

- graphbolt/src/cuda/expand_indptr.cu
> [GraphBolt] Address #7592 review and rename variable.

- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
> [GraphBolt] Test `query_and_then_replace` more rigorously.

- script/create_dev_conda_env.sh
- script/dgl_dev.yml.template
> [GraphBolt]support torch2.4&cuda12.4

- docs/source/api/python/dgl.graphbolt.rst
> [GraphBolt][Doc] Add new features to documentation.

- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
> [GraphBolt][Doc] Fix rest of the `read_async` docs.

- graphbolt/src/cnumpy.cc
We have a list of queues. We need to make sure to allocate buffers for each existing queue. We also make sure to print the errno from io_uring calls if something goes wrong for better error message and debuggability.
> [GraphBolt][io_uring] Fix queue assignment bug.

- graphbolt/include/graphbolt/async.h
> [GraphBolt] Enable exceptions for `gb::parallel_for`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
In addition, since torch enforces CXX11ABI=0, std::list<>::size() is linear time, causing quadratic complexity, fixing that by tracking the size of the small list ourselves.
> [GraphBolt] Cleanup and refine `CachePolicy`.

- python/dgl/graphbolt/impl/cpu_cached_feature.py
@Liu-rj FYI. @frozenbugs what do you think about this limitation?
> [GraphBolt] Update `CPUCachedFeature` docstring.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/feature_cache.cc
- graphbolt/src/feature_cache.h
- python/dgl/graphbolt/impl/cpu_cached_feature.py
Refactoring more. Right now, I am trying to fix a correctness bug that only shows up when overlap_fetch is enabled in FeatureFetcher. Meanwhile, as I notice refactoring opportunities, I am opening PRs to fix them from time to time. Deleting as much as I can while simplifying things.
> [GraphBolt] Refactor `CachePolicy` more.

- graphbolt/src/cache_policy.h
These checks never fail, there is no need to check them.
> [GraphBolt] Remove assertions from `CachePolicy`.

- graphbolt/src/cache_policy.h
> [GraphBolt] Relax memory order of cache hit case.

- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/index_select.cc
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
Some redundant dispatches are removed and InSubgraph is improved.
Also fixes #6737.
> [GraphBolt] Remove unnecessary dispatch and refine.

- graphbolt/src/cache_policy.h
> [GraphBolt] Better naming for split key variable.

- examples/graphbolt/disk_based_feature/node_classification.py
When testing the in-mem performance, I changed the `in_memory` field to True but forgot to revert it back. This PR corrects it. @mfbalin 
> [GraphBolt] Fix in_memory setting in DGL example

- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/index_select.cc
Before, the CPU IndexSelectCSC was going through InSubgraph of CPU. Now, it is the other way around as it should be. I am trying to clean up the messes from before.
> [GraphBolt] Implement proper `IndexSelectCSC` for CPU.

- python/setup.py
> Reorder dependency list in setup

- python/dgl/__init__.py
> [dev] do not import distributed and graphbolt when import dgl

- tests/scripts/task_distributed_test.sh
> [Dist] enable partition tests

- graphbolt/src/cnumpy.h
The current code should already be working. This redundant mechanism of releasing the semaphore should not be needed at all. If it is needed, then the existing code should be fixed.
We acquire the semaphore once in the main thread and once in each worker thread. Then, the first worker thread exiting releases the semaphore twice, including the main thread's. Since we use RAII, any acquire operation will have a corresponding release. For the main thread's ticket, it will be released by the first exiting worker thread. If no worker thread acquires the semaphore, then the main thread will release the semaphore itself in the destructor.
The role of this whole mechanism is that if the read operation finishes (any worker threads exit), then another pending read operation should immediately be …
> [GraphBolt][io_uring] Remove redundant mechanism.

- graphbolt/src/cnumpy.cc
- graphbolt/src/cnumpy.h
Simplify the logic. Now, there is no unexpected error on the AWS instance with mounted volume. @Liu-rj 
> [GraphBolt][io_uring] Fix io_uring queue distribution bug.

- graphbolt/include/graphbolt/async.h
Closes #7700. When there are no visible GPUs, torch cuda is available returns false. When graphbolt::async asks the current stream when cuda is unavailable, the call fails. We check if torch cuda is availalbe is true and only in that case, ask for the stream.
> [GraphBolt][CUDA] Keep CUDAStream only if cuda is available.

- examples/graphbolt/link_prediction.py
- examples/graphbolt/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
- examples/graphbolt/rgcn/hetero_rgcn.py
Enabling overlap_graph_fetch and asynchronous optimizations in the examples.
> [GraphBolt][CUDA] Enable recent optimizations in the examples.

- python/dgl/graphbolt/__init__.py
> [dev] add more info about load failure of GraphBolt

- examples/multigpu/graphbolt/node_classification.py
@TristonC this is the breakthrough I am talking about.
> [GraphBolt][CUDA] Enable asynchronous sampling for multigpu example.

- CMakeLists.txt
- cmake/modules/CUDA.cmake
> Revert "[Build] Organize cmake file."

- graphbolt/src/cnumpy.cc
- graphbolt/src/cnumpy.h
> [GraphBolt][io_uring] Document `QueueAndBufferAcquirer`.

- examples/graphbolt/disk_based_feature/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
> [GraphBolt][Doc] Improve documentation.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_disk_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
> [GraphBolt] `Feature.count()`.

- examples/graphbolt/pyg/hetero/node_classification.py
`torch.compile()` does not quite work yet due to https://github.com/pytorch/pytorch/issues/133942. Haven't yet verified its equivalance to the DGL example.
Related to #7711.
> [GraphBolt][PyG] Heterogenous example.

- examples/graphbolt/disk_based_feature/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt] Refine examples.

- graphbolt/src/cache_policy.h
- python/dgl/graphbolt/item_sampler.py
> [GraphBolt] Minor improvement to item sampler and cache policy.

- examples/multigpu/graphbolt/node_classification.py
> [GraphBolt][CUDA] Destroy dist group at the end of script.

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/setup.py
- python/update_version.py
> [2.4.0] Release branch cut.

- docs/source/api/python/dgl.graphbolt.rst
> [GraphBolt][Doc] Add `numpy_save_aligned` to documentation. (#7739)

- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
> [GraphBolt][Doc] Fix typo in documentation.

- tests/python/test_dgl_import.py
- tests/scripts/task_unit_test.sh
> [dev] make sure graphbolt is not imported together with dgl

- examples/distributed/graphsage/node_classification.py
- examples/distributed/graphsage/node_classification_unsupervised.py
- examples/distributed/rgcn/node_classification.py
- examples/pytorch/graphsage/dist/train_dist.py
- examples/pytorch/graphsage/dist/train_dist_transductive.py
- examples/pytorch/graphsage/dist/train_dist_unsupervised.py
- examples/pytorch/graphsage/dist/train_dist_unsupervised_transductive.py
- examples/pytorch/rgcn/experimental/entity_classify_dist.py
As distributed module is not imported in default when import dgl, `import dgl.distributed` is required to use any components distributed module such as `DistNodeDataLoader`, `DistEdgeDataLoader` and so on.
> [Dist] import dgl.distributed for examples

- graphbolt/src/utils.h
Explicitly include `<optional>` header file in `graphbolt/src/utils.h`, in case `<torch/script.h>` does not have it included in some torch versions.
@pyynb FYI.
> Include <optional> header file in utils.h

- graphbolt/src/cuda/cooperative_minibatching_utils.cu
- graphbolt/src/cuda/cooperative_minibatching_utils.h
- graphbolt/src/cuda/extension/unique_and_compact_map.cu
Refactor the partition function for more general use.
Towards implementing https://github.com/dmlc/dgl/issues/7273, Cooperative Minibatching [2].
> [GraphBolt][CUDA] Refine the added partition function for later reuse.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
> [GraphBolt][Doc] Clarify `gb.fused_csc_sampling_graph` `type_per_edge` arg.

- python/dgl/distributed/dist_dataloader.py
> [DistGB] fix prob attr not exist

- examples/graphbolt/pyg/multigpu/node_classification.py
Towards #7273.
This example demonstrates the use of Cooperative Minibatching.
Currently, the accuracy does not seem right. I will debug it and fix it.
> [GraphBolt][CUDA] Add Cooperative Minibatching example.

- graphbolt/src/cuda/cooperative_minibatching_utils.cu
- graphbolt/src/cuda/cooperative_minibatching_utils.h
- graphbolt/src/cuda/extension/unique_and_compact_map.cu
- python/dgl/graphbolt/impl/cooperative_conv.py
- tests/python/pytorch/graphbolt/impl/test_cooperative_minibatching_utils.py
Towards #7273.
With these, the multiGPU example works and accuracy seems to be good.
Future PRs will add more tests, examples, refactoring and potential optimizations.
> [GraphBolt][CUDA] Fix Cooperative Minibatching bugs.

- examples/graphbolt/pyg/hetero/node_classification.py
- examples/graphbolt/pyg/multigpu/node_classification.py
Minor improvements such as removing and/or using unused variables.
> [GraphBolt][PyG] Refine examples.
