- src/array/cuda/cuda_filter.cu
- tests/compute/test_filter.py
Fix #5153 by determining the stream at function invocation
> Replace global cudaStream in Filter with runtime calls (fix #5153)

- python/dgl/sparse/sddmm.py
> [Sparse] Use X to represent dense tensors in sddmm

- python/dgl/sparse/diag_matrix.py
- python/dgl/sparse/sparse_matrix.py
> [Sparse] Only support scalar or vector values in SparseMatrix creators

- python/dgl/sparse/elementwise_op.py
- python/dgl/sparse/elementwise_op_sp.py
- python/dgl/sparse/matmul.py
- python/dgl/sparse/reduction.py
- python/dgl/sparse/sddmm.py
- python/dgl/sparse/softmax.py
- python/dgl/sparse/sparse_matrix.py
- python/dgl/sparse/unary_op_sp.py
To address issue:
exc_info = (&lt;class 'SyntaxError'&gt;, SyntaxError('unexpected EOF while parsing', ('&lt;doctest smin[0]&gt;', 1, 35, 'indices = torch.tensor([[0, 1, 1],\n')), &lt;traceback object at 0x7f3d6c5857c8&gt;)
> Change example code for indices creation from two line to one line to avoid test break.

- python/dgl/dataloading/labor_sampler.py
When importance sampling option is used, the returned blocks include edge weights that need to be used during the message passing operation. So, I am including this in the documentation.
> [Doc] Labor sampling improvement

- tools/distpartitioning/parmetis_preprocess.py
- tools/distpartitioning/parmetis_wrapper.py
`input_dir` is not defined at all in
https://github.com/dmlc/dgl/blob/master/tools/distpartitioning/parmetis_preprocess.py#L169
Let's enable user to specify a base directory when calling `parmetis_preprocess.py`.
> [Dist] add input_dir for parmetis preprocess

- tests/tools/utils.py
- tools/distpartitioning/dataset_utils.py
If the keys in the metadata.json file are ordered differently in EDGE_TYPE list and EDGE_DATA dictionaries, then the current implementation of the preprocessing pipeline is incorrectly assigning ETYPE_ID's to the edges. Currently the pipeline always assumes that the Edges are loaded/read from the disk, as the order defined in the EDGE_TYPE list. But if the data files in the EDGE_DATA are ordered differently, compared to EDGE_TYPE list, then the etype_ids will be incorrect and this leads to several errors as noticed in the search CTR graph.
The utils.py file is modified accordingly to cover this unit test case. Now the dataset created for the unit tests will have random ordering of the EDGE_TYPE and EDGE_DATA keys in the metadata.json file.
This PR is created to merge the changes in the PR …
> Remove order-sensitivity of the keys in metadata.json file for the preprocessing pipeline

- dgl_sparse/build.sh
- tensoradapter/pytorch/build.sh
Previously I approved that `rm -rf build` in the build scripts of `tensoradapter` and `dgl_sparse` is unnecessary.  This is actually wrong since during release the `build` directory is reused multiple times for different PyTorch versions.
This PR makes a separate subdirectory for every PyTorch version and build the binaries there, to avoid rebuilding the libraries from scratch and allow building multiple versions at the same time.
> [Build] Fix build for multiple pytorch versions

- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_matrix.cc
- dgl_sparse/src/sparse_matrix_coalesce.cc
- python/dgl/sparse/sparse_matrix.py
- tests/python/pytorch/sparse/test_sparse_matrix.py
Resolve #5373, #5145.
* Support conversions to/from torch sparse tensor.
* Use the stacked row and column tensor in C++ FromCOO.
* Fix typos in the from_coo, from_csr, from_csc docstrings.
> [Sparse] Support converson to/from torch sparse tensor.

- tools/distpartitioning/dist_lookup.py
Handling corner cases in the distributed lookup service. When the get partition ids function is invoked with empty request. This is needed because we are using alltoall function in the get_partition_ids function.
Functions like torch.cat() will fail when empty arguments are passed. This is checked and appropriate action is taken. 
Unit Test cases, is blocked by the following PR - https://github.com/dmlc/dgl/pull/5365
This corner case will be covered in the above mentioned unit test cases PR. 
> Distributed Lookup Service Robustness

- docs/source/api/python/dgl.data.rst
- python/dgl/data/__init__.py
- python/dgl/data/cluster.py
- tests/python/common/data/test_data.py
Add an inductive node classification dataset CLUSTER.
> [Dataset] Add CLUSTER dataset

- script/create_dev_conda_env.sh
to fix below error:
```
ERROR: Could not find a version that satisfies the requirement torch==1.12+cu117 (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, 1.11.0+cu113, 1.11.0+cu115, 1.11.0+rocm4.3.1, 1.11.0+rocm4.5.2, 1.12.0, 1.12.0+cpu, 1.12.0+cu102, 1.12.0+cu113, 1.12.0+cu116, 1.12.0+rocm5.0, 1.12.0+rocm5.1.1, 1.12.1, 1.12.1+cpu, 1.12.1+cu102, 1.12.1+cu113, 1.12.1+cu116, 1.12.1+rocm5.0, 1.12.1+rocm5.1.1, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.0+rocm5.1.1, 1.13.0+rocm5.2, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 1.13.1+cu117.with.pypi.cudnn, 1.13.1+rocm5.1.1, 1.13.1+rocm5.2)
--
ERROR: No matching distribution found for torch==1.12+cu117
```
> [BugFix] fix torch cuda version

- python/dgl/dataloading/dataloader.py
- tests/python/pytorch/dataloading/test_dataloader.py
Addresses one of the problems in #4507 as requested.
> [Bugfix] Fix duplicate worker_init_fn argument when provided in DataLoader

- tests/tools/test_parmetis.py
- tools/distpartitioning/parmetis_postprocess.py
- tools/distpartitioning/parmetis_preprocess.py
- tools/distpartitioning/parmetis_wrapper.py
- tools/verification_utils.py
- tools/verify_partitions.py
1. In the preprocess.py, make sure that num_partitions is defined as input argument. Also, align 'input_dir' with the input dataset. schema_file is assumed to be located inside the input_dir. Also, graph_stats.txt file is assumed to be present in the input_dir.
2. Use DGL_HOME environment variable so that parmetis_wrapper command can be run anywhere.
> [DistDGL][UserEx]Sync parmetis_wrapper with changes in metadata.json

- script/create_dev_conda_env.sh
The default torch version `1.12.0` does not support `cu117`, so sometimes we need to specify torch version.
> [Dev] enable to specify torch version when create conda env

- src/array/cuda/atomic.cuh
when I am trying to build DGL with cuda11.7 on ubuntu22.04(g++11.3.0), below error is thrown.
```
/dgl/src/graph/sampling/randomwalks/../../../array/cuda/atomic.cuh(171): error: identifier "uint16_t" is undefined
...
/dgl/src/runtime/cuda/../../array/cuda/atomic.cuh(129): error: identifier "printf" is undefined 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
> Fix compile error on ubuntu22.04_g++11.3.0

- python/dgl/nn/pytorch/sparse_emb.py
- python/dgl/optim/pytorch/sparse_optim.py
- tests/python/pytorch/nn/test_sparse_emb.py
- tests/python/pytorch/optim/test_optim.py
Resolves #5270
1. Add `state_dict`, `load_state_dict` to `dgl.optim.SparseGradOptimizer`
2. Add `param_groups` to `dgl.optim.SparseGradOptimizer`. Note that different from torch's optimizer, our `param_groups` doesn't contain parameters because getting the whole embedding is very expensive. It still contains other attributes, e.g., lr, betas, eps, for debugging.
3. To support the above functionalities, we further add `_all_get_optm_state` and `_all_set_optm_state` to `dgl.nn.NodeEmbedding`. Ideally, the optimizer states should be attached to the optimizer instead of the embedding, however, to gather multi-GPU states, we have to leverage the TCPStore and communicator of the embedding, so I just follow the current design.
4. Add unit tests.
Please feel free to remove inapplicable items for …
> [Feature] Add `state_dict`, `load_state_dict`, `param_groups` to `dgl.optim.SparseGradOptimizer`

- python/dgl/dataloading/base.py
- tests/python/pytorch/dataloading/test_dataloader.py
Fixes https://github.com/dmlc/dgl/issues/5410
> [Dataloading] Ignore edge types without reverse types in edge dataloader

- examples/tensorflow/dgi/train.py
- examples/tensorflow/gat/train.py
- examples/tensorflow/gcn/train.py
Some of the examples in _examples/tensorflow_ were raising the following error:
after the change, the examples work properly:
> [BugFix] Tensorflow examples fix

- dgl_sparse/include/sparse/sparse_format.h
- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_format.cc
- dgl_sparse/src/sparse_matrix.cc
- dgl_sparse/src/spspmm.cc
This is one of the PR for the issue #5367 . 
> [Sparse] Support Diag sparse format in C++

- tools/dispatch_data.py
Adds an argument to allow custom-named metadata JSON files for `dispatch_data.py`. We provide the previous value as a default to ensure backwards compatibility.
> [Dist] Add argument in dispatch_data.py to allow user-defined metadata JSON filename.

- dgl_sparse/src/sparse_format.cc
- tests/python/pytorch/sparse/test_sparse_matrix.py
`arange_out` is not applicable because it changes the shape of a tensor.
> [Sparse] Fix bugs in Diag format conversions

- docs/source/api/python/dgl.data.rst
- python/dgl/data/__init__.py
- python/dgl/data/wiki_network.py
- tests/python/common/data/test_wiki_network.py
This PR adds the variant of Squirrel as introduced in [Geom-GCN: Geometric Graph Convolutional Networks](https://arxiv.org/abs/2002.05287).
> [Dataset] SquirrelDataset

- docs/source/api/python/dgl.data.rst
- python/dgl/data/__init__.py
- python/dgl/data/actor.py
- tests/python/common/data/test_actor.py
> [Dataset] Actor

- dgl_sparse/src/matmul.cc
- dgl_sparse/src/sddmm.cc
- dgl_sparse/src/utils.h
- tests/python/pytorch/sparse/test_matmul.py
- tests/python/pytorch/sparse/test_sddmm.py
- tests/python/pytorch/sparse/utils.py
> [Sparse] Support strided tensor when calling old DGL APIs

- dgl_sparse/CMakeLists.txt
Fix sparse library link issue, caused by wrong Torch MKL CMake settings
Resolves issue: https://github.com/dmlc/dgl/issues/5474
> [Misc] Add MKL library path for standalone installation

- CMakeLists.txt
- include/dgl/aten/macro.h
- include/dgl/runtime/bfloat16.h
- include/dgl/runtime/ndarray.h
- python/setup.py
- src/array/cpu/gather_mm.cc
- src/array/cpu/sddmm.cc
- src/array/cpu/segment_reduce.cc
- src/array/cpu/segment_reduce.h
- src/array/cpu/spmm.cc
- src/array/cpu/spmm.h
- src/array/cpu/spmm_binary_ops.h
- src/array/cpu/spmm_blocking_libxsmm.h
- tests/cpp/test_aten.cc
- tests/cpp/test_spmm.cc
- tests/python/common/ops/test_ops.py
Enabling BFloat16 data type for CPU.
> [Feature] Add bfloat16 support for CPU

- python/dgl/dataloading/base.py
- tests/python/pytorch/dataloading/test_dataloader.py
When calling `as_edge_prediction_sampler` with `exclude=reverse_types`, both original eids and reverse eids should be removed from latest MFG, but currently only  reverse eids are removed, so this PR is used to fix this bug.
> [Bug] Merge rather replace when find reverse eids

- cmake/modules/CUDA.cmake
- src/random/random.cc
- src/runtime/cuda/cuda_common.h
Remove curand host functions and linked library because they're never used.
In DGL, we're using curand device APIs which don't require a generator or linking to the curand library.
> [Fix] Remove curand host functions

- tests/python/common/test_heterograph.py
Closes #5555 
Fixed the bug reported in this issue, https://github.com/dmlc/dgl/issues/5555,  by replacing the deprecated API with the recommended one.
* replaced `numpy.asscalar()` with `.item()`
> [Fix] np.asscalar deprecated usage

- python/dgl/nn/pytorch/gt/graphormer.py
- tests/python/pytorch/nn/test_nn.py
In common with Graphormer and GraphGPS, we’d like to add `attn_dropout` parameter in `GraphormerLayer` module to distinguish `dropout` and `attn_dropout`, which is convenient for users to set different values of `attn_dropout` and `dropout`. By setting `attn_dropout` individually, users can better control the sparsity of the attention weight matrix.
> [NN] Refine the API of GraphormerLayer

- src/runtime/config.cc
Resolves https://github.com/dmlc/dgl/issues/5554
> [Misc] Add libxsmm_config.h only when LIBXSMM is enabled

- tests/python/common/ops/test_ops.py
To fix https://github.com/dmlc/dgl/issues/5571, this PR bypasses the cases if the running GPU does not support atomic operations for half precision.
Skip the tests if atomicAdd is not supported for fp16.
> [Bugfix] Fix unit test failures on older GPUs

- include/dgl/aten/coo.h
- include/dgl/aten/csr.h
- src/runtime/config.cc
- tests/python/common/test_heterograph-index.py
- tests/python/common/test_heterograph.py
This is to fix https://github.com/dmlc/dgl/issues/5592. For future/own reference, I will detail the root cause in the following.
The root cause is when the first relational graph is empty, the entire heterograph could return `is_pinned() = true` even if they are never being pinned by DGL or PyTorch at all. 
This is because (1) the empty unit graph would return `is_pinned = True` due to the following init. logic: https://github.com/dmlc/dgl/blob/ae8cbde5cfa699ff8d9e774ae6acd2cb8f7b451a/include/dgl/aten/coo.h#L67-L69 and (2) the first relational graph determines if the entire hetero-graph is pinned. 
https://github.com/dmlc/dgl/blob/ae8cbde5cfa699ff8d9e774ae6acd2cb8f7b451a/src/graph/heterograph.h#L58
As a result, when the sub-graph is pickled/unpickled by workers/main process after …
> [Bugfix] Fix the uninitialized pin_memory flag for empty graph

- python/dgl/backend/pytorch/tensor.py
- python/dgl/dataloading/dataloader.py
- Fix `tensor.storage()` deprecation warning since PyTorch 2.0. Part of #5104.
- Remove several compatibility codes for old PyTorch versions.
> [Fix] Fix `tensor.storage()` deprecation warning

- python/dgl/distributed/dist_graph.py
- tests/distributed/test_dist_graph_store.py
fix for https://github.com/dmlc/dgl/issues/5631.
The crash happens when no `mask==1` nodes/edges are found for target partition. 
> [Dist] fix crash issue if empty test set

- graphbolt/CMakeLists.txt
As cuda is not used in graphbolt at present, remove it from cmake file.
> [GraphBolt] Remove cuda option in cmake 

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
After each release we should bump the nightly version on the master branch to let the nightly build continue.  I have updated the release build guide accordingly as well.  @czkkkkkk
> [Build] Bump nightly version

- python/dgl/homophily.py
- tests/python/common/test_homophily.py
Fail to calculate `dgl.linkx_homophily` when all class homophily = 0 due to inpropriate type of initial value.
```log
File "<stdin>", line 1, in <module>
File "${path_to_venv}/.venv/lib/python3.7/site-packages/dgl/homophily.py", line 189, in linkx_homophily
return value.item() / (num_classes - 1)
AttributeError: 'int' object has no attribute 'item'
```
Check issue #5710 for details.
> [Bugfix] `dgl.linkx_homophily` calculation fails when all class homophily=0

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/csc_sampling_graph.cc
Remove node and edge types from C graph, as they are not used for calculation.
> [Graphbolt] Remove node and edge types from C graph

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/include/graphbolt/sampled_subgraph.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/__init__.py
Fix some issues and do the binding for `SampledSubgraph`.
> [GraphBolt] Add subgraph binding

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/csc_sampling_graph.cc
add support for extracting induced subgraph from parent graph.
> [GraphBolt] add InSubgraph() for CSCSamplingGraph in c++ level

- graphbolt/src/shared_memory_utils.cc
Use `std::tuple_cat` to simplify the code of returning a tuple in a function.
@Rhett-Ying , I don't use variadic template when copy to/load from shared memory because it will make the code too complicated. It requires to write variadic template functions such as `CopyTensorMetaToTorchArchive`, `CopyTensorDataToSharedMemory`, and their loading version. We also need to handle torch tensors and optional tensors in these template functions.
> [Graphbolt] Improve code quality

- examples/pytorch/GATNE-T/requirements.txt
- examples/pytorch/GNN-FiLM/README.md
- examples/pytorch/TAHIN/readme.md
- examples/pytorch/cluster_gcn/README.md
- examples/pytorch/gatv2/README.md
- examples/pytorch/gin/README.md
- examples/pytorch/grace/README.md
- examples/pytorch/ogb/seal_ogbl/README.md
- examples/pytorch/stgcn_wave/README.md
Now, we have to use scikit-learn in pip requirements files as pip install sklearn is now deprecated. 
source: https://github.com/scikit-learn/sklearn-pypi-package
Change `sklearn` --> `scikit-learn`
> [Example][Minor] Update README/requirements from sklearn -> scikit-learn

- examples/pytorch/dtgrnn/train.py
By printing the messages: `Batch: XYZ` on the same line on the screen, we make the output of the training script much better:
```
Epoch: 0 Train Loss: 3.7948007539113364 Valid Loss: 2.795261863809866 Test Loss: 3.0333544105707206
Epoch: 1 Train Loss: 2.7208512636820474 Valid Loss: 2.720377560393147 Test Loss: 2.9376083156443222
Epoch: 2 Train Loss: 2.6939743881225584 Valid Loss: 2.725586600032616 Test Loss: 2.9333534335773077
Epoch: 3 Train Loss: 2.6862449487050375 Valid Loss: 2.693360625590208 Test Loss: 2.915788319969165
Epoch: 4 Train Loss: 2.683133149464925 Valid Loss: 2.6903926561599554 Test Loss: 2.944984791167583
Epoch: 5 Train Loss: 2.679369389851888 Valid Loss: 2.6951579150301144 Test Loss: 2.9178620783741143
Epoch: 6 Train Loss: 2.675840035120646 Valid Loss: 2.7057937984609755 …
```
> [Misc]Improving the output of the DCRNN training script.

- python/dgl/transforms/functional.py
- tests/python/common/transforms/test_transform.py
Current `khop_adj` api wrongly includes a transpose operation when accessing adjacency matrix. Fix the bug.
> [BugFix] Fix khop_adj

- tensoradapter/pytorch/CMakeLists.txt
C++ 17 is required to build pytorch extensions, after the latest pytorch upstream change. https://github.com/pytorch/pytorch/pull/100557
https://github.com/pytorch/pytorch/blob/52b32599650dd4346ae46550b08b1b4dd383d6cc/c10/util/C%2B%2B17.h#L25-L28
> [Build] use c++17 on tensoradaptor build

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
1. `__len__` and `__getitem__` are removed. Do not implement at all is the best practice and make `ItemSet`/`ItemSetDict` more flexible. For example, if `__len__` is defined which raise `NotImplementedError`, `list(item_set)` crashes.
2. add examples into docstring.
3. add size check for tuple items.
> [GraphBolt] refine ItemSet/ItemSetDict and add examples

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
1. define `__len__` to enable `len()` if possible. This definition will not result in crash if call with `list(item_set)`. Referred from https://github.com/pytorch/pytorch/blob/6acb8d3d1cf577b63cd11bf88c627d3e86669901/torch/utils/data/datapipes/iter/combinatorics.py#L47-L51 What's more, enabling length could make it possible to do optimization: slice batch of items from original data directly instead of iterating one by one.
2. remove size check for tuple items as `.size()` is available in `torch.Tensor` only, not general enough as `Iterable` is required only for the input items.
> [GraphBolt] define __len__ for ItemSet/ItemSetDict

- src/graph/unit_graph.cc
- tests/python/common/test_heterograph-misc.py
Based on the previous [PR#5851 [Sparse] Clean formats function docstring](https://github.com/dmlc/dgl/pull/5851) and [Issue#5846: [Sparse] Standardize the behavior of `formats()`](https://github.com/dmlc/dgl/issues/5846), this PR primarily accomplishes the following:
With these changes, the behavior of `formats()` will be consistent with its description in `heterograph.py`.
> [Sparse] Update code and add unittest for `formats` 

- python/dgl/distributed/dist_context.py
> [DistDGL] keep net_type in public API even it is deprecated

- python/dgl/distributed/partition.py
- tests/distributed/test_partition.py
under the help of `sorting logic` added here, any previously partitioned graphs/jsons could be handled correctly.
what's more, `sort_keys=False` will make sure dumped node/edge_map is what we expected.
> [DistDGL] sort node/edge_map to obtain expected id ranges

- tests/backend/backend_unittest.py
- tests/backend/mxnet/__init__.py
- tests/backend/pytorch/__init__.py
- tests/backend/tensorflow/__init__.py
- tests/python/pytorch/nn/test_nn.py
To make a comparison "before/after" doable,  there is a need to have the same internal results (matrices) -> the same seed for each run should be used for all randomized functions.
> [TESTS] Make pytorch test_nn.py fully reproducible

- python/dgl/data/utils.py
I change the paper link in the [docstring](https://docs.dgl.ai/generated/dgl.data.utils.add_node_property_split.html) of `dgl.data.utils.add_node_property_split` and `dgl.data.utils.mask_nodes_by_property` in order to cite the latest version of our paper, not the first one.
This resolves the issue https://github.com/dmlc/dgl/issues/5897.
> [Doc] fix the paper link in `dgl.data.utils.add_node_property_split`

- graphbolt/src/csc_sampling_graph.cc
- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
This PR use torch built-in dispatch macro to dispatch types of edge ids, and change all related data access from 'item()' to raw pointer.
This PR combined with #5890 will improve the performance by around 30%.
> [Graphbolt] Dispatch edge ids in neighbor sampling

- src/array/cpu/rowwise_pick.h
Accelerating the row pick process by using binary search instead of linear search to find the boundary of an edge type.
> [Performance] Use binary search in rowwise pick

- tests/lint/pylintrc
Add `dp` and `it` as good names since they are commonly used in PyTorch DataPipe codes.
> [GraphBolt] Pylintrc changes

- graphbolt/src/csc_sampling_graph.cc
- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
This PR use torch built-in dispatch macro to dispatch scalar type of edge type, and change all replated data access from 'item()' to raw pointer.
In the local test, this change combined with #5889 will improve the e2e performance of `sample_neighbors` by around 30%.
> [GraphBolt] Dispatch type edges in neighbor sampling 

- tests/python/common/ops/test_ops.py
- tests/python/pytorch/distributed/optim/test_dist_optim.py
Previously the test was run on doubles, as NumPy produces doubles by default.
Additionally set seed to make tests fully reproducible.
> [Test] Run test_spmm also on floats

- python/dgl/graphbolt/graph_storage/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
I find it's common to convert DGLGraph to CSCSamplingGraph such as constructing graph topology when creating Dataset for GraphBolt on disk or converting from coo(#5820)
> [GraphBolt] enable to convert DGLGraph to CSCSamplingGraph

- tests/python/pytorch/graphbolt/test_csc_sampling_graph.py
`__main__` is not required in pytest unit test scripts: https://docs.pytest.org/en/7.3.x/explanation/goodpractices.html#conventions-for-python-test-discovery
> [GraphBolt] remove main function from unit test script

- python/dgl/transforms/functional.py
This is to fix https://github.com/dmlc/dgl/issues/5943.
Due to this PR: https://github.com/scipy/scipy/pull/18508, scipy changes the output of divide (sparse, dense) from dense to sparse format. As a result, it would break the function `random_walk_pe`, as follows:https://github.com/dmlc/dgl/blob/4b585ba068b67f10a25eada64532c09da6561d10/python/dgl/transforms/functional.py#L3592
Reference: 
Release note of scipy 1.11.0: https://github.com/scipy/scipy/releases/tag/v1.11.0
If scipy < 1.11.0, uses `np.array` to change the output to dense ndarray.
Otherwise, uses `.toarray()` to change the output to dense ndarray.
> [Bugfix] Update dgl function `random_walk_pe` to be compatible with latest scipy 

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/utils.py
- tests/python/pytorch/graphbolt/test_dataset.py
add support for TVT sets of homograph/hetergraph + node/edge + classification/prediction.
> [GraphBolt] add support to generate TVT in ItemSet or ItemSetDict format

- python/dgl/graphbolt/feature_store.py
- tests/python/pytorch/graphbolt/test_feature_store.py
> [GraphBolt] update FeatureStore to use tuple as key

- src/array/cpu/spmm.h
Unfortunately SpMM Cmp was disabled for AVX2 and less platforms in [LIBXSMM](https://github.com/libxsmm/libxsmm/blob/main_stable/src/generator_mateltwise_sse_avx_avx512.c#L746)
Resolves https://github.com/dmlc/dgl/issues/5960
> [Misc] Disable LibXSMM SpMM Cmp for AVX2 platforms

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
To be unified, let's use `type`(used in `feature_data`) instead of `type_name` in TVT.
> [GraphBolt] use type instead of type_name to be unified

- include/dgl/aten/coo.h
- include/dgl/aten/csr.h
- python/dgl/dataloading/labor_sampler.py
- python/dgl/sampling/labor.py
- src/array/array.cc
- src/array/array_op.h
- src/array/cpu/labor_pick.h
- src/array/cpu/labor_sampling.cc
- src/array/cuda/labor_sampling.cu
- src/graph/sampling/neighbor/neighbor.cc
- src/random/continuous_seed.h
Adding dependency between sampled minibatches increases temporal locality of graph and feature accesses. This can be utilized with the GPU cache PR #4341. #4718 also depends on this PR.
> [Feature] Adding kappa feature for labor (Cooperative Minibatching)

- benchmarks/benchmarks/api/bench_fused_sample_neighbors.py
- include/dgl/aten/csr.h
- include/dgl/sampling/neighbor.h
- python/dgl/dataloading/neighbor_sampler.py
- python/dgl/sampling/neighbor.py
- src/array/array.cc
- src/array/array_op.h
- src/array/cpu/concurrent_id_hash_map.cc
- src/array/cpu/concurrent_id_hash_map.h
- src/array/cpu/rowwise_pick.h
- src/array/cpu/rowwise_sampling.cc
- src/graph/sampling/neighbor/neighbor.cc
- src/graph/unit_graph.cc
- src/graph/unit_graph.h
- tests/python/common/sampling/test_sampling.py
Changes described and discussed in github RFC https://github.com/dmlc/dgl/issues/5328.
This change introduces new algorithm for NeighborSampler class. This algorithm samples mini-batches from hetero/homo-geneous graphs in one c++ function that compacts functionalities of _CAPI_DGLToBlock and _CAPI_DGLSampleNeighbors reducing time of this process. Moreover sampled DGLBlocks are already in CSC/CSR format and as such they require no COOToCSR transformation for forward pass.  Additional COO matrix is attached as well to avoid CSRTranspose function call when it would be necessary for backward pass.
Coauthor: @hesham-mostafa
- ogbn-products and ogbn-papers100M datasets
- DGL built with DUSE_LIBXSMM=ON DUSE_CUDA=OFF DBUILD_SPARSE=OFF
- Benchmark script consists of sampling and forward_backward …
> [Performance] Fused sampling with compaction

- graphbolt/src/csc_sampling_graph.cc
We've optimized the `SampleNeighborsImpl` function in `csc_sampling_graph.cc`. This PR primarily resolves this [Issue#5817 Optimize CSC neighbor sampler performance.](https://github.com/dmlc/dgl/issues/5817)
The original algorithm, when conducting multithreaded Neighbor Sampling, would place all sampled results into a general vector of Tensor. We want to optimize this part.
Let's consider a scenario where we have $n$ `Tensors`(same size) and $m$ `threads`, and we need to concatenate all `Tensors` into one large `Tensor`. We consider two different strategies:
- Strategy **A**: Each `thread` uses `torch::cat` to combine up to $\frac{n}{m}$ `Tensors` into a `big Tensor`, then `torch::cat` is used again to combine the $m$ `big Tensors` into the `result`.
- Strategy **B**: Each `thread` only …
> [Graphbolt] Add `cat` optimization for UniformPick

- python/dgl/backend/pytorch/tensor.py
- tests/python/pytorch/utils/test_pin_memory.py
Calling pin_memory_() on a DGLBlock can generate errors for cases in which there are empty views. This PR makes it so we only ensure non-empty Tensors are contiguous and not views, since it is no-op in these cases.
> [Bugfix] Allow pinning of empty tensor

- examples/pytorch/gatv2/train.py
- examples/pytorch/model_zoo/citation_network/run.py
In the current PR we eliminate the following warnings:
```
/usr/local/lib/python3.10/dist-packages/dgl/data/utils.py:354: UserWarning: Property dataset.num_labels will be deprecated, please use dataset.num_classes instead.
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
```
and few nan outputs:
```
Epoch 00000 | Time(s) nan | Loss 1.9473 | TrainAcc 0.1143 | ValAcc 0.1900 | ETputs(KTEPS) nan
Epoch 00001 | Time(s) nan | Loss 1.9422 | TrainAcc 0.1643 | ValAcc 0.2840 | ETputs(KTEPS) nan
Epoch 00002 | Time(s) nan | Loss …
```
> Improving the GATv2 example.

- examples/pytorch/dgi/train.py
- examples/pytorch/model_zoo/citation_network/run.py
In the current PR we eliminate the following warnings:
```
/usr/local/lib/python3.10/dist-packages/dgl/data/citation_graph.py:314: RuntimeWarning: divide by zero encountered in power
r_inv = np.power(rowsum, -1).flatten()
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
```
and few `nan` outputs:
```
Epoch 00000 | Time(s) nan | Loss 1.3864 | ETputs(KTEPS) nan
Epoch 00001 | Time(s) nan | Loss 1.3987 | ETputs(KTEPS) nan
Epoch 00002 | Time(s) nan | Loss 1.3864 | ETputs(KTEPS) nan
```
Current PR is quite similar to …
> Improving the DGI example.

- examples/pytorch/hardgat/train.py
- examples/pytorch/model_zoo/citation_network/run.py
In the current PR we eliminate the following warnings:
```
/usr/local/lib/python3.10/dist-packages/dgl/data/utils.py:354: UserWarning: Property dataset.num_labels will be deprecated, please use dataset.num_classes instead.
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
```
and few `nan` outputs:
```
Epoch 00000 | Time(s) nan | Loss 1.7912 | TrainAcc 0.1917 | ValAcc 0.5440 | ETputs(KTEPS) nan
Epoch 00001 | Time(s) nan | Loss 1.7897 | TrainAcc 0.2417 | ValAcc 0.6600 | ETputs(KTEPS) nan
Epoch 00002 | Time(s) nan | Loss …
```
> Improving the HARD_GAT example

- python/dgl/dataloading/dataloader.py
- python/dgl/storages/tensor.py
Branched off of #4341 to utilize gpu cache inside dataloader to cache feature copies. #4718 depends on this feature. Only the dataloader is modified in this PR. Should be merged after #4341.
@frozenbugs
> [Feature] Dataloader gpu cache

- python/dgl/_ffi/_cython/ndarray.pxi
Update some Cython Code in python/dgl/_ffi/_cython/ndarray.pxi to adapt the latest cython version.
The original version of code would raise error:
```
[1/1] Cythonizing dgl/_ffi/_cython/core.pyx
Error compiling Cython file:
------------------------------------------------------------
...
"""
cdef DLManagedTensor* dltensor
if self.c_is_view != 0:
raise ValueError("to_dlpack do not work with memory views")
CALL(DGLArrayToDLPack(self.chandle, &dltensor, alignment))
return pycapsule.PyCapsule_New(dltensor, _c_str_dltensor, _c_dlpack_deleter)
^
------------------------------------------------------------
dgl/_ffi/_cython/./ndarray.pxi:80:66: Cannot assign type 'void (object) except *' to 'PyCapsule_Destructor'
File "/home/ubuntu/dgl/python/setup.py", line …
```
> [BugFix] Updated some Cython code to adapt to Cython 3.0.0 version.

- docs/source/guide/mixed_precision.rst
- examples/pytorch/gat/train.py
- examples/pytorch/gcn/train.py
- examples/pytorch/graphsage/node_classification.py
- examples/pytorch/graphsage/train_full.py
- python/dgl/backend/backend.py
- python/dgl/backend/pytorch/tensor.py
- python/dgl/backend/tensorflow/tensor.py
- python/dgl/frame.py
- python/dgl/transforms/functional.py
- tests/python/common/test_heterograph.py
Added functions to support bfloat16 graph conversion.
Performance collected on Intel(R) Xeon(R) Platinum 8480+ (4th Generation Xeon, which supports [AMX](https://en.wikipedia.org/wiki/Advanced_Matrix_Extensions) instruction)
| #threads     |               | 16            |          |                    | full socket   |          |                    |
|--------------|---------------|---------------|----------|--------------------|---------------|----------|--------------------|
| example      | dataset       | Test accuracy |          | perf diff % | Test accuracy |          | perf diff % |
|              |               | float         | bf16 |                    | float         | bf16 |                    |
| gat          | citeseer      | 0.706         | 0.707    | 1.500155075        | …
> [Feature] Enable bfloat16 convert functions in Python API

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/impl/__init__.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/link_data_format.py
- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
UDF of negative sampler in graphbolt.
> [Graphbolt]Add negative sampler udf

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- python/dgl/graphbolt/utils/internal.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
New format:
```
train_sets:
- type: paper
data: # each file will be one element in tuple of ItemSet.
- format: numpy
path: set/paper-train-src.npy
- format: numpy
path: set/paper-train-dst.npy
- format: numpy
path: set/paper-train-label.npy
- type: author
data: # each file will be one element in tuple of ItemSet.
- format: numpy
path: set/author-train-src.npy
- format: numpy
path: set/author-train-dst.npy
- format: numpy
path: set/author-train-label.npy
validation_sets:
- type: author
data: # each file will be one element in tuple of ItemSet.
- format: numpy
path: set/author-val-src.npy
- format: numpy
path: set/author-val-dst.npy
- format: numpy
path: set/author-val-neg-src.npy
- format: numpy
path: set/author-val-neg-dst.npy
test_sets:
- type: paper
data: # each file will be one element …
```
> [GraphBolt] change TVT format of OnDiskDataset

- graphbolt/src/csc_sampling_graph.cc
- python/dgl/graphbolt/impl/csc_sampling_graph.py
Change the Labor sampling algorithm to match the behavior of Neighbor algorithm.
I simply changed the calculation of the actual picked number at the beginning of Labor process. However, since soon the picked number will be calculated in advance, this calculation will become useless and will be deleted.
Trying to solve https://github.com/dmlc/dgl/pull/6101/files/5e0de154b1d896e5c26be164b3480b9b81232c6c#r1285651084.
- Modified Labor.
- Modified comments.
> [Graphbolt] Update the sampler algorithm documentation for fanout = -1.

- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/test_dataset.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
`TVT` is wrapped into `Task` and data format is shown below:
```
tasks: # Multiple tasks are listed below.
- name: "node_classification" # "node/link/graph prediction/classification"
num_classes: 3
train_set:
- type: 'paper:cites:paper'
data: # each file will be one element in tuple of ItemSet.
- format: numpy
path: set/cites-train-src.npy
- format: numpy
path: set/cites-train-dst.npy
- format: numpy
path: set/cites-train-label.npy
- type: 'author:writes:paper'
data: # each file will be one element in tuple of ItemSet.
- format: numpy
path: set/writes-train-src.npy
- format: numpy
path: set/writes-train-dst.npy
- format: numpy
path: set/writes-train-label.npy
validation_set:
- type: 'author:writes:paper'
data: # each file will be one element in tuple of ItemSet.
- format: numpy
path: …
```
> [GraphBolt] wrap tvt with task structure

- script/dgl_dev.yml.template
`model_validator` requires pydantic>=2.0
> [dev] specify minimum version of pydantic

- python/dgl/nn/pytorch/conv/gatedgraphconv.py
In the GatedGraphConv, the out_feats (output dimension) must be not less than in_feats (input dimension), so add assert in  GatedGraphConv __init__ function.
related issue: https://github.com/dmlc/dgl/issues/6042
``` python
>>> from dgl.nn import GatedGraphConv
>>> conv = GatedGraphConv(10, 10, 2, 3) # No problem
>>> conv = GatedGraphConv(10, 5, 2, 3)# raise assert
File "<stdin>", line 1, in <module>
File "dgl/python/dgl/nn/pytorch/conv/gatedgraphconv.py", line 63, in __init__
assert in_feats <= out_feats, "out_feats must be not less than in_feats"
AssertionError: out_feats must be not less than in_feats
```
> [BugFix] add input/output shape check in GatedGraphConv

- python/dgl/transforms/functional.py
- tests/python/common/transforms/test_transform.py
Removing the following warning that appears in tests implemented in `tests/python/common/transforms/test_transform.py`:
```
================================================================================================= warnings summary =================================================================================================
tests/python/common/transforms/test_transform.py: 10 warnings
/usr/local/lib/python3.10/dist-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
dgl_warning(
tests/python/common/transforms/test_transform.py::test_reverse_shared_frames[idtype0]
tests/python/common/transforms/test_transform.py::test_reverse_shared_frames[idtype1]
/usr/local/lib/python3.10/dist-packages/dgl/transforms/functi …
```
> Improving transform tests.

- python/dgl/backend/pytorch/tensor.py
- python/dgl/convert.py
- tests/python/common/test_propagate.py
- tests/python/common/test_subgraph.py
- tests/python/common/test_traversal.py
Removing the following warning that appears in tests implemented in `test_heterograph-update-all.py`, `test_heterograph.py`, ``test_propagate.py`, `test_subgraph.py` and `test_traversal.py`:
```
================================================================================================= warnings summary =================================================================================================
tests/python/common/test_heterograph-update-all.py::test_binary_op[idtype0]
tests/python/common/test_heterograph-update-all.py::test_binary_op[idtype1]
/usr/local/lib/python3.10/dist-packages/dgl/backend/pytorch/tensor.py:509: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed.
Its .grad attribute won't be populated during autograd.backward(). If you …
```
> Fixing some unittest warnings.

- graphbolt/src/concurrent_id_hash_map.cc
This is a patch pr for id_map, throw an exception when key not found.
> [Graphbolt]Throw exception when id not found

- src/array/cuda/csr_mm.cu
According to the [doc](https://docs.nvidia.com/cuda/cusparse/index.html#:~:text=the%20pointer%20csrRowOffsets%20must%20be%20not%20NULL) (cuda 12.2), it states `csrRowOffsets` must be not NULL for the function `cusparseCreateCsr`. This PR sets the `csrRowOffsets` to a proper value for compatible with cuda 12.2 release.
The fifth argument of `cusparseCreateCsr` is set to `dC_csrOffsets_data`.
> [Bugfix] Fix cusparseCreateCsr format for cuda12

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
This PR primarily addresses the issue: [[Graphbolt] Update OndiskDataset loading logic](https://github.com/dmlc/dgl/issues/6022).
In the previous PR: [[Graphbolt] Update preprocess to Accept Dataset Path Instead of YAML File Path](https://github.com/dmlc/dgl/pull/6091). We've observed that moving the `dataset` directory invalidates the prior preprocessing due to absolute path issues.
To address this, we now ensure that after preprocessing, all paths within the YAML file are relative. To ensure data accessibility from any location, we've introduced a `_convert_yaml_path_to_absolute_path` function, which temporarily converts paths in the YAML to absolute paths before loading.
> [Graphbolt] Enhance preprocessing: Ensure relative paths in YAML and convert to absolute paths before loading.

- src/array/cuda/bf16.cuh
- src/array/cuda/fp16.cuh
CUDA 12.2 adds "emulated" support for FP16/BF16 operators on older devices ([reference](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-math-release-12-2)), which causes conflicts with the overloads we have in DGL.
> [Build] Fix bf16/fp16 building issues for CUDA 12.2

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/csc_sampling_graph.cc
As the pick numbers are calculated beforehand, we can pre-allocate tensors for nodes.
I adjusted the pick functions to put the result directly into allocated tensor storage.
In detail, I added one more param to pick method functions: `picked_data_ptr`, the address of the reserved tensor data.
This is the step 3 out of 4. The main process will be rewritten in the next PR (the small modification in the `SampleNeighborsImpl` in this PR is just a temporary adaptation).
> [Graphbolt] Utilize pre-allocation in sampling

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/test_ondisk_dataset.py
This PR addresses the issue: [[Graphbolt] Update OndiskDataset loading logic](https://github.com/dmlc/dgl/issues/6022).
In the previous PRs:  [[Graphbolt] Update preprocess to Accept Dataset Path Instead of YAML File Path](https://github.com/dmlc/dgl/pull/6091) and [[Graphbolt] Enhance preprocessing: Ensure relative paths in YAML and convert to absolute paths before loading. ](https://github.com/dmlc/dgl/pull/6110), we have completed the enhancement of the `preprocess_ondisk_dataset`function.
Now, we need to update the `OndiskDataset` loading logic to: **Implement a two-step loading process, where the initiation method only loads the YAML, and adds a `.load()` method to trigger the actual loading.**
I have added comprehensive tests to cover as many cases as possible in `.load` function. …
> [Graphbolt] 2-step loading, Add `OnDiskDataset.load()` method to trigger actual loading.

- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
Change negative sampler input ot `LinkPredictionBlock`.
> [Graphbolt] Adapt negative sampler input

- python/dgl/distributed/standalone_kvstore.py
The standalone kvstore should maintain the gdata name list correctly.
> Fix a bug in standalone mode

- python/dgl/graphbolt/utils/sample_utils.py
- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
Change compact result from tuple to list, this is a patch for current solution.
> [Graphbolt] Patch: Change compact to list 

- docs/source/guide/data-loadcsv.rst
- python/dgl/data/csv_dataset_base.py
- tests/python/common/data/test_data.py
In the test `_test_DefaultDataParser`, when `data_frame` is saved to CSV file with parameter `index=True`: 
```
data_frame.to_csv(csv_path, index=True)
```
a column named "Unnamed 0:" is created. There was a test for reading such CSV files but it was accidentally deactivated by [PR#6144](https://github.com/dmlc/dgl/pull/6144), where we started using
```
data_frame.to_csv(csv_path, index=False)
```
for all subtests.
In the current PR, we are restoring testing of reading CSV files with unnamed columns and fixing a few typos.
> Testing a data frame with unnamed columns.

- tests/python/common/cuda/test_gpu_cache.py
Elimination  of the following warning that appears in `test_gpu_cache` implemented in `cuda/test_gpu_cache.py`:
```
tests/python/common/cuda/test_gpu_cache.py::test_gpu_cache[idtype0]
tests/python/common/cuda/test_gpu_cache.py::test_gpu_cache[idtype1]
/usr/local/lib/python3.10/dist-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
```
> Improving gpu_cache test.

- python/dgl/transforms/functional.py
> [Optimization] Use scipy's eigs instead of numpy in lap_pe

- python/dgl/graphbolt/itemset.py
- python/dgl/graphbolt/minibatch_sampler.py
- tests/python/pytorch/graphbolt/test_itemset.py
- tests/python/pytorch/graphbolt/test_minibatch_sampler.py
update in `ItemSet` and `MinibatchSampler`. part of https://github.com/dmlc/dgl/issues/6211.
> [GraphBolt] use str instead of tuple for canonical etype

- python/dgl/graphbolt/data_block.py
- python/dgl/graphbolt/link_prediction_block.py
> [GraphBolt] use str etype in data block

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/negative_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] use str etype in sampler

- python/dgl/transforms/functional.py
Avoid importing `packaging` directly. Use `dgl.utils.version` instead, which handles the situation where `packaging` is not installed.
Resolves https://github.com/dmlc/dgl/issues/6258.
> [Bug] Avoid importing packaging directly

- graphbolt/src/csc_sampling_graph.cc
Deleted an time-expensive check in NeighborSampling.
Solve #6257.
Only tested the affected branches:
Before:
Labor, False, True: 51.4157
Labor, True, True: 86.6231
After:
Labor, False, True: 33.5337
Labor, True, True: 66.5594
- Deleted a check.
> [Graphbolt] Delete the expensive check

- examples/sampling/link_prediction.py
Fix typo in description of official example for link prediction with sampling: file name of previous example should be `node_classification.py` instead of `link_prediction.py`.
> [Doc] Fix typo in link prediction with sampling example

- graphbolt/include/graphbolt/csc_sampling_graph.h
- graphbolt/src/csc_sampling_graph.cc
- graphbolt/src/shared_memory_utils.cc
- graphbolt/src/shared_memory_utils.h
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
I plan to add a `SharedMemoryHelper` to refactor the shared memory utility. With this class, the  copy to/read from shared memory logic may become:
```c++
void save_to_shm() {
SharedMemoryHelper helper;
helper.WriteTensor(indptr);
helper.WriteTensor(indices);
...
helper.WriteTensorDict(edge_attributes);
}
void load_from_shm() {
indptr = helper.ReadTensor();
indices = helper.ReadTensor();
...
}
```
Basically I will maintain a offset to the shared memory to record the number of bytes that have beed read/write. All data structure read/write will append after the offset. @frozenbugs, please let me know whether the design make sense to you.
Resolve #6192.
> [Graphbolt] Refactor shared memory utility.

- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_matrix.cc
- python/dgl/sparse/sparse_matrix.py
- tests/python/pytorch/sparse/test_sparse_matrix.py
Sparse slice operator implementation, include index_select and range_select.
> [Sparse] Add sparse matrix slicing operator implementation

- python/dgl/graphbolt/item_sampler.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
Add mapper to instantiate `MiniBatch`. Removals of `minibatch_converter` in other testcases will be done in another PR after this one is merged.
> [GraphBolt] convert item list to MiniBatch

- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
For now, we assume `node_pairs` are saved/loaded as a tensor with shape of `(N, 2)` while it's assumed to be tuple of `(src , dst)` in `MiniBatch.node_pairs` and following modules. This PR aims to remove such discrepancy.
Another solution is to loaded from ondisk via `seed_srcs` and `seed_dsts` separately and pass them to instantiate `MiniBatch.node_pairs` to compose the tuple of `(src, dst)`. [Existing test cases for `NegativeSampler` are using this format.]
So the question is what kind of data format we're assuming for `node_pairs`: a `(N, 2)` tensor or 2 separate tensor of `(N, 1)`.
One more alternative:
```
node_pairs = (torch.arange(0, 5), torch.arange(5, 10))
labels = torch.arange(0, 5)
np.save()
np.load()
item_set = gb.ItemSet((node_pairs, labels), names=("node_pairs", "labels")) …
```
> [GraphBolt] split node_pairs to tuple of (src, dst)

- python/dgl/sparse/sparse_matrix.py
Define sparse sample operator API.
> [Sparse] Add sparse sample python API

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/negative_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] enable to invoke gb samplers in functional form

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
The original implementation of `ItemSet.__iter__` uses `zip` to obtain an iterator for `self._items`. When `self._items` is a `tuple` of `torch.Tensor`, `zip(self._items)` ends up calling `torch.unbind(0)`, which pre-slices the tensor and need a lot of time.
Although using `zip` is more efficient, it results in **significant waiting time for the user**( $100\sim 200s$ for most case). We've opted for a straightforward `for` loop to yield each item. While this approach incurs some performance overhead, it offers a better user experience, especially during **debugging** or when the full dataset is not required for training.
The following are the performance reports for both approaches. The share of time taken by `zip` (1.6%) and `for` (3.2%) in the overall training phase is negligible, …
> [Graphbolt] Use `for` to implement `ItemSet.__iter__`

- tests/tools/test_launch.py
- tools/launch.py
This PR fixes future warning from ``torch.distributed.launch`` (discussed in issue #5493) with minor fix typo.
The ``torch.distributed.launch`` module is deprecated and it always prints ``FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.``.
Note that the typo issue from ``--local-rank`` argument is already fixed.
> [Tools] use torchrun instead of torch.distributed.launch

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
> [GraphBolt] fix type_per_edge when convert DGLGraph to CSCSamplingGraph

- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/sparse_matrix.cc
- python/dgl/sparse/sparse_matrix.py
- tests/python/pytorch/sparse/test_sparse_matrix.py
The implementation of sparse 'sample' operator. The sparse 'sample' operator differs slightly from DGL's 'sample' API. In the sparse sample, it only returns the submatrix selected by the index, rather than the entire original matrix.
> [Sparse] Sparse sample implementation

- CMakeLists.txt
- cmake/modules/CUDA.cmake
Move DGL cuda file declaration to the main CMakeLists.txt. Later both graphbolt and dgl sparse can use `dgl_config_cuda` to configure CUDA compilation
> [CMAKE] Move DGL cuda file declaration to the main CMakeLists.txt

- python/dgl/nn/pytorch/explain/pgexplainer.py
- tests/python/pytorch/nn/test_nn.py
Implemented Node explanations for PGExplainer (https://arxiv.org/pdf/2011.04573.pdf) for Heterogenous Graphs. (extending https://github.com/dmlc/dgl/pull/5739)
* Added the `explain_node` method for heterogeneous implementation of PGExplainer.
* cleaned up `explain_node` internals for homogeneous implementation 
An example of using the method is included in the documentation.
Tests run for [MUTAG visualization scripts](https://gist.github.com/ndbaker1/68b956f9232acc948116e90d3aad14af#file-hetero_pgexplainer_node-py) utilizing `explain_node`.
> [Model] Add Node explanation for Heterogenous PGExplainer Impl. 

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/minibatch_transformer.py
- python/dgl/graphbolt/negative_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
With this PR, the follow UX are supported:
import dgl.graphbolt as gb
datapipe = datapipe.transform(gb.exclude_seed_edges)
datapipe = datapipe.transform(gb.exclude_seed_edges_and_reverse(reverse_etypes={}))
> [Graphbolt] Add MiniBatchTransformer to support exclude edges.

- python/dgl/sparse/sparse_matrix.py
Add sparse relabel python API, a resubmission of https://github.com/dmlc/dgl/pull/6316 
> [Sparse] Add relabel python API 

- examples/sampling/graphbolt/link_prediction.py
```
~/workspace/dgl_2$ DGL_HOME=/home/ubuntu/workspace/dgl_2 DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=tests:$DGL_HOME/python:tests/python/pytorch/graphbolt:$PYTHONPATH python3 examples/sampling/graphbolt/link_prediction.py 
Training in cpu mode.
Loading data
Downloading datasets/ogbl-citation2.zip from https://data.dgl.ai/dataset/graphbolt/ogbl-citation2.zip...
Extracting file to datasets
Training...
0%|                                                                                                                                                            | 0/10 [00:00<?, ?it/s]Epoch 00000 | Step 00100 | Loss 0.3516
0%|                                   
```
> [GraphBolt] update example to use built-in dataset

- src/geometry/geometry.cc
Fixed "used but never defined",
> [Misc] Fix compile warning

- python/dgl/data/__init__.py
- python/dgl/data/lrgb.py
- tests/integration/test_data.py
The peptides structural dataset based on DGLDataset
Related issue: https://github.com/dmlc/dgl/issues/5352
> [Dataset] Add peptides structural dataset in LRGB

- python/dgl/data/utils.py
Fix overwrite default parameter in extrace_archive function
> [Bug] fix extrace_archive default parameter

- examples/sampling/graphbolt/lightning/README.md
- examples/sampling/graphbolt/lightning/node_classification.py
Using `sample_layer_neighbor` for training is not only faster but also gives the same accuracy as `sample_neighbor`. Since graphbolt layer neighbor sampler has the same quality of implementation as neighbor sampler, there is no reason we shouldn't recommend and show the users the new sampler for the node prediction example. Graphbolt should showcase the best available functionality to the users for each use case especially if there are no drawbacks of doing so. It is not an advanced functionality either, just replace `sample_neighbor` with `sample_layer_neighbor`.
The added `log_node_and_edge_counts` function shows the user how many nodes and edges are sampled. It is not crucial to keep it in case it creates unwanted output.
Results with early stopping:
``` …
```
> [GraphBolt] Improving the node prediction example

- python/dgl/dataloading/labor_sampler.py
- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/sampling/labor.py
> Update Labor sampler docs, add NeurIPS acceptance

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
Support return reverse edge ids in sampling, which always used when need edge features.
> [Graphbolt] Support return reverse edge ids in sampling

- dgl_sparse/CMakeLists.txt
Support the compilations of sparse native operators. After this PR, CUDA operators can be added in `dgl_sparse/src/cuda`. I didn't refactor the compilation of CUDA as suggested by [@yaox12 in this PR](https://github.com/dmlc/dgl/pull/6300#issuecomment-1711143917) to get rid of `FindCUDA` because it cannot find some CUDA flags like `CUDA_NVCC_EXECUTABLE`.
> [Sparse] Add CUDA compilation support.

- docs/source/api/python/dgl.data.rst
- python/dgl/data/__init__.py
- python/dgl/data/lrgb.py
- tests/integration/test_data.py
The peptides functional dataset based on DGLDataset
Related issue: https://github.com/dmlc/dgl/issues/5352
> [Dataset] Add peptides functional dataset in LRGB

- docs/source/api/python/dgl.data.rst
- python/dgl/data/__init__.py
- python/dgl/data/lrgb.py
- tests/integration/test_data.py
The Pascal VOC Superpixels dataset based on DGLDataset
Related issue: https://github.com/dmlc/dgl/issues/5352
> [Dataset] Add VOCSuperpixels dataset in LRGB

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
I've made modification to `gb.from_dglgraph` function to store the `ORIGINAL_EDGE_ID` within the CSCSamplingGraph.
Additionally, I've implemented the requisite unit test to validate the correctness of the `ORIGINAL_EDGE_ID` mapping. By utilizing the `CSCSamplingGraph` and the mapping, we can retrieve node pairs from the `DGLGraph` and verify their equalities. 
More Specifically:
```mermaid
graph TD;
Start(Start) --> GetCOO[Generate COO Representation];
GetCOO --> CheckEdgeMapping[Verify Edge Mapping using ORIGINAL_EDGE_ID];
CheckEdgeMapping --> End(End);
```
```mermaid
graph TD;
Start(Start) --> MapNodeIDs["Create Node ID Mapping (GB -> DGL)"];
MapNodeIDs --> GetCOO[Generate COO Representation by Node ID Mapping];
GetCOO --> VerifyEtypes[Verify GraphBolt and DGL Edge Type Order]; …
```
> [GraphBolt] Store `ORIGINAL_EDGE_ID` in CSCSamplingGraph's `edge_attributes`.

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/impl/ondisk_metadata.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
to avoid import error when pydantic 1.10 is installed.
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-1-326679278365>](https://localhost:8080/#) in <cell line: 10>()
10 try:
11     import dgl
---> 12     import dgl.graphbolt as gb
13     installed = True
14 except ImportError as e:
4 frames
[/usr/local/lib/python3.10/dist-packages/dgl/graphbolt/impl/ondisk_metadata.py](https://localhost:8080/#) in OnDiskTaskData()
81     extra_fields: Optional[Dict[str, Any]] = {}
82 
---> 83     @pydantic.model_validator(mode="before")
84     @classmethod
85     def build_extra(cls, values: Dict[str, Any]) -> Dict[str, Any]:
AttributeError: module 'pydantic' has no attribute 'model_validator'
```
> [GraphBolt] support both pydantic 1.x and 2.x

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
Currently, the `__init__` function of `ItemSet` only accepts `Iterable` or `Turple[Iterable]` as parameters. This PR enables it to accept an integer.
> [GraphBolt] Enable ItemSet to initiate by integer

- python/dgl/dataloading/neighbor_sampler.py
It fixes the issue https://github.com/dmlc/dgl/issues/6315 (at least for CPU-only configuration)
The fused version of NeighborSampler (sample_neighbors_fused) is prepared as multithreaded, so we can not use it when the number of available threads is lower than 2.
This way we can achieve the same performance as previously with not fused version (which is also multithreaded but with less overhead).
Performance results of the script from the issue https://github.com/dmlc/dgl/issues/6315 (modified to be allowed to run on CPU-only configuration) on AWS EC2 instance r6i.32xlarge (2 socket Intel(R) Xeon(R) Platinum 8375C) are as follow :
> [Performance] Do not fuse neighbor sampler for 1 thread

- graphbolt/src/csc_sampling_graph.cc
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
As highlighted in [Issue: [GraphBolt] Enable CSCSamplingGraph::edge_attributes save and load](https://github.com/dmlc/dgl/issues/6406), the original `CSCSamplingGraph::Load` and `CSCSamplingGraph::Save` methods do not support saving and loading `CSCSamplingGraph::edge_attributes`.
I've updated the function to address this. However, the latest `BuiltinDataset` doesn't include `edge_attributes`, which I'll address later.
I believe there's room for improvement in my implementation. Please review and suggest refinements.
> [GraphBolt] Enable `CSCSamplingGraph::edge_attributes` save and load.

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
1. Change the return type of `CSCSamplingGraph.num_nodes` from `Dict[str, Tensor]` to `Dict[str, int]` ;
2. Change `ItemSet or ItemSetDict` to `Union[ItemSet, ItemSetDict]` .
> [Misc] Polish the python code

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Add a load option `original_edge_id` for `preprocess` and `from_dglgraph`. 
After adding this option, we should determine the need for `gb.ORIGINAL_EDGE_ID` before preprocessing.
> [Graphbolt] Add a load option `original_edge_id` for `preprocess` and `from_dglgraph`

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
This PR is part of performance improvement for shuffle/batching in `ItemSampler`.
see more details in https://quip-amazon.com/bIfOAW6GMsIG/Benchmark-on-rgcnhetero#temp:C:FIGba38038eb04347578db86f3f1
> [GraphBolt] enable indexing on ItemSet instance

- examples/sampling/graphbolt/link_prediction.py
Use API `size()` to replace the operation of getting feature size.
> [Misc] Replace API to get feature size in example `link prediction`.

- python/dgl/graphbolt/impl/csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py
Modify function `from_dglgraph()` in `python/dgl/graphbolt/impl/csc_sampling_graph.py`, forbidding Initializing and passing metadata in case of homogenous graph.
> [GraphBolt] Modify `from_dglgraph()`

- python/dgl/transforms/functional.py
Fix issue [#6423](https://github.com/dmlc/dgl/issues/6423). 
Fixed function lap_se() branch bug.
> [Sparse] Fix graph_transformer example

- python/dgl/graphbolt/item_sampler.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
```
num_users = num_ids // 2
ids = {
"user": gb.ItemSet(
(torch.arange(0, num_users), torch.arange(0, num_users)),
names=("seed_nodes", "labels"),
),
"item": gb.ItemSet(
(torch.arange(num_users, num_ids), torch.arange(num_users, num_ids)),
names=("seed_nodes", "labels"),
),
}
item_set = gb.ItemSetDict(ids)
```
`use_indexing=False shuffle=False num_ids=10,000 batch_size=1000`: 0.1644s
`use_indexing=True shuffle=False num_ids=10,000 batch_size=1000`: 0.0027s
`use_indexing=False shuffle=True num_ids=10,000 batch_size=1000`: 0.1342s
`use_indexing=True shuffle=True num_ids=10,000 batch_size=1000`: 0.0030s
`use_indexing=False shuffle=False num_ids=100,000 batch_size=1000`: 1.1503s
`use_indexing=True shuffle=False num_ids=100,000 batch_size=1000`: 0.0129s
`use_indexing=False shuffle=True …
> [GraphBolt] enable indexing ItemSetDict in ItemSampler

- examples/sampling/graphbolt/link_prediction.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
1. Add warning to `_init_all_nodes_set` of `OnDiskDataset` when `graph` is None.
2. Add names to `ItemSet`s in `_init_all_nodes_set`.
> [GraphBolt] Add names to `ItemSets` in `_init_all_nodes_set`

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/utils/internal.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/utils/test_internal.py
Fix bugs of changing 1-D tasks sets when preprocess feature data.
> [Misc] Fix bugs of changing 1-D tasks sets when preprocess feature data.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
Added `to` device function for SampledSubgraph using reflection.
> [GraphBolt] Add to function for SampledSubgraph

- examples/sampling/graphbolt/lightning/node_classification.py
- examples/sampling/graphbolt/node_classification.py
During benchmarking, I noticed several discrepancies between DGL and GraphBolt in the node classification example, which could cause potential errors. To prevent this, I'll refine the examples for consistency.
The train log is as following:
```
Training...
193it [02:18,  1.39it/s]                                                      | 0/10 [00:00<?, ?it/s]
39it [00:16,  2.36it/s]]
Epoch 00000 | Loss 1.7883 | Accuracy 0.8264 
193it [02:20,  1.37it/s]                                             | 1/10 [02:35<23:16, 155.20s/it]
39it [00:16,  2.39it/s]]
Epoch 00001 | Loss 0.7776 | Accuracy 0.8584 
193it [02:08,  1.50it/s]                                             | 2/10 [05:12<20:50, 156.28s/it]
39it [00:16,  2.37it/s]]
Epoch 00002 | Loss 0.6224 | …
```
> [GraphBolt] Update the param to make the code consistent

- examples/sparse/graphsage.py
- examples/sparse/sampling/graphsage.py
A sparse graphSAGE example. 
Run example: 
```
$ python examples/sparse/graphsage.py
Training in gpu mode.
Loading data
Training...
[W TensorAdvancedIndexing.cpp:1615] Warning: scatter_reduce() is in beta and the API may change at any time. (function operator())
Epoch 00000 | Loss 2.0963 | Accuracy 0.7756 
Epoch 00001 | Loss 0.8108 | Accuracy 0.8443 
Epoch 00002 | Loss 0.6264 | Accuracy 0.8593 
Epoch 00003 | Loss 0.5662 | Accuracy 0.8675 
Epoch 00004 | Loss 0.5311 | Accuracy 0.8721 
Epoch 00005 | Loss 0.5047 | Accuracy 0.8744 
Epoch 00006 | Loss 0.4846 | Accuracy 0.8759 
Epoch 00007 | Loss 0.4766 | Accuracy 0.8756 
Epoch 00008 | Loss 0.4674 | Accuracy 0.8796 
Epoch 00009 | Loss 0.4528 | Accuracy 0.8799 
Testing...
Test accuracy 0.7216
```
Please feel free to remove inapplicable items for …
> [Sparse] Add a graphSAGE example

- examples/sampling/graphbolt/link_prediction.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
This PR try to address the following issues:
Trainning Log:
```
$ python examples/sampling/graphbolt/link_prediction.py --device cuda --early-stop 1000 --epochs 10 --num-workers 8
...
later
```
> [GraphBolt] Fix Link Prediction eample evaluation function bug and Enable cuda execution

- examples/sampling/graphbolt/node_classification.py
Currently, in `examples/sampling/graphbolt/node_classification.py`, function `create_dataloader()` has a parameter `args`, which contains the arguments parsed from the command line. This PR intends to decouple `create_dataloader()` from parameter `args`, bringing the following benefits:
1. Allow user to set different values for parameters(e.g. batch_size, num_workers) in trainning, evaluating and inference.
2. Make it easier to migrate function `create_dataloader()` to other code.
> [Misc] Modify `create_dataloader()`

- examples/sampling/link_prediction.py
Given that the entire training set in `ogbl-citation2` is excessively large, requiring substantial computational resources, we have introduced an `early-stop` option in the new GraphBolt link prediction example to manage and reduce the time cost during the training stage.
Currently, I need to implement a regression test. To maintain consistency, I believe it is crucial to include this option in the DGL version example as well.
> [Example] Add early stop option for better regression test.

- tests/python/pytorch/graphbolt/impl/__init__.py
Currently, you can use `pytest`  
```
python3 -m pytest -v --junitxml=pytest_compute.xml --durations=100 tests/python/pytorch/graphbolt
```
to run all tests from the `graphbolt` directory, including those in the `graphbolt` directory including those in `graphbolt/impl/` subdirectory.  Unfortunately, attempting to run only tests from `graphbolt/impl/` or any of its files in this manner fails:
```
_________ ERROR collecting tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py ______________________________________________________
ImportError while importing test module '/opt/dgl/dgl-source/tests/python/pytorch/graphbolt/impl/test_csc_sampling_graph.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in …
```
> Improvement in running tests from the GRAPHBOLT test suite.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
1. Enable `FusedCSCSamplingGraph.in_subgraph()` to accept `Dict[str, torch.Tensor]` as parameter.
2. Update the test.
3. Update the code comments.
> [GraphBolt] Enable `FusedCSCSamplingGraph.in_subgraph()` to accept dict

- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
In previous implementation, it requires passed-in `nodes` is sorted or `indptr` is incorrect in the returned subgraph. This PR fixes it.
what's more, fixed `int64_t` is replaced with dynamic `scalar_t`.
> [GraphBolt] fix incorrect indptr of in_subgraph

- examples/sampling/graphbolt/link_prediction.py
Given that the original sampling-based evaluation function is considerably slower compared to the DGL inference-based evaluation, enabling the `model.inference` in the Link Prediction example is crucial for a more efficient and straightforward regression test.
The updated evaluation function significantly reduces processing time, requiring less than 1 hour as opposed to over 12 hours with the original evaluation function.
Train log:
```
$ python examples/sampling/graphbolt/link_prediction.py --early-stop 1000 --train-batch-size 1024 --eval-batch-size 4096 --epochs 10 --device cuda --num-workers 4
Training in cuda mode.
Loading data
Training...
0%|                               | 0/10 [00:00<?, ?it/s]
Epoch 00000 | Loss 0.1416 | Time 97.7365 s
10%|██▎ …
```
> [Graphbolt] Enable Link Prediction example model.inference to accelerate the evaluation speed

- graphbolt/src/fused_csc_sampling_graph.cc
Add sort to `Pick` in sampling to ensure that when there is type_per_edge in the graph, the type_per_edge in sampled subgraph remains an increasing sequence.
> [GraphBolt] Add sort to `Pick` in sampling.

- examples/sampling/node_classification.py
Add non-uva mode in `examples/sampling/node_classification.py`, which is consistent with 'cuda' mode in `examples/sampling/graphbolt/node_classification.py`, for regression test.
> [Misc] Add compare-to-graphbolt mode for regression test

- python/dgl/nn/pytorch/network_emb.py
The default value descrbed in the documentation of the DeepWalk code was wrong. Indeed, the default value for the negative_size parameter is 5 and not 1.
- [x ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
> Update doc network_emb.py

- python/dgl/heterograph.py
- tests/python/common/transforms/test_transform.py
Fix for https://github.com/dmlc/dgl/issues/6577. What's more, I use `g.idtype` instead of `F.int64` for return values of `batch_num_nodes/edges()`.
> [BugFix] return batch related ids in g.idtype

- examples/sparse/sampling/ladies.py
A LADIES model example use sparse library.
LADIES Algorithm:
Run example:
```
$ python examples/sparse/sampling/ladies.py
Training in gpu mode.
Loading data
[W TensorAdvancedIndexing.cpp:1615] Warning: scatter_reduce() is in beta and the API may change at any time. (function operator())
Training...
Epoch 00000 | Loss 2.8380 | Accuracy 0.5665 
Epoch 00001 | Loss 1.5582 | Accuracy 0.6852 
Epoch 00002 | Loss 1.2412 | Accuracy 0.7335 
Epoch 00003 | Loss 1.0939 | Accuracy 0.7564 
Epoch 00004 | Loss 1.0059 | Accuracy 0.7731 
Epoch 00005 | Loss 0.9572 | Accuracy 0.7796 
Epoch 00006 | Loss 0.9081 | Accuracy 0.7855 
Epoch 00007 | Loss 0.8707 | Accuracy 0.7935 
Epoch 00008 | Loss 0.8386 | Accuracy 0.7984 
Epoch 00009 | Loss 0.8159 | Accuracy 0.7994 
Epoch 00010 | Loss 0.7983 | Accuracy 0.8045 …
```
> [Sparse] Add a LADIES example

- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
Previously, `indptr` and `indices` are required to be `torch.int64` or runtime error shown below will be thrown:
```
RuntimeError: expected scalar type Long but found Int
```
> [GraphBolt] enable more dtypes for sample_neighbors

- examples/sampling/graphbolt/sparse/graphsage.py
Add an example using graphbolt as dataloader and sparse as sampler.
Run example: 
```
$ python examples/sampling/graphbolt/sparse/graphsage.py
Training in gpu mode.
Loading data
Training...
[W TensorAdvancedIndexing.cpp:1615] Warning: scatter_reduce() is in beta and the API may change at any time. (function operator())
Epoch 00000 | Loss 2.0136 | Accuracy 0.7910 
Epoch 00001 | Loss 0.7598 | Accuracy 0.8483 
Epoch 00002 | Loss 0.5923 | Accuracy 0.8648 
Epoch 00003 | Loss 0.5326 | Accuracy 0.8710 
Epoch 00004 | Loss 0.5011 | Accuracy 0.8747 
Epoch 00005 | Loss 0.4802 | Accuracy 0.8775 
Epoch 00006 | Loss 0.4652 | Accuracy 0.8798 
Epoch 00007 | Loss 0.4524 | Accuracy 0.8811 
Epoch 00008 | Loss 0.4437 | Accuracy 0.8809 
Epoch 00009 | Loss 0.4359 | Accuracy …
```
> [Sparse] Add graphbolt sparse graphSAGE example

- examples/pytorch/ogb/ogbn-products/mlp/mlp.py
Changes were made in accordance with the [CPU best practices for DGL](https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html). By doing this, we resolved the following warning:
```
/usr/local/lib/python3.10/dist-packages/dgl/dataloading/dataloader.py:1149: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
dgl_warning(
```
and improved the training run time. For 5 epochs, the execution time improvement is:
```
Before:           After:
real    4m39.307s        0m28.892s
user    3m59.116s        1m55.143s
sys     1m16.790s        0m58.011s
```
> Improving the MLP example.

- src/array/cuda/utils.h
> [CUDA] Fix issue about integer overflow

- examples/pytorch/jknet/model.py
Elimination of the `UserWarning`:
```
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py:881: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/cudnn/RNN.cpp:982.)
``` 
by using `flatten_parameters()` call for `lstm` mode.
> Improving the JKNET example.

- include/dgl/aten/coo.h
- include/dgl/aten/csr.h
This PR addresses https://github.com/dmlc/dgl/issues/6561.
It moves the `IsPinned` checking block out of the coo/csr constructor, to avoid initialize cuda instances at sampling(child) processes and align with PyTorch dataloader convention.
> [Misc.] Avoid calling `IsPinned` in the coo/csr constructor from every sampling process

- python/dgl/heterograph.py
Resolve #6542.
In the following code snippet
```
import dgl
import torch
from dgl.dataloading import GraphDataLoader
dataset = dgl.data.QM9EdgeDataset()
dataloader = GraphDataLoader(dataset, batch_size=64)
graph_list = []
for batch_graph, _ in dataloader:
batch_graph = batch_graph.to('cuda:0')
split_graphs = dgl.unbatch(batch_graph)
graph_list.extend([graph.cpu() for graph in split_graphs])
print(f'memory allocation: {torch.cuda.memory_allocated() / 1024**2} Mb')
torch.cuda.empty_cache()
```
The GPU memory of node and edge features of `split_graphs` is not released properly. This is because when copying the split graphs to CPU, the `Column`, which is the DGL internal feature storage, does not copy data to CPU when [Column.to()](https://github.com/dmlc/dgl/blob/2f47c2413eb0764066651c56a9727 …
> [BUGFIX] Fix the lazy device copy issue of DGL node/edge features.

- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/dataloader.py
Given that the starting of workers is slow, we can set `persistent_workers` to True to avoid restarting at each epoch.
The multigpu example is also modified correspondingly.
> [GraphBolt] Set persistent_workers in MultiProcessDataLoader

- examples/multigpu/graphbolt/node_classification.py
Move data loader creations to the beginning to make `persistent_workers` effective.
> [GraphBolt] Modify multi-gpu example to make use of the persistent_workers

- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
> [examples] create dataloader before train epoch

- graphbolt/src/cuda/index_select_impl.cu
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
Here, we make index select independent of the input type and use the largest possible type to perform the copies since for example copying 2 uint32_t equals copying 1 uint64_t. Should help a lot especially for smaller types such as int8, float16, etc. to reduce resource requirements and also potentially improve performance. It also allows supporting all native torch dtypes while using minimum compilation time by sharing the code path for dtypes with the same alignment.
> [Graphbolt][CUDA] Optimize UVA index select

- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Multiple tests from `test_ondisk_dataset.py` generate the following warning:
```
tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py: 10 warnings
  /usr/local/lib/python3.10/dist-packages/dgl/graphbolt/impl/ondisk_dataset.py:480: DGLWarning: `all_node_set` is returned as None, since graph is None.
```
These changes resolve these warnings and some code duplication.
> Improved GraphBolt `ondisk_dataset` tests.

- graphbolt/src/cuda/common.h
- graphbolt/src/cuda/index_select_impl.cu
- graphbolt/src/cuda/utils.h
The current implementation utilizes torch::sort which is slower than cub sort. This PR improves on the current code by swapping torch::sort with cub sort. The following throughput numbers are taken from #6590, the NVIDIA T4 results.
* params:  n_rows=100000, feat_size=100, num_indices=1, feature_device=Device.Pinned, indices_device=Device.GPU
|            |USE_TORCH_SORT=1|USE_TORCH_SORT=0|
|------------|------------|------------|
|USE_PERM=1  |       3.364|       4.454|
* params:  n_rows=100000, feat_size=100, num_indices=1000, feature_device=Device.Pinned, indices_device=Device.GPU
|            |USE_TORCH_SORT=1|USE_TORCH_SORT=0|
|------------|------------|------------|
|USE_PERM=1  |    1605.974|    2421.417|
* params:  n_rows=100000, feat_size=100, num_indices=10000, …
> [Graphbolt][CUDA] Optimize UVA by using CUB sort

- examples/mxnet/appnp/appnp.py
- examples/mxnet/gat/train.py
- examples/mxnet/gcn/gcn_concat.py
- examples/mxnet/gcn/train.py
- examples/mxnet/graphsage/main.py
- examples/mxnet/monet/citation.py
- examples/mxnet/sgc/sgc.py
- examples/mxnet/tagcn/train.py
- examples/pytorch/dimenet/qm9.py
- examples/pytorch/gat/train_ppi.py
- examples/pytorch/geniepath/ppi.py
- examples/pytorch/sgc/sgc.py
- examples/pytorch/sgc/sgc_reddit.py
- examples/pytorch/sign/dataset.py
- examples/pytorch/tagcn/train.py
- examples/tensorflow/dgi/train.py
- examples/tensorflow/gat/train.py
- examples/tensorflow/gcn/gcn_builtin.py
- examples/tensorflow/gcn/gcn_mp.py
- examples/tensorflow/gcn/train.py
- python/dgl/data/ppi.py
- python/dgl/data/qm7b.py
- python/dgl/data/qm9.py
update the examples and 3 datasets, from num_labels to num_classes
examples are updated to use data.num_classes instead of nums_labels
each dataset that explicitly defined num_labels has been checked or updated to include num_classes
> Fix num_labels to num_classes in dataset files

- graphbolt/src/macro.h
- src/array/libra_partition.cc
- src/graph/transform/compact.cc
- tests/cpp/test_partition.cc
Eliminates:
```
In file included from /localscratch/dgl-1/graphbolt/src/index_select.cc:8:
/localscratch/dgl-1/graphbolt/src/index_select.cc: In function ‘at::Tensor graphbolt::ops::IndexSelect(at::Tensor, at::Tensor)’:
/localscratch/dgl-1/graphbolt/src/./macro.h:18:16: warning: unused variable ‘XPU’ [-Wunused-variable]
18 |     const auto XPU = c10::DeviceType::CUDA;                         \
|                ^~~
/localscratch/dgl-1/graphbolt/src/./macro.h:18:16: note: in definition of macro ‘GRAPHBOLT_DISPATCH_CUDA_ONLY_DEVICE’
18 |     const auto XPU = c10::DeviceType::CUDA;                         
```
and
```
/localscratch/dgl-1/tests/cpp/test_partition.cc: In instantiation of ‘void _TestRemainder_MapToX() [with DGLDeviceType XPU = kDGLCUDA; IdType = int]’: …
```
> [Misc] Eliminate compile warnings

- python/dgl/utils/internal.py
`recursive_apply` would turn tuple into list, which is not expected.
Now an if-branch is added to fix this bug.
When use `to_dgl` after `copy_to` in the graphbolt dataloader, this error will happen:
```
File "../dgl/examples/sampling/graphbolt/node_classification.py", line 426, in <module>
main(args)
File "../dgl/examples/sampling/graphbolt/node_classification.py", line 408, in main
train(args, graph, features, train_set, valid_set, num_classes, model)
File "../dgl/examples/sampling/graphbolt/node_classification.py", line 307, in train
data = data.to_dgl()
File "/opt/conda/envs/dgl-dev-gpu-118/lib/python3.8/site-packages/dgl-1.2-py3.8-linux-x86_64.egg/dgl/graphbolt/minibatch.py", line 467, in to_dgl
blocks=self._to_dgl_blocks(),
File …
```
> [Misc] Fix recursive_apply when data is a tuple

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/include/graphbolt/shared_memory.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/shared_memory.cc
- graphbolt/src/shared_memory_helper.cc
- graphbolt/src/shared_memory_helper.h
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
part of #6661 
Previously we have to pre-define metadata size when creating shared memory. This will results in crash if metadata is larger than assumption(For example, large number of node/edge types are available or many fields are added into `edge_attributes`). For now, such limitation and assumption is gone.
> [GraphBolt] avoid pre-defined metadata size

- examples/multigpu/graphbolt/node_classification.py
- examples/sampling/graphbolt/lightning/node_classification.py
- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
- examples/sampling/graphbolt/quickstart/link_prediction.py
- examples/sampling/graphbolt/quickstart/node_classification.py
- examples/sampling/graphbolt/rgcn/hetero_rgcn.py
Modified examples to move the `to_dgl` out of data loaders.
Examples involved:
- `examples/multigpu/graphbolt/node_classification.py`
- `examples/sampling/graphbolt/lightning/node_classification.py`
- `examples/sampling/graphbolt/link_prediction.py`
- `examples/sampling/graphbolt/node_classification.py`
- `examples/sampling/graphbolt/quickstart/link_prediction.py`
- `examples/sampling/graphbolt/quickstart/node_classification.py`
- `examples/sampling/graphbolt/rgcn/hetero_rgcn.py`
So we can remove `DGLMiniBatch` and `MiniBatchBase` after this.
Plus, the data type in ogbn-products is now `float32` so the model data type needs to be changed to float too in the `lightning/node_classification.py`.
> [GraphBolt] Move to_dgl out of data loader in examples.

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
- tests/python/pytorch/graphbolt/test_graphbolt_utils.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Add `unique_and_compact_csc_format` to support deduplicate and compact csc format sampled subgraph.
Homo (us) :
|size| unique_compact_node_piars | unique_compact_csc_format | compact_csc_fotmat |
|----|----|----|----|
|10000| 860 | 405 | 283 |
|10000000| 236536 | 217717 | 22976 |
Hetero (us) :
|size| unique_compact_node_piars | unique_compact_csc_format | compact_csc_fotmat |
|----|----|----|----|
|10000| 880 | 778 | 604 |
|10000000| 920170 | 861199 | 106093 |
Homo (us):
| | 1 | 2 | 3 | 4|
| --- | --- | --- | --- | --- |
|size| 10000 | 10000000 | 10000000 | 10000000 |
|fanout| 2 | 2 | 1024 | 1024 |
|batch_size| 4 | 4 | 4 | 1024 |
| uniquet_node_piars | 550 | 558 | 558 | 554 |
| unique_csc_format | 544 | 554 | 543 | 532 |
| duplicate_csc_fotmat | 526 | 524 | 530 | 526 |
Hetero (us): …
> [GraphBolt] Add `unique_and_compact_csc_format`.

- graphbolt/src/python_binding.cc
- python/dgl/distributed/partition.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_integration.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
> [GraphBolt] rename from_fused_csc as fused_csc_sampling_graph

- dgl_sparse/include/sparse/sddmm.h
- dgl_sparse/include/sparse/sparse_format.h
- dgl_sparse/include/sparse/sparse_matrix.h
- dgl_sparse/include/sparse/spmm.h
- dgl_sparse/include/sparse/spspmm.h
- dgl_sparse/include/sparse/torch_headers.h
- dgl_sparse/src/elemenwise_op.cc
- dgl_sparse/src/matmul.cc
- dgl_sparse/src/matmul.h
- dgl_sparse/src/matrix_ops.cc
- dgl_sparse/src/python_binding.cc
- dgl_sparse/src/reduction.cc
- dgl_sparse/src/sddmm.cc
- dgl_sparse/src/softmax.cc
- dgl_sparse/src/sparse_matrix.cc
- dgl_sparse/src/spmm.cc
- dgl_sparse/src/spspmm.cc
- dgl_sparse/src/utils.h
Fix the build fail issue when building DGL sparse on windows with Pytorch 2.1.1.
> [Sparse] Fix Windows.h dependency issue

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/link_prediction.py
> [Graphbolt[ Add reverse edgs in link prediction example

- notebooks/stochastic_training/link_prediction.ipynb
> [GraphBolt] add exclude_seed_edges() for link prediction example

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
For the easy access of temporal attributes later.
> [Graphbolt] Add an EdgeAttribute function in FusedCSCSamplingGraph to access an edge attribute by name.

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
This PR defines the interface for Graphbolt to support temporal neighbor sampling. Please comment if you feel anything is wrong. Meanwhile, I will continue to implement the `FusedCSCSamplingGraph::TemporalSampleNeighbors` function following the steps in the function.
> [Graphbolt] Define the interface of temporal neighbor sampling.

- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
Add `__repr__` to feature store.
```
TorchBasedFeature(feature=tensor([[[1, 2],
[3, 4]],
[[4, 5],
[6, 7]]]),
metadata={'max_value': 3},
)
```
```
TorchBasedFeatureStore{(<OnDiskFeatureDataDomain.NODE: 'node'>, 'paper', 'a'): TorchBasedFeature(feature=tensor([[1, 2, 4],
[2, 5, 3]]),
metadata={},
), (<OnDiskFeatureDataDomain.EDGE: 'edge'>, 'paper:cites:paper', 'b'): TorchBasedFeature(feature=tensor([[[1, 2],
[3, 4]],
[[2, 5],
[3, 4]]]),
metadata={},
)}
```
> [GraphBolt] Add `__repr__` to feature store.

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
Add `__repr__`  to ItemSet. 
```
ItemSet(items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
)
```
```
ItemSetDict(items={'user': ItemSet(items=(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9])),
names=('seed_nodes', 'labels'),
), 'item': ItemSet(items=(tensor([5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14])),
names=('seed_nodes', 'labels'),
)},
names=('seed_nodes', 'labels'),
)
```
> [GraphBolt] Add `__repr__`  to ItemSet.

- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/utils.h
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
Implemented TemporalNeighborSampler.
Since there are more and more samplers in Graphbolt, we may need to refactor the sampling logic. The current PickFn and NumPickFn are lambdas, which are pretty tedious since they forward a lot of arguments multiple times during the sampling logic. And it is not straightforward to support template in lambda. I'd suggest to use a abstract class for various sampling methods, which offer NumPick and Pick functions but with private attributes to support different sampling logics.
> [Graphbolt] Implement Temporal Neighbor Sampling.

- dgl_sparse/CMakeLists.txt
A simple solution to fix the NOMINMAX problem in Windows. After this PR, https://github.com/dmlc/dgl/pull/6741 should be reverted.
> [Sparse] Fix the NOMINMAX problem on Windows.

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/common.h
- graphbolt/src/cuda/index_select_csc_impl.cu
Refactoring `SliceCSCIndptr` function so that it can be reused in the Neighbor Sampling implementation in #6770.
> [GraphBolt][CUDA] Refactoring SliceCSCIndptr for Neighbor Sampling.

- python/dgl/graphbolt/sampled_subgraph.py
Modify docstring of `SampledSubgraph` from coo to csc.
> [GraphBolt] Modify docstring of `SampledSubgraph`.

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
Reverts dmlc/dgl#6773, so that examples can sample in csc format.
> [GraphBolt] Remove opt `output_cscformat` from examples.

- tests/scripts/task_distributed_test.sh
- tests/tools/test_change_etype_to_canonical_etype.py
- tests/tools/test_convert_partition.py
- tools/distpartitioning/convert_partition.py
The bug in previous implementation of `srcids update` is the line that recover the sorted `srcids` back to original order: `srcids[sort_ids] = srcids`.  Such in-place is incorrect as it sequentially overwrites elements in the sorted array, leading to incorrect results and loss of data. This error will results in unexpected value of `NID/EID`. The correct way is to create a new array to store like:
```
new_srcids = np.zeros_like(srcids)
new_srcids[sort_ids] = srcids
srcids = new_srcids
```
But in this PR, I[Rui] just replace previous implementation via a single call: `srcids = np.searchsorted(uniques, srcids, side="left")`. From my understanding, it should be more efficient in both performance and memory compared to iterating over manually. But for the record, I haven't profiled it. …
> [DistDGL] fix distributed partition issue

- python/dgl/graphbolt/item_sampler.py
In principle, we should shuffle upon the whole item set to achieve good randomness.
For now, accuracy aligns with https://github.com/dmlc/dgl/blob/master/examples/sampling/graphbolt/rgcn/README.md#accuracies
**use_indexing=True, buffer_size=-1**
Training~Epoch 02: 615it [01:01,  9.92it/s]
Evaluating the model on the training set.
Inference: 154it [00:17,  8.61it/s]
Finish evaluating on training set.
Evaluating the model on the validation set.
Inference: 16it [00:01,  9.47it/s]
Finish evaluating on validation set.
Evaluating the model on the test set.
Inference: 11it [00:01,  8.93it/s]
Finish evaluating on test set.
Run: 01, Epoch: 03, Loss: 1.8374, Train: 65.51%, Valid: 41.73%, Test: 41.36%
Finish evaluating on test set.
Run 01:
Highest Train: 65.51
Highest Valid: 42.13
Final Train: 59.28 …
> [GraphBolt] set buffer_size as whole itemset in default

- examples/core/rgcn/README.md
- examples/core/rgcn/hetero_rgcn.py
1. deleted `--runs` and `Logger`.
2. update the log format for benchmark.
stdout:
```shell
Start to transform graph. This may take a while...
Loaded graph: Graph(num_nodes={'author': 1134649, 'field_of_study': 59965, 'institution': 8740, 'paper': 736389},
num_edges={('author', 'affiliated_with', 'institution'): 1043998, ('author', 'writes', 'paper'): 7145660, ('field_of_study', 'rev_has_topic', 'paper'): 7505078, ('institution', 'rev_affiliated_with', 'author'): 1043998, ('paper', 'cites', 'paper'): 10832542, ('paper', 'has_topic', 'field_of_study'): 7505078, ('paper', 'rev_writes', 'author'): 7145660},
metagraph=[('author', 'institution', 'affiliated_with'), ('author', 'paper', 'writes'), ('institution', 'author', 'rev_affiliated_with'), ('paper', 'paper', 'cites'), ('paper', …
```
> [Example] modify dgl rgcn example to make it consistent with graphbolt's

- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
```
MiniBatch(seed_nodes=None,
sampled_subgraphs=[SampledSubgraphImpl(sampled_csc={'n1:e1:n2': CSCFormatBase(indptr=tensor([0, 2, 4]),
indices=tensor([1, 0, 0, 1]),
), 'n2:e2:n1': CSCFormatBase(indptr=tensor([0, 2, 4]),
indices=tensor([0, 1, 0, 2]),
)},
original_row_node_ids={'n1': tensor([1, 0]), 'n2': tensor([0, 1, 2])},
original_edge_ids=None,
original_column_node_ids={'n1': tensor([1, 0]), 'n2': tensor([0, 1])},
),
SampledSubgraphImpl(sampled_csc={'n1:e1:n2': CSCFormatBase(indptr=tensor([0, 2, 4]),
indices=tensor([1, 0, 0, 1]),
), 'n2:e2:n1': CSCFormatBase(indptr=tensor([0, 2]),
indices=tensor([0, 1]),
)},
original_row_node_ids={'n1': tensor([1, 0]), 'n2': tensor([0, 1])},
original_edge_ids=None,
original_column_node_ids={'n1': tensor([1]), 'n2': tensor([0, 1])},
)], …
```
> [GraphBolt] sample with unknown etype

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
> [GraphBolt][CUDA] Fix pinned `edge_id` index_select

- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_minibatch.py
Since PyTorch has provided `diff()` API, we can take advantage of it to avoid prolix code.
Only tested 1-D Tensor, as it is the only possible shape of `indptr`.
Code:
```python
def test(dtype, size, loops, device):
t0 = time.time()
for i in range(loops):
x = torch.randint(low=0, high=1000000000, size=(size,), dtype=dtype, device=device)
y = x[1:] - x[:-1]
assert y.shape[0] == size - 1, y.shape
t1 = time.time()
print(f"primitive: {t1-t0}")
def test_diff(dtype, size, loops, device):
t0 = time.time()
for i in range(loops):
x = torch.randint(low=0, high=1000000000, size=(size,), dtype=dtype, device=device)
y = x.diff()
assert y.shape[0] == size - 1, y.shape
t1 = time.time()
print(f"diff: {t1-t0}")
```
Result:
```
dtype: torch.int32      size: 100       loops: 10000    device: cpu
primitive: …
```
> [GraphBolt] Use `diff()` to calculate the differences for simplicity

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
Adding a list version of `node_type_offset` that is called `node_type_offset_list`. Whenever we access it from the code with CPU indexes one-by-one, we should make sure to use `node_type_offset_list` so that there is no unnecessary CPU GPU transfer and synchronization as lists are guaranteed to be stored on the CPU and are fast to access element-wise. Should fix #6885.
> [GraphBolt][CUDA] Add a `node_type_offset_list` property.

- python/dgl/graphbolt/base.py
Clarify the attribute selection in CopyTo.
> [GraphBolt] Add more detail to CopyTo docstring

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/internal/utils.py
- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/utils/test_internal.py
Support numpy for edges when constructing graph in `preprocess_ondisk_dataset`.
**Using numpy for edges in YAML file:**
```
edges:
- format: numpy
path: your_edge_path.npy
```
TBD.
> [GraphBolt] Support numpy for edges when constructing graph in `preprocess_ondisk_dataset`.

- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/index_select.cc
- graphbolt/src/isin.cc
- graphbolt/src/unique_and_compact.cc
- graphbolt/src/utils.h
- tests/python/pytorch/graphbolt/test_dataloader.py
Fixes #6921. We defer calling `is_pinned` to avoid initializing torch cuda internals by forcing the user to provide the `nodes` tensor on the GPU to be able to use pinned graph sampling via UVA. If the `nodes` or `index` tensor is not on the GPU, then we don't need to check if the graph is pinned or not. If the `nodes` tensor is on the GPU, then that means torch cuda is already initialized, and calling `is_pinned` is fine.
> [GraphBolt][CUDA] Dataloader `num_workers > 0` fix.

- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/index_select.cc
- graphbolt/src/isin.cc
- graphbolt/src/unique_and_compact.cc
- graphbolt/src/utils.h
- tests/python/pytorch/graphbolt/test_dataloader.py
> [GraphBolt][CUDA] Dataloader `num_workers > 0` fix. (#6924)

- graphbolt/src/cuda/neighbor_sampler.cu
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
The weighted sampling implementation was already there, the only thing that was missing was ensuring we didn't sample any edges with the `probs_or_mask` value set to 0. So, this PR adds the code for counting edges with nonzero weights and enables the weighted sampling tests. Fixes #6918.
> [GraphBolt][CUDA] Enable tests for weighted sampling

- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
```
TorchBasedFeature(
feature=tensor([[1, 2, 3],
[4, 5, 6]]),
metadata={'max_value': 3},
)
```
```
TorchBasedFeatureStore(
{(<OnDiskFeatureDataDomain.NODE: 'node'>, 'paper', 'a'): TorchBasedFeature(
feature=tensor([[1, 2, 4],
[2, 5, 3]]),
metadata={},
), (<OnDiskFeatureDataDomain.EDGE: 'edge'>, 'paper:cites:paper', 'b'): TorchBasedFeature(
feature=tensor([[[1, 2],
[3, 4]],
[[2, 5],
[3, 4]]]),
metadata={},
)}
)
```
> [GraphBolt] Update `__repr__` of `TorchBasedFeature` and `TorchBasedFeatureStore`

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/internal/utils.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/utils/test_internal.py
Automatically force preprocess on-disk dataset in following situations.
- `include_original_eids` has been changed.
- Value in file has been changed, no matter data files or yaml file.
> [GraphBolt] Automatically force preprocess on-disk dataset.

- python/dgl/graphbolt/impl/ondisk_dataset.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
If edge IDs are not saved when edge feature is stored, make warnings to user.
> [GraphBolt] Add check about whether edge IDs are saved when edge feature is stored.

- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
Currently `dgl/tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py::test_OnDiskDataset_preprocess_homogeneous` tests `gb.ondisk_dataset.preprocess_ondisk_dataset` with `include_original_edge_id=False` twice, but should be `True` and `False` each once.
This PR intends to correct it.
> [Misc] Correct `test_OnDiskDataset_preprocess_homogeneous`

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
> [GraphBolt][CUDA] Add `.to()` method to Graph and FeatureStore.

- examples/sampling/graphbolt/node_classification.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
torch pin_memory method creates a copy of the tensor. When we work with large datasets or use multi-GPU training, we don't want copies to be made. So, this PR ensures that `pin_memory_()` method is in-place by using `cudaHostRegister`.
> [GraphBolt][CUDA] Inplace pin memory for Graph and TorchFeatureStore

- examples/multigpu/graphbolt/node_classification.py
Modified the example to utilize GPU sampling. We need to fix the replication problem due to the use of torch pin_memory.
Here is a discussion about how we can fix the process graph and feature duplication issue: https://github.com/pytorch/pytorch/issues/32167
The fix is in #6962.
> [GraphBolt][CUDA] Modify multiGPU example to use GPU sampling.

- examples/core/rgcn/hetero_rgcn.py
Temporarily turn off `fused` option of the sampler in DGL rgcn example to compare with GB.
> [Misc] Turn off `fused` in DGL rgcn example

- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
If the user runs the following:
```python
for data in dataloader:
pass
```
Moreover, this PR fixes the multi-GPU example crash tracked by #6978. I believe the crash is due to dropping uneven inputs, basically meaning that we discard the last minibatch coming from the dataloader. It is like the case above but only just for the last minibatch.
Because the feature fetch operation doesn't synchronize, the edge id and vertex id tensors might get freed while the fetch operation is still ongoing. If there are forward/backward operations inside the loop, this doesn't happen because we make the current stream wait for the UVA stream via CUDA events.
https://github.com/dmlc/dgl/blob/f7e065f7672198f033bd50da8694a5ec20b4a160/python/dgl/graphbolt/dataloader.py#L85-L94 …
> [GraphBolt][CUDA] Handle edge case for fetch feature overlap

- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
Add check to NegativeSampler to select which function to use. This check will be cleaned up once refactor is done.
> [GraphBolt] Add check to NegativeSampler.

- python/dgl/graphbolt/item_sampler.py
```
Test accuracy 45.8261
Epoch: 01, Loss: 2.3362, Valid accuracy: 48.41%, Time 68.9185
Training~Epoch 02: 0it [00:00, ?it/s]rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: tensor([404999, 305221, 507294,  ..., 354460, 285126, 516371])
rank None shuffled indices: …
```
> [GraphBolt] fix random generator for shuffle among all workers

- examples/multigpu/graphbolt/node_classification.py
Add `mode` arg which can be set to `cpu-cuda` or `pinned-cuda`.
> [GraphBolt] Modify multigpu example arguments

- examples/core/rgcn/README.md
- examples/sampling/graphbolt/rgcn/README.md
> [example] update RGCN README

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
`sample_negative_edges_uniform_2` in fused_csc_sampling_graph: the function to sample negative seeds uniformly and construct corresponding indexes. Return: N*2 tensor representing negative edges and 1D tensor representing indexes. The function name will be update later.
`_collate`: deal with the concatenation of pos_edges and neg_edges, also construct `labels`.
> [GraphBolt] Refactor `NegativeSampler`.

- python/dgl/distributed/dist_graph.py
> [DistGB] enable DistGraphServer to load graphbolt partitions

- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/dataloader.py
- tests/python/pytorch/graphbolt/test_dataloader.py
See the picture in #6983. The Awaiter block is missing. This is due to a bug in the wrap parent usage. Fixes #7028 and #7008. This bug arised due to a buggy use of the _find_and_wrap_parent function. It needs to return the modified datapipe_graph to the user so that the user uses the updated version after modifications.
Below, you can see that both Bufferer and Awaiter is present after modification. Awaiter basically synchronizes the feature copy on the uva_stream with the main stream. When it is missing, the fetched features will be accessed when the copy operation has not finished yet.
> [GraphBolt][CUDA] Dataloader feature overlap fix

- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
> [GraphBolt] Fix `NegativeSampler` seeds support.

- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
Will use this function inside the dataloader for sanity checks to make it robust against erroneous use by the users.
> [GraphBolt][CUDA] Add `is_pinned` method to `TorchBasedFeatureStore`.

- python/dgl/graphbolt/impl/torch_based_feature_store.py
Eliminates the following warning:
```
tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py::test_basic_feature_store_errors
/usr/local/lib/python3.10/dist-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function TorchBasedFeature.__del__ at 0x7f6150076ef0>
File "/localscratch/dgl-3/python/dgl/graphbolt/impl/torch_based_feature_store.py", line 93, in __del__
for tensor in self._is_inplace_pinned:
AttributeError: 'TorchBasedFeature' object has no attribute '_is_inplace_pinned'
warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```
> [GraphBolt] Eliminate test warning

- graphbolt/src/cuda/index_select_csc_impl.cu
- graphbolt/src/cuda/index_select_impl.cu
We need to limit the index select csc CUDA thread count similar to how we did for UVA index select so that its operations can be overlapped with other kernels running on the GPU.
Making the BLOCK_SIZE maximum possible ensures that the UVA kernels use the fewest number of SMs possible, otherwise it is possible that multiple small blocks can occupy more multiple SMs. It probably is better to have SM isolation between kernels.
> [GraphBolt][CUDA] IndexSelectCSC kernel launch config change.

- examples/multigpu/graphbolt/node_classification.py
- graphbolt/src/cuda/gpu_cache.cu
The missing_len argument to the GPU cache needs to be on the GPU because the cache performs atomic operations on it. Results in a 1000x performance improvement. Before this change, it turns out that the GPUCache was practically not usable at all.
Testable with #7074, @TristonC could you test it on multiGPU machines with `--gpu-cache-size=1000000`, either before or after this PR is merged?
When the GPUCachedFeature is used, the feature fetching operation has a GPU synchronization. We might want to run the feature fetching operation in another thread. Hoping that the main thread will make progress while the feature fetching thread is waiting for synchronization. However, if the GIL is not released while waiting, then it may not do what we expect, which will pose a problem, and the overlap …
> [GraphBolt][CUDA] GPUCache performance fix.

- graphbolt/src/cuda/gpu_cache.cu
- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
When cache hit rate is %100, this function is called with 0-sized tensors. If it is called with empty tensors, then we do nothing and return as there is nothing to do.
> [GraphBolt][CUDA] Handle edge case of %100 cache hit rate.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
Adding argument `return_eids` for `_sample_neighbors()` will benefit DistGB to sample neighbors with consistent arguments with underlying C++ call.
> [GraphBolt] move return_eids check to internal python API

- python/dgl/convert.py
When printing a graph, the edge types are supposed to be listed lexicographically.
> [Misc] Correct docstrings in `python/dgl/convert.py`

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
1. move `seeds`, `indexes`, `labels` to GPU when sampling on GPU.
2. Add tests for `NegativeSampler` on GPU.
> [GraphBolt] Fix gpu `NegativeSampler` for seeds.

- examples/multigpu/graphbolt/node_classification.py
The existing help string was misleading, @TristonC got confused and thought it is size in bytes.
> [GraphBolt][CUDA] Improve GPUCache help string in multiGPU example.

- docs/source/api/python/dgl.graphbolt.rst
- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- tests/python/pytorch/graphbolt/test_base.py
The existing example was moving the feature memory to the device memory. We change it to the storage_device instead.
When I started this PR, I thought I would use `gb.index_select` to load features for inferencing. Then I realized that I can just update the features and rely on the dataloader to fetch the features for inferencing. Otherwise, the copies for all the different modes become too complicated and ugly, which the dataloader automatically handles for us. However, I am sure that `gb.index_select` will be useful to us down the road, it is a very simple wrapper over `torch.ops.graphbolt.index_select`.
> [GraphBolt][CUDA] Add `gb.index_select` and fix example inferencing.

- python/dgl/distributed/graph_services.py
- tests/distributed/test_distributed_sampling.py
1. unify `sample_neighbors()` to return `global_src, global_dst, global_eids, etype_ids`.
2. split testcases into separate ones to be clearer.
> [DistGB] return eids together with etype_ids in sampling

- examples/sampling/graphbolt/link_prediction.py
- python/dgl/graphbolt/feature_fetcher.py
Fixes #7082. When feature overlap is enabled, the dataloader has buffers for the future feature fetches. When we reuse the same dataloader after stopping early, it tries to pickle the objects in the buffers, then tries the pickle CUDAEvent stored in the object stored in the buffer. Creating a new dataloader after stopping early avoids this issue.
More details and a potential alternative fix here: https://github.com/pytorch/data/issues/1161
> [GraphBolt][CUDA] Fix link prediction early-stop.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
There was a bug related to the permutation of the vertices and recording the inputs to the graph fetching datapipe. This PR fixes these issues.
Now, enabling graph fetch in the dataloader or not enabling it gives the identical accuracies.
I would like to modify the node_classification example to add the overlap_graph_fetch option so that we can run the regression test for this case as well.
> [GraphBolt][CUDA] Pipelined sampling accuracy fix

- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Modify `SubgraphSampler` to support `seeds`.
For 1D `seeds`, it will be treated as original `seed_nodes`.
For 2D `sseds`, it will be treated as original `node_pairs`.
tensor with other dimensions is not supported
> [GraphBolt] Modify `SubgraphSampler` to support `seeds`.

- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
Added `cuda-cuda` option for the multiGPU example. Since the `OndiskDataset` can not be modified, I thought that if pin_memory_ method returns a reference to self, the code will be simpler at the end. Otherwise, extra two lines to separately assign `graph = dataset.graph` and `feature = dataset.feature` is needed.
<details><summary>Evaluating `cpu-cuda`, `pinned-cuda` and `cuda-cuda` on 2 A100 GPUs</summary>
<p>
root@a100cse:/localscratch/dgl-3/examples/sampling/graphbolt/lightning# python ../../../multigpu/graphbolt/node_classification.py --gpu=2,3 --mode=pinned-cuda
Training with 2 gpus.
Training...
96it [00:05, 17.48it/s]
Validating...
20it [00:00, 30.66it/s]
Epoch 00000 | Average Loss 1.7811 | Accuracy 0.8321 | Time 6.1841
96it [00:02, 37.11it/s] …
> [GraphBolt][CUDA] puregpu option for the multiGPU example.

- tests/python/pytorch/graphbolt/gb_test_utils.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
> [Misc] Correct some typos

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_minibatch.py
Correct a mistake in the `to_pyg_data`.
> [GraphBolt] Correct `to_pyg_data`

- tutorials/multi/2_node_classification.py
I don't know how to add a page under the GraphBolt tutorials to include the modified tutorial. Does this align with what you have in mind @frozenbugs @Rhett-Ying?
> [GraphBolt][Doc] Updated MultiGPU tutorial

- examples/pytorch/gcmc/data.py
The following `ParserWarning`
```
/opt/dgl/dgl-source/examples/pytorch/gcmc/data.py:686: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
```
has been fixed exactly as suggested.
> [GCMC] Fixing a parser warning appearing in one of the `gcmc` examples.

- examples/sampling/graphbolt/link_prediction.py
- examples/sampling/graphbolt/node_classification.py
Since we are adding larger scale datasets such as papers100M, it is important that we use in-place pinning.
> [GraphBolt][CUDA] Make sure in-place pinning is used in examples.

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/sampled_subgraph.py
- python/dgl/graphbolt/utils.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_utils.py
1. Add `add_reverse_edges_2` to support seeds format.
2. Add `_exclude_homo_edges` to support seeds format.
3. Add tests to test function in `utils.py`.
> [GraphBolt] Modify `exclude_seed_edges` to support seeds.

- examples/multigpu/graphbolt/node_classification.py
- examples/sampling/graphbolt/node_classification.py
- tutorials/multi/2_node_classification.py
Fixing minor typos and aligning the multiGPU example with the tutorial updated in #7126.
> [GraphBolt][CUDA] refine the node_classification examples.

- python/dgl/distributed/dist_tensor.py
- python/dgl/distributed/graph_partition_book.py
- python/dgl/distributed/graph_services.py
- python/dgl/distributed/kvstore.py
- python/dgl/distributed/nn/pytorch/sparse_emb.py
- python/dgl/distributed/utils.py
- tests/distributed/test_dist_tensor.py
- tests/distributed/test_distributed_sampling.py
> [DistGB] remove toindex() as torch tensor is always be expected

- python/dgl/graphbolt/itemset.py
- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_itemset.py
Scalar torch tensor option is added to ItemSet so that we can generate `all_nodes_set` with a specific dtype.
Should help #7127 CI tests to pass.
Also related to #7130.
Now, we will need to modify all the itemsets in our BuiltinDatasets that are simple integers and wrap them into a `torch.tensor(N, dtype=dtype)`.
> [GraphBolt] Fix scalar itemset dtype issue

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
When we are at the end of the program, the cudart can not be found as it get unloaded before unpinning happens. Saving a reference to the unpinner function resolves the issue and warnings at the end of some examples.
> [GraphBolt][CUDA] Fix cudart destructor race in unpinning.

- examples/sampling/graphbolt/node_classification.py
Even though the `args.dataset` option was added, the dataset name was hardcoded to `ogbn-products`.
> [GraphBolt] Fix typo in node_classification example.

- python/dgl/distributed/partition.py
- tests/distributed/test_distributed_sampling.py
- tests/distributed/test_partition.py
Due to #7175 , I'd like to restrict NID/EID as **int64** for now. And the additional memory consumption( **int32** -> **int64**) is usually relatively small(node/edge feature always takes the major parts).
Below are diff for `ogbn-products` and `ogbn-papers100M`.
```
-rw-rw-r-- 1 ubuntu ubuntu 252M Feb 28 07:29 ogbn_products/part0/fused_csc_sampling_graph.pt
-rw-rw-r-- 1 ubuntu ubuntu 262M Feb 28 07:29 ogbn_products/part1/fused_csc_sampling_graph.pt
VS
-rw-rw-r-- 1 ubuntu ubuntu 255M Feb 29 06:39 new_ogbn_products/part0/fused_csc_sampling_graph.pt
-rw-rw-r-- 1 ubuntu ubuntu 265M Feb 29 06:39 new_ogbn_products/part1/fused_csc_sampling_graph.pt
```
```
-rw-rw-r-- 1 ubuntu ubuntu 4.1G Feb 28 11:24 ogbn_papers100M/part0/fused_csc_sampling_graph.pt
-rw-rw-r-- 1 ubuntu ubuntu 3.8G Feb 28 11:24 …
```
> [DistGB] restrict NID/EID as int64_t

- python/dgl/graphbolt/minibatch.py
We need this change after #7127 is merged. #7123 depends on this change. PyG expects `edge_index` to be `int64`.
> [GraphBolt] `to_pyg_data` should return `int64` `edge_index`.

- graphbolt/src/expand_indptr.cc
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/base.py
- tests/python/pytorch/graphbolt/test_base.py
Details in this document by PyTorch developers: https://docs.google.com/document/d/1W--T6wz8IY8fOI0Vm8BF44PdBgs283QvpelJZWieQWQ/edit?usp=sharing
This PR utilizes `torch>=2.2.0` features.
> [GraphBolt] `torch.compile()` support for `gb.expand_indptr`.

- examples/sampling/pyg/node_classification.py
- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_minibatch.py
Add `batch_size` and `n_id` in the `to_pyg_data` to reduce the modification to the PyG inference function when migrating.
So it'll be more seamless.
> [GraphBolt][PyG] Add more attributes in `to_pyg_data`

- python/dgl/graphbolt/impl/neighbor_sampler.py
There was an asymmetry between the different samplers. Now, the unnecessary extra sampler argument of NeighborSampler is eliminated.
> [GraphBolt] Refactor `NeighborSamplerImpl`

- graphbolt/include/graphbolt/cuda_sampling_ops.h
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
> [GraphBolt] Implement labor dependent minibatching - python side.

- tests/python/pytorch/graphbolt/test_minibatch.py
The following warning
``` 
tests/python/pytorch/graphbolt/test_minibatch.py:944
/opt/dgl/dgl-source/tests/python/pytorch/graphbolt/test_minibatch.py:944: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
assert (
```
is fixed in `graphbolt/test_minibatch.py::test_to_pyg_data` test.
> [GraphBolt] Fixing warning in `test_to_pyg_data`.

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_minibatch.py
Update `to_pyg_data()` in `MiniBatch` to support get batch_size from `seeds`.
> [GraphBolt] Update `to_pyg_data()` to support get batch_size from `seeds`.

- graphbolt/include/graphbolt/continuous_seed.h
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/fused_csc_sampling_graph.cc
Should fix #7209. Need to watch regression tests and see if actually fixes the slow down.
> [GraphBolt] Labor dependent template specialization.

- python/dgl/data/tu.py
The len(data) of TUDataset('DD') must be 1178.
> [Doc] The len(data) of TUDataset('DD') must be 1178.

- graphbolt/include/graphbolt/continuous_seed.h
- graphbolt/src/cuda/neighbor_sampler.cu
Fixes #7173. Neighbor Sampling kernel is sped up by 4-5x compared to old, non-specialized version.
> [GraphBolt][CUDA] Specialize non-weighted neighbor sampling impl

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
The code will work without this check. It adds unnecessary overhead, especially when things are running on the GPU by introducing a CPU GPU synchronization.
> [GraphBolt] Remove unique requirement from in_subgraph.

- graphbolt/src/concurrent_id_hash_map.cc
- graphbolt/src/concurrent_id_hash_map.h
Doc: https://docs.google.com/document/d/1fWX6GhQySniFCSmXnKw8mxZQ26WngD5jEi8vt2H41Ss
> [GraphBolt] Make unique_and_compact deterministic

- python/dgl/convert.py
- python/dgl/graphbolt/minibatch.py
- python/dgl/utils/data.py
The hetero sampling case has too many GPU synchronizations, we need to hunt them down one by one if we want to get good performance.
I would appreciate any help in this direction as some of these are inside DGL itself, not GraphBolt.
> [CUDA] Make sanity check optional for `dgl.create_block`.

- python/dgl/graphbolt/minibatch.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
When `seeds` is a one-dimensional tensor, it represents seed nodes, which does not need to do unique and compact.
> [GraphBolt] Modify `_seeds_preprocess` in subgraph_sampler.

- python/dgl/graphbolt/minibatch.py
- tests/python/pytorch/graphbolt/test_base.py
In examples, we will use `copy_to` after `ItemSampler` and `fetch_feature`.
When using `copy_to` after `ItemSampler`, we will copy all attributes because at this time, only `seed_nodes`, `node_pairs` and `labels` have value in minibatch.
When using `copy_to` after `fetch_feature`, we will only copy attributes we need.
These two situations are selected by checking `seed_nodes` and `compacted_pairs` to determine the current stage and the task. However, when using `seeds`, it is difficult to determine these through `seeds` and `compacted_seeds`. For example, when running evaluation in quickstart/link_prediction, `seeds` will not be transfered due to existing `labels`, which may cause error. So, I have changed the `transfer_attr` to confirm `seeds` will be transfered every situation to avoid …
> [GraphBolt] Fix `to` when using `seeds`.

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Currently the time overhead of the `ItemSet`'s `__getitem__` method is high because each call to `__getitem__` requires the execution of `len(self)`. This PR intends to make `len(self)` a fixed value since `ItemSet` itself is immutable.
> [GraphBolt] Update `__len__()` and `__getitem__()` of `ItemSet`

- notebooks/stochastic_training/ondisk_dataset_homograph.ipynb
When I was learning(https://docs.dgl.ai/stochastic_training/ondisk_dataset_homograph.html) to build the Graphbolt local data set, the data built according to the document tutorial code had an error when calculating the AUC in the link prediction task.
Fix data generation for lp_test_dode_pairs
"lp_test_node_pairs = edges[-num_tests, :] to lp_test_node_pairs = edges[-num_tests:, :] "
Refer to https://github.com/dmlc/dgl/pull/7252
> [Doc]fix ondisk_dataset_homograph.ipynb

- graphbolt/src/cuda/neighbor_sampler.cu
Explanation is in the PR diff comments. I don't know why I didn't code it up like this in the first place.
> [GraphBolt][CUDA] Sample neighbors synchronization optimization.

- graphbolt/build.sh
Instead of always compiling GraphBolt for Volta, we compile for the given latest architecture if it is greater than Volta. This way, if the user compiles for only a single architecture different from Volta (such as 80 (Ampere)), they won't have to compile for Volta unnecessarily.
> [GraphBolt][CUDA] Better `TORCH_CUDA_ARCH_LIST` initialization.

- examples/sampling/graphbolt/link_prediction.py
Peak memory usage after fixing bug is 22GB (was getting runtime error before). Any GPU with 24GB should be able to run the `cuda-cuda` mode successfully.
Error message:
```
File "/home/mfbalin/dgl-1/examples/sampling/graphbolt/lightning/../link_prediction.py", line 427, in <module>
main(args)
File "/home/mfbalin/dgl-1/examples/sampling/graphbolt/lightning/../link_prediction.py", line 416, in main
valid_mrr, test_mrr = evaluate(
File "/home/mfbalin/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home/mfbalin/dgl-1/examples/sampling/graphbolt/lightning/../link_prediction.py", line 297, in evaluate
compute_mrr(args, model, node_emb, seeds, labels, indexes)
File …
```
> [GraphBolt][CUDA] Link prediction `--mode=cuda-cuda` fix.

- src/array/cuda/csr_transpose.cc
Running the hetero_rgcn example of graphbolt crashes on NVIDIA 4090 (CUDA 12.4) and A100 (CUDA 12.3). With this PR, it runs successfully. Another place where there may be a bug is the #7239, however #7297 strongly supports that there is no bug there. Before merging this, we want to ensure that the bug is here, I don't know how to do that. Compute sanitizer does not complain at all with this PR. Without this PR, compute sanitizer output below:
```
mfbalin@BALIN-PC:~/dgl-1/examples/sampling/graphbolt/lightning$ CUDA_LAUNCH_BLOCKING=1 compute-sanitizer --tool memcheck python ../rgcn/hetero_rgcn.py
========= COMPUTE-SANITIZER
Loaded dataset: node_classification
node_num for rel_graph_embed: {'author': tensor(1134649, device='cuda:0', dtype=torch.int32), …
```
> [CUDA][Bug] CSR transpose bug in CUDA 12

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/uniform_negative_sampler.py
- python/dgl/graphbolt/negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
Remove old version negative sampler, which is based on `node_pairs`.
> [GraphBolt] Remove old version negative sampler.

- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Remove old version `subgraph sampler`, which is based on `seed_nodes` and `node_pairs`.
> [GraphBolt] Remove old version `subgraph sampler`.

- examples/pytorch/rgcn/README.md
- examples/pytorch/rgcn/link.py
The RGCN link example uses test dataset when training and get the test result using the same test dataset, the final result may not be accurate enough.
As the FB15k237Dataset dataset also has a validation dataset, so using it when training.
> [Misc] Fix validation dataset's usage in RGCN link example

- graphbolt/src/cuda/common.h
- graphbolt/src/cuda/unique_and_compact_impl.cu
With this PR:
```
root@a100cse:/localscratch/dgl-3/build# ldd graphbolt/libgraphbolt_pytorch_2.3.0a0.so 
linux-vdso.so.1 (0x00007ffc5e5af000)
libc10.so => /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so (0x00007fad7511e000)
libcudart.so.12 => /usr/local/cuda/lib64/libcudart.so.12 (0x00007fad74e00000)
libc10_cuda.so => /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so (0x00007fad74d76000)
libtorch_cpu.so => /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so (0x00007fad69d8f000)
libtorch_cuda.so => /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so (0x00007fad142b0000)
libtorch.so => /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so (0x00007fad75115000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 …
```
> [GraphBolt][CUDA] Don't link against `libcuda.so`.

- .clang-format
clang-format -style=Google -dump-config > .clang-format
Manually changed: `AlignAfterOpenBracket: AlwaysBreak`
> [Misc] Update clang-format.

- graphbolt/src/cuda/common.h
When upgrading to CCCL 2.4, our code failed compilation. This is due to CCCL reorganizing headers and since we do not explicitly include the execution policy header, some source files that use thrust fail to compile. Adding this include in the header that provides `THRUST_CALL` ensures that we won't have this problem in the future.
> [GraphBolt][CUDA] Add missing thrust include for later CCCL versions.

- tests/python/pytorch/graphbolt/test_item_sampler.py
This test does not run any differently on GPU machines as it purely runs on the CPU. Hence, I disable it on the GPU so that the CI times and my development workflow are improved. This is due to these tests running very slow, taking as much time as the rest of the GraphBolt tests.
> [GraphBolt] Enable `DistributedItemSampler` test only on CPU.

- src/array/cuda/labor_sampling.cu
I tried compiling our code with CCCL 2.4. Removing these together with #7325 makes the code base compatible with CCCL 2.4. Looks like these headers are unused so removing them does not break anything.
> [CUDA] Remove unused headers for CCCL 2.4 compat

- python/dgl/graphbolt/internal/utils.py
- python/dgl/graphbolt/minibatch.py
Details in #7315. In this PR, we ensure that we do not call properties of the minibatch object when filtering its attributes. The CPU usage is still high, we might want to continue the investigation. PyG advanced example regression is mostly resolved though.
> [GraphBolt][CUDA] `Minibatch.to()` patch.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/itemset.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_base.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
Doc: https://docs.google.com/document/d/18mKlawR2F_WT6VKPkaEBhHLAi65cbtdJfVtu811VwKo/edit?usp=sharing
> [GraphBolt] Hyperlink support in `subgraph_sampler`.

- python/dgl/graphbolt/feature_fetcher.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [graphbolt] skip non-existent types in input_nodes

- examples/multigpu/graphbolt/node_classification.py
- examples/sampling/graphbolt/pyg/node_classification_advanced.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
Fixes #7377. I realized there was an issue with the modified PyG advanced example. I will use the cache version in the DGL 2.2 release blog so I would like to merge the example change too.
> [GraphBolt][CUDA] GPUCachedFeature update fix.

- examples/multigpu/graphbolt/node_classification.py
- examples/sampling/graphbolt/pyg/node_classification_advanced.py
- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- script/dgl_dev.yml.template
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> [release] cherry-pick from master and release for 2.2.1

- examples/sampling/graphbolt/link_prediction.py
- notebooks/stochastic_training/link_prediction.ipynb
- python/dgl/graphbolt/base.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Fixes #7082 in a better way. The user does not have to change their code anymore.
Right now, GraphBolt lightning example crashes.
Solution credit: https://github.com/pytorch/data/issues/1161#issuecomment-1656853707
> [GraphBolt][CUDA] Make dataloader pickleable.

- tools/distpartitioning/data_shuffle.py
In some edge cases where workers end up with no rows of features to send over the network (e.g. in range partition) the existing code was creating tensors of shape (0, 0) and trying to communicate/aggregate those over the network, whereas workers that had non-zero rows assigned would communicate (num_rows, feature_dimension), leading to an assertion error being triggered in https://github.com/dmlc/dgl/blob/6f2ccbff3c94cb3f5767bdfef88f5b535d6843d3/tools/distpartitioning/gloo_wrapper.py#L144-L146
This PR handles the 2D tensor case as a special case, ensuring the correct shape for the tensors being sent over the network, (0, feature_dimension).
This PR also removes an array that was being created but never used, reducing the memory footprint of the function.
Ping @Rhett-Ying for review …
> [DistPart] Fix corner case in dist partition which always led to an assertion error being triggered.

- Jenkinsfile
- python/dgl/backend/pytorch/tensor.py
> [dev] update minimum torch version to 2.1.0

- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
1. Update `ItemSampler` to support correct stochastic sharding across distributed groups.
2. Modify the logic of `ItemSet.__getitem__()` when index is an iterable of int.
Benchmark: https://docs.google.com/document/d/1Pzk2PJoFtTZSu17wTXVK4mqvfrMLAj2xK6fcGC1pwEg/edit?usp=sharing 
> [GraphBolt] Update `ItemSampler`

- examples/pytorch/transformer/modules/viz.py
This is a fix for [Issue#7406](https://github.com/dmlc/dgl/issues/7406): **Transformer example is dated and does not work with latest networkx**
I just took this function from the previous version of **networkx**.
> [BUG][Example] Implementing the deprecated function `is_string_like`.

- docs/source/api/python/dgl.graphbolt.rst
- docs/source/guide/minibatch-custom-sampler.rst
- docs/source/guide/minibatch-edge.rst
- docs/source/guide/minibatch-node.rst
- python/dgl/graphbolt/dataset.py
- python/dgl/graphbolt/impl/legacy_dataset.py
- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/item_sampler.py
- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_negative_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_ondisk_dataset.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
- tests/python/pytorch/graphbolt/test_item_sampler.py
- tests/python/pytorch/graphbolt/test_itemset.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_utils.py
Though `ItemSetDict` is named with dict and takes a dictionary as input, it does not behave as a dictionary, but like a Sequence instead. So maybe we should rename it to avoid confusion.
Relative issues: #6672 #6785 
> [GraphBolt] Rename `ItemSetDict` as `HeteroItemSet`

- python/dgl/distributed/constants.py
- python/dgl/distributed/dist_graph.py
- python/dgl/distributed/graph_services.py
- python/dgl/distributed/partition.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- tests/distributed/test_dist_graph_store.py
- tests/distributed/test_partition.py
> [DistGB] enable find_edges() for GraphBolt partitions

- tests/distributed/test_mp_dataloader.py
For now, exclude edges are done after sampling, right before returning the frontier back to DGL sample_blocks(). Such logic is shared with both DistDGL and DistGB. We need to profile the performance to see if we need to turn to GraphBolt's exclude edges logic/implementation.
https://github.com/dmlc/dgl/blob/002f1bc363508a410ae601dc01e2d33a20f71f09/python/dgl/distributed/dist_graph.py#L1443-L1451
> [DistGB] enable exclude edges for graphbolt-based DistGraph

- python/dgl/graphbolt/item_sampler.py
Since global sharding is applied, buffer is no longer needed when iterating the `ItemSampler`.
Remove it for simplicity.
Before:
```
$ python /home/ubuntu/dgl/examples/sampling/graphbolt/node_classification.py 
Training in pinned-cuda mode.
Loading data...
Training...
Training: 193it [00:08, 21.83it/s]
Evaluating: 39it [00:01, 24.40it/s]
Epoch 00000 | Loss 1.2657 | Accuracy 0.8605 | Time 8.8440
Training: 193it [00:08, 22.78it/s]
Evaluating: 39it [00:01, 24.42it/s]
Epoch 00001 | Loss 0.5886 | Accuracy 0.8753 | Time 8.4753
Training: 193it [00:08, 22.78it/s]
Evaluating: 39it [00:01, 24.41it/s]
Epoch 00002 | Loss 0.4930 | Accuracy 0.8853 | Time 8.4744
Training: 193it [00:08, 22.71it/s]
Evaluating: 39it [00:01, 24.42it/s]
Epoch 00003 | Loss 0.4465 | …
```
> [GraphBolt] remove buffer in `ItemSampler.__iter__`

- python/dgl/distributed/partition.py
> [DistGB] store original homo eids in default for GB partitions

- docs/source/install/index.rst
Related:
https://github.com/dmlc/dgl/issues/7278
Feel free to modify this PR with more info.
> [Doc] Update index.rst: gcc 9 is needed

- python/dgl/graphbolt/itemset.py
- tests/python/pytorch/graphbolt/test_itemset.py
Alias `ItemSetDict` to `HeteroItemSet` and add deprecation warning to provide a smooth transition for external users who use the old class name.
> [GraphBolt] Alias `ItemSetDict` to `HeteroItemSet`

- python/setup.py
- script/dgl_dev.yml.template
let's limit the numpy < 2.0.0 for now. we need to support 2.0.0 in near future.
> [dev] limit numpy < 2.0.0 for compatibility

- graphbolt/src/cuda/extension/gpu_graph_cache.cu
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Depends on #7470 and cpp changes were moved to #7483.
> [GraphBolt][CUDA] Incremental GPU graph cache into `gb.Dataloader`.

- graphbolt/src/cuda/unique_and_compact_impl.cu
- graphbolt/src/cuda/utils.h
Utilize existing cub function to get compute capability in a cached manner using https://nvidia.github.io/cccl/cub/api/function_namespacecub_1a75d6eade310f187ff42915ae82e963d0.html
> [GraphBolt][CUDA] Compute capability check refactor.

- python/dgl/nn/pytorch/conv/grouprevres.py
The following warnings that appear in `test_nn.py::test_group_rev_res` have been fixed:
```
tests/python/pytorch/nn/test_nn.py::test_group_rev_res[idtype0]
/usr/local/lib/python3.10/dist-packages/dgl/nn/pytorch/conv/grouprevres.py:35: UserWarning: TypedStorage is deprecated. 
It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you 
if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead 
of tensor.storage()
```
> [UserWarning] Fixing the warnings appearing in `test_nn.py::test_group_rev_res`.

- python/dgl/graphbolt/base.py
- tests/python/common/test_traversal.py
The following two sets of warnings  that appear in `test_traversal.py::test_bfs` have been fixed:
```
./../../usr/local/lib/python3.10/dist-packages/dgl/graphbolt/base.py:80
/usr/local/lib/python3.10/dist-packages/dgl/graphbolt/base.py:80: DeprecationWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.
@torch.library.impl_abstract("graphbolt::expand_indptr")
tests/python/common/test_traversal.py::test_bfs[idtype0]
tests/python/common/test_traversal.py::test_bfs[idtype1]
/usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py:812: DeprecationWarning:
random_tree is deprecated and will be removed in NX v3.4
Use random_labeled_tree instead.
return …
```
> [DeprecationWarning] Fixing the warnings appearing in `test_traversal.py::test_bfs`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/feature_cache.cc
- graphbolt/src/feature_cache.h
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/feature_cache.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
Refactored the code and added the [SIEVE](https://cachemon.github.io/SIEVE-website/), LRU and CLOCK cache policy algorithm.
CLOCK: https://people.csail.mit.edu/saltzer/Multics/MHP-Saltzer-060508/bookcases/M00s/M0104%20074-12).PDF
The S3-FIFO implementation was behaving a bit differently from the official implementation (upto 2% higher miss rate). So I wrote a short script to compare against the official implementation on several datasets as can be seen below. Moreover, I got rid of garbage collection if the ghost map gets too big and instead used a queue for it so that we never have to do extra work sometimes. This is because when using parallelism, we will wait for the slowest partition and when we do overlapping in the dataloader, these delays will cause a bubble in the pipeline.
Now, …
> [GraphBolt] Refactor S3-FIFO and add SIEVE, LRU and CLOCK.

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/index_select_csc_impl.cu
- graphbolt/src/index_select.cc
- graphbolt/src/index_select.h
- graphbolt/src/python_binding.cc
- graphbolt/src/utils.h
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
The overlap_graph_fetch code path benefits from this change by avoiding the duplicate indexing of the indptr tensor multiple times for each `index_select_csc` call..
> [GraphBolt] `index_select_csc_batched`.

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/internal_utils.py
Should warn users against errors like in #7512 and #7494.
When there is no visible GPU to the process, `torch.cuda.is_available()` returns `False`. So we need to check discrepancy only if `torch.cuda.is_available()` is `True`.
> [GraphBolt] Runtime warning for CUDA availability mismatch.

- graphbolt/src/cnumpy.cc
- graphbolt/src/cnumpy.h
- graphbolt/src/detect_io_uring.cc
Eliminate redundant check and unnecessary nested if. Improve detection by checking if underlying system supports file read requests via io_uring. This is to fix test failure on machines with old kernel versions.
TODO for later: Overlap disk reads with memcpy operations after reads are done by submitting 2 times group_size_ operations into the submission queue. After the second submission, wait for the first set of submissions.
TODO for later: Consider using readv so that we don't need memcpy.
@chang-l tested the code (big thanks!), our detection logic works for old kernel versions that have io uring but does not support the file read operations.
> [GraphBolt][io_uring] Improve detection and simplify code.

- python/dgl/graphbolt/internal_utils.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
I am using WSL myself, I had these manual skips for months now. Merging this patch will enable our tests to pass in Windows Subsystem for Linux users.
> [GraphBolt][CUDA] Skip in-place pinning tests on WSL.

- python/dgl/graphbolt/base.py
Looks like register_fake is not available in 2.3.1, I mistakenly assumed in #7493 that it is. This should fix one issue our user was having in https://discuss.dgl.ai/t/distdgl-v2-4-built-from-source-training-error/4474/3.
PyTorch documentation on deprecation: https://pytorch.org/docs/2.4/library.html#torch.library.impl_abstract
> [GraphBolt] Fix issue on torch 2.3.1

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/internal_utils.py
Force the user to reinstall if the user has a GPU, installed the CUDA version of torch but installs the CPU version of GraphBolt.
Feel free to close the PR if we do not want that. This mismatch causes problems for them so I thought not even letting them use it is the best way to resolve these issues.
Fixes #7512 and #7494
> [GraphBolt][CUDA] Force CUDA version if torch is.

- Jenkinsfile
**This is a pull request for adding my Github ID to intern contributor name list in Jenkinsfile in root directory. **
> [Jenkinsfile] Add my GitHub ID to intern name list

- graphbolt/src/feature_cache.cc
- graphbolt/src/feature_cache.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/feature_cache.py
This op is needed for zero copy access from the GPU. GPU reading tests will be included in a follow-up PR when I make use of this added functionality.
> [GraphBolt][CUDA] Add `FeatureCache::IndexSelect`.

- python/dgl/graphbolt/__init__.py
- python/dgl/graphbolt/external_utils.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
- python/dgl/graphbolt/internal/utils.py
- tests/python/pytorch/graphbolt/internal/test_utils.py
If we store our features in the numpy format using this new function, our io_uring and mmap disk read operations will speedup significantly (2.1 GiB/s vs 1.7 GiB/s) for nice close to power of 2 embedding sizes such as 768 `float`s or 512 `int8`s
> [GraphBolt] Add `gb.numpy_save_aligned`.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
Otherwise our examples crash when run on WSL.
> [GraphBolt][CUDA] In-place pinning should be out-of-place on WSL.

- tests/python/pytorch/graphbolt/impl/test_disk_based_feature_store.py
> [GraphBolt] Improve `DiskBasedFeature` tests.

- graphbolt/src/index_select.cc
- python/dgl/graphbolt/base.py
- tests/python/pytorch/graphbolt/impl/test_legacy_dataset.py
- tests/python/pytorch/graphbolt/test_base.py
We need this invariant. If index is in pinned memory, it means that its output will be copied to the GPU later. Copying the pinned result is faster.
> [GraphBolt] Add additional capabilities to `gb.index_select`.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/dataloader.py
These will be used to overlap copies from device to host or host to device in nested caches such as `GPUCachedFeature<-CPUCachedFeature<-DiskBasedFeature`.
I am working on a feature that needs both #7535 and the functionality here so to be able to work, I need to copy code around from these branches.
> [GraphBolt][CUDA] Add stream for host to device copies.

- graphbolt/src/cache_policy.cc
- python/dgl/graphbolt/impl/feature_cache.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
And fix bugs. I could move the bug fixes to another PR too normally.
> [GraphBolt] Rename to `CPUFeatureCache` and bug fixes. [1]

- graphbolt/src/index_select.cc
- graphbolt/src/index_select.h
- graphbolt/src/python_binding.cc
- tests/python/pytorch/graphbolt/test_base.py
`torch::scatter` does not accept 1d index tensor, needs it to match the dimensionality of src tensor.
> [GraphBolt] `scatter_async`.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
> [GraphBolt] Add `read_async` to `gb.Feature`. [1]

- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
> [GraphBolt][CUDA] `GPUCachedFeature` read_async tests 1. [5]

- python/dgl/graphbolt/impl/cpu_cached_feature.py
> [GraphBolt] `CPUCachedFeature.read_async` body. [4]

- python/dgl/graphbolt/impl/cpu_cached_feature.py
> [GraphBolt] `CPUCachedFeature.read_async` branch 2 [7]

- tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
> [GraphBolt] `CPUCachedFeature.read_async` tests [9]

- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
> [GraphBolt][CUDA] `GPUCachedFeature.read_async` tests 2. [10]

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
When using virtual classes, the destructor needs to be virtual so that the derived object destructor gets called instead of the base class. Running AddressSanitizer revealed the bug, the `BaseCachePolicy` destructor was being called for the derived `CachePolicy` objects.
More information about it is here: https://learn.microsoft.com/en-us/cpp/cpp/destructors-cpp?view=msvc-170#order-of-destruction
Moreover, fixing a potential bug in `SieveCachePolicy` due to accessing uninitialized class member function before the object is constructed. It is better to ensure it is constructed manually.
> [GraphBolt] Fix new delete mismatch for CachePolicy.

- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/basic_feature_store.py
- tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
We don't need to expose `Feature.read_async` and related functions in `FeatureStore`. This functionality will let us access the stored Features in FeatureFetcher and we will be able to call the hidden read_async functions as the user will mostly keep 
FeatureStore objects around, not Features. Moreover, it is possible to provide the implementations of read, update and other functions if we expose a `__getitem__` method, increasing code reuse.
It will also make the examples look better and our components easier to use.
https://github.com/dmlc/dgl/blob/69fd95e370fb935dbce9896ad56165b8097dcd3e/examples/multigpu/graphbolt/node_classification.py#L299-L303
> [GraphBolt] Refactor and extend `FeatureStore`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cnumpy.cc
- graphbolt/src/feature_cache.cc
- graphbolt/src/index_select.cc
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/python_binding.cc
- graphbolt/src/utils.cc
- graphbolt/src/utils.h
- python/dgl/graphbolt/dataloader.py
When `torch::Tensor::is_pinned()` is called, it initializes the CUDA context. If the process is a worker, is_pinned should not even call that function and return false. #7559 requires it for the tests.
> [GraphBolt] Avoid initializing `CUDAContext` in DataLoader workers.

- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
In our read_async pipeline, multiple async threads can try to access the cache policy so we protect it with a mutex. Otherwise the code crashes horribly due to data races. Needed by #7559.
> [GraphBolt] Make `PartitionedCachePolicy` thread safe.

- graphbolt/src/cnumpy.cc
- graphbolt/src/cnumpy.h
During our pipelined read_async feature fetch pipeline, it is possible that multiple async workers try to fetch at the same time. It is crucial to make it threadsafe to avoid catastrophic crashes and data races. Needed by #7559.
> [GraphBolt][io_uring] Make `OnDiskNpyArray` threadsafe.

- graphbolt/src/cuda/gpu_cache.cu
When it is constructed with 0, the code can crash unexpectedly. It is better to give a good error message instead.
> [GraphBolt][CUDA] Ensure GPUCache has can store at least 1 item.

- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
- examples/multigpu/graphbolt/node_classification.py
Depends on #7559. Using `DiskBasedFeature` in labor example depends on #7541, though it works without it, just impossible to enable. There is no API for the user to choose currently when loading builtin datasets.
> [GraphBolt][Example] Slightly improve examples.

- graphbolt/CMakeLists.txt
- graphbolt/src/random.cc
- graphbolt/src/random.h
Also remove unnecessary dependency on dmlc just for thread local. I have tested and each threads gets their own engines. Each run results in different random numbers for each thread because manual_seed gets initialized randomly.
> [GraphBolt] Per-thread `RandomEngine` initialization fix.

- CMakeLists.txt
> [dev] define _POSIX_C_SOURCE for metis build only

- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
When the class' static wait method captures tensors, some of them stay in memory for way too long, causing memory leak and running out of memory. Storing the captured variables as member variables instead resolves the issue.
> [GraphBolt][CUDA] Eliminate memory leaks in `FeatureFetcher`.

- python/dgl/graphbolt/dataloader.py
Even when the number of cached edges is 0, the `GPUGraphCache` is being created and used. This makes it waste a lot of memory. Adding condition to check if the number of cached edges is > 0 fixes the issue.
> [GraphBolt][CUDA] GPUGraphCache is being unnecessarily created.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/feature_cache.cc
- graphbolt/src/feature_cache.h
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
In async feature loading pipeline, after we insert into the policy, values may not be still written into the cache yet. Using writer locks in addition to reader locks, we can act as if inserted values whose payload has not been inserted yet do not exist during our reads.
The PR is a bit large because I needed to do the change for all 4 cache policies at once.
> [GraphBolt] CachePolicy Writer lock for read_async correctness.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/feature_cache.cc
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
1. Make `BaseCachePolicy` threadsafe instead of `PartitionedCachePolicy`.
2. Switch to `graphbolt::parallel_for`.
3. Avoid torch native CPU ops that might spawn OpenMP threadpool.
4. Reuse the partition result from `PartitionedCachePolicy::Replace` in `PartitionedCachePolicy::WritingCompleted`.
> [GraphBolt] Use parallel_for and return replace partition out.

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/index_select_csc_impl.cu
- graphbolt/src/index_select.cc
- graphbolt/src/index_select.h
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_in_subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Fixes the edge id incorrectness issue for the general noncached graph case. Cached graph case will be fixes in a later PR.
> [GraphBolt][CUDA] Fix `overlap_graph_fetch` edge_ids.

- python/dgl/graphbolt/impl/ondisk_dataset.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
- python/dgl/graphbolt/internal/utils.py
- python/dgl/graphbolt/internal_utils.py
- python/dgl/graphbolt/minibatch.py
> [GraphBolt] Move `get_attributes` utils.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
The PR is a bit large because the same change is applied to all 4 caching policies and it is not possible to do a majority of the changes 1-by-1. Some of the diff comes from simply indentation difference.
1. The mutex is removed from the caching policy and is moved to partitioned caching policy instead.
2. The optimization we apply here is that we don't have to partition again to mark read entries as complete as query already had computed it.
3. Instead of returning found keys, we return the found cache pointer entries so that the reading completed operation does not have to do hashmap lookup.
4. Instead of returning only positions from replace, we also return the cache pointer entries so that writing completed operation does not have to do a hashmap lookup.
5. LRU caching policy had a …
> [GraphBolt] Optimize `CachePolicy` even further.

- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
We reuse the partition result from Query so that Replace does not have to recompute it.
> [GraphBolt] Reuse `CachePolicy::Query` partition result.

- python/dgl/distributed/partition.py
- tests/distributed/test_partition.py
Add option to use multi-processing to speed up conversion of DGL to GraphBolt partitions.
> [GraphBolt] Allow using multiple processes for GraphBolt partition conversion

- graphbolt/CMakeLists.txt
- graphbolt/src/concurrent_id_hash_map.cc
- graphbolt/src/concurrent_id_hash_map.h
- graphbolt/src/unique_and_compact.cc
Using the new `std::atomic_ref` for portable compare and swap implementation. See #7614.
> [GraphBolt] Overhaul `unique_and_compact` CPU.

- graphbolt/CMakeLists.txt
- graphbolt/src/cnumpy.cc
- graphbolt/src/cnumpy.h
We can rely on our existing libcudacxx dependency on the CPU backend for its library facilities. Does not require CUDA or GPUs at all.
> [GraphBolt][io_uring] Launch `parallel_for` when queues are available.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
Fusing the query and replace operations will make the cache more performant. The costliest operation was the map lookup in the cache. By fusing the Query and Replace like this, we make sure only 1 map lookup operation is performed per key whether it already exists or not.
The PR ended up a bit large due to the same change being applied to all 4 existing cache policy implementations.
Next PR will add `PartitionCachePolicy::QueryAndThenReplace`.
Then the next PR should add its tests and incorporate it into `CPUCachedFeature` and `CPUFeatureCache` classes.
> [GraphBolt] `CachePolicy::QueryAndThenReplace`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/feature_cache.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
Followup to #7619. Testing the implementation for the single part case. Will add multi-part implementation and tests in the next PR.
> [GraphBolt] Test `CachePolicy::QueryAndThenReplace` for `num_parts==1`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/partitioned_cache_policy.cc
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
Follow-up to #7620.
TODO: Refactor the code so that the permute portions of the Query, QueryAndThenReplace and Replace can be shared.
> [GraphBolt] `CachePolicy::QueryAndThenReplace` for `num_parts>1`.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/minibatch_transformer.py
- tests/python/pytorch/graphbolt/test_feature_fetcher.py
> Use torch core instead of torchdata modules.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
The algorithm does not have the exact same semantics as calling Query and Replace back to back anymore. This is done for safety (if the hashmap rehashes, it was going mayhem) and reduce our reliance on iterator stability of the hashmap container. This way, we can switch to faster hashmaps in a later PR that does not have iterator stability.
> [GraphBolt] `QueryAndReplace` replaces `QueryAndThenReplace`.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
Due the Global Interpreter Lock (GIL) in Python, having an extra thread does not provide any benefit. When we make a call to C++, the GIL is taken and not released until back into python, so no benefit. GIL will be removed from Python in 3.13 and future versions (will be opt-in first). We need another C++ sided solution for asynchronous calls.
It turns out that this modification was actually reducing the performance due to GIL.
> [GraphBolt][CUDA] Remove python thread from `overlap_graph_fetch`.

- python/dgl/graphbolt/base.py
- python/dgl/graphbolt/dataloader.py
https://pytorch.org/tutorials/intermediate/pinmem_nonblock.html
According to this tutorial, pinning before copying is not a requirement for `non_blocking` copies. However, when the data is pinned, it is possible to run the copies in a separate stream, this optimization can be enabled later. This should bring down the regression test runtimes for `cpu-cuda`.
> [GraphBolt][CUDA] Optimize `CopyTo` performance.

- .gitmodules
- graphbolt/CMakeLists.txt
- graphbolt/src/cache_policy.h
1.5x faster compared to phmap. This hash table is used across the industry for its excellent performance. See the benchmark results in https://martin.ankerl.com/2022/08/27/hashmap-bench-01/#benchmark-results-table for reference. We chose to use `tsl::robin_map` for our use case after trying out a few alternatives.
@frozenbugs 50% performance improvement is not small so I am hoping it is fine for me to add this hash table dependency.
> [GraphBolt] Change hash table for performance.

- python/dgl/graphbolt/__init__.py
- tests/python/pytorch/graphbolt/test_base.py
I have 24GB GPU. Without this, some examples go OOM. With this, they don't even use half the GPU memory. This is due to the irregular sizes of the minibatches in GNN training. Each minibatch has different sized `node_ids()` for example. The default allocator does not work well in this use case. The added option is much better suited for GNN minibatch training with GraphBolt.
See https://pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf.
> [GraphBolt][CUDA] Use better memory allocation algorithm to avoid OOM.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
- graphbolt/src/feature_cache.cc
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
After we switched the hash table we use and the optimizations we applied such as passing pointers to `CacheKey` objects around, we needed to make sure that these pointers and references stay valid by utilizing data structures that guarantee to keep them valid.
> [GraphBolt] Keep references valid in `CachePolicy`.

- python/dgl/graphbolt/internal/utils.py
The `node-feat.npy` of products dataset is not saved in C_CONTIGUOUS (and possibly the same for other small datasets). Currently there is no check on the flags before directly copying the file, which will leads to errors [here](https://github.com/dmlc/dgl/blob/master/python/dgl/graphbolt/impl/torch_based_feature_store.py#L381-L383) if the data file is not C_CONTIGUOUS.
A simple solution here is to judge whether the data file is C_CONTIGUOUS. If yes, we can directly copy the file, otherwise we will need to proceed the save process.
> [GraphBolt] Check data alignment before copying the file

- python/dgl/graphbolt/impl/cpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
Fixes the overlap_fetch=False case for CPUCachedFeature. @Liu-rj 
> [GraphBolt] `CPUCachedFeature` no overlap fix.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
@frozenbugs When a key is already being written, the cache query treats it as missing and it is fetched from the fallback feature. However, this is somehow causing correctness bugs when `FeatureFetcher` `overlap_fetch` argument is enabled.
When a key is already being written, taking the writer lock again and also writing ourself too seems to fix it at the cost of the writer lock might stay taken forever. I am looking into permanently fixing this issue and rolling this workaround back.
> [GraphBolt] Temporary workaround for `CachePolicy`.

- graphbolt/src/cache_policy.cc
- graphbolt/src/cache_policy.h
Removing the duplicate insert function and using the more efficient one for `CachePolicy::Replace`. Less code, less places there could be bugs.
> [GraphBolt] Remove duplicate `CachePolicy::Insert` function.

- graphbolt/src/cache_policy.h
- graphbolt/src/partitioned_cache_policy.cc
The ReadingCompleted and WritingCompleted operations are made lock-free so we don't have to take the lock before calling them anymore.
Compiled with thread-sanitizer and checked for data races. Everything seems to simply work.
> [GraphBolt] Lock-free `CachePolicy::ReadWriteCompleted`.

- graphbolt/include/graphbolt/async.h
The variables captured by the lambda are copied too many times without this move operation.
> [GraphBolt] Move the function object into `gb::async`.

- graphbolt/include/graphbolt/async.h
- graphbolt/src/cnumpy.cc
- graphbolt/src/feature_cache.cc
- graphbolt/src/partitioned_cache_policy.cc
Adding for_each algorithm so that I don't have to manually handle cases of offloading work to different threads manually by checking begin + 1 == end etc. and make the code simpler. A lot of `TORCH_CHECK`s can simply be removed with this.
> [GraphBolt] Add `gb::parallel_for_each`.

- graphbolt/include/graphbolt/cuda_sampling_ops.h
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/include/graphbolt/fused_sampled_subgraph.h
- graphbolt/src/cuda/insubgraph.cu
- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/index_select.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
`return_eids` option is always `True`. No need to keep this option. Since it is always true now, went ahead and modified `FusedSamplingGraph` so that it is always expected to be passed. Made it come right after indices so that the rest of the parameters can have default values.
> [GraphBolt] Remove unused `return_eids` option.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
We need to make a distinction between `sampled_edge_ids` and `original_edge_ids`. `sampled_edge_ids` will be specifically used to fetch indices later as indices tensor does not need permutation with the `ORIGINAL_EDGE_ID`.
> [GraphBolt][CUDA] `sampled_edge_ids` to fetch indices later.

- graphbolt/include/graphbolt/cuda_sampling_ops.h
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
This PR implements overlapping indices fetches for NS after sampling is completed.
The PR ended up on the slightly large side.
The changes are:
1. Add returning_indices_is_optional to C++ and Python API (pretty repetitive change).
2. Add returning_indices_is_optional to SamplePerLayer, with False as default value.
3. Modify gb.DataLoader so that returning_indices_is_optional is enabled for sample_neighbor code path (Important logic here.)
4. Modify the default `max_uva_threads` from `6144` to `10240` as larger value is faster on 4090 (we can watch the regression tests for sample_layer_neighbor).
5. Implement the logic for the indices overlapped fetch in SamplePerLayer (Important logic here.)
6. Modify the tests to fix them and add tests for the new feature.
Please feel free to remove …
> [GraphBolt][CUDA] Fetch indices for NS later.

- examples/graphbolt/disk_based_feature/node_classification.py
- examples/graphbolt/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
- examples/graphbolt/rgcn/hetero_rgcn.py
- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/dataloader.py
Now, when graph is pinned, overlap_graph_fetch is faster for all branches.
> [GraphBolt][CUDA] Enable `overlap_graph_fetch` in examples.

- docker/install/conda_env/torch_cpu_pip.txt
- docker/install/conda_env/torch_gpu_pip.txt
- docs/source/guide/minibatch-parallelism.rst
- python/setup.py
- script/dgl_dev.yml.template
- tests/lint/pylintrc
> Remove datapipe from dgl dependency.

- graphbolt/include/graphbolt/cuda_sampling_ops.h
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/src/cuda/neighbor_sampler.cu
- graphbolt/src/fused_csc_sampling_graph.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/temporal_neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
CUDA temporal backend is implemented. Tests and a potential optimization will be in the next PR.
This PR has a few things:
1. Make naming of parameters consistent with other places.
2. Add the main temporal sampling implementation on the GPU.
3. Change a few places where the CPU backend was assumed and CUDA was not taken into consideration.
The PR is a bit large due to the repetitive changes of the same kind. Main implementation is <100 lines.
> [GraphBolt][CUDA][Temporal] Complete implementation.

- examples/graphbolt/temporal_link_prediction.py
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
- tests/python/pytorch/graphbolt/test_subgraph_sampler.py
On my machine with AMD Ryzen 9 5950X and NVIDIA RTX 4090:
`cpu-cuda`: 6.77s per iteration
`cuda-cuda`: 8.51s per epoch
There are 107 iterations in an epoch, meaning the speedup is 85x.
> [GraphBolt][CUDA][Temporal] Tests and example enablement.

- graphbolt/src/cnumpy.cc
- graphbolt/src/cnumpy.h
Make use of RAII to ensure the queues are returned back in a guaranteed way due to the object destructors.
This should make the code more error prone (I mean safer). Even if the worker threads or the main thread face an error or an exception, the destructors will be called, releasing the acquired shared resources.
> [GraphBolt][io_uring] Use RAII to ensure queues are returned.

- examples/graphbolt/disk_based_feature/node_classification.py
- examples/graphbolt/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
- examples/graphbolt/rgcn/hetero_rgcn.py
- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/dataloader.py
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
1. Move the logic from `gb.DataLoader` to the sampling classes for `overlap_graph_fetch`. It is an argument of the sampler now.
2. Move the `gpu_graph_cache` to the FusedCSCSamplingGraph because otherwise it won't be shared across train or validation dataloader for example. That way, there will be a single graph cache for multiple dataloader instances.
The end goal is to make sampling and compaction async and hide the latency of GPU CPU synchronizations during these stages. A lot of our optimizations also have inherent GPU CPU synchronization, which will be handled in the same way. I needed to clean the code and refactor before #7682.
I might refactor more and reduce the amount of code in our code base in the future.
> [GraphBolt][CUDA] Refactor `overlap_graph_fetch`, simplify `gb.DataLoader`.

- graphbolt/src/cnumpy.h
Calling the semaphore constructor.
https://en.cppreference.com/w/cpp/thread/counting_semaphore/counting_semaphore
> [GraphBolt][io_uring] Call semaphore constructor.

- graphbolt/include/graphbolt/async.h
Needed by #7682 and future PRs containing async CUDA operations.
> [GraphBolt][CUDA] Use same CUDA stream in async op.

- graphbolt/src/fused_csc_sampling_graph.cc
This output is unused. SampleNeighbors returns it nullopt as well. The output computes ids for every node in the original graph, which I think is completely wrong.
> [GraphBolt] Remove unused output from `InSubgraph`.

- examples/graphbolt/pyg/labor/node_classification.py
- graphbolt/include/graphbolt/fused_csc_sampling_graph.h
- graphbolt/include/graphbolt/unique_and_compact.h
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/python_binding.cc
- graphbolt/src/unique_and_compact.cc
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
- tests/python/pytorch/graphbolt/test_dataloader.py
We want to hide the latency of GPU CPU synchronization using pipelining. We want to eliminate the white gaps in the profile below:
Before:
After:
This is going to be achieved by using pipelining so that the output of one stage is not required by the next. Then, we can launch kernels for all stages at the same time in an async manner, ensuring there are no white gaps.
Preliminary results:
Without torch.compile
------------
Without asynchronous: 1.51s
With asynchronous: 1.37s
With torch.compile:
---------------
Without asynchronous: 1.11s
WIth asynchronous: 0.98s
> [GraphBolt][CUDA] Async sample neighbors and compaction.

- graphbolt/src/cuda/extension/gpu_cache.cu
- graphbolt/src/cuda/extension/gpu_cache.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/gpu_cache.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
Use async launch to hide the latency of CPU GPU synchronization for GPU cache query.
Runtime: 1.36s (old) to 1.16s (this PR)
> [GraphBolt][CUDA] Eliminate GPUCache synchronization.

- graphbolt/src/cuda/extension/gpu_graph_cache.cu
- graphbolt/src/cuda/extension/gpu_graph_cache.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/gpu_graph_cache.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
We hide the synchronization latencies for GPUGraphCache functions as well.
> [GraphBolt][CUDA] Use async for GPUGraphCache.

- graphbolt/include/graphbolt/fused_sampled_subgraph.h
> Clarify the docstring for original_edge_ids in fused_sampled_subgraph.

- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/impl/sampled_subgraph_impl.py
Renaming as suggested in previous review.
> [GraphBolt] Rename `sampled_edge_ids` for clarity.

- graphbolt/include/graphbolt/async.h
- graphbolt/src/cuda/extension/gpu_cache.cu
- graphbolt/src/cuda/extension/gpu_graph_cache.cu
- graphbolt/src/fused_csc_sampling_graph.cc
- graphbolt/src/unique_and_compact.cc
> [GraphBolt][CUDA] `gb::async` supports alternative streams now.

- graphbolt/src/cuda/extension/gpu_graph_cache.cu
- graphbolt/src/cuda/extension/gpu_graph_cache.h
- python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
- python/dgl/graphbolt/impl/gpu_graph_cache.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- tests/python/pytorch/graphbolt/impl/test_gpu_graph_cache.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
Similar to indices, `ORIGINAL_EDGE_ID` fetch is also handled. When there is no gpu graph cache, its fetch can be delayed similar to indices. When there is a GPU cache, we let the GPUGraphCache know that it will cache ORIGINAL_EDGE_ID as well and does not have to return edge ids assuming it is `arange(num_edges)`
> [GraphBolt][CUDA] Overlap original edge ids fetch.

- graphbolt/src/fused_csc_sampling_graph.cc
- tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
The code was simply wrong. I don't know why the tests didn't catch it.
Fixes https://discuss.dgl.ai/t/neighbour-sampling-on-cpu-crashes-for-graphbolt-heterographs/4521.
> [GraphBolt] Fix hetero sampling bug with single fanout.

- python/dgl/graphbolt/dataloader.py
The only difference between the new dataloader CopyTo related code and old code replaced in https://github.com/dmlc/dgl/pull/7603 is the change in this PR. I am hoping it will fix the regression we are having in the cpu-cpu case.
I don't know why disabling prefetch in the CPU only case would cause a regression.
@frozenbugs can we test if this PR fixes the regression issue for the cpu-cpu case? I can't seem to reliably verify it but I strongly suspect this PR will fix it.
> [GraphBolt] Always enable prefetch before `CopyTo`.

- graphbolt/src/partitioned_cache_policy.cc
- graphbolt/src/partitioned_cache_policy.h
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/feature_cache.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_feature_cache.py
The cache will be constructed first (applies to both CPU and GPU). The GPUCachedFeature and CPUCachedFeature will have an `_offset` field that is set to 0 by default (no effect). When it is nonzero, the keys will be offset by the `_offset` field according to the node_type_offset in FusedCSCSamplingGraph. Then, the same cache can be used for hetero features that have the same dimensions.
> [GraphBolt] Make `CachePolicy` hetero capable [1]

- docs/source/api/python/dgl.graphbolt.rst
- examples/graphbolt/disk_based_feature/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
- examples/multigpu/graphbolt/node_classification.py
- python/dgl/graphbolt/feature_store.py
- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
- tests/python/pytorch/graphbolt/impl/test_hetero_cached_feature.py
> [GraphBolt] `CachedFeature` can handle hetero features now.

- graphbolt/src/feature_cache.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/impl/cpu_feature_cache.py
Addressing the reviews in #7729.
> [GraphBolt] Do not expose `CPUFeatureCache` storage tensor.

- docs/source/api/python/dgl.graphbolt.rst
We are going to recommend the users to use numpy_save_aligned instead of `numpy.save` before doing out of core training with graphbolt.
> [GraphBolt][Doc] Add `numpy_save_aligned` to documentation.

- python/dgl/graphbolt/impl/cpu_cached_feature.py
- python/dgl/graphbolt/impl/gpu_cached_feature.py
- python/dgl/graphbolt/impl/torch_based_feature_store.py
Trying to fix https://github.com/dmlc/dgl/pull/7718#issuecomment-2307509731.
https://lpn-doc-sphinx-primer.readthedocs.io/en/latest/concepts/inline-markup.html
it must be separated from surrounding text by non-word characters. Use a backslash escaped space to work around that: thisis\ **one**\ word (thisisoneword).
> [GraphBolt][Doc] Fix `read_async` doc display issue.

- docs/source/api/python/dgl.graphbolt.rst
I am moving the docs of gpu and cpu feature cache construction functions to utils because they don't show up under Feature/FeatureStore as we discussed.
Also adding the newly added `indptr_edge_ids` function there as well.
> [GraphBolt][Doc] Fix `[gpu|cpu]_cached_feature` rendering.

- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
> [GraphBolt][PyG] Add `to_pyg` for layer input conversion.

- examples/graphbolt/pyg/hetero/node_classification.py
- examples/graphbolt/pyg/labor/node_classification.py
- examples/graphbolt/pyg/node_classification_advanced.py
> [GraphBolt][PyG] Use `SampledSubgraph.to_pyg` in examples.

- python/dgl/graphbolt/__init__.py
When the user sets the value as `PYTORCH_CUDA_ALLOC_CONF=`, there is an error. This shouldn't be an error. In this case, the environment variable is set to an empty string we make sure to check this case.
> [GraphBolt][CUDA] Fix error when empty env variable is used.

- python/dgl/distributed/graph_services.py
Fix the issue introduced in https://github.com/dmlc/dgl/pull/7663 as `return_eids` argument is removed. If `EID` are stored in `g.edge_attributes`, they will be fetched into `subgraph.original_edge_ids`. Otherwise, EID are assumed to be `arange(0, num_edges). This assumption does not fit in DistGB.
> [DistGB] fix return_eids argument

- examples/graphbolt/link_prediction.py
- examples/graphbolt/pyg/link_prediction.py
- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/include/graphbolt/isin.h
- graphbolt/src/cuda/isin.cu
- graphbolt/src/isin.cc
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/external_utils.py
- python/dgl/graphbolt/sampled_subgraph.py
- tests/python/pytorch/graphbolt/test_utils.py
> [GraphBolt][CUDA] Eliminate synchronization from exclude edges.

- conda/dgl/meta.yaml
- include/dgl/runtime/c_runtime_api.h
- python/dgl/_ffi/libinfo.py
- python/update_version.py
> [release] bump version to 2.5 for nightly

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/src/cuda/unique_and_compact_impl.cu
> [GraphBolt][CUDA] Remove unused `num_bits` argument from `UniqueAndCompact`

- tests/python/common/sampling/test_sampling.py
Fix #7766
Commented out a line that will cause `AttributeError: module 'numpy' has no attribute 'ComplexWarning'`.
> [UnitTest] Fix "[UnitTest] AttributeError: module 'numpy' has no attribute 'ComplexWarning'" in #7766

- graphbolt/src/cuda/extension/unique_and_compact_map.cu
Fix the bug introduced in #7765 for the heterogenous case.
The hetero example regression test failed yesterday due to it.
The bug was that it left some entries uninitiailized if certain edge types contain no edges. When the uninitialized memory is accessed, it causes crash.
We fix it by initializing the memory to infinity, then using atomic min to write the correct values. It is possible that some entries might still be uninitialized due to the same reason. But this time, they will have the value infinity and a backward scan using min operation re-initializes those values to the correct value.
> [GraphBolt][CUDA] Fix hetero `UniqueAndCompact` bug.

- graphbolt/include/graphbolt/cuda_ops.h
- graphbolt/include/graphbolt/unique_and_compact.h
- graphbolt/src/cuda/unique_and_compact_impl.cu
- graphbolt/src/python_binding.cc
- graphbolt/src/unique_and_compact.cc
- python/dgl/graphbolt/impl/in_subgraph_sampler.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/internal/test_sample_utils.py
Towards implementing #7273.
Tests will be in a follow-up PR.
> [GraphBolt][CUDA] Expose `UniqueAndCompact` offsets.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Somehow, the PR ended up being this long because there are various branches.
I wonder if there is a way to generalize...
> [GraphBolt][CUDA] Refactor `gb.unique_and_compact`, add `async_op`.

- python/dgl/distributed/partition.py
- tests/distributed/test_partition.py
> [Dist] fix node/edge map for few nodes/edges

- python/dgl/graphbolt/internal/sample_utils.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
Towards implementing #7273.
The code is untested right now. I need to merge some of the changes so that the PR size stays limited.
The initial exchange is required because each process needs to sample for the nodes they are assigned. There is no guarantee about any partitioning after things come from ItemSampler or when negative edges are added. Thus, initial exchange ensures that each process samples only for the nodes that they own.
Follow up work:
1. Exchanges after each sampling stage.
2. Add torch layer for GNN forward backward using Cooperative Minibatching and stored tensors including exchange information.
3. Add multi-GPU example showcasing Cooperative Minibatching.
4. Optimize Cooperative Minibatching using partitioning. (More details to come later.)
Please feel free to remove …
> [GraphBolt][CUDA] Cooperative Minibatching initial exchange.

- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Towards implementing #7273
The implementation of cooperative sampling is mostly done. The code path is tested with a single process for now while the expected outputs are not tested yet.
There will be multiple follow-up PRs to polish the code, test more throughly, add more documentation and get everything working.
I have to merge to master often because otherwise there will be too much code. When it is done, I will make sure the code is in good shape.
> [GraphBolt][CUDA] Get `world_size=1` somewhat for cooperative sampling.

- python/dgl/graphbolt/impl/__init__.py
- python/dgl/graphbolt/impl/cooperative_conv.py
- python/dgl/graphbolt/impl/neighbor_sampler.py
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Towards implementing #7273.
`CooperativeConv` will be used in-between layers and during feature loading to exchange feature data or intermediate layer results.
> [GraphBolt][CUDA] Add `CooperativeConv` and minor fixes.

- python/dgl/graphbolt/feature_fetcher.py
- python/dgl/graphbolt/impl/cooperative_conv.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Towards implementing #7273. We reuse the all_to_all function for feature loading.
Follow-up PRs will refactor the functionality added so far, add more tests, fixing any bugs and adding a multiGPU example utilizing the new functionality.
> [GraphBolt][CUDA] Cooperative Minibatching - Feature Loading

- graphbolt/src/cuda/extension/unique_and_compact_map.cu
- python/dgl/graphbolt/impl/cooperative_conv.py
- tests/python/pytorch/graphbolt/impl/test_cooperative_minibatching_utils.py
Towards #7273.
The added code was not working, with these changes, a simple homo multiGPU cooperative node classification example works. The example will be in the followup PR.
More refactoring and tests will be added to make things robust.
> [GraphBolt][CUDA] Fix Cooperative bug and additional tests.

- graphbolt/src/cuda/cooperative_minibatching_utils.cu
- graphbolt/src/cuda/cooperative_minibatching_utils.h
- graphbolt/src/python_binding.cc
- python/dgl/graphbolt/subgraph_sampler.py
- tests/python/pytorch/graphbolt/test_dataloader.py
Towards #7273.
Eliminating synchronization from `rank_sort`.
> [GraphBolt][CUDA] `rank_sort_async` for Cooperative Minibatching.

- python/dgl/dataloading/dataloader.py
- python/dgl/distributed/dist_dataloader.py
Previously, we use `from dgl.dataloading.dist_dataloader import _remove_kwargs_dist`. From now on, we need to use `from dgl.dataloading.dataloader import _remove_kwargs_dist`
> [DistDGL] back-compatible with dgl.dataloading

- examples/pytorch/ogb/directional_GSN/main.py
- examples/pytorch/ogb/ogbn-arxiv/gcn.py
- examples/pytorch/ogb/ogbn-products/gat/gat.py
- examples/pytorch/ogb/ogbn-products/mlp/mlp.py
- examples/pytorch/ogb/ogbn-proteins/gat.py
By removing the use of the deprecated verbose parameter, we are eliminating the associated warnings.
```
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:63: UserWarning: The verbose parameter is deprecated.
Please use get_last_lr() to access the learning rate.
warnings.warn(
```
> [UserWarning] Eliminating the use of the deprecated `verbose` parameter.

- examples/pytorch/eeg-gcnn/EEGGraphDataset.py
The current PR fixes the following warnings:
```
/opt/dgl/dgl-source/examples/pytorch/eeg-gcnn/EEGGraphDataset.py:91: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  x1 = float(coords_1010[coords_1010.label == ref_sensor1]["x"])
/opt/dgl/dgl-source/examples/pytorch/eeg-gcnn/EEGGraphDataset.py:92: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y1 = float(coords_1010[coords_1010.label == ref_sensor1]["y"])
/opt/dgl/dgl-source/examples/pytorch/eeg-gcnn/EEGGraphDataset.py:93: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use …
```
> [FutureWarning] Resolving the warning related to the use of a single-element series.

- python/dgl/nn/pytorch/conv/cugraph_relgraphconv.py
As we can see [here](https://github.com/pyg-team/pytorch_geometric/issues/8570):
```
test/nn/conv/cugraph/test_cugraph_rgcn_conv.py: 72 warnings
/usr/local/lib/python3.10/dist-packages/pylibcugraphops/pytorch/graph.py:302: DeprecationWarning: SampledHeteroCSC is deprecated with the 23.08 release and will be removed in 23.10, use HeteroCSC instead.
warnings.warn(
test/nn/conv/cugraph/test_cugraph_rgcn_conv.py: 72 warnings
/usr/local/lib/python3.10/dist-packages/pylibcugraphops/pytorch/graph.py:330: DeprecationWarning: StaticHeteroCSC is deprecated with the 23.08 release and will be removed in 23.10, use HeteroCSC instead.
warnings.warn(
```
the `SampledHeteroCSC` and `StaticHeteroCSC` classes were expected to be deprecated. Since `pylibcugraphops-24.8` does not contain these classes, the …
>  [Test] Fixing issues related to `SampledHeteroCSC` and `StaticHeteroCSC` deprecation.

- python/dgl/distributed/dist_dataloader.py
- python/dgl/distributed/dist_graph.py
- tests/distributed/test_distributed_sampling.py
Add a new parameter "padding" to add_edge_attribute, the edge's mask will be filled with padding rather than 0.
When use DistEdgeDataloader the padding will be set to 1 to fully sample the edge with no mask.
> [distGB] graphbolt graph edge's mask will be filled with 0 if these edges have no mask initial

- graphbolt/src/cuda/common.h
- tensoradapter/pytorch/torch.cpp
This PR resolves multiple warnings:
```
[W110 03:11:01.976023226 Context.h:353] Warning: lazyInitCUDA is deprecated. Please use lazyInitDevice(at::kCUDA) instead. (function lazyInitCUDA)
[W110 03:11:01.979291350 Context.h:353] Warning: lazyInitCUDA is deprecated. Please use lazyInitDevice(at::kCUDA) instead. (function lazyInitCUDA)
[W110 03:11:01.980258297 Context.h:353] Warning: lazyInitCUDA is deprecated. Please use lazyInitDevice(at::kCUDA) instead. (function lazyInitCUDA)
[W110 03:11:01.983385323 Context.h:353] Warning: lazyInitCUDA is deprecated. Please use lazyInitDevice(at::kCUDA) instead. (function lazyInitCUDA)
[W110 03:11:01.984356630 Context.h:353] Warning: lazyInitCUDA is deprecated. Please use lazyInitDevice(at::kCUDA) instead. (function lazyInitCUDA)
```
generated by …
> [DeprecationWarning] Replacing soon-to-be-deprecated `lazyInitCUDA` with `lazyInitDevice(at::kCUDA)`

- include/dgl/runtime/parallel_for.h
This fixes a compilation issue on macOS when compiling with OpenMP support:
```
dgl/include/dgl/runtime/parallel_for.h:88:22: error: no matching function for call to 'min'
auto end_tid = std::min(end, chunk_size + begin_tid);
^~~~~~~~
```
Same kind of bug as in https://github.com/dmlc/dgl/issues/3631.
> fix(dgl/runtime): add static_cast to fix clang compilation when using OpenMP

- python/dgl/nn/pytorch/conv/edgegatconv.py
- python/dgl/nn/pytorch/conv/gatconv.py
- python/dgl/nn/pytorch/conv/gatv2conv.py
- tests/python/pytorch/nn/test_nn.py
Added conditionals to skip calls to .view() or reshape on tensors with zero elements in three places. This prevents runtime errors caused by ambiguous shape inference when reshaping empty tensors.
Improves robustness when input tensors can be empty. 
Bug Issue: #7893 
check changed files
> [Bugfix][nn/PyTorch]: add checks to avoid view/reshape (0, -1, *) on empty tensors
